!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING DDT

INFORMATION LOGICAL-NAMES

!SOURCES
COPY FROM-SOURCE:DDT.MAC TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:F2EDDT.MAC TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:F2FDDT.MAC TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:F2KDDT.MAC TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:F2MDDT.MAC TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:F2RDDT.MAC TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:F2UDDT.MAC TO-LANG-SRC:*.*.-1

!COMMAND FILES
COPY FROM-SOURCE:DDT.CMD TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:DDT.CTL TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:EDDT.CMD TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:FILDDT.CMD TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:KDDT.CMD TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:MDDT.CMD TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RDDT.CMD TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:SDDT.CCL TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:UDDT.CCL TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:UDDT.CMD TO-LANG-SRC:*.*.-1

!OUTPUT FILES
COPY FROM-SOURCE:EDDT.REL TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:FILDDT.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:KDDT.REL TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:MDDT.REL TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:RDDT.REL TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:SDDT.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:UDDT.EXE TO-SUBSYS:*.*.-1

!DOCUMENTATION
COPY FROM-DOC:DDT42.DOC TO-DOC:*.*.-1
COPY FROM-DOC:DDT42.MEM TO-DOC:*.*.-1
COPY FROM-DOC:DDTMAN.TXT TO-DOC:*.*.-1

!DONE
TAKE
