;Command files to build BLIS20
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:BLIS20.CMD TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:BLIS20.CTL TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:NOONCE.MAC TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LOIO.MAC TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:AD0.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:AD2.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:AR2N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:AR2N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:AS3.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:BEGIN.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:BL10ER.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:BLIS10.ERR TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:BLIS20.LNK TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:BLS7E.BWR TO-DOC:*.*.-1
COPY FROM-SOURCE:BLSERR.RNO TO-DOC:*.*.-1
COPY FROM-SOURCE:CC3.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:CN1N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:CN1N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:CN2N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:CN2N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:CN3.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:DE0N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:DE0N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:DE1N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:DE1N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:DE3N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:DE3N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:DR0N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:DR0N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:DR3N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:DR3N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:GT0.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:GT1N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:GT1N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:GT2.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:H2ADDR.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:H2GTRE.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:H2REGI.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:H3ASSY.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:H3CCL.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:H3CNTR.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:H3LEXA.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:H3PEEP.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:INDEX.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LD3N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LD3N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LOADDR.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LOGTRE.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LOLSTP.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LS0.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LS3N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LS3N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LX0N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LX0N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LX1N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LX1N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:LX3.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:MA0N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:MA0N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:MA1N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:MA1N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:PE3.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RG2.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RG3N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RG3N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RQ1N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RQ1N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:SIX12.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:SN1N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:SN1N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:XR0N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:XR0N.SUP TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:XR3N.BLI TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:XR3N.SUP TO-LANG-SRC:*.*.-1

;Documentation for product
COPY FROM-SOURCE:BLIS10.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:BLIS10.DOC TO-DOC:*.*.-1

;Library files used for symbols
COPY FROM-SUBSYS:SIX12.REL TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SUBSYS:INDEX.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:BLIS10.EXE TO-SUBSYS:*.*.-1
