
;Files required to build product
COPY FROM-SOURCE:RMS20.CMD TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RMS20.CTL TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RMS201.REL TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RMS2C1.LNK TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RMS2P1.REL TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RMS2S1.LNK TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RMS2U1.LNK TO-LANG-SRC:*.*.-1
COPY FROM-SOURCE:RMS2U1.REL TO-LANG-SRC:*.*.-1

;Documentation for product
COPY FROM-DOC:RMS20.DOC TO-DOC:*.*.-1
COPY FROM-DOC:RMSREF.MEM TO-DOC:*.*.-1

;Library files used for symbols

;Final product
COPY FROM-SUBSYS:B362LB.REL TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:RMS.EXE TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:RMS.REL TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:RMSCOB.EXE TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:RMSINI.REL TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:RMSINT.R36 TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:RMSINT.UNV TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:RMSSYM.LUS TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:RMSUTL.EXE TO-SUBSYS:*.*.-1

;UETP files
COPY FROM-SOURCE:RMS.VER TO-UETP:*.*.-1
