@NOERROR
!
def dsk:
def mon: dsk:,cwl:<5-4-net>,cwl:<dec-6-1-base>,cwl:<dec-6-1-base.ap7>
def r:   dsk:
def sys: dsk:,sys:
def unv: dsk:
def utl: dsk:
@ena
!
@DEL PROLOG.UNV.1000
@EXP
!
.GOTO MCMN%:'SN,N,Y,Y'/Monsym or Macsym? /
.MCMNY:::
!
MONSYM::
@COMPILE MON:MONSYM.MAC R:MONSYM
MACSYM::
@COMPILE MON:MACSYM.MAC R:MACSYM
!
.MCMNN:::
!
.GOTO PROL%:'SN,N,Y,Y'/Prolog? /
.PROLY:::
!
PROLOG::
@COMPILE /compile MON:PROLG0.MAC+MON:PROLOG.MAC+MON:GLOBS.MAC R:PROLOG
@REN PROLOG.*.0 PROLOG-NO-BUGS.*.*
@COMPILE /compile MON:PROLG0.MAC+MON:PROLOG.MAC+MON:BUGS.MAC+MON:GLOBS.MAC R:PROLOG
@COP PROLOG.*.0 PROLOG-BUGS.*.*
!
.PROLN:::
.GOTO UNV%:'SN,N,Y,Y'/Unvs? /
.UNVY:::
!
PROKL::
@COMPILE MON:PROKL.MAC R:PROKL
PHYPAR::
@COMPILE MON:PHYPAR.MAC R:PHYPAR
NSPPAR::
@COMPILE MON:NSPPAR.MAC R:NSPPAR
SERCOD::
@COMPILE MON:SERCOD.MAC R:SERCOD
!
.UNVN:::
!
.DEFINE 'ANADEP' 
.GOTO ANA%:'SN,N,Y,Y'/Anaunv? /
.ANAY:::
.GOTO AFOR%:'SN,N,Y,Y'/Force compile of ANAUNV dependencies? /
.AFORY:::
.DEFINE 'ANADEP' /COMPILE
.DEFINE /NI? / Y
.DEFINE /Multinet? / Y
.DEFINE /Ip? / Y
.DEFINE /Tcp? / Y
.DEFINE /Tty? / Y
.DEFINE /Stg? / Y
.DEFINE /Mods? / Y
.AFORN:::
!
ANAUNV::
.GOTO ANM%:'SN,N,Y,Y'/Specifying MNTMN in MNTMN.MAC? /
.ANMY:::
@COMPILE MON:MNTMN.MAC+MON:ANAUNV.MAC R:ANAUNV
.GOTO ANAN
.ANMN:::
@COMPILE MON:ANAUNV.MAC R:ANAUNV
!
.ANAN:::
!
.GOTO DOM%:'SN,N,Y,Y'/Domsym? /
.DOMY:::
!
DOMSYM::
@COMPILE MON:DOMSYM.MAC R:DOMSYM
!
.DOMN:::
!
@COP PROLOG-NO-BUGS.UNV.0 PROLOG.UNV.1000
!
.GOTO NI%:'SN,N,Y,Y'/NI? /
.NIY:::
!
NIPAR::
@COMPILE MON:NIPAR.MAC R:NIPAR
NISYM::
@COMPILE MON:NISYM.MAC R:NISYM
NISRV::
@COMPILE MON:REL5.MAC+MON:TOPS.MAC+MON:NISRV.MAC+MON:PHYKNI.MAC R:NISRV
NIUSR::
@COMPILE MON:NIUSR.MAC R:NIUSR
NITEST::
@COMPILE MON:REL5.MAC+MON:NITEST.MAC R:NITEST
IPNIDV::
@COMPILE %'ANADEP' MON:IPNIDV.MAC R:IPNIDV
!
.NIN:::
.GOTO MNT%:'SN,N,Y,Y'/Multinet? /
.MNTY:::
!
MNETDV::
@COMPILE %'ANADEP' MON:REL5.MAC+MON:MNETDV.MAC R:MNETDV
1822DV::
@COMPILE %'ANADEP' MON:1822DV.MAC R:1822DV
IMPANX::
@COMPILE %'ANADEP' MON:IMPANX.MAC R:IMPANX
IMPBBN::
@COMPILE %'ANADEP' MON:IMPBBN.MAC R:IMPBBN
NFEPHY::
@COMPILE %'ANADEP' MON:NFEPHY.MAC R:NFEPHY
!
.MNTN:::
.GOTO IP%:'SN,N,Y,Y'/Ip? /
.IPY:::
!
IPFREE::
@COMPILE %'ANADEP' MON:REL5.MAC+MON:IPFREE.MAC R:IPFREE
IPIPIP::
@COMPILE %'ANADEP' MON:REL5.MAC+MON:IPIPIP.MAC R:IPIPIP
!
.IPN:::
.GOTO TCP%:'SN,N,Y,Y'/Tcp? /
.TCPY:::
!
TCPCRC::
@COMPILE %'ANADEP' MON:TCPCRC.MAC R:TCPCRC
TCPTCP::
;zzz 1 or 2 parts
@COMPILE %'ANADEP' MON:TCPTCP.MAC R:TCPTCP
;TCPT2P::
;@COMPILE %'ANADEP' MON:TCPT2P.MAC R:TCPT2P
TCPBBN::
@COMPILE %'ANADEP' MON:REL5.MAC+MON:TCPBBN.MAC R:TCPBBN
TCPJFN::
@COMPILE %'ANADEP' MON:REL5.MAC+MON:TCPJFN.MAC R:TCPJFN
!
.TCPN:::
.GOTO TTY%:'SN,N,Y,Y'/Tty? /
.TTYY:::
!
TTYSNV::
@COMPILE %'ANADEP' MON:ARPAF.MAC+MON:KLPRE.MAC+MON:TTYSRV.MAC+MON:TTANDV.MAC+MON:TTPHDV.MAC R:TTYSNV
TTYSDN::
@COMPILE %'ANADEP' MON:ARPAD.MAC+MON:KLPRE.MAC+MON:TTYSRV.MAC+MON:TTANDV.MAC+MON:TTPHDV.MAC R:TTYSDN
!
.TTYN:::
.GOTO STG%:'SN,N,Y,Y'/Stg? /
.STGY:::
!
STGAN::
@COMPIL/COMP MON:REL5.MAC+MON:KLPRE.MAC+MON:ANPLND.MAC+MON:PARSYF.MAC+MON:PARAMS.MAC+MON:STG.MAC R:STGAN
!
.STGN:::
!
MNTBEG::
@COMPILE MON:MNTBEG.MAC R:MNTBEG
MNTEND::
@COMPILE MON:MNTEND.MAC R:MNTEND
JSYSB::
@COMPILE MON:JSYSB.MAC R:JSYSB
!
.GOTO MODX%:'SN,N,Y,Y'/Mods? /
.MODXY:::
!
MEXEC::
@COMPILE %'ANADEP' MON:MEXEC.MAC R:MEXEC
!
.MODXN:::
!
@DEL PROLOG.UNV.1000
@EXP
!
.GOTO MODS%:'SN,N,Y,Y'/Mods? /
.MODSY:::
!
EFILIN::
@COMPILE %'ANADEP' MON:EXPRE.MAC+MON:FILINI.MAC R:EFILIN
FILMSC::
@COMPILE %'ANADEP' MON:FILMSC.MAC R:FILMSC
FORK::
@COMPILE %'ANADEP' MON:FORK.MAC R:FORK
GTJFN::
@COMPILE MON:GTJFN.MAC R:GTJFN
JSYSF::
@COMPILE %'ANADEP' MON:JSYSF.MAC R:JSYSF
PAGEM::
@COMPILE %'ANADEP' MON:PAGEM.MAC R:PAGEM
POSTLD::
@COMPILE %'ANADEP' MON:POSTLD.MAC R:POSTLD
SCHED::
@COMPILE %'ANADEP' MON:SCHED.MAC R:SCHED
!
.MODSN:::
.GOTO SYS%:'SN,N,Y,Y'/Sys? /
.SYSY:::
!
TAPE::
@COMPILE MON:TAPE.MAC R:TAPE
DTESRV::
@COMPILE MON:KLPRE.MAC+MON:DTESRV.MAC R:DTESRV
GETSAV::
@COMPILE MON:GETSAV.MAC R:GETSAV
LDINIT::
@COMPILE MON:LDINIT.MAC R:LDINIT
APRSRV::
@COMPILE MON:KLPRE.MAC+MON:APRSRV.MAC R:APRSRV
COMND::
@COMPILE MON:COMND.MAC R:COMND
DEVICE::
@COMPILE MON:DEVICE.MAC R:DEVICE
DIRECT::
@COMPILE MON:DIRECT.MAC R:DIRECT
DISC::
@COMPILE MON:DISC.MAC R:DISC
SWPALC::
@COMPILE MON:SWPALC.MAC R:SWPALC
DSKALC::
@COMPILE MON:DSKALC.MAC R:DSKALC
ENQ::
@COMPILE MON:ENQ.MAC R:ENQ
FREE::
@COMPILE MON:FREE.MAC R:FREE
FUTILI::
@COMPILE MON:FUTILI.MAC R:FUTILI
IO::
@COMPILE MON:IO.MAC R:IO
IPCF::
@COMPILE MON:IPCF.MAC R:IPCF
JSYSA::
@COMPILE MON:JSYSA.MAC R:JSYSA
LINEPR::
@COMPILE MON:KLPRE.MAC+MON:LINEPR.MAC+MON:LPFEDV.MAC R:LINEPR
CDPSRV::
@COMPILE MON:CDPSRV.MAC R:CDPSRV
CDRSRV::
@COMPILE MON:KLPRE.MAC+MON:CDRSRV.MAC+MON:CDKLDV.MAC R:CDRSRV
LOGNAM::
@COMPILE MON:LOGNAM.MAC R:LOGNAM
LOOKUP::
@COMPILE MON:LOOKUP.MAC R:LOOKUP
MAGTAP::
@COMPILE MON:MAGTAP.MAC R:MAGTAP
MSTR::
@COMPILE MON:MSTR.MAC R:MSTR
PHYH2::
@COMPILE MON:PHYH2.MAC R:PHYH2
PHYM2::
@COMPILE MON:PHYM2.MAC R:PHYM2
PHYM78::
@COMPILE MON:PHYM78.MAC R:PHYM78
PHYP4::
@COMPILE MON:PHYP4.MAC R:PHYP4
PHYX2::
@COMPILE MON:PHYX2.MAC R:PHYX2
PHYP2::
@COMPILE MON:PHYP2.MAC R:PHYP2
PHYSIO::
@COMPILE MON:PHYSIO.MAC R:PHYSIO
PLT::
@COMPILE MON:PLT.MAC R:PLT
PTR::
@COMPILE MON:PTR.MAC R:PTR
PTP::
@COMPILE MON:PTP.MAC R:PTP
DIAG::
@COMPILE MON:DIAG.MAC R:DIAG
SYSERR::
@COMPILE MON:SYSERR.MAC R:SYSERR
TIMER::
@COMPILE MON:TIMER.MAC R:TIMER
FESRV::
@COMPILE MON:KLPRE.MAC+MON:FESRV.MAC R:FESRV
MFLIN::
@COMPILE MON:MFLIN.MAC R:MFLIN
MFLOUT::
@COMPILE MON:MFLOUT.MAC R:MFLOUT
DATIME::
@COMPILE MON:DATIME.MAC R:DATIME
NSPSRV::
@COMPILE MON:NSPSRV.MAC R:NSPSRV
!
.SYSN:::
!
@COMPIL/COMP MON:ANNLND.MAC+MON:VERSIO.MAC R:VERSIO
!
.GOTO ANPLND
!
GOTO FORCE1
!
FORCE::
@NOERROR
@TAKE BATCH
@SET DEFAULT COMPILE MAC /COMPILE
@TAKE MON:ASEMBL.CMD
FORCE1::
@CHKPNT FORCE1
@EXPUNGE
@DELETE R:T20AN.REL
@EXPUNGE R:
@APPEND R:APRSRV.REL,R:SCHED.REL,R:PAGEM.REL,R:FORK.REL	R:T20AN.REL
@APPEND R:MEXEC.REL,R:GETSAV.REL,R:SYSERR.REL,R:COMND.REL R:T20AN.REL
@APPEND R:DEVICE.REL,R:DIRECT.REL,R:ENQ.REL,R:FREE.REL R:T20AN.REL
@APPEND R:FUTILI.REL,R:GTJFN.REL,R:IO.REL,R:IPCF.REL R:T20AN.REL
@APPEND R:JSYSA.REL,R:JSYSF.REL,R:LOGNAM.REL,R:LOOKUP.REL R:T20AN.REL
@APPEND R:MSTR.REL,R:SWPALC.REL,R:DISC.REL,R:EFILIN.REL	R:T20AN.REL
@APPEND R:FILMSC.REL,R:MFLIN.REL,R:MFLOUT.REL,R:DATIME.REL R:T20AN.REL
@APPEND R:PHYSIO.REL,R:DIAG.REL,R:DSKALC.REL,R:PHYH2.REL R:T20AN.REL
@APPEND R:PHYP4.REL,R:PHYP2.REL,R:TTYSDN.REL,R:FESRV.REL R:T20AN.REL
@APPEND R:MAGTAP.REL,R:TAPE.REL,R:TIMER.REL,R:PHYM2.REL	R:T20AN.REL
@APPEND R:PHYM78.REL,R:PHYX2.REL,R:DTESRV.REL,R:LINEPR.REL R:T20AN.REL
@APPEND R:CDRSRV.REL,R:PLT.REL,R:PTR.REL,R:PTP.REL,R:CDPSRV.REL R:T20AN.REL
@APPEND R:IMPANX.REL,R:IPIPIP.REL,R:IPFREE.REL,R:TTYSNV.REL R:T20AN.REL
;zzzz 1 or 2 parts
@APPEND R:TCPTCP.REL,R:TCPT2P,R:TCPCRC.REL,R:MNETDV.REL R:T20AN.REL
@APPEND R:IMPDV.REL,R:TCPJFN.REL,R:TCPBBN.REL,R:NSPSRV.REL R:T20AN.REL
@APPEND R:IPNIDV.REL,R:NISRV.REL,R:NITEST.REL,R:NIUSR.REL R:T20AN.REL
@APPEND R:KDDT.REL,R:MDDT.REL,R:POSTLD.REL R:T20AN.REL

!BUILD A BIG NON DECNET NON NI MONITOR

LINK::
ANPBIG::
@CHKPNT ANPBIG
@NOERROR
@TAKE BATCH
@DEL R:STGAN.REL,R:VERSIO.REL,AMON.EXE
@COMPIL/COMP MON:ANNBIG.MAC+MON:VERSIO.MAC R:VERSIO
@COMPIL/COMP MON:KLPRE.MAC+MON:ANPBIG.MAC+MON:PARAMS.MAC+MON:STG.MAC R:STGAN
@R LINK
*@MON:LNKANS.CCL
*R:T20AN/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
@DEL AMON.*
@RENAME AMONITR.EXE.0 AN-MONBIG.EXE
@VDIR AN-MONBIG.EXE.0,
@CHECKSUM SEQ
@

!BUILD A LARGE NON DECNET NON NI MONITOR

ANPLGE::
@CHKPNT ANPLGE
@NOERROR
@TAKE BATCH
@DEL R:STGAN.REL,R:VERSIO.REL,AMON.EXE
@COMPIL/COMP MON:ANNLGE.MAC+MON:VERSIO.MAC R:VERSIO
@COMPIL/COMP MON:KLPRE.MAC+MON:ANPLGE.MAC+MON:PARAMS.MAC+MON:STG.MAC R:STGAN
@R LINK
*@MON:LNKANS.CCL
*R:T20AN/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
@DEL AMON.*
@RENAME AMONITR.EXE.0 AN-MONLGE.EXE
@VDIR AN-MONLGE.EXE.0,
@CHECKSUM SEQ
@

!BUILD A LARGE NON DECNET NI MONITOR

ANPLNI::
@CHKPNT ANPLNI
@NOERROR
@TAKE BATCH
@DEL R:STGAN.REL,R:VERSIO.REL,AMON.EXE
@COMPIL/COMP MON:ANNLNI.MAC+MON:VERSIO.MAC R:VERSIO
@COMPIL/COMP MON:KLPRE.MAC+MON:ANPLNI.MAC+MON:PARAMS.MAC+MON:STG.MAC R:STGAN
@R LINK
*@MON:LNKAND.CCL
*R:T20AN/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
@DEL AMON.*
@RENAME AMONITR.EXE.0 AN-MONLNI.EXE
@VDIR AN-MONLNI.EXE.0,
@CHECKSUM SEQ
@

!BUILD A LARGE NON DECNET NON AN20 NI MONITOR

ANPNAN::
@CHKPNT ANPNAN
@NOERROR
@TAKE BATCH
@DEL R:STGAN.REL,R:VERSIO.REL,AMON.EXE
@COMPIL/COMP MON:ANNNAN.MAC+MON:VERSIO.MAC R:VERSIO
@COMPIL/COMP MON:KLPRE.MAC+MON:ANPNAN.MAC+MON:PARAMS.MAC+MON:STG.MAC R:STGAN
@R LINK
*@MON:LNKAND.CCL
*R:T20AN/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
@DEL AMON.*
@RENAME AMONITR.EXE.0 AN-MONNAN.EXE
@VDIR AN-MONNAN.EXE.0,
@CHECKSUM SEQ
@

!BUILD A LARGE DECNET NON NI MONITOR

ANPLGD::
@CHKPNT ANPLGD
@NOERROR
@TAKE BATCH
@DEL R:STGAN.REL,R:VERSIO.REL,AMON.EXE
@COMPIL/COMP MON:ANNLGD.MAC+MON:VERSIO.MAC R:VERSIO
@COMPIL/COMP MON:KLPRE.MAC+MON:ANPLGD.MAC+MON:PARAMS.MAC+MON:STG.MAC R:STGAN
@R LINK
*@MON:LNKAND.CCL
*R:T20AN/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
@DEL AMON.*
@RENAME AMONITR.EXE.0 AN-MONLGD.EXE
@VDIR AN-MONLGD.EXE.0,
@CHECKSUM SEQ
@

!BUILD A LARGE DECNET NI MONITOR

.ANPLND:::
.GOTO FIN%:'SN,N,Y,Y'/Link? /
.FINY:::
!
;@CHKPNT ANPLND
@NOERROR
;@TAKE BATCH
;@DEL R:STGAN.REL,R:VERSIO.REL,AMON.EXE
;@COMPIL/COMP MON:ANNLND.MAC+MON:VERSIO.MAC R:VERSIO
;@COMPIL/COMP MON:KLPRE.MAC+MON:ANPLND.MAC+MON:PARAMS.MAC+MON:STG.MAC R:STGAN
!
LINK::
@R LINK
;*@MON:LNKAND.CCL
TTY:/LOG/LOGL:5
AMON/SAVE,/HASHSIZE:12007, -
/FRECOR:0, -
/SET:RSCOD:1000, -
/SET:INCOD:121000, -
/SET:RSDAT:143000,/SYMSEG:PSECT:RSDAT,/PATCHSIZE:100, -
/SET:PPVAR:205000, -
/SET:RSVAR:211000, -
/SET:SYVAR:327000, -
/SET:PSVAR:330000, -
/SET:JSVAR:346000, -
/SET:NRVAR:424000, -
/SET:BGPTR:450000/UPTO:447777, -
/SET:NRCOD:452000, -
/SET:BGSTR:727000, -
/SET:POSTCD:741000, -
/SET:NPVAR:727000, -
;/NOLOCALS, -
R:MONSYM.REL, -
R:LDINIT, -
R:VERSIO,R:STGAN, -
;/LOCALS, -
*;R:T20AN/S, -
R:APRSRV.REL/s,R:SCHED.REL/s,R:PAGEM.REL/s,R:FORK.REL/s, -
R:MEXEC.REL/s,R:GETSAV.REL/s,R:SYSERR.REL/s,R:COMND.REL/s, -
R:DEVICE.REL/s,R:DIRECT.REL/s,R:ENQ.REL/s,R:FREE.REL/s, -
R:FUTILI.REL/s,R:GTJFN.REL/s,R:IO.REL/s,R:IPCF.REL/s, -
R:JSYSA.REL/s,R:JSYSF.REL/s,R:LOGNAM.REL/s,R:LOOKUP.REL/s, -
R:MSTR.REL/s,R:SWPALC.REL/s,R:DISC.REL/s,R:EFILIN.REL/s, -
R:FILMSC.REL/s,R:MFLIN.REL/s,R:MFLOUT.REL/s,R:DATIME.REL/s, -
R:PHYSIO.REL/s,R:DIAG.REL/s,R:DSKALC.REL/s,R:PHYH2.REL/s, -
R:PHYP4.REL/s,R:PHYP2.REL/s,R:TTYSDN.REL/s,R:FESRV.REL/s, -
R:MAGTAP.REL/s,R:TAPE.REL/s,R:TIMER.REL/s,R:PHYM2.REL/s, -
R:PHYM78.REL/s,R:PHYX2.REL/s,R:DTESRV.REL/s,R:LINEPR.REL/s, -
R:CDRSRV.REL/s,R:PLT.REL/s,R:PTR.REL/s,R:PTP.REL/s, -
R:CDPSRV.REL/s,R:TTYSNV.REL/s, -
r:mntbeg,r:jsysb,r:1822dv/s,r:impbbn/s,r:nfephy/s, -
R:IMPANX.REL/s,R:IPIPIP.REL/s,R:IPFREE.REL/s, -
;zzzz 1 or 2 parts
;R:TCPTCP.REL/s,R:TCPT2P.REL/s,R:TCPCRC.REL/s,R:MNETDV.REL/s, -
R:TCPTCP.REL/s,R:TCPCRC.REL/s,R:MNETDV.REL/s, -
R:TCPJFN.REL/s,R:TCPBBN.REL/s, -
r:mntend, -
R:NSPSRV.REL/s, -
R:IPNIDV.REL/s,R:NISRV.REL/s,R:NITEST.REL/s,R:NIUSR.REL/s, -
R:KDDT.REL,R:MDDT.REL,R:POSTLD.REL, -
*;/NOLOCALS, -
*;/SYSLIB, -
*/G
@EXP
AMON::
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
DBUGSW/1
DCHKSW/1
WEFLAG/-1
LPSNAM/"/CWL/
BUGH0+1/JFCL
=G
!
;setssp+13/jfcl
;ddmp0+2/jrst ddmpa
; no moved ... chkum1-5/tln chkdms
!
;@DEL AMON.*
;@RENAME AMONITR.EXE.0 AN-MONLND.EXE
;@VDIR AN-MONLND.EXE.0,
;@CHECKSUM SEQ
@
.FINN:::
FINFIN::
@SEND 6 %/!CTLFILENAME/ is done
@
%TERR::
@SEND 6 %/!CTLFILENAME/ is running out of time
@CONT
@
%FIN::
!
@DEL PROLOG.UNV.1000
@EXP
!
