REDIT 1(104) COMPARE by user CLYNN, 10-Feb-86 18:55:19
File 1: CWL:<DEC-6-1-BASE.AP7>FILMSC.MAC.1
File 2: CWL:<5-4-NET>FILMSC.MAC.1
***** CHANGE #1; PAGE 21, LINE 41; PAGE 21, LINE 41
	.MOSLC,,TTMSLC		;SET LINE COUNTER
	.MORLM,,TTMRLM		;READ LINE MAXIMUM
	.MOSLM,,TTMSLM		;SET LINE MAXIMUM
	.MOTPS,,TTLIPS		;SET PSI FOR SPECIFIC LINE 
	.MOPCS,,TTPCS		;SET PAGE PAUSE CHARACTER
	.MOPCR,,TTPCR		;READ PAGE PAUSE CHARACTER

 ---------------------------------
	.MOSLC,,TTMSLC		;SET LINE COUNTER
	.MORLM,,TTMRLM		;READ LINE MAXIMUM
	.MOSLM,,TTMSLM		;SET LINE MAXIMUM
	.MOTPS,,TTLIPS		;SET PSI FOR SPECIFIC LINE 
	.MOPCS,,TTPCS		;SET PAGE PAUSE CHARACTER
	.MOPCR,,TTPCR		;READ PAGE PAUSE CHARACTER
	.MONEG,,TTTNEG		;Negotiate TELNET option
	.MOGSB,,TTTGSB		;Get TELNET subnegotiation
	.MOSSB,,TTTSSB		;Send TELNET subnegotiation string


