REDIT 1(104) COMPARE by user CLYNN, 13-Feb-86 22:06:32
File 1: CWL:<DEC-6-1-BASE>GLOBS.MAC.1
File 2: CWL:<CMU>GLOBS.MAC.34
***** CHANGE #1; PAGE 1, LINE 654; PAGE 1, LINE 654
	XLIST
	.XCREF

DEFINE QEXT (SYM)<
IRP SYM,<.IF SYM,NEEDED,<EXTERN SYM>>
>

QEXT <TAD11,TO11TM,DTETIM>
 ---------------------------------
	XLIST
	.XCREF

DEFINE QEXT (SYM)<
IRP SYM,<.IF SYM,NEEDED,<EXTERN SYM>>
>
QEXT <TAD11,TO11TM,DTETIM>

***** CHANGE #2; PAGE 1, LINE 676; PAGE 1, LINE 675
QEXT <INIDV1,MCPRON,RLDFRK>

QEXT <NWSPGS,WSPGS,XWSPGS>		;TEMP - TO BE REMOVED

;From here on in alphabetical order

QEXT <ABFRZB,ABTBFF,ABTBUF,ACBAS,ACCCHK,ACCTSL,ACCTSR,ACCTSX>
QEXT <ACJFN,ACJJN,ACJKIL,ACKLST,ACSAV0,ACTLCK,ACTOFN,ACTPG,ACTPGN,ADJALC>
 ---------------------------------
QEXT <INIDV1,MCPRON,RLDFRK>

QEXT <NWSPGS,WSPGS,XWSPGS>		;TEMP - TO BE REMOVED

;From here on in alphabetical order

;QEXT <ABFRZB,ABTBFF,ABTBUF,ACBAS,ACCCHK,ACCTSL,ACCTSR,ACCTSX>
QEXT <ABFRZB,ACBAS,ACCCHK,ACCTSL,ACCTSR,ACCTSX>
QEXT <ACJFN,ACJJN,ACJKIL,ACKLST,ACSAV0,ACTLCK,ACTOFN,ACTPG,ACTPGN,ADJALC>

***** CHANGE #3; PAGE 1, LINE 817; PAGE 1, LINE 817
QEXT <FORCTC,FORCTM,FORKN,FORKX,FPC>
QEXT <FPG0,FPG0A,FPG1,FPG1A,FPG2,FPG2A,FPG3,FPG3A>
QEXT <FPTA>
QEXT <FPTABL,FRECB,FREFK,FREJFK,FREJOB,FREJP,FREJPA,FRESPT>
QEXT <FRESTR,FRJSSO,FRJSST,FRKSTM,FRKSTO,FRTOFF,FRTON>
QEXT <FRZLST,FRZWT,FSHFIL,FSIBLK,FSIINI,FSKT,FSMAX,FSN>
QEXT <FSSUN,FSTGFB,FSTTBL,FUNLK,FUNLKI,,FUNNYC,GAPRID,GCCOR,GCCOR0,GCCTIM>
QEXT <GCMINP,GDIRST,GDSTX,GENBLK,GENGEN,GETBAT,GETCAL,GETCHA>
 ---------------------------------
QEXT <FORCTC,FORCTM,FORKN,FORKX,FPC>
QEXT <FPG0,FPG0A,FPG1,FPG1A,FPG2,FPG2A,FPG3,FPG3A>
QEXT <FPTA>
QEXT <FPTABL,FRECB,FREFK,FREJFK,FREJOB,FREJP,FREJPA,FRESPT>
QEXT <FRESTR,FRJSSO,FRJSST,FRKSTM,FRKSTO,FRTOFF,FRTON>
QEXT <FRZLST,FRZWT,FSHFIL,FSIBLK,FSIINI,FSKT,FSMAX,FSN>
QEXT <FSSUN,FSTGFB,FSTTBL,FUNLK,FUNLKI,FUNNYC,GAPRID,GCCOR,GCCOR0,GCCTIM>
QEXT <GCMINP,GDIRST,GDSTX,GENBLK,GENGEN,GETBAT,GETCAL,GETCHA>

***** CHANGE #4; PAGE 1, LINE 836; PAGE 1, LINE 836
QEXT <GTTAB,GTTOPF,GTWFRK,GT%DEF,GUDOBJ,HALTF1>
QEXT <HALTT,HASHLN,HB%1OK,HB%2OK,HB%HBM,HB%MUN>
QEXT <HB%PUB,HB%WLK,HBCCHK,HBLEN,HIDSYF,HIBERT,HLTFK1>
QEXT <HLTJB,HM1BLK,HM2BLK,HOME,HOMLUN,HOMMID,HOMSER>
QEXT <HOMNAM,HOMPG,HOMPGA,HOMSNM,HOMTAB,HOMTBL,HOMUID,HOSTN,HOSTNN>
QEXT <HQFSUM,HQLAV,HSHPG,HSPTTM,HSTDED,HSTHSH,HSTINI>
QEXT <HSTNAM,HSTSTS,HSYBLK,HSYPTR,HSYST1,HSYSWP,HTNADR,HUSPTR,HWPT,HWPTA>
QEXT <I8CAL,I8COP,IBFRC,IBFRC1,IBPTIM>
 ---------------------------------
QEXT <GTTAB,GTTOPF,GTWFRK,GT%DEF,GUDOBJ,HALTF1>
QEXT <HALTT,HASHLN,HB%1OK,HB%2OK,HB%HBM,HB%MUN>
QEXT <HB%PUB,HB%WLK,HBCCHK,HBLEN,HIDSYF,HIBERT,HLTFK1>
QEXT <HLTJB,HM1BLK,HM2BLK,HOME,HOMLUN,HOMMID,HOMSER>
QEXT <HOMNAM,HOMPG,HOMPGA,HOMSNM,HOMTAB,HOMTBL,HOMUID,HOSTN,HOSTNN>
QEXT <HQFSUM,HQLAV,HSHPG,HSPTTM,HSTDED,HSTHSH,HSTINI>
QEXT <HSTNAM,HSTNML,HSTSTS,HSYBLK,HSYPTR,HSYST1,HSYSWP,HTNADR,HUSPTR,HWPT,HWPTA>
QEXT <I8CAL,I8COP,IBFRC,IBFRC1,IBPTIM>

***** CHANGE #5; PAGE 1, LINE 847; PAGE 1, LINE 847
QEXT <IGDMSG,IGDTIM,IGTDAL,IICSLF,IIMBUF,ILIST,ILRD,ILTAB>
;**;[2873]ADD ILUUO1
QEXT <ILUUO,ILUUO1,ILWR,IMC8XM>
QEXT <IMCCLK,IMCCNP,IMCGC,IMCGIB,IMCIDL,IMCLL0>
QEXT <IMCLST,IMCNCC,IMCNCK,IMCNRB,IMCNVI,IMCOS>
QEXT <IMCP1,IMCRFN,IMCTS,IMECHF,IMIB,IMIDSP>
QEXT <IMINFB,IMINP,IMISRT,IMITYP,IMMPTR,IMNIDL,IMODSP>
QEXT <IMODUN,IMOIRD,IMOTYP,IMP8XB,IMP8XC,IMP8XI,IMP8XO>
QEXT <IMP8XQ,IMP8XS,IMPABL,IMPALL,IMPBEG>
QEXT <IMPCCH,IMPCHK,IMPCHO,IMPCHR,IMPCHU,IMPCLL>
QEXT <IMPCLS,IMPDNT,IMPDRQ,IMPERR,IMPFLG,IMPFLS,IMPFPF>
QEXT <IMPFRI,IMPGDM,IMPGI1,IMPGIB,IMPGTN,IMPHBI,IMPHBO>
QEXT <IMPHLT,IMPIAC,IMPIBI,IMPIBO,IMPICX,IMPINI,IMPINP>
QEXT <IMPINR,IMPINS,IMPIOV,IMPLBT,IMPLT1,IMPLT2>
QEXT <IMPLT3,IMPLT4,IMPLT5,IMPNCL,IMPNFI,IMPNIB,IMPNLK>
QEXT <IMPNOL,IMPNOS,IMPOB,IMPOBI,IMPOBO,IMPOJB>
QEXT <IMPOPL,IMPOPS,IMPORD,IMPOUP,IMPRDL,IMPRDT,IMPRDY>
QEXT <IMPRLQ,IMPRRP,IMPRSD,IMPRSN,IMPRSS,IMPRTS>
QEXT <IMPSDB,IMPSTR,IMPSYN,IMPTIM,IMPTM2,IMPUPT>
QEXT <IMPXOU,IMSRST,IMSTK,IMULKB,INCMNT>
QEXT <INCOD,INCODL,INCODP,INCODZ,INDPTR>
 ---------------------------------
QEXT <IGDMSG,IGDTIM,IGTDAL,IICSLF,IIMBUF,ILIST,ILRD,ILTAB>
;**;[2873]ADD ILUUO1
QEXT <ILUUO,ILUUO1,ILWR,IMC8XM>
QEXT <IMCCLK,IMCCNP,IMCGC,IMCGIB,IMCIDL,IMCLL0>
QEXT <IMCLST,IMCNCC,IMCNCK,IMCNRB,IMCNVI,IMCOS>
QEXT <IMCP1,IMCRFN,IMCTS,IMECHF,IMIB,IMIDSP>
QEXT <IMINP,IMISRT,IMITYP,IMMPTR,IMNIDL,IMODSP>
QEXT <IMODUN,IMOIRD,IMOTYP>
QEXT <IMP8XQ>
QEXT <IMPCCH,IMPCHR>
QEXT <IMPDNT,IMPDRQ,IMPFLS,IMPFPF>
QEXT <IMPGI1,IMPGIB,IMPGTN,IMPHBI,IMPHBO>
QEXT <IMPIAC,IMPICX,IMPINI,IMPINP>
QEXT <IMPIOV>
QEXT <IMPOB,IMPOBI,IMPOBO,IMPOJB>
QEXT <IMPORD,IMPOUP,IMPRDL,IMPRDT,IMPRDY>
QEXT <IMPRLQ,IMPRSD,IMPRSN,IMPRSS>
QEXT <IMPUPT>
QEXT <IMPXOU,INCMNT>
QEXT <INCOD,INCODL,INCODP,INCODZ,INDPTR>

***** CHANGE #6; PAGE 1, LINE 901; PAGE 1, LINE 900
QEXT <LPTN,LPTRST,LPTSLA,LPTTLS,LPWINA,LPXJEN,LPXPTB>
QEXT <LQFSUM,LQLAV,LSKT,LSTAGE,LSTERR,LSTLGN,LSTLLS,LSTINT,LSTPFK,LSTTMR,LSTXGR,LSTXGT,LUNLK0>
QEXT <LUNLKF,MAKIDX,MAPBTB,MAPDIR,MAPFKH,MAPJSB>
QEXT <MAPPHA,MAPRCA,MASBGX,MAXBAD,MAXBFR,MAXBP,MAXBPM,MAXCHN>
QEXT <MAXCOR,MAXDRA,MAXDRM,MAXFKS,MAXFPU,MAXHNR,MAXJFN,MAXLC>
QEXT <MAXLW,MAXNOD,MAXNR,MAXPPB,MAXQ,MAXSEC>
QEXT <MAXSPL,MAXWPM,MDDDIR,MDDEXT,MDDNAM,MDDTX,MDDVER,MDSKIO>
QEXT <MEMPA,MEMPAR,MENT0,MENTM,MENTU,MFRKWD,MHOSTS>
 ---------------------------------
QEXT <LPTN,LPTRST,LPTSLA,LPTTLS,LPWINA,LPXJEN,LPXPTB>
QEXT <LQFSUM,LQLAV,LSKT,LSTAGE,LSTERR,LSTLGN,LSTLLS,LSTINT,LSTPFK,LSTTMR,LSTXGR,LSTXGT,LUNLK0>
QEXT <LUNLKF,MAKIDX,MAPBTB,MAPDIR,MAPFKH,MAPJSB>
QEXT <MAPPHA,MAPRCA,MASBGX,MAXBAD,MAXBFR,MAXBP,MAXBPM,MAXCHN>
QEXT <MAXCOR,MAXDRA,MAXDRM,MAXFKS,MAXFPU,MAXHNR,MAXJFN,MAXLC>
QEXT <MAXLW,MAXNOD,MAXNR,MAXPPB,MAXQ,MAXSEC>
QEXT <MAXSPL,MDDDIR,MDDEXT,MDDNAM,MDDTX,MDDVER,MDSKIO>
QEXT <MEMPA,MEMPAR,MENT0,MENTM,MENTU,MFRKWD,MHOSTS>

***** CHANGE #7; PAGE 1, LINE 928; PAGE 1, LINE 927
QEXT <NAMLUK,NAMUTP,NATMSK,NBNSB,NBP,NBPROC,NBQ,NBSL,NBSWP,NBW>
QEXT <NBWT,NCHBF,NCPFRK,NCPLCK,NCPLCN,NCPLFC>
QEXT <NCPLLK,NCPLPC,NCPUPT,NCSWCH,NDEV,NDIRPG,NDLL,NDRMEW>
QEXT <NDSKEW,NDSKUT,NDST,NDUMP,NEBAL,NEGCHK,NEGTIM>
QEXT <NETAWD,NETBAL,NETBTC,NETBUF,NETCHK,NETCNC>
QEXT <NETDAL,NETDED,NETDTB,NETDWN,NETFLD,NETFRE,NETFRK,NETHDN,NETHLK>
QEXT <NETHST,NETINI,NETKFK,NETLGO,NETMOV,NETRAL>
QEXT <NETSTS,NETTCH,NETTCS,NETTIM,NETWK1,NETWKF>
QEXT <NEWIB,NFACHK,NFBSZ,NFKS,NFKSPP,NGCCOR,NGOJOB>
QEXT <NHIPG,NHOME,NHOSTS,NHQFK,NHSTN,NHSTST,NIC>
QEXT <NIDXPG,NILDTB,NIMSTK,NINIDV,NINIPG,NJOBS>
QEXT <NLFKS,NLHOST,NLINES,NLQFK,NMAPLK,NNAMES,NNTBFS>
QEXT <NOATRF,NODINI,NODLOK,NODMAP,NODSIZ,NODTSZ,NOF,NOFN,NOHOST,NOPCNT>
QEXT <NORMTF,NORMTY,NOSK11,NOSKD0,NOSTR,NOUTX,NOUTXX>
QEXT <NPDRMS,NPG,NPGSBT,NPGSFE,NPIPDL,NPISET>
QEXT <NPMAX,NPRIVP,NPSIPG,NPTYS,NPVAR,NPVARL,NPVARP,NPVARZ>
 ---------------------------------
QEXT <NAMLUK,NAMUTP,NATMSK,NBNSB,NBP,NBPROC,NBQ,NBSL,NBSWP,NBW>
QEXT <NBWT,NCHBF,NCPFRK,NCPLCK,NCPLCN,NCPLFC>
QEXT <NCPLLK,NCPLPC,NCPUPT,NCSWCH,NDEV,NDIRPG,NDLL,NDRMEW>
QEXT <NDSKEW,NDSKUT,NDST,NDUMP,NEBAL,NEGCHK,NEGTIM>
QEXT <NETAWD,NETBAL,NETBTC,NETBUF,NETCHK,NETCNC>
QEXT <NETDAL,NETDED,NETDTB,NETDWN,NETFLD,NETFRE,NETFRK,NETHDN,NETHLK>
QEXT <NETHST,NETKFK,NETLGO,NETMOV,NETRAL>
QEXT <NETSTS,NETTCH,NETTCS,NETTIM,NETWK1,NETWKF>
QEXT <NEWIB,NFACHK,NFBSZ,NFKS,NFKSPP,NGCCOR,NGOJOB>
QEXT <NHIPG,NHOME,NHOSTS,NHQFK,NHSTN,NHSTST,NIC>
QEXT <NIDXPG,NILDTB,NIMSTK,NINIDV,NINIPG,NJOBS>
QEXT <NLFKS,NLHOST,NLINES,NLQFK,NMAPLK,NNAMES>
QEXT <NOATRF,NODINI,NODLOK,NODMAP,NODSIZ,NODTSZ,NOF,NOFN,NOHOST,NOPCNT>
QEXT <NORMTF,NORMTY,NOSK11,NOSKD0,NOSTR,NOUTX,NOUTXX>
QEXT <NPDRMS,NPG,NPGSBT,NPGSFE,NPIPDL,NPISET,NPISK6>
QEXT <NPMAX,NPRIVP,NPSIPG,NPTYS,NPVAR,NPVARL,NPVARP,NPVARZ>

***** CHANGE #8; PAGE 1, LINE 945; PAGE 1, LINE 944
QEXT <NQUEUE,NRBKGR,NRCOD,NRCODL,NRCODP,NRCODZ>
QEXT <NRCPCZ,NREMJ,NREMR,NRESDN,NRESFB,NRJAVS>
QEXT <NROFN,NRPLEV,NRPLQ,NRPMIN,NRSNDM,NRSPG>
QEXT <NRTWTS,NRVAR,NRVARL,NRVARP,NRVARZ,NRVCPG>
QEXT <NSALNK,NSBYTR,NSBYTS,NSCONR,NSCONS,NSDIR0,NSDIRT,NSINAC,NSKDP,NSKED>
QEXT <NSKFLV,NSKT,NSMSGR,NSMSGS,NSPCH7,NSPINI,NSPMCB,NSPMQ,NSPQ,NSPSPC,NSPVEC>
QEXT <NSQ,NSRCNE,NSSNTQ,NSSUN,NSTAT,NSTIMO,NSWPGS,NTBFIX,NTBUFS,NTCMAX,NTCTAB,NTCOFF>
QEXT <NTMS,NTRFE,NTRK,NTSK,NTSQWD,NTTBF,NTTBL,NTTD10>
 ---------------------------------
QEXT <NQUEUE,NRBKGR,NRCOD,NRCODL,NRCODP,NRCODZ>
QEXT <NRCPCZ,NREMJ,NREMR,NRESDN,NRESFB,NRJAVS>
QEXT <NROFN,NRPLEV,NRPLQ,NRPMIN,NRSNDM,NRSPG>
QEXT <NRTWTS,NRVAR,NRVARL,NRVARP,NRVARZ,NRVCPG>
QEXT <NSALNK,NSBYTR,NSBYTS,NSCONR,NSCONS,NSDIR0,NSDIRT,NSINAC,NSKDP,NSKED>
QEXT <NSKFLV,NSKT,NSMSGR,NSMSGS,NSPCH7,NSPINI,NSPMCB,NSPMQ,NSPQ,NSPSPC,NSPVEC>
QEXT <NSQ,NSRCNE,NSSNTQ,NSSUN,NSTAT,NSTIMO,NSWPGS,NTBUFS,NTCMAX,NTCTAB,NTCOFF>
QEXT <NTMS,NTRFE,NTRK,NTSK,NTSQWD,NTTBF,NTTBL,NTTD10>

***** CHANGE #9; PAGE 1, LINE 967; PAGE 1, LINE 966
QEXT <PGROFF,PGRON,PGRTRP,PGSIBS,PGSOBS,PGTIM,PHCVBO,PHYALC,PHYALZ>
QEXT <PHYBLK,PHYCCW,PHYCHK,PHYCHL>
QEXT <PHYCHT,PHYCNT,PHYINI,PHYINT,PHYIOW,PHYKIL,PHYLOG>
QEXT <PHYMOV,PHYOFL,PHYONL,PHYPDN,PHYPOS,PHYRST,PHYRWD>
QEXT <PHYSDN,PHYSEC,PHYSIO,PHYSTO,PHYTIM,PHYUDB,PHYUNL>
QEXT <PHYUNT,PHYXFL,PI1AC1,PI4AC,PI4R,PI5AC>
QEXT <PI6AC,PI6R,PI7AC1,PIAC,PIAPRX,PIDINI>
QEXT <PIDJBI,PIDKFK,PIDLOK,PIDRFK,PIDWAT,PIFL>
 ---------------------------------
QEXT <PGROFF,PGRON,PGRTRP,PGSIBS,PGSOBS,PGTIM,PHCVBO,PHYALC,PHYALZ>
QEXT <PHYBLK,PHYCCW,PHYCHK,PHYCHL>
QEXT <PHYCHT,PHYCNT,PHYINI,PHYINT,PHYIOW,PHYKIL,PHYLOG>
QEXT <PHYMOV,PHYOFL,PHYONL,PHYPDN,PHYPOS,PHYRST,PHYRWD>
QEXT <PHYSDN,PHYSEC,PHYSIO,PHYSTO,PHYTIM,PHYUDB,PHYUNL>
QEXT <PHYUNT,PHYXFL,PI1AC1,PI4AC,PI4R,PI5AC>
QEXT <PI6AC,PI6R,PI6STK,PI7AC1,PIAC,PIAPRX,PIDINI>
QEXT <PIDJBI,PIDKFK,PIDLOK,PIDRFK,PIDWAT,PIFL>

***** CHANGE #10; PAGE 2, LINE 11; PAGE 2, LINE 11
QEXT <.STDDP,.STDEV,.STDFE,.STDFP,.STDIR,.STDMX,.STDNE>
QEXT <.STDSD,.STKST,.STP,.VACCT>
QEXT <BUGTIM,BUGINT,BUGTMS>
;TEMP - 3A ONLY
QEXT <XB2RED,XB2WRT>
QEXT <BLKLLK>

QEXT <ADDOUT,OUTSEG,NODTBL,MAXHST>
QEXT <ASGWDW,BLKASG,CMPLEN,DCNNAM,DCNSET,EXTSET,ITSID>
QEXT <ITSNAM,ITSNUM,LASTSK,LLBIT,LLBITS,LLHEAD,LLLLCK>
QEXT <MAXBLK,MAXEXP,MAXLNK,MCBDTE,MSGQ,NAKCNT,NETDIR>
QEXT <NETSR1,NETSQ1,NETUIN,NETUOU,NODNUM,NSPLPB,NSPMAX>
QEXT <OBJMAX,OBJTBL,OPNDNC,OPNSRC,OURNUM>
QEXT <PRSNAM,RMSGQ,SMSGQ,SRCNAM,SRNSET,VERSET>
QEXT <STMXDF,ASMCB,TTSETH>
 ---------------------------------
QEXT <.STDDP,.STDEV,.STDFE,.STDFP,.STDIR,.STDMX,.STDNE>
QEXT <.STDSD,.STKST,.STP,.VACCT>
QEXT <BUGTIM,BUGINT,BUGTMS>
;TEMP - 3A ONLY
QEXT <XB2RED,XB2WRT>
QEXT <BLKLLK>
QEXT <ADDOUT,OUTSEG,NODTBL,MAXHST>
QEXT <ASGWDW,BLKASG,CMPLEN,DCNNAM,DCNSET,EXTSET,ITSID>
QEXT <ITSNAM,ITSNUM,LASTSK,LLBIT,LLBITS,LLHEAD,LLLLCK>
QEXT <MAXBLK,MAXEXP,MAXLNK,MCBDTE,MSGQ,NAKCNT,NETDIR>
QEXT <NETSR1,NETSQ1,NETUIN,NETUOU,NODNUM,NSPLPB,NSPMAX>
QEXT <OBJMAX,OBJTBL,OPNDNC,OPNSRC,OURNUM>
QEXT <PRSNAM,RMSGQ,SMSGQ,SRCNAM,SRNSET,VERSET>
QEXT <STMXDF,ASMCB,TTSETH>

***** CHANGE #11; PAGE 7, LINE 14; PAGE 2, LINE 32
QEXT <ASGRSB,TTPPCS,TTPPCR,LSTIPC,FRKNOP>
QEXT <PHYDUA,DUALCT,PI5R,OLDIDL,SETPCV>
QEXT <PATLEV,DMSLEV,TTCLSH>

;ARPANET SYMBOLS

QEXT <IMIS32,IMOS32,CHKBUF,IMPIWC,IMPOWC,IMPRBF,IMPSV,TNBFFL>
QEXT <%NETS,$NETS,ANT3EN,ASNWTB,BADPCT,BULKND,BULKST,CLEARQ,CLRLCK,CLRWTB,DQ>
QEXT <FNDPGW,FREAVL,FREINI,FRELCK,GATINI,GENCFL,GETBBK,GETBLK,GWTAB,INETID>
QEXT <INETLB,INITQ,INTABC,INTBEG,INTBFF,INTBLK,INTBYP>
QEXT <INTCKS,INTCLS,INTFAC,INTFLG>
QEXT <INTFRE,INTFRI,INTFRK,INTFSP,INTFSZ,INTHST,INTIBD,INTIBI,INTIBO,INTIX>
QEXT <INTLGO,INTLHX,INTNCP,INTNET,INTNFB,INTNFI,INTNIB,INTOBI,INTOBO,INTON>
QEXT <INTOOT,INTPIX,INTRAN,INTRAQ,INTRAT,INTSCR,INTSEC,INTSIZ,INTSVC,INTSVR>
QEXT <INTSVT,INTTIM,INTTRC,INTWTB,INTXPB,INTXPW,INTZOT,LCKCAL,LCLHID,MAXNET>
QEXT <MRGFLG,NETGWA,NFIXED,NIQ,NLHOST,NQ,ODDBLK,PPBLCK,PPBUF,PRNPKI,RELLCK>
QEXT <RETBLK,RETPKT,RPICHK,RPICHN,RPIIB,RPIICT,RPIINI,RPIINP,RPIOB,RPIOBI>
QEXT <RPIOBO,RPIOCT,RPIOUP,RPIQOB,RPIS32,RPISRT,RPISV,RPISVX,RPIXOU,RPOS32>
QEXT <SETHIQ,SETLCK,SETSPQ,SETWTB,SNDARP,SNDGAT,SNDPRN,SNDRCC,UNLCK,WTBINI>
QEXT <DATCKS,ICMCHK,ICMCKS,ICMFLG,ICMICM,ICMINI,ICMIPQ,ICMON,ICMPCL,ICMPRC>
QEXT <ICMSID,ICMTIM,ICMTM0,PINGT0,PINGTM,INQCHK,INQFLG,INQICM,INQINI,INQIPQ>
QEXT <INQON,INQPCL,INQPRC,INQTIM,INTQFK,INTQHD,INTQJB,INTQLK,INTQM0,INTQM1>
QEXT <INTQM2,INTQM3,INTQMX,INTQOB,INTQSP,INTQT0,INTQTM,INTQV0,INTQV1>
QEXT <INTQV2,INTQV3>
QEXT <ABTCBS,ABTCON,ABTJCS,ABTPTR,ACDLAY,BG,BGRNCT,BGUSE,BITS,BYTRCT,BYTSCT>
QEXT <CHKWND,CLOSE1,CLRBLK,DBGIN,DBGINT,DG,DGRNCT,DGUSE,DUPKCT,DWNSHR,ENCPKT>
QEXT <FINRCT,FINSCT,FKABCP,FRCPKT,GETRBS,IMULKB,INTRBF,IP,IPDLAY,IPPKCT,IPRNCT>
QEXT <IPUSE,JCNTCB,MAXJCN,MAXTCB,MAXWPM,MLKMA,MRETN,NTWBWD,NXTLBL,OHUSE,OPDLAY>
QEXT <OPPKCT,OPRNCT,OPUSE,PROC,PZ,PZDLAY,PZPKCT,PZRNCT,PZUSE,RA,RADLAY,RAPKCT>
QEXT <RARNCT,RAUSE,RELWTB,RETJCN,RSTRCT,RSTSCT,RSVTSO,RX,RXDLAY,RXPKCT,RXRNCT>
QEXT <RXUSE,SETLAB,SETTSO,SNDSOP,STAT0,STATF,STATZZ,SYNRCT,SYNSCT,TASKCT>
QEXT <TCBCNT,TCBDQ,TCBH,TCBHLK,TCBHSZ,TCBHUC,TCBMAX,TCPABC,TCPBDQ,TCPBGT>
QEXT <TCPBYS,TCPCHK,TCPCKS,TCPCKT,TCPDGT,TCPDTL,TCPDXD,TCPDXI,TCPDXN,TCPFLG>
QEXT <TCPICM,TCPIDQ,TCPIFG,TCPINI,TCPIPQ,TCPISN,TCPON,TCPPCL,TCPPFN,TCPPRC>
QEXT <TCPPSA,TCPPSJ,TCPPSQ,TCPPTB,TCPPTC,TCPPTE,TCPPTM,TCPPTO,TCPRA0,TCPRX0>
QEXT <TCPRXF,TCPRXN,TCPRXS,TCPRXV,TCPRXW,TCPRXX,TCPSID,TCPSY0,TCPTIM,TCPUS0>
QEXT <TIMPTR,TODCLK,ASNTVT,CHKTVT,NTTTVT,PRCTVT,SNDTVT,TATNVT,TVMNTR,TVMSTM>
QEXT <TVTCHK,TVTCLS,TVTCSO,TVTISP,TVTLSN,TVTNCK,TVTNOF,TVTNTM,TVTOPN,TVTOPR>
QEXT <TVTOSP,TVTPTR,TVTWTM>
QEXT <TCPDTB,.PFTCN,.PFTPR,.PFTTM,.PFTTS,.PFTSC,.PFTCM,.PFTHR,.PFTTC>
QEXT <.PFTFH,.PFTLH,HTUNLK,HTLOCK,TCBHSH,NVTDTT,TTFLG1,TT%SAL,BBNOK,DECOK>
QEXT <IPFCHK,NIMPIB,NINTIB,OPEN1,GETJCN,ABTTCB,TCPABT,DOPKTZ,DY>
QEXT <CHKADD,FLSRBX,FLSSBX,NUWNDO,RSTBFR,RXPARS,SIGNAL,TCPTSK,TCPUOP>
QEXT <BMNTLK,DEFADR,DEFNET,EMNTLK,FNDNCT,HFNNCT> ;remove HFNNCT ?
QEXT <HNETCK,LCLHST,LCLNET,LKSTOR> ;,MAXNET?
QEXT <MNTCHK,MNTHLT,MNTINI,MNTKIL,MNTRED,MNTSET>
QEXT <NCTVT,NETCHK,NETCMP,NETHT0,NETHTM,NETNCT,%NETS,NETSUP,NOHDR>
QEXT <NTHSND,NTISND,NTLSND,NTMHDR,NTSNDI,.SAVP1>
QEXT <INTDWN,INTUP,NETGWY,NETHSH,NETHSI,NETHSZ,NETHTB>
QEXT <ABFCNT,BIMPLK,CHKIMP,EIMPLK,IMICHK,IMINFB,IMODUN,IMPABL,IMPALL>
QEXT <IMPBEG,IMPCHK,IMPCHO,IMPCHU,IMPCLL,IMPCLQ,IMPCLS,IMPEIN,IMPERR>
QEXT <IMPFLB,IMPFLG,IMPFRI,IMPGDM,IMPHDR,IMPHLT,IMPIBI,IMPIBO,IMPINR>
QEXT <IMPINS,IMPLKB,IMPLT1,IMPLT2,IMPLT3,IMPLT4,IMPLT5,IMPNCL,IMPNFI>
QEXT <IMPNIB,IMPNIT,IMPNLK,IMPNOL,IMPNOS,IMPOPL,IMPOPS,IMPRBF,IMPRRP>
QEXT <IMPRTS,IMPSDB,IMPSTR,IMPSYN,IMPTIM,IMPTM2,IMP8XB,IMP8XC,IMP8XI>
QEXT <IMP8XO,IMP8XS,IMSRST,NOIBFS,NUMNCP,SIQNXT>
QEXT <ANISRT,ANOSRT,ANXINI,ANXKIL,ANXRSS,ANXSCK,IMPPDP,IMSTK>
QEXT <CONNCK,CVNHST,GHSTNM,GIMLT1,GIMLT2,GIMLT3,GIMLT4,GNTBAL,GNTBTC>
QEXT <GNTBUF,GNTLSK,GNTRDY,GNTFSK,GNTSTS,HSTLUK,IMPLBT,NETENT>
QEXT <TSTEX0,TSTEX1,DBUGIP,HOSTPN,TVTMSG,TCPBFD,BUFHNT>
QEXT <IMPIN0,IMINRB,IMPSTT,SIQCHK,GWYINI>
QEXT <BF1822,BF18BI,BF18BO,BF18SZ,PRFNET,PRFADR,PRFNFD,TVTJFN>
QEXT <FKSTA2,JOBUNI,TATTVT>
QEXT <RETNIB,GETNIB,GET18B,RET18B,RTN>


 ---------------------------------
QEXT <ASGRSB,TTPPCS,TTPPCR,LSTIPC,FRKNOP>
QEXT <PHYDUA,DUALCT,PI5R,OLDIDL,SETPCV>
QEXT <PATLEV,DMSLEV,TTCLSH>

;ARPANET SYMBOLS

QEXT <%NETS,.PFFLG,.PFTCM,.PFTCN,.PFTFH,.PFTHR,.PFTLH,.PFTPR,.PFTSC>
QEXT <.PFTTC,.PFTTM,.PFTTS,AASDT,ABFCNT,ABTCON,ABTREP>
QEXT <ABTTCB,ACDLAY,AD1822,ADCHAN,ADCHAP,ADDNAP,ADETHR,ADIDKW>
QEXT <ADIPP,ADLHM,ADLNPA,ADMON,ADNFE,ADPRIO,ADPSIZ,ADPUPP,ADPVEC>
QEXT <ADRHSH,ADRINI,ADSET,ADSETC,ADURFC,ADXNSP,ALTADR,ALTNCT>
QEXT <ANISRT,ANOSRT,ANXKIL,ANXNCT,ANXRSS,ANXSCK,ASNTVT,ASNWTB>
QEXT <ASNWTF,BADPCT,BBNOK,BG,BITS,BOL,BSTADR>
QEXT <BUFCHK,BUFFRE,BUFHNT,BULKND,BULKST,BYTRCT,BYTSCT,CHAINI>
QEXT <CHAOS,CHAVEC,CHKADD,CHKBUF,CHKTVT,CHKWND,CLOSE1,CLRBLK>
QEXT <CLRLCK,CLRWTB,CMDNAM,DATCKS,DBUGIP,DECOK,DLAYPZ,DQ>
QEXT <DM2SEC,DOMINI,DOMIDX,DOMPAR,DOMSEC,DOMSRV>
QEXT <DUPKCT,DWNSHR,DY,EMTPKT,ENCPKT,ETHRAH,ETHRTB,ETHRTS,ETHVEC>
QEXT <FHPADR,FINRCT,FINSCT,FKSTA2,FLSRBX,FLSSBX,FNDGWY>
QEXT <FRCPKT,FREAVL,FREINI,FRELCK,GENCFL,GENCKS,GENCKU,GETBBK,GETBLK>
QEXT <GETBUF,GETJCN,GWTAB,GWYINI,GWYLUK,HOSTNW,HOSTPN,HSTDWN>
QEXT <HSTLUK,HSTUP,HTBJFN,HTBLCK,HTLOCK,HTUNLK,IAD.IP,ICMAA,ICMCHK>
QEXT <ICMCZF,ICMERR,ICMFLG,ICMICM,ICMINI,ICMIPQ,ICMKFK>
QEXT <ICMKJB,ICMON,ICMPCL,ICMPRC,ICMSID,ICMTIM,IHSHSZ,IMODUN>
QEXT <IMPEIN,IMPHDR,IMPNCT,IMPSV,INFAA,INFT0,INGAA,INITQ>
QEXT <INLAA,INMAA,INPAA,INPSW,INQAA,INQCHK,INQCZF,INQFK>
QEXT <INQFLG,INQHD,INQICM,INQINI,INQIPQ,INQJB,INQKFK,INQKJB>
QEXT <INQLK,INQM0,INQM1,INQM2,INQM3,INQMX,INQON,INQPCL>
QEXT <INQPRC,INQRS,INQSID,INQSP,INQT0,INQTIM,INQTM,INQV0>
QEXT <INQV1,INQV2,INQV3,INSVC,INSVR,INSVT,INTBCK,INTBEG>
QEXT <INTBFF,INTBLK,INTCLS,INTCZF,INTDWN,INTFLG,INTFRE>
QEXT <INTFRK,INTFRZ,INTFSP,INTFSZ,INTHST,INTKFK,INTKJB,INTLHX,INTLNN>
QEXT <INTMBE,INTMBF,INTMBS,INTMDA,INTMES,INTMFR,INTMIB,INTMIP>
QEXT <INTMLK,INTMON,INTNAM,INTNET,INTON,INTOOT,INTPIX>
QEXT <INTRBF,INTTIM,INTUP,INTWTB,INTZOT,INUAA,INWAA>
QEXT <INXPB,INXPW,IP,IPDLAY,IPEIN,IPHST,IPIQ,IPNET>
QEXT <IPODN,IPPKCT,IPRAN,IPRAQ,IPRAT,JCNTCB,JOBUNI,LCKCAL>
QEXT <LCLHST,LCLNET,LKSTOR,LOGHST,LUPNCT,LV6ACS,LV6PDP,LV6SAV>
QEXT <MAXJCN,MAXTCB,MNETON,MNOSRT,MNOUTD,MNTAA,MNTB0,MNTBT>
QEXT <MNTCFN,MNTCHK,MNTCZF,MNTEIN,MNTFKI,MNTFLG,MNTFRK,MNTFRT>
QEXT <MNTFWT,MNTHLT,MNTI0,MNTIM,MNTINI,MNTIX,MNTKFK,MNTKJB>
QEXT <MNTODN,MNTPIN,MNTPTP,MNTPWR,MNTRAC,MNTRAP,MNTRED,MNTRFN>
QEXT <MNTSEC,MNTSET,MNTSW,MNTUNQ,MNTWAK,MRETN,MRGFLG,MYCHAD>
QEXT <NCPUNQ,NCPVEC,NCT0A,NCT0B,NCTDWN,NCTHSH,NCTTBL,NCTUP,NCTVT,NETCHK>
QEXT <NETENT,NETGWY,NETHSH,NETHSI,NETHSZ,NETHTB,NETIFC,NETLUK>
QEXT <NETNCT,NETSUP,NETWHN,NETWHO,NFENCT,NFEVEC,NFIXED,NHSTN>
QEXT <NHSTNL,NINCT,NIQ,NMLHST,NLHOST,NQ,NTFRI,NTFRO,NTHSND>
QEXT <NTHT0,NTHTM,NTLSND,NTPOSS,NTPRNG,NTSNDI,NTTTVT,NTWBWD,NULPKT,NUM.IP>
QEXT <NUWNDO,NVTDTT,ODDBLK,OHUSE,OP,OPDLAY,OPEN1,OPPKCT,OPSTAB,OVRLAP>
QEXT <PERROT,PKTEND,PKTIZE,PNGT0,PNGTM,PPBLCK,PPBUF,PRCTVT,PRNPKH>
QEXT <PRNPKI,PRNPKT,PROC,PROCZF,PROEIN,PROHST,PROIAD,PROINZ,PROKFK>
QEXT <PROKJB,PRONAM,PRONDN,PRONET,PRONUM,PRONUP,PROODN,PROON,PROOVH>
QEXT <PULBAS,PULMAP,PULTOP,PVNCT,PZ,PZDLAY,PZPKCT,RA,RADLAY,RAPKCT>
QEXT <RDFLD,RDHNUM,RDNUM,REASEM,RELLCK,RELWTB,REMRXQ,RETBLK,RETBUF>
QEXT <RETJCN,RETPKT,RETRNP,REXMIT,RFN8TO,RFNGCT,RFNM0,RFNTAB,RFNTSZ>
QEXT <RSTBFR,RSTRCT,RSTSCT,RTN,RX,RXDLAY,RXPARS,RXPKCT>
QEXT <SAVEDP,SETLCK,SETTAB,SETURP,SETWTB,SIGNAL,SKDACK,SNDGAT,SNDTVT>
QEXT <STAR3,STAT0,STATCT,STATF,STATPT,STATZZ,STEALP,STORAT>
QEXT <STRFNC,STRHTY,STSINI,STSLIM,STSTAB,SWTTAB,SYNRCT,SYNSCT>
QEXT <TASKCT,TATNVT,TATTVT,TCAAA,TCBDQ,TCBH,TCBHLK,TCBHSH>
QEXT <TCBHSZ,TCBHUC,TCBSPD,TCCAA,TCDAA,TCFAA,TCIAA,TCJAA,TCKAA,TCMAA>
QEXT <TCOAA,TCPAA,TCPBDQ,TCPBFD,TCPBGT,TCPBRD,TCPCHK>
QEXT <TCPCKS,TCPCKT,TCPCZF,TCPDTB,TCPDTL,TCPFAT,TCPFLG,TCPICM,TCPIDQ>
QEXT <TCPINI,TCPIPK,TCPIPQ,TCPISN,TCPKFK,TCPKJB,TCPMXS,TCPOMZ,TCPON>
QEXT <TCPPCL,TCPPRC,TCPPSI,TCPPST,TCPPTM,TCPRA0,TCPSID,TCPSW,TCPSY0>
QEXT <TCPTIM,TCPTSK,TCPUOP,TCPUS0,TCPXOP,TCSQT,TCSTAT,TCTAA,TCUAA>
QEXT <TCVAA,TCXAA,TCZAA,TERM,TFRTST,TIMCAL,TIMPTR,TMPBUF,TODCLK,TPDXD>
QEXT <TPDXI,TPDXN,TPMSL,TPNOW,TPPZ0,TPQMAX,TPRMAX,TPRX0>
QEXT <TPRXD,TPRXF,TPRXI,TPRXN,TPRXV,TPRXW,TPRXX,TPSB0>
QEXT <TPSMAX,TPSQ0,TSTAMP,TT%SAL,TTFLG1,TTTGSB,TTTNEG,TTTSSB,TVMNTR>
QEXT <TVMSTM,TVSBE1,TVTCHK,TVTCLS,TVTCSO,TVTISP,TVTJFN,TVTLSN>
QEXT <TVTMSG,TVTNC1,TVTNCK,TVTNOF,TVTNTM,TVTOPN,TVTOPR,TVTOSP,TVTPR>
QEXT <TVTPTR,TVTTIM,TVTWTM,TYPNAM,UNLCK,USRERR,USREVT,VIRNCT,VNCTFN>


