REDIT 1(104) COMPARE by user CLYNN, 10-Feb-86 18:56:05
File 1: CWL:<DEC-6-1-BASE>GTJFN.MAC.1
File 2: CWL:<5-4-NET>GTJFN.MAC.2
***** CHANGE #1; PAGE 23, LINE 36; PAGE 23, LINE 36
	[ASCIZ /CHARGE/],,.PFACN ;NETWORK ACCOUNT STRING
	[ASCIZ/COMPARTMENTS/],,.PFTCM ;TCP COMPARTMENT DATA
	[ASCIZ/CONNECTION/],,.PFTCN ;TCP CONNECTION MODE
	[ASCIZ/COPIES/],,.PFCOP	;SPOOLED FILE COPIES
	[ASCIZ /DATA/],,.PFOPT	;NETWORK OPTIONAL DATA
	[ASCIZ/EXPIRATION-DATE/],,.PFEXP ;MAGTAPE EXPRIATION DATE
	[ASCIZ/FOREIGN-HOST/],,.PFTFH ;TCP FOREIGN HOST
 ---------------------------------
	[ASCIZ /CHARGE/],,.PFACN ;NETWORK ACCOUNT STRING
	[ASCIZ/COMPARTMENTS/],,.PFTCM ;TCP COMPARTMENT DATA
	[ASCIZ/CONNECTION/],,.PFTCN ;TCP CONNECTION MODE
	[ASCIZ/COPIES/],,.PFCOP	;SPOOLED FILE COPIES
	[ASCIZ /DATA/],,.PFOPT	;NETWORK OPTIONAL DATA
	[ASCIZ/EXPIRATION-DATE/],,.PFEXP ;MAGTAPE EXPRIATION DATE
	[ASCIZ/FLAGS/],,.PFFLG	;Flags (e.g., TCP)
	[ASCIZ/FOREIGN-HOST/],,.PFTFH ;TCP FOREIGN HOST

