@NOERROR
!
def n:   cwl:<5-4-net>
def b:   cwl:<5-4-build>
def dsk:
def mon: dsk:,cwl:<5-4-net>,cwl:<dec-6-1-base>,cwl:<dec-6-1-base.ap7>
def r:   dsk:,cwl:<5-4-build>
def sys: dsk:,sys:
def unv: dsk:
def utl: dsk:
!
@ena
!
@EXP
!
ANAUNV::
@COMPILE MON:ANAUNV.MAC R:ANAUNV
!
MNETDV::
@COMPILE /COMPILE MON:REL5.MAC+MON:MNETDV.MAC R:MNETDV
1822DV::
@COMPILE /COMPILE MON:1822DV.MAC R:1822DV
IMPANX::
@COMPILE /COMPILE MON:IMPANX.MAC R:IMPANX
IMPBBN::
@COMPILE /COMPILE MON:IMPBBN.MAC R:IMPBBN
NFEPHY::
@COMPILE /COMPILE MON:NFEPHY.MAC R:NFEPHY
!
IPFREE::
@COMPILE /COMPILE MON:REL5.MAC+MON:IPFREE.MAC R:IPFREE
IPIPIP::
@COMPILE /COMPILE MON:REL5.MAC+MON:IPIPIP.MAC R:IPIPIP
!
TCPCRC::
@COMPILE /COMPILE MON:TCPCRC.MAC R:TCPCRC
TCPTCP::
@COMPILE /COMPILE MON:TCPTCP.MAC R:TCPTCP
TCPBBN::
@COMPILE /COMPILE MON:REL5.MAC+MON:TCPBBN.MAC R:TCPBBN
TCPJFN::
@COMPILE /COMPILE MON:REL5.MAC+MON:TCPJFN.MAC R:TCPJFN
!
TTYSNV::
@COMPILE /COMPILE MON:ARPAF.MAC+MON:KLPRE.MAC+MON:TTYSRV.MAC+MON:TTANDV.MAC+MON:TTPHDV.MAC R:TTYSNV
TTYSDN::
@COMPILE /COMPILE MON:ARPAD.MAC+MON:KLPRE.MAC+MON:TTYSRV.MAC+MON:TTANDV.MAC+MON:TTPHDV.MAC R:TTYSDN
!
STGAN::
@COMPIL/COMP MON:REL5.MAC+MON:KLPRE.MAC+MON:ANPLND.MAC+MON:PARSYF.MAC+MON:PARAMS.MAC+MON:STG.MAC R:STGAN
!
MNTBEG::
@COMPILE MON:MNTBEG.MAC R:MNTBEG
MNTEND::
@COMPILE MON:MNTEND.MAC R:MNTEND
JSYSB::
@COMPILE MON:JSYSB.MAC R:JSYSB
!
MEXEC::
@COMPILE /COMPILE MON:MEXEC.MAC R:MEXEC
!
@NOERROR
!
LINK::
@R LINK
;*@MON:LNKAND.CCL
TTY:/LOG/LOGL:5
AMON/SAVE,/HASHSIZE:12007, -
/FRECOR:0, -
/SET:RSCOD:1000, -
/SET:INCOD:121000, -
/SET:RSDAT:143000,/SYMSEG:PSECT:RSDAT,/PATCHSIZE:100, -
/SET:PPVAR:205000, -
/SET:RSVAR:211000, -
/SET:SYVAR:327000, -
/SET:PSVAR:330000, -
/SET:JSVAR:346000, -
/SET:NRVAR:424000, -
/SET:BGPTR:450000/UPTO:447777, -
/SET:NRCOD:452000, -
/SET:BGSTR:727000, -
/SET:POSTCD:741000, -
/SET:NPVAR:727000, -
;/NOLOCALS, -
R:MONSYM.REL, -
R:LDINIT, -
R:VERSIO,R:STGAN, -
;/LOCALS, -
*;R:T20AN/S, -
R:APRSRV.REL/s,R:SCHED.REL/s,R:PAGEM.REL/s,R:FORK.REL/s, -
R:MEXEC.REL/s,R:GETSAV.REL/s,R:SYSERR.REL/s,R:COMND.REL/s, -
R:DEVICE.REL/s,R:DIRECT.REL/s,R:ENQ.REL/s,R:FREE.REL/s, -
R:FUTILI.REL/s,R:GTJFN.REL/s,R:IO.REL/s,R:IPCF.REL/s, -
R:JSYSA.REL/s,R:JSYSF.REL/s,R:LOGNAM.REL/s,R:LOOKUP.REL/s, -
R:MSTR.REL/s,R:SWPALC.REL/s,R:DISC.REL/s,R:EFILIN.REL/s, -
R:FILMSC.REL/s,R:MFLIN.REL/s,R:MFLOUT.REL/s,R:DATIME.REL/s, -
R:PHYSIO.REL/s,R:DIAG.REL/s,R:DSKALC.REL/s,R:PHYH2.REL/s, -
R:PHYP4.REL/s,R:PHYP2.REL/s,R:TTYSDN.REL/s,R:FESRV.REL/s, -
R:MAGTAP.REL/s,R:TAPE.REL/s,R:TIMER.REL/s,R:PHYM2.REL/s, -
R:PHYM78.REL/s,R:PHYX2.REL/s,R:DTESRV.REL/s,R:LINEPR.REL/s, -
R:CDRSRV.REL/s,R:PLT.REL/s,R:PTR.REL/s,R:PTP.REL/s, -
R:CDPSRV.REL/s,R:TTYSNV.REL/s, -
r:mntbeg,r:jsysb,r:1822dv/s,r:impbbn/s,r:nfephy/s, -
R:IMPANX.REL/s,R:IPIPIP.REL/s,R:IPFREE.REL/s, -
R:TCPTCP.REL/s,R:TCPCRC.REL/s,R:MNETDV.REL/s, -
R:TCPJFN.REL/s,R:TCPBBN.REL/s, -
r:mntend, -
R:NSPSRV.REL/s, -
R:IPNIDV.REL/s,R:NISRV.REL/s,R:NITEST.REL/s,R:NIUSR.REL/s, -
R:KDDT.REL,R:MDDT.REL,R:POSTLD.REL, -
*;/NOLOCALS, -
*;/SYSLIB, -
*/G
@EXP
AMON::
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
DBUGSW/1
DCHKSW/1
WEFLAG/-1
LPSNAM/"/CWL/
BUGH0+1/JFCL
=G
!
FINFIN::
@CONT
@
%FIN::
!
