REDIT 1(104) COMPARE by user CLYNN, 10-Feb-86 18:57:13
File 1: CWL:<DEC-6-1-BASE>MACSYM.MAC.1
File 2: CWL:<5-4-NET>MACSYM.MAC.2
***** CHANGE #1; PAGE 32, LINE 46; PAGE 32, LINE 46
  DEFINE EXIT. <
	JRST %TGE>>		;;EXIT LOOP

DEFINE ENDDO. <
	OD.>

DEFINE ..SVLD (%SY1,%SY2,%SY3,%SY4,%SY5)<
	SYN OD.,%SY1
	SYN LOOP.,%SY2
	SYN TOP.,%SY3
	SYN EXIT.,%SY4
	SYN ENDLP.,%SY5
	.PSHX <
	 SYN %SY1,OD.
	 SYN %SY2,LOOP.
	 SYN %SY3,TOP.
	 SYN %SY4,EXIT.
	 SYN %SY5,ENDLP.>>
 ---------------------------------
  DEFINE EXIT. <
	JRST %TGE>>		;;EXIT LOOP

DEFINE ENDDO. <
	OD.>

DEFINE ..SVLD (%SY1,%SY2,%SY3)<
	SYN OD.,%SY1
	SYN TOP.,%SY2
	SYN ENDLP.,%SY3
	.PSHX <
	 SYN %SY1,OD.
	 SYN %SY2,TOP.
	 SYN %SY3,ENDLP.
  DEFINE LOOP. <
	JRST TOP.>		;;LOOP TO TOP
  DEFINE EXIT. <
	JRST ENDLP.>		;;EXIT LOOP
>>

