REDIT 1(104) COMPARE by user CLYNN, 10-Feb-86 18:57:25
File 1: CWL:<DEC-6-1-BASE>MEXEC.MAC.1
File 2: CWL:<5-4-NET>MEXEC.MAC.1
***** CHANGE #1; PAGE 1, LINE 508; PAGE 1, LINE 508
;<4.MONITOR>MEXEC.MAC.279,  5-Oct-77 13:08:35, Edit by HESS
;JOB 0 - SEND MESSAGE TO PULSAR WHEN MTA STATUS CHANGE FLAG SET

;COPYRIGHT (C) 1976,1977,1978,1979,1980,1981,1982,1983,
;BY DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.

	SEARCH PROLOG,SERCOD,ACTSYM
	TTITLE MEXEC

 ---------------------------------
;<4.MONITOR>MEXEC.MAC.279,  5-Oct-77 13:08:35, Edit by HESS
;JOB 0 - SEND MESSAGE TO PULSAR WHEN MTA STATUS CHANGE FLAG SET

;COPYRIGHT (C) 1976,1977,1978,1979,1980,1981,1982,1983,
;BY DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.

	SEARCH PROLOG,SERCOD,ACTSYM,ANAUNV
	TTITLE MEXEC

ND CHAOS,0


***** CHANGE #2; PAGE 14, LINE 38; PAGE 14, LINE 38
	JRST RUNDD4		;YES
	MOVEI 1,ERRPT		;GET NAME OF SYSTEM ERROR FILE
	CALL PUTNAM		;ADD STRUCTURE NAME
	MOVSI 1,(GJ%FOU!GJ%PHY!GJ%SHT)	;NONE, SO OPEN FILE FOR MESSAGES
	HRROI 2,ERRPT		;GET NAME OF SYSTEM ERROR FILE
	GTJFN
	 BUG(NOSERF)
	MOVE 2,[44B5+1B20]
	OPENF
	 BUG(SERFOF)
RUNDD4:	HRRM 1,PRIMRY		;USE IT FOR OUTPUT
 ---------------------------------
	JRST RUNDD4		;YES
	MOVEI 1,ERRPT		;GET NAME OF SYSTEM ERROR FILE
	CALL PUTNAM		;ADD STRUCTURE NAME
	MOVSI 1,(GJ%FOU!GJ%PHY!GJ%SHT)	;NONE, SO OPEN FILE FOR MESSAGES
	HRROI 2,ERRPT		;GET NAME OF SYSTEM ERROR FILE
	GTJFN
;	 BUG(NOSERF)
	 BUG.(CHK,NOSERF,MEXEC,HARD,<CANNOT GTJFN ERROR REPORT FILE>,,<

Cause:	This BUG is not documented yet.

Action:

>)
	MOVE 2,[44B5+1B20]
	OPENF
;	 BUG(SERFOF)
	 BUG.(CHK,SERFOF,MEXEC,HARD,<CANNOT OPENF ERROR REPORT FILE>,,<

Cause:	This BUG is not documented yet.

Action:

>)
RUNDD4:	HRRM 1,PRIMRY		;USE IT FOR OUTPUT

***** CHANGE #3; PAGE 15, LINE 19; PAGE 15, LINE 19

;DO NETWORK-RELATED FUNCTIONS

RUNDD7:	MOVEI T1,RUNDD8		;GO TO RUNDD8 IF AN INTERRUPT OCCURS
	MOVEM T1,JB0XFR		;SAVE THE ADDRESS FOR JB0INT
	CALL MNTINI		; Initialize Multinet tables etc.
	CALL INTBEG		;Init the Internet Fork
	CALL KDPINI		;INIT THE KDP(KMC11/DUP11) CODE
 ---------------------------------

;DO NETWORK-RELATED FUNCTIONS

RUNDD7:	MOVEI T1,RUNDD8		;GO TO RUNDD8 IF AN INTERRUPT OCCURS
	MOVEM T1,JB0XFR		;SAVE THE ADDRESS FOR JB0INT
	CALL MNTINI		; Initialize Multinet tables etc.
	CALL KDPINI		;INIT THE KDP(KMC11/DUP11) CODE

***** CHANGE #4; PAGE 16, LINE 62; PAGE 16, LINE 62
	HRRM T1,MONBK		; NOW THAT WE SURVIVED THIS ROUTINE
	MOVE T1,JB0XFR		;SEE WHERE WE ARE TO GO NEXT
	JRST 0(T1)		; AND GO THERE

;HERE WHEN AN ERROR OCCURRED WHILE IN JB0INT. GIVE UP.

J0EMER:	BUG (STRTER)

 ---------------------------------
	HRRM T1,MONBK		; NOW THAT WE SURVIVED THIS ROUTINE
	MOVE T1,JB0XFR		;SEE WHERE WE ARE TO GO NEXT
	JRST 0(T1)		; AND GO THERE

;HERE WHEN AN ERROR OCCURRED WHILE IN JB0INT. GIVE UP.

J0EMER:	;BUG (STRTER)
	BUG.(HLT,STRTER,MEXEC,soft,<FATAL ERROR WHILE PROCESSING PREVIOUS STARTUP ERROR>,,<

Cause:	When a software channel 34 or 35 interrupt happens on fork
	0, the monitor transfers control to the code specified in the right 
	half of MONBK.  This address will often be the starting address of 
	JB0INT.  JB0INT handles errors in fork 0.  While JB0INT is doing its 
	error recovery, it sets MONBK to J0EMER, so that this STRTER BUGHLT
	will occur if another error happens during JB0INT execution.
>)


***** CHANGE #5; PAGE 18, LINE 28; PAGE 18, LINE 28
	PSOUT
	JRST LOGSS1		;TRY, TRY AGAIN

LOGSS3:	MOVX T1,RL%LEN
	MOVX T2,RL%SIZ
	CALL ALCSEB		;GET SYSERR STORAGE
	 JRST [BUG(SYSERF)
		RET]
 ---------------------------------
	PSOUT
	JRST LOGSS1		;TRY, TRY AGAIN

LOGSS3:	MOVX T1,RL%LEN
	MOVX T2,RL%SIZ
	CALL ALCSEB		;GET SYSERR STORAGE
	 JRST [;BUG(SYSERF)
		BUG.(CHK,SYSERF,MEXEC,HARD,<LOGSST-NO SYSERR STORAGE FOR RESTART ENTRY>,,<

Cause:	This BUG is not documented yet.

Action:

>)
		RET]

***** CHANGE #6; PAGE 22, LINE 23; PAGE 22, LINE 23
	SETOM SWPMLF		; INIT COUNT OF LOCKERS OF SWP MON
	SKIPN EDDTF		;KEEP EDDT?
	CALL ULKINI		;NO, UNLOCK IT
	NOSKED
	MOVE 1,BOOTFL		;GET DEVICE SELECTOR
	CAIL 1,NBOOTD		;LEGAL?
	BUG(ILBOOT)
	JRST BOOTD(1)		;GO TO SELECTED BOOTSTRAP
 ---------------------------------
	SETOM SWPMLF		; INIT COUNT OF LOCKERS OF SWP MON
	SKIPN EDDTF		;KEEP EDDT?
	CALL ULKINI		;NO, UNLOCK IT
	NOSKED
	MOVE 1,BOOTFL		;GET DEVICE SELECTOR
	CAIL 1,NBOOTD		;LEGAL?
;	BUG(ILBOOT)
	BUG.(HLT,ILBOOT,MEXEC,soft,<GETSWM-ILLEGAL VALUE OF BOOTFL>,,<

Cause:	BOOTFL is an index into a table designating the device from which
	to boot the swappable monitor.  ILBOOT occurs if this index is
	too large.  Note, however, that if it's negative, ILBOOT will not
	occur!
>)
	JRST BOOTD(1)		;GO TO SELECTED BOOTSTRAP

***** CHANGE #7; PAGE 24, LINE 13; PAGE 24, LINE 13
	SUBI T1,1000		;TWO LESS SINCE WE DON'T LOCK BOOT'S EPT/MMAP
	LSH T1,-PGSFT		;GET PAGES
	MOVE T2,TOTRC		;GET TOTAL FREE
	SUB T2,T1		;COMPUTE FREE PAGES AFTER VBOOT
	SUB T2,SUMNR		;DISCOUNT FORK OVERHEAD PAGES
	SKIPG P1,T2		;SAVE IN P1
	BUG(BOOTCR)
	LSH P1,PGSFT		;CONVERT TO WORDS
 ---------------------------------
	SUBI T1,1000		;TWO LESS SINCE WE DON'T LOCK BOOT'S EPT/MMAP
	LSH T1,-PGSFT		;GET PAGES
	MOVE T2,TOTRC		;GET TOTAL FREE
	SUB T2,T1		;COMPUTE FREE PAGES AFTER VBOOT
	SUB T2,SUMNR		;DISCOUNT FORK OVERHEAD PAGES
	SKIPG P1,T2		;SAVE IN P1
;	BUG(BOOTCR)
	BUG.(HLT,BOOTCR,MEXEC,hard,<GETSWM - NOT ENOUGH CORE FOR SWPMON>,,<

Cause:	The computation of space available came out negative.  This
	computation takes TOTRC, subtracts boot's space as computed as
	the difference between the halves of the contents of BUTPGS, then
	subtracts the contents of SUMNR.
>)
	LSH P1,PGSFT		;CONVERT TO WORDS

***** CHANGE #8; PAGE 24, LINE 26; PAGE 24, LINE 33
	LSH P2,-^D9		;CONVERT TO CORE PAGE #
	HLL P2,BUTPHY		;GET - # OF PAGES TO MAP
	MOVE P3,BUTVIR		;GET FIRST VIRTUAL ADR TO MAP
GSMD1:	HRRZ T1,P2		;GET PAGE # TO MAP
	MOVE T2,P3		;GET VIRTUAL ADDRESS
	CALL MAPPHA		;GO MAP A PHYSICAL PAGE
	 BUG(BOOTMP)
	ADDI P3,PGSIZ		;NEXT VIRTUAL ADDRESS
 ---------------------------------
	LSH P2,-^D9		;CONVERT TO CORE PAGE #
	HLL P2,BUTPHY		;GET - # OF PAGES TO MAP
	MOVE P3,BUTVIR		;GET FIRST VIRTUAL ADR TO MAP
GSMD1:	HRRZ T1,P2		;GET PAGE # TO MAP
	MOVE T2,P3		;GET VIRTUAL ADDRESS
	CALL MAPPHA		;GO MAP A PHYSICAL PAGE
;	 BUG(BOOTMP)
	 BUG.(HLT,BOOTMP,MEXEC,soft,<GSMDSK - CANNOT MAP BOOTSTRAP PAGES>,,<

Cause:	The call to MAPPHA which was attempting to map a page for
	BOOT failed.  MAPPHA fails if the requested page was already locked,
	which implies corrupted data in some monitor table.
>)
	ADDI P3,PGSIZ		;NEXT VIRTUAL ADDRESS

***** CHANGE #9; PAGE 24, LINE 47; PAGE 24, LINE 60
	CALL SETMPG		;SET MAP

	HLLZ T1,BUTPGS		;GET STARTING ADDRESS FOR VBOOT
	HLR T1,BUTEPT		;GET ADDRESS OF VBOOT MMAP PAGE
	SUBI T1,1		;WANT LAST PAGE BELOW MMAP LOCKED
	CALL CGPLK		;CREATE A GROUP OF PAGES AND LOCK
GSMLER:	 BUG(BOOTLK)
	HRRZ T1,BUTEPT		;GET ADDRESS OF VBOOT EPT PAGE
 ---------------------------------
	CALL SETMPG		;SET MAP

	HLLZ T1,BUTPGS		;GET STARTING ADDRESS FOR VBOOT
	HLR T1,BUTEPT		;GET ADDRESS OF VBOOT MMAP PAGE
	SUBI T1,1		;WANT LAST PAGE BELOW MMAP LOCKED
	CALL CGPLK		;CREATE A GROUP OF PAGES AND LOCK
GSMLER:	;BUG(BOOTLK)
	 BUG.(HLT,BOOTLK,MEXEC,soft,<GSMDSK - FAILED TO LOCK NEEDED PAGES>,,<

Cause:	CGPLK is called three times during the booting of the
	swappable monitor, firstly to lock BOOT itself in, then to lock
	BOOT's executive process table, and lastly to lock the swappable 
	monitor's area.  If any of the calls to CGPLK fail, BOOTLK occurs.
>)
	HRRZ T1,BUTEPT		;GET ADDRESS OF VBOOT EPT PAGE

***** CHANGE #10; PAGE 26, LINE 17; PAGE 26, LINE 17
	MOVEM P,FPC		;SAVE STACK POINTER
	MOVE T1,[POINT 7,BOOTST] ;GET POINTER TO COMMAND STRING
	HRRZ T2,BUTPGS		;GET ADDRESS OF LAST PAGE IN VBOOT AREA
VBCALL::JSP 16,777(T2)		;GO LOAD SOME MONITOR
				; CALL BOOT AT LAST INSTRUCTION ON
				; LAST PAGE WHICH IS A JRST TO VBOOT
	 BUG(BOOTER)
	MOVE P,FPC		;RECOVER STACK
 ---------------------------------
	MOVEM P,FPC		;SAVE STACK POINTER
	MOVE T1,[POINT 7,BOOTST] ;GET POINTER TO COMMAND STRING
	HRRZ T2,BUTPGS		;GET ADDRESS OF LAST PAGE IN VBOOT AREA
VBCALL::JSP 16,777(T2)		;GO LOAD SOME MONITOR
				; CALL BOOT AT LAST INSTRUCTION ON
				; LAST PAGE WHICH IS A JRST TO VBOOT
;	 BUG(BOOTER)
	 BUG.(HLT,BOOTER,MEXEC,hard,<GETSWM - ERROR LOADING SWPMON>,,<

Cause:	The monitor calls BOOT with a JSP CX,777(T2) in order to
	load a section of the swappable monitor.  This transfers to
	the VBOOT tag within BOOT, which does the work and takes a
	skip return if there are not errors.

	It takes a non-skip return if there is an error, in which case
	BOOTER results.

Action:	BOOTER has been observed when memory parity errors exist, so
	check for this and do memory corrective maintenance.
>)
	MOVE P,FPC		;RECOVER STACK

***** CHANGE #11; PAGE 28, LINE 8; PAGE 28, LINE 8
;'MINI-EXEC' - SIMPLE COMMAND INTERPRETER FOR SPECIAL FUNCTIONS

	SWAPCD

EXEC2:	MOVE T1,JOBBIT
	IFXN. T1,LOGIOB		;LOGIN OR OUT?
	  BUG(EXILGO)
	  WAIT%			;YES, SOME KIND OF DISASTER. GO AWAY QUIETLY.
 ---------------------------------
;'MINI-EXEC' - SIMPLE COMMAND INTERPRETER FOR SPECIAL FUNCTIONS

	SWAPCD

EXEC2:	MOVE T1,JOBBIT
	IFXN. T1,LOGIOB		;LOGIN OR OUT?
;	  BUG(EXILGO)
	  BUG.(CHK,EXILGO,MEXEC,SOFT,<EXECI - Interrupt during login or logout>,,<

Cause: Control has passed to the mini-exec because the top fork hit
a terminating condition or monitor interrupt.  The top fork EXEC may
have been wiped out.  In addition, the job was trying to log in or
out.

Action: The fork is put into an infinite wait state since any other
action might lead to further itraps, interrupts, looping, etc.
>)
	  WAIT%			;YES, SOME KIND OF DISASTER. GO AWAY QUIETLY.

***** CHANGE #12; PAGE 34, LINE 66; PAGE 34, LINE 66
	MOVE	T1,JOBBIT	;[2886]get job bits
	TXNN	T1,LOGIOB	;[2886]in LOGIN or LOGOUT?
	 RET			;[2886]no, return +1
	MOVE	T1,JOBNO	;[2874]get current job number
	HLRZ	T1,JOBPT(T1)	;[2874]get controlling TTY:
	MOVE	T2,LSTERR	;[2874]get last error this process
	BUG(LGFAIL,<<T1,JOBPT>,<T2,LSTERR>>) ;[2874]bug!
	DTACH			;[2874]attempt to detach
 ---------------------------------
	MOVE	T1,JOBBIT	;[2886]get job bits
	TXNN	T1,LOGIOB	;[2886]in LOGIN or LOGOUT?
	 RET			;[2886]no, return +1
	MOVE	T1,JOBNO	;[2874]get current job number
	HLRZ	T1,JOBPT(T1)	;[2874]get controlling TTY:
	MOVE	T2,LSTERR	;[2874]get last error this process
;	BUG(LGFAIL,<<T1,JOBPT>,<T2,LSTERR>>) ;[2874]bug!
	BUG.(INF,LGFAIL,MEXEC,SOFT,<LGOUT or LOGIN JSYS failed>,
<<T1,JOBPT>,<T2,LSTERR>>,<

Cause:  An attempt to log in/out a job has failed when it should have succeded.
The most likely cause of this is terminals that have been TTYSTPed, then a
LGOUT or LOGIN JSYS was attemped.  An attempt to detach the terminal, then
logout the job is made.  If either of these fail, the job is put in a permanent
wait state.

Action: None.

Data:   The terminal number, and the reason of the failure.

>)				;[2874]bug!
	DTACH			;[2874]attempt to detach

***** CHANGE #13; PAGE 38, LINE 43; PAGE 38, LINE 43
	MOVX T1,SF%CTY		;MAKE SURE CTY CAN LOG IN
	IORM T1,FACTSW		;EVEN IF HE COULD NOT DO IT BEFORE
	CALL DWNMSG		;SEND LAST MESSAGE
	SETOM HSYST1		;CLEAR FLAGS IN CASE RESTARTED
	MOVSI T1,(1B1)		;CREATE FORK WITH SAME CAPS
	CFORK
	 BUG(HSYFRK)
	MOVEI T2,HSYS4		;SET IT TO START NEXT SHUTDOWN PHASE
 ---------------------------------
	MOVX T1,SF%CTY		;MAKE SURE CTY CAN LOG IN
	IORM T1,FACTSW		;EVEN IF HE COULD NOT DO IT BEFORE
	CALL DWNMSG		;SEND LAST MESSAGE
	SETOM HSYST1		;CLEAR FLAGS IN CASE RESTARTED
	MOVSI T1,(1B1)		;CREATE FORK WITH SAME CAPS
	CFORK
;	 BUG(HSYFRK)
	 BUG.(HLT,HSYFRK,MEXEC,soft,<HSYS-JOB 0 CFORK FAILED>,,<

Cause:	This will occur if the CFORK JSYS fails to create a fork for
	shutting down the system.

	This failure will occur if the forks are totally used up, or if job
	0 has used the maximum number of forks permitted.  NUFKS contains this
	maximum number.
>)
	MOVEI T2,HSYS4		;SET IT TO START NEXT SHUTDOWN PHASE

***** CHANGE #14; PAGE 39, LINE 11; PAGE 39, LINE 11
HSYS4:	MOVSI 1,(UMODF)
	MOVEM 1,FFL		;ESTABLISH USUAL JSYS CONTEXT
	SETZM FPC		;SET PC
	MCENTR
	MOVX T1,SF%RMT!SF%LCL!SF%PTY
	ANDCAM T1,FACTSW	;ONLY ALLOW CTY TO LOGIN
	MOVE 6,[XWD -NJOBS+1,1]	;START WITH JOB 1
 ---------------------------------
HSYS4:	MOVSI 1,(UMODF)
	MOVEM 1,FFL		;ESTABLISH USUAL JSYS CONTEXT
	SETZM FPC		;SET PC
	MCENTR
	MOVX T1,SF%RMT!SF%LCL!SF%PTY
	ANDCAM T1,FACTSW	;ONLY ALLOW CTY TO LOGIN
	SETO T1,		;TELL NETWORK SYSTEM IS
	CALL MNTHLT		;ABOUT TO BE DOWN
	MOVE 6,[XWD -NJOBS+1,1]	;START WITH JOB 1

***** CHANGE #15; PAGE 39, LINE 44; PAGE 39, LINE 46
	JRST HSYS81		;YES, IGNORE
	MOVEI 1,^D1000		;NO, WAIT 1 SEC., THEN CHECK AGAIN
	DISMS
	JRST HSYS8

HSYS9:	CALL PHYLOG		;LOG DISK, TAPE STATISTICS
	SETZM DDTIME		;POKE DDMP
 ---------------------------------
	JRST HSYS81		;YES, IGNORE
	MOVEI 1,^D1000		;NO, WAIT 1 SEC., THEN CHECK AGAIN
	DISMS
	JRST HSYS8

HSYS9:	CALL PHYLOG		;LOG DISK, TAPE STATISTICS
	MOVE T1,HSYST4		;GET TIME BACK UP
	MOVEI T2,^D12		;SHOULD BE CODE FOR REASON FOR HALT
				;BUT FOR NOW, JUST SAY "SCHEDULED DOWN"
	CALL MNTHLT		;TELL THE NETWORK WE ARE GOING AWAY
	SETZM DDTIME		;POKE DDMP

***** CHANGE #16; PAGE 41, LINE 13; PAGE 41, LINE 13
	MOVE 1,TODCLK
	ADD T1,CHKPER		;NOW PLUS MAX CHECK PERIOD
	MOVEM 1,CHKTIM		;LEAVE FOR SCHED TO CHECK
	CALL RESLCK		;LOCK OR UNLOCK RESIDENT FREE SPACE
	CALL KNIJB0		;DO JOB ZERO STUFF FOR THE KLNI
	CALL DTEPOL		;GO SEE IF ANY DTE'S NEED ATTENTION
	CALL MNTCHK		;Keep multinet running
	SKIPL DRMJ0R		;DRUM JOB 0 REQUEST?
 ---------------------------------
	MOVE 1,TODCLK
	ADD T1,CHKPER		;NOW PLUS MAX CHECK PERIOD
	MOVEM 1,CHKTIM		;LEAVE FOR SCHED TO CHECK
	CALL RESLCK		;LOCK OR UNLOCK RESIDENT FREE SPACE
	CALL KNIJB0		;DO JOB ZERO STUFF FOR THE KLNI
	CALL DTEPOL		;GO SEE IF ANY DTE'S NEED ATTENTION
	SKIPL DRMJ0R		;DRUM JOB 0 REQUEST?

***** CHANGE #17; PAGE 41, LINE 35; PAGE 41, LINE 34
	CALL DDMP0		;DISK BACKUP
	CALL CHKBGS		;CHECK IF TIME TO STORE ASCII TIME
	SKIPE A,HSYST1		;SHUTDOWN PROCESS ACTIVE?
	CAMN A,[-1]		;OR IS SYSTEM SHUTDOWN
	SKIPA			;SYSTEM SHUTDOWN OR PROCESS NOT ACTIVE
	CALL CHKHSY		;YES, CHECK IT
	CALL IMICHK		;MAKE SURE IMP INPUT Q'S EMPTIED
	MOVE A,TODCLK
 ---------------------------------
	CALL DDMP0		;DISK BACKUP
	CALL CHKBGS		;CHECK IF TIME TO STORE ASCII TIME
	SKIPE A,HSYST1		;SHUTDOWN PROCESS ACTIVE?
	CAMN A,[-1]		;OR IS SYSTEM SHUTDOWN
	SKIPA			;SYSTEM SHUTDOWN OR PROCESS NOT ACTIVE
	CALL CHKHSY		;YES, CHECK IT
	MOVE A,TODCLK

***** CHANGE #18; PAGE 46, LINE 16; PAGE 46, LINE 16
	HLRZ 3,2		;CHECK LH OF POINTER
	CAIN 3,-1		;DEFAULT?
	HRLI 2,(<POINT 7,0>)	;YES, DO IT
   >
	SETO T3,		;SAY ALL LINE
	TTMSG			;TYPE THE STUFF
	 ERJMP [BUG (TTFSMS)	;FAILED TO SEND MESSAGE
		JRST .+1]	;CONTINUE
 ---------------------------------
	HLRZ 3,2		;CHECK LH OF POINTER
	CAIN 3,-1		;DEFAULT?
	HRLI 2,(<POINT 7,0>)	;YES, DO IT
   >
	SETO T3,		;SAY ALL LINE
	TTMSG			;TYPE THE STUFF
	 ERJMP [;BUG (TTFSMS)	;FAILED TO SEND MESSAGE
		BUG.(INF,TTFSMS,MEXEC,SOFT,<Failed to send system message>,,<

Cause: Most likely reason for failure is that RSX20F
cannot complete the previous TTMSG request. Typically this
is caused by a hung DH11 line, but could be a software bug
as well.
>)
		JRST .+1]	;CONTINUE

***** CHANGE #19; PAGE 48, LINE 43; PAGE 48, LINE 43
NR EXPFRK,1		;        0 := NO EXPUNGE FORK
			; -1,,FRKH := FORK RUNNING
			;  0,,FRKH := EXPUNGE DONE

EXPALL:	MOVX T1,CR%CAP		;PASS CAPABILITIES DOWN
	CFORK			;CREATE FORK
	 BUG (EXPAFK)
	HRROM T1,EXPFRK		;MARK FORK RUNNING
 ---------------------------------
NR EXPFRK,1		;        0 := NO EXPUNGE FORK
			; -1,,FRKH := FORK RUNNING
			;  0,,FRKH := EXPUNGE DONE

EXPALL:	MOVX T1,CR%CAP		;PASS CAPABILITIES DOWN
	CFORK			;CREATE FORK
;	 BUG (EXPAFK)
	 BUG.(HLT,EXPAFK,MEXEC,soft,<EXPALL: JOB 0 CFORK FAILED>,,<

Cause:	This will happen if the CFORK JSYS fails to create a fork
	for doing the system-wide expunge of structure PS:.

	This could most likely happen if all the fork slots are used up.
>)
	HRROM T1,EXPFRK		;MARK FORK RUNNING

***** CHANGE #20; PAGE 48, LINE 74; PAGE 48, LINE 81
	CALL ALLMSG
	MOVEI T1,^D30000
	DISMS			;GIVE USERS TIME TO UNDELETE
	MOVX T1,RC%AWL		;ALLOW WILD CARDS
	HRROI T2,[ASCIZ "PS:<*>"]
	RCDIR			;GET FIRST DIRECTORY NUMBER
	 ERJMP [BUG (EXPRCD)
		JRST EXPAL3]	;WE TRIED
 ---------------------------------
	CALL ALLMSG
	MOVEI T1,^D30000
	DISMS			;GIVE USERS TIME TO UNDELETE
	MOVX T1,RC%AWL		;ALLOW WILD CARDS
	HRROI T2,[ASCIZ "PS:<*>"]
	RCDIR			;GET FIRST DIRECTORY NUMBER
	 ERJMP [;BUG (EXPRCD)
		BUG.(CHK,EXPRCD,MEXEC,HARD,<EXPALL: RCDIR FAILURE>,,<

Cause:	This BUG is not documented yet.

Action:

>)
		JRST EXPAL3]	;WE TRIED

***** CHANGE #21; PAGE 56, LINE 38; PAGE 56, LINE 38
FLOGO1:	MOVX 1,LOGIOB		;SAY JOB DESTRUCTION IN PROGRESS
	IORM 1,JOBBIT
	MOVEI 1,400000
	SETO 2,
	DIC			;DEACTIVATE INTERRUPTS AND KEYS
	CALL DTIALL
	CALL NETLGO		;RELEASE ANY JOB-WIDE NETWORK RESOURCES
	CALL INTLGO		; Release any Internet user queues
	MOVEI T1,-4
 ---------------------------------
FLOGO1:	MOVX 1,LOGIOB		;SAY JOB DESTRUCTION IN PROGRESS
	IORM 1,JOBBIT
	MOVEI 1,400000
	SETO 2,
	DIC			;DEACTIVATE INTERRUPTS AND KEYS
	CALL DTIALL
	CALL MNTKJB		;RELEASE NETWORK RESOURCES FOR THIS JOB
	MOVEI T1,-4

***** CHANGE #22; PAGE 57, LINE 3; PAGE 57, LINE 3
	SETOM JOBONT(T3)		;MAKE IT UNOWNED, SO IT FINISHES
SJLGO2:	AOBJN T3,SJLGO1		;SEE IF I OWN ANY MORE JOBS
	; ..

	; ..
SJLGO4:	SETO T1,			;CLEAR USER MAP OF TOP FORK
	MOVSI 2,<.FHSLF!FH%EPN>		;THIS FORK
	MOVE 3,[PM%CNT!PM%EPN!<1000>B35] ;REQUEST 1000 PAGES
	PMAP
	 ERJMP .+1
	MOVE FX,FORKX
 ---------------------------------
	SETOM JOBONT(T3)		;MAKE IT UNOWNED, SO IT FINISHES
SJLGO2:	AOBJN T3,SJLGO1		;SEE IF I OWN ANY MORE JOBS
	; ..

	; ..
SJLGO4:	MOVX T1,.FHSLF			; FOR THIS FORK
	CLZFF
; DO A CLZFF ; HOPEFULLY THAT CLZFF GETS RID OF ANY BAD INTERACTIONS
; BETWEEN THINGS LIKE THE TCP AND THE UPT
	SETO T1,			;CLEAR USER MAP OF TOP FORK
	MOVSI 2,<.FHSLF!FH%EPN>		;THIS FORK
	MOVE 3,[PM%CNT!PM%EPN!<1000>B35] ;REQUEST 1000 PAGES
	PMAP
	 ERJMP [JSR BUGHLT]	; SHOULDN'T FAIL
	MOVE FX,FORKX

***** CHANGE #23; PAGE 62, LINE 18; PAGE 62, LINE 18
	MOVEI T2,LOGLST		;POINT TO PARAMETERS
	USAGE
	 ERCAL XUSAGE		;REPORT USAGE FAILURE
	POP P,1
	CALLRET LOGCR		;AND CRLF

XUSAGE:	BUG (UXXFAI)
	RET			;CONTINUE
 ---------------------------------
	MOVEI T2,LOGLST		;POINT TO PARAMETERS
	USAGE
	 ERCAL XUSAGE		;REPORT USAGE FAILURE
	POP P,1
	CALLRET LOGCR		;AND CRLF

XUSAGE:	;BUG (UXXFAI)
	BUG.(CHK,UXXFAI,MEXEC,HARD,<USAGE JSYS FAILURE>,,<

Cause:	This BUG is not documented yet.

Action:

>)
	RET			;CONTINUE

***** CHANGE #24; PAGE 71, LINE 44; PAGE 71, LINE 44
	XXX JOBPNM,JOBPNM,NJOBS
	XXX BLDTD,SYSTAD,1
	XXX			;;FORMERLY LSTDRN
	XXX APRID,APRSER,1
	XXX HQLAV,HQLAV,NRJAVS
	XXX LQLAV,LQLAV,NRJAVS
	XXX NETRDY,0,10,GNTRDY
	XXX				;FORMERLY IMPHRT
 ---------------------------------
	XXX JOBPNM,JOBPNM,NJOBS
	XXX BLDTD,SYSTAD,1
	XXX			;;FORMERLY LSTDRN
	XXX APRID,APRSER,1
	XXX HQLAV,HQLAV,NRJAVS
	XXX LQLAV,LQLAV,NRJAVS
	XXX 				;FORMERLY NETRDY,0,10,GNTRDY
	XXX				;FORMERLY IMPHRT

***** CHANGE #25; PAGE 71, LINE 65; PAGE 71, LINE 65
	XXX 				;FORMERLY IMPLT3
	XXX 				;FORMERLY IMPLT4
	XXX LHOSTN,NOHOST,2		;ARPA HOST NUMBER, NVT COUNTER
	XXX JBONT,JOBONT,NJOBS		;OWNING JOB
	XXX NSWPGS,NSWPGS,1		;DEFAULT SWAPPING PAGES
	XXX SCOUNT,SCOUNT,NNAMES	;COUNT OF SETSN'S S FOR SUBSYSTEM
   >
 ---------------------------------
	XXX 				;FORMERLY IMPLT3
	XXX 				;FORMERLY IMPLT4
	XXX LHOSTN,NOHOST,2		;ARPA HOST NUMBER, NVT COUNTER
	XXX JBONT,JOBONT,NJOBS		;OWNING JOB
	XXX NSWPGS,NSWPGS,1		;DEFAULT SWAPPING PAGES
	XXX SCOUNT,SCOUNT,NNAMES	;COUNT OF SETSN'S S FOR SUBSYSTEM
IFE CHAOS,<
	XXX
	XXX
> ; End of IFE CHAOS
IFG CHAOS,<
	XXX CHSTAT,CHAON,CHASBS		;100
	XXX CHPMXT,CHPMXT,1		;100
> ; End of IFG CHAOS
   >

***** CHANGE #26; PAGE 83, LINE 11; PAGE 83, LINE 11

JOBCOF::SKIPGE SLOWF		;IN JSYS CONTEXT?
	JRST [	MCENTR		;NO, GET THERE
		PUSH P,[IFIW!MRETN]	;SETUP RETURN
		JRST .+1]
	SE1ENT			;GET INTO SECTION 1
	SAVET
	MOVE 1,JOBNO
 ---------------------------------

JOBCOF::SKIPGE SLOWF		;IN JSYS CONTEXT?
	JRST [	MCENTR		;NO, GET THERE
		PUSH P,[IFIW!MRETN]	;SETUP RETURN
		JRST .+1]
	SE1ENT			;GET INTO SECTION 1
	SAVEAC	<T1,T2,T3,T4,P4,CX> ; Save critical registers
	MOVE 1,JOBNO

***** CHANGE #27; PAGE 87, LINE 23; PAGE 87, LINE 23

	MOVE T4,ATACJN		;GET OBJECT JOB
	MOVEM FX,CTRLTT(Q2)	;SET CTRLTT IN DEST JOB
	HRLM FX,JOBPT(T4)
	MOVEI T1,.TTDES(FX)	;T1/ DEVICE DESIGNATOR FOR TERMINAL
	CALL CHKDES 		;GET INDEX TO DEVICE TABLES
	 BUG(TTBAD1)
	MOVE T1,ATACJN		;GET OTHER JOB NUMBER
 ---------------------------------

	MOVE T4,ATACJN		;GET OBJECT JOB
	MOVEM FX,CTRLTT(Q2)	;SET CTRLTT IN DEST JOB
	HRLM FX,JOBPT(T4)
	MOVEI T1,.TTDES(FX)	;T1/ DEVICE DESIGNATOR FOR TERMINAL
	CALL CHKDES 		;GET INDEX TO DEVICE TABLES
;	 BUG(TTBAD1)
	 BUG.(HLT,TTBAD1,MEXEC,soft,<BAD DEVICE DESIGNATOR FOR TERMINAL AT ATACH2>,,<

Cause:	The call to CHKDES failed.  This should not happen, since the terminal
	number involved comes from Q3, which is either the number of terminal
	controlling the job, or a user-supplied terminal number from the user's
	AC4.  If a user-supplied number is being used, it was range-checked by
	comparing it to NLINES.  If it is the number of the controlling
	terminal, the job was already verified to be attached somewhere, so
	this BUGHLT should not occur.
>)
	MOVE T1,ATACJN		;GET OTHER JOB NUMBER

***** CHANGE #28; PAGE 88, LINE 32; PAGE 88, LINE 32
	JRST [	TMSG <? System accounting will not be done due to file system errors
>
		RET]
USGIN1:	HRROI T2,USGFIL		;FILESPEC FOR USAGE FILE
	CALL USGOPN		;OPEN FILE
	 JRST [	CALL CRUSGF	;NONE - CREATE USAGE FILE
		 BUG (UXXCRE)
		JRST USGIN1]	;TRY AGAIN
 ---------------------------------
	JRST [	TMSG <? System accounting will not be done due to file system errors
>
		RET]
USGIN1:	HRROI T2,USGFIL		;FILESPEC FOR USAGE FILE
	CALL USGOPN		;OPEN FILE
	 JRST [	CALL CRUSGF	;NONE - CREATE USAGE FILE
;		 BUG (UXXCRE)
		 BUG.(HLT,UXXCRE,MEXEC,soft,<CANNOT CREATE USAGE FILE>,,<

Cause:	If the GTJFN (GJ%PHY,GJ%OLD) or the OPENF (OF%RD,OF%WR,
	OF%RTD) on the file pointed to by CKPFIL (PS:[ACCOUNTS]
	CHECKPOINT.BIN.1) fails, then another GTJFN (GJ%FOU) and OPENF
	(OF%WR) is attempted in order to create a new checkpoint file.
	If these latter GTJFN and OPENF fail, the UXXCRE BUGHLT occcurs.

Action:	Analyze the error code from the failing JSYS, and fix the
	checkpoint file so that the error does not happen.
>)
		JRST USGIN1]	;TRY AGAIN

***** CHANGE #29; PAGE 88, LINE 42; PAGE 88, LINE 53
	TXO T1,CO%NRJ		;RETAIN JFN
	CLOSF			;THIS SHOULD CORRECT PAGE COUNT
	 JFCL			;SHOULDN'T HAPPEN
	MOVX T2,44B5+OF%RD!OF%WR!OF%RTD
	MOVE T1,USGJFN		;FETCH JFN
	OPENF			;OPEN FOR REAL NOW
	 BUG (UXXOPN)
	HRRZ T1,T1		;GET RID OF OPEN FLAGS
 ---------------------------------
	TXO T1,CO%NRJ		;RETAIN JFN
	CLOSF			;THIS SHOULD CORRECT PAGE COUNT
	 JFCL			;SHOULDN'T HAPPEN
	MOVX T2,44B5+OF%RD!OF%WR!OF%RTD
	MOVE T1,USGJFN		;FETCH JFN
	OPENF			;OPEN FOR REAL NOW
;	 BUG (UXXOPN)
	 BUG.(HLT,UXXOPN,MEXEC,soft,<UNABLE TO OPEN USAGE FILE>,,<

Cause:	USGINI invoked OPENF (OF%RD,OF%WR,OF%RTD), which failed to open the
	file pointed to by USGFIL, probably PS:[ACCOUNTS]SYSTEM-DATA.BIN.
>)
	HRRZ T1,T1		;GET RID OF OPEN FLAGS

***** CHANGE #30; PAGE 88, LINE 53; PAGE 88, LINE 69
	MOVE T1,USGJFN		;JFN AGAIN
	MOVE T2,[1,,.FBBYV]	;GET PAGE COUNT
	MOVEI T3,T4		; INTO T4
	GTFDB
	HRRZS T4		;PAGE # ONLY
	CAME Q1,T4		;CORRECT NUMBER
	BUG (USGHOL)
	JUMPE Q1,USGIN4		;EMPTY FILE IF 0
 ---------------------------------
	MOVE T1,USGJFN		;JFN AGAIN
	MOVE T2,[1,,.FBBYV]	;GET PAGE COUNT
	MOVEI T3,T4		; INTO T4
	GTFDB
	HRRZS T4		;PAGE # ONLY
	CAME Q1,T4		;CORRECT NUMBER
;	BUG (USGHOL)
	BUG.(INF,USGHOL,MEXEC,HARD,<LOST PAGE(S) IN USAGE FILE>,,<

Cause:	This BUG is not documented yet.

Action:

>)
	JUMPE Q1,USGIN4		;EMPTY FILE IF 0

***** CHANGE #31; PAGE 89, LINE 11; PAGE 89, LINE 11

;CHECKPOINT INIT

USGIN5:	HRROI T2,CKPFIL		;FILE NAME FOR CHECKPOINT
	CALL USGOPN		;OPEN IT
	 JRST [	CALL CRCKPT	;NON-EX CREATE NEW ONE
		 BUG (UXXCKP)
		JRST USGIN5]
 ---------------------------------

;CHECKPOINT INIT

USGIN5:	HRROI T2,CKPFIL		;FILE NAME FOR CHECKPOINT
	CALL USGOPN		;OPEN IT
	 JRST [	CALL CRCKPT	;NON-EX CREATE NEW ONE
;		 BUG (UXXCKP)
		 BUG.(HLT,UXXCKP,MEXEC,soft,<COULDN'T CREATE CHECKPOINT FILE>,,<

Cause:	The file PS:[ACCOUNTS]CHECKPOINT.BIN.1 could not be referenced
	for one reason or another.  The code first attempts a GTJFN (GJ%PHY,
	GJ%OLD) and an OPENF (OF%RD,OF%WR,OF%RTD), one of which must fail
	for UXXCKP to be a possibility.

	After the above GTJFN or OPENF has failed, then a GTJFN (GJ%PHY,GJ%NEW)
	is attempted.  If this succeeds, then UXXCKP will occur if a failure
	happens on one of the following: the subsequent OPENF (OF%WR,OF%RD),
	the call to ASGSWP to allocate CKPSIZ words, or the SOUT writing
	CKPSIZ words to the checkpoint file.

	If the GTJFN (GJ%PHY,GJ%NEW) fails, then another GTJFN (GJ%PHY,GJ%DEL)
	is attempted, and its failure will cause UXXCKP.  If this GTJFN
	succeeds, however, then a CHFDB (turning off FB%DEL to undelete the
	file) is done, and its failure will also cause UXXCKP.

Action:	Use EDDT to patch the system so that you can bring up the system
	without the checkpoint file being referenced.  Then get the checkpoint
	file into a state such that none of the above failures will occur.
>)
		JRST USGIN5]

***** CHANGE #32; PAGE 89, LINE 24; PAGE 89, LINE 46
	CALL USGMAP		;MAP PAGE
	MOVE Q1,FPG0A+1		;GET # OF JOBS IN FILE
	ERJMP CKPBAD		;IF NON-EX PAGE, FILE IS BAD
	MOVE T1,FPG0A+3		;SIZE OF CHECKPOINT RECORD
	CAIN T1,CKPSIZ		;BETTER BE SAME
	CAIGE Q1,NJOBS		;.GE. MAX JOBS IN MONITOR
CKPBAD:	JRST [	BUG (UXXFIT)
		CALL UNMAPC
 ---------------------------------
	CALL USGMAP		;MAP PAGE
	MOVE Q1,FPG0A+1		;GET # OF JOBS IN FILE
	ERJMP CKPBAD		;IF NON-EX PAGE, FILE IS BAD
	MOVE T1,FPG0A+3		;SIZE OF CHECKPOINT RECORD
	CAIN T1,CKPSIZ		;BETTER BE SAME
	CAIGE Q1,NJOBS		;.GE. MAX JOBS IN MONITOR
CKPBAD:	JRST [	;BUG (UXXFIT)
		BUG.(INF,UXXFIT,MEXEC,HARD,
<CHECKPOINT FILE NOT IN CORRECT FORMAT FOR THIS SYSTEM, REBUILDING...>,,<

Cause:	This BUG is not documented yet.

Action:

>)
		CALL UNMAPC

***** CHANGE #33; PAGE 90, LINE 25; PAGE 90, LINE 25
	SKIPGE 0(T4)		;IS ENTRY ACTIVE?
	JRST USGIN8		;NO, GET NEXT ENTRY
	MOVEI T2,.UTCKP		;RECORD TYPE FOR CHECKPOINT MERGE
	HRLM T2,1(T4)		;STORE IN HEADER
	HRRZ T3,1(T4)		;GET RECORD LENGTH
	CAIL T3,CKPSIZ		;IS LENGTH LESS THAN MAX SIZE?
	JRST [	BUG (CKPLEN)	;NO, THIS IS A BUG
		JRST USGIN8]	;AND IGNORE ENTRY
 ---------------------------------
	SKIPGE 0(T4)		;IS ENTRY ACTIVE?
	JRST USGIN8		;NO, GET NEXT ENTRY
	MOVEI T2,.UTCKP		;RECORD TYPE FOR CHECKPOINT MERGE
	HRLM T2,1(T4)		;STORE IN HEADER
	HRRZ T3,1(T4)		;GET RECORD LENGTH
	CAIL T3,CKPSIZ		;IS LENGTH LESS THAN MAX SIZE?
	JRST [	;BUG (CKPLEN)	;NO, THIS IS A BUG
		BUG.(CHK,CKPLEN,MEXEC,HARD,
<USGINI - ILLEGAL CHECKPOINT ENTRY LENGTH>,,<

Cause:	While executing USGINI, an active checkpoint entry was found with
	an illegal length.  This could be caused by a trashed CHECKPOINT.BIN
	file.

Action:	Delete CHECKPOINT.BIN and reload system.

>)
		JRST USGIN8]	;AND IGNORE ENTRY

***** CHANGE #34; PAGE 92, LINE 35; PAGE 92, LINE 35
	RET			;Return from USGUPS

;IO ERROR IN USAGE FILE

USGIOE:	MOVE T1,USGEOF		;REPORT BAD PAGE
	LSH T1,-PGSFT
	BUG (UXXWER,<<T1,D>>)
	RET			;CONTINUE
 ---------------------------------
	RET			;Return from USGUPS

;IO ERROR IN USAGE FILE

USGIOE:	MOVE T1,USGEOF		;REPORT BAD PAGE
	LSH T1,-PGSFT
;	BUG (UXXWER,<<T1,D>>)
	BUG.(CHK,UXXWER,MEXEC,HARD,<WRITE ERROR IN USAGE FILE>,<<T1,D>>,<

Cause:	This BUG is not documented yet.

Action:

>)
	RET			;CONTINUE

***** CHANGE #35; PAGE 94, LINE 52; PAGE 94, LINE 52
	SKIPE T1,CKPGID		;GET CURRENT PAGE THAT'S MAPPED
	UFPGS			;UPDATE IT
	 JFCL			;WE TRIED
	POP P,T1		;RESTORE PAGE IDENT
	MOVEM T1,CKPGID		;REMEMBER NEW PAGE IDENT
	CALL JFNOFN		;CONVERT TO OFN,,PN
	 BUG (UXXMAP)
	POP P,T2		;RESTORE ACCESS INFO
 ---------------------------------
	SKIPE T1,CKPGID		;GET CURRENT PAGE THAT'S MAPPED
	UFPGS			;UPDATE IT
	 JFCL			;WE TRIED
	POP P,T1		;RESTORE PAGE IDENT
	MOVEM T1,CKPGID		;REMEMBER NEW PAGE IDENT
	CALL JFNOFN		;CONVERT TO OFN,,PN
;	 BUG (UXXMAP)
	 BUG.(HLT,UXXMAP,MEXEC,soft,<USGMAP: CALL TO JFNOFN FAILED>,,<

Cause:	USGMAP wants to map a page of a file into FPG0 via SETMPG.
	It calls JFNOFN to convert the JFN.PN atom to OFN.PN, which SETMPG
	wants.  If JFNOFN fails, this BUGHLT occurs.  Some reasons that JFNOFN 
	will fail are: JFN is not associated with a disk file; JFN is not open;
	attempt to create a new page table for a file that is not open for 
	writing; attempt to create a new page table for a directory file; 
	attempt to create a new page table for which there is no room on disk.

>)
	POP P,T2		;RESTORE ACCESS INFO

***** CHANGE #36; PAGE 95, LINE 8; PAGE 95, LINE 8

USGMES:	SAVEAC <Q1,Q2,FX>	;SAVE REGS
USGMS0:	SKIPN Q1,USGBEG		;ANYTHING ON QUEUE?
	RET			;NO - DONE
	LOAD T1,UQFCN,(Q1)	;GET FCN CODE
	CAILE T1,USGLGL		;CHECK VALID
USGBFC:	BUG (UXXILL)
	CALL @USGREQ(T1)	;DISPATCH
 ---------------------------------

USGMES:	SAVEAC <Q1,Q2,FX>	;SAVE REGS
USGMS0:	SKIPN Q1,USGBEG		;ANYTHING ON QUEUE?
	RET			;NO - DONE
	LOAD T1,UQFCN,(Q1)	;GET FCN CODE
	CAILE T1,USGLGL		;CHECK VALID
USGBFC:	;BUG (UXXILL)
	BUG.(HLT,UXXILL,MEXEC,soft,<USGMES: ILLEGAL FUNCTION CODE>,,<

Cause:	The USAGE JSYS causes entries in the usage queue.  Each
	entry has a dispatch offset which is used by USGMES as an index into
	a vector for calling the appropriate support routine.

	If the dispatch offset is too large, this BUGHLT occurs.  Since the
	monitor itself is creating the entries in the queue, such a mismatch
	should never occur.
>)
	CALL @USGREQ(T1)	;DISPATCH

***** CHANGE #37; PAGE 98, LINE 23; PAGE 98, LINE 23
	RET			;DONE

;CLOSE OUT CURRENT FILE AND START A NEW ONE

USGCLS:	STKVAR <NJFN>
	CALL CRUSGF		;CREATE A NEW FILE
	 JRST [	BUG (UXXCL1)
		RET]		;JUST EXIT - NOTHING DONE
	HRROI T2,USGFIL		;NOW OPEN IT
	CALL USGOPN
	 JRST [	BUG (UXXCL2)
		RET]		;TOUGH AGAIN
 ---------------------------------
	RET			;DONE

;CLOSE OUT CURRENT FILE AND START A NEW ONE

USGCLS:	STKVAR <NJFN>
	CALL CRUSGF		;CREATE A NEW FILE
	 JRST [	;BUG (UXXCL1)
		BUG.(CHK,UXXCL1,MEXEC,HARD,<UNABLE TO CREATE NEW USAGE FILE>,,<

Cause:	This BUG is not documented yet.

Action:

>)
		RET]		;JUST EXIT - NOTHING DONE
	HRROI T2,USGFIL		;NOW OPEN IT
	CALL USGOPN
	 JRST [	;BUG (UXXCL2)
		BUG.(CHK,UXXCL2,MEXEC,HARD,<UNABLE TO OPEN NEW USAGE FILE>,,<

Cause:	This BUG is not documented yet.

Action:

>)
		RET]		;TOUGH AGAIN

***** CHANGE #38; PAGE 98, LINE 40; PAGE 98, LINE 54
	MOVX T2,FB%NOD		;SET TO CLEAR THIS BIT
	SETZ T3,		; TO ALLOW FILE TO DUMP
	CHFDB
	 ERJMP .+1		;WE TRIED
	HRRZS T1		;RESTORE JFN
	CLOSF			;CLOSE OUT FILE
	 BUG (UXXCL3)
	SETZM USGEOF		;SETUP FOR NEW FILE
 ---------------------------------
	MOVX T2,FB%NOD		;SET TO CLEAR THIS BIT
	SETZ T3,		; TO ALLOW FILE TO DUMP
	CHFDB
	 ERJMP .+1		;WE TRIED
	HRRZS T1		;RESTORE JFN
	CLOSF			;CLOSE OUT FILE
;	 BUG (UXXCL3)
	 BUG.(CHK,UXXCL3,MEXEC,HARD,<UNABLE TO CLOSE USAGE FILE>,,<

Cause:	This BUG is not documented yet.

Action:

>)
	SETZM USGEOF		;SETUP FOR NEW FILE

