;SIERRA::SRC:<GROSSMAN.NOLAT>SYSFLG.MAC.2,  6-Nov-86 14:23:01, Edit by GROSSMAN
; Turn off LAHFLG
;------------------------- Autopatch Tape # 13 -------------------------
;------------------------- Autopatch Tape # 12 -------------------------
; UPD ID= 2191, SNARK:<6.1.MONITOR>SYSFLG.MAC.7,   5-Jun-85 11:10:44 by MCCOLLUM
;TCO 6.1.1406  - Update copyright notice.
; UPD ID= 1338, SNARK:<6.1.MONITOR>SYSFLG.MAC.6,  15-Jan-85 14:10:52 by GROSSMAN
;TCO 6.1.1136 - Remove references to KNIN.
; UPD ID= 1309, SNARK:<6.1.MONITOR>SYSFLG.MAC.5,  11-Jan-85 14:06:17 by PAETZOLD
;Remove symbols that should not be here.
; UPD ID= 1179, SNARK:<6.1.MONITOR>SYSFLG.MAC.3,  11-Dec-84 14:09:13 by LEACHE
;Change EHLJSB to EXTJSB for extended JSB
; UPD ID= 1026, SNARK:<6.1.MONITOR>SYSFLG.MAC.2,  12-Nov-84 08:47:55 by GRANT
;Remove FTCI, CFSCOD, and LCSFLG
;SNARK:<6.1.MONITOR.CFS>SYSFLG.MAC.11  7-May-84 17:13:45, Edit by DMCDANIEL
;Turn LAT on via LAHFLG.
;SNARK:<6.1.MONITOR.CFS>SYSFLG.MAC.9  1-May-84 07:52:05, Edit by DMCDANIEL
;Add LAHFLG for LATSRV.
;SNARK:<6.1.MONITOR.KL>SYSFLG.MAC.11 15-Apr-84 14:07:50, Edit by GROSSMAN
;Remove FTNIDLL
;SNARK:<6.1.MONITOR.CFS>SYSFLG.MAC.7 15-Apr-84 08:47:17, Edit by GROSSMAN
;Update from CFS60:
;<6.MONITOR.KL>SYSFLG.MAC.26,  21-Mar-84 13:00:12, Edit by LOMARTIRE
;Remove SCADBG and SCARNG and place them under DEBUG
;Remove PIDBG because it is not needed anymore
;<6.MONITOR.KL>SYSFLG.MAC.25,  12-Mar-84 16:12:32, Edit by LOMARTIRE
;Add SCARNG
;Remove KLPDBG, it's now under DEBUG
;<6.MONITOR.KL>SYSFLG.MAC.21,  7-Nov-83 14:06:05, Edit by PURRETTA
;Remove FTKEARLY
;<6.MONITOR.KL>SYSFLG.MAC.20, 28-Oct-83 15:38:04, Edit by TGRADY
; Set DYNFLG to 0, not needed for this release
;Define CFSCOD and CFSSCA
;SNARK:<6.MONITOR.KL>SYSFLG.MAC.15  4-May-83 08:49:19, Edit by MOSER


;THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY  BE  USED
;OR COPIED ONLY IN ACCORDANCE WITH THE TERMS OF SUCH LICENSE.
;
;COPYRIGHT  (C)  DIGITAL  EQUIPMENT  CORPORATION  1976, 1985.
;ALL RIGHTS RESERVED.

;IFN STANSW,<
	SEARCH MONSYM		;Define STANSW
;>;End of IFN STANSW

;SPECIAL INSTALLATION DEPENDENT PARAMETERS NEEDED  FOR KL10

KLFLG==:1			;KL10
SMFLG==:0			;NOT KS10
KCFLG==:0			;NOT A KC10
DTFLG==:1			;USE FE FOR ALL TTY
DCFLG==:0			;NO DC10
DYNFLG==:0			;Don't Allow Dynamic Libraries
CTSFLG==:0			;Don't Allow Canonical Terminal Support
FTNSPSRV==:0			;Don't use NSPSRV for release 6.1
FTD36MM==:0			;Don't use DECNET-36 dull memory manager
				;Use ASGRES instead.
IFE STANSW,<
LAHFLG==:1			;Include LAT host code
>;End of IFE STANSW
IFN STANSW,<
LAHFLG==:0			;Don't include LAT host code
>;End of IFN STANSW
EXTJSB==:0			;No extended JSB

;Note: At present you must have KLPDBG turned on if you intend to use
;MSCDBG. It is OK to have KLPDBG turned on while MSCDBG is off however...
;
FTKLIPA==:1			;Include KLIPA code
FTMSCP==:1			;Include MSCP code
MSCDBG==:0			;Turn off MSCP debug code
CFSSCA==:1			;SCA interface for CFS code

;SPECIAL INSTALLATION DEPENDENT PARAMETERS NEEDED IN UNIVERSAL
;FILE

DEBUG==:0			;TURN ON DEBUGGING STUFF
SPTDSW==:0			;FORCE OFN LOCK DEBUGGING OFF

; 6.1 Specific parameters

FTP4R==:1			;Phase IV Router code from D36PAR
FTRTST==:1			;Router message looper


