!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING MMAILR
INFORMATION LOGICAL-NAMES FROM-*:
INFORMATION LOGICAL-NAMES TO-*:

;Files required to build product
COPY FROM-SOURCE:MMAILR.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MMAILR.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MMAILR.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:BLANKT.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:WAKEUP.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:HSTNAM.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SMTPSV.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAISER.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MMLBX.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SNDDEF.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:RELAY.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SNDMSG.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SMTJFN.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ARMAIL.MAC TO-SRCE:*.*.-1
COPY FROM-SOURCE:ARMAIL.MAC TO-SOURCE:MMAILR-ARMAIL.MAC
COPY FROM-SOURCE:SMTPSV.EXE TO-SRCE:*.*.-1
;Final product
COPY FROM-SOURCE:MMAILR.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:MAISER.EXE TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:SMTJFN.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:MMAILBOX.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:SMTPSV.EXE TO-SUBSYS:*.*.-1
