;[MIT-XX]SSY:<EXEC.TEST>EEASSM.CMD.2, 16-Jun-83 18:56:01, Edit by TEK
;716 add CE module
;715 move symbol table and patch area to high segment
;   add	PC,PI,PM,PS,PU,PX modules
;   if PCL is not to be included remove PI,PC,PX,PU modules by hand
;714 add MI,MP modules
;713 reorganize assembly files
;   source: EXEC??.MAC => object: XXEX??.REL

%"/SET:.HIGH.:150000/SYMSEG:HIGH"
EXEC:EECONF.MAC+EXEC:EXECDE.MAC+EXEC:EXECGL.MAC EEEXGL
EXEC:EXECPR.MAC EEEXPR		
EXEC:EXECVR.MAC EEEXVR		
EXEC:EXEC0.MAC  EEEX0
EXEC:EXECCA.MAC EEEXCA		
EXEC:EXEC1.MAC  EEEX1		
EXEC:EXECSE.MAC EEEXSE		
EXEC:EXECMT.MAC EEEXMT		
EXEC:EXECP.MAC  EEEXP		
EXEC:EXECIN.MAC EEEXIN		
EXEC:EXEC2.MAC  EEEX2
EXEC:EXEC3.MAC  EEEX3
EXEC:EXEC4.MAC  EEEX4	
EXEC:EXECED.MAC EEEXED		
EXEC:EXECCS.MAC EEEXCS		
EXEC:EXECQU.MAC EEEXQU		
EXEC:EXECMP.MAC EEEXMP
EXEC:EXECMI.MAC EEEXMI
EXEC:EXECCE.MAC EEEXCE
EXEC:EXECPM.MAC EEEXPM
EXEC:EXECPS.MAC EEEXPS
EXEC:EXECPI.REL
EXEC:EXECPC.REL
EXEC:EXECPX.REL
EXEC:EXECPU.REL
EXEC:EXECSU.MAC EEEXSU		
SYS:MACREL.REL

