condcc -c -IC: crt.c
condcc -c -IC: abort.c
condcc -c -IC: atoi.c
condcc -c -IC: bcopy.c
condcc -c -IC: cputm.c
condcc -c -IC: ctype.c
condcc -c -IC: dup.c
condcc -c -IC: fork.c
condcc -c -IC: getenv.c
condcc -c -IC: getpid.c
condcc -c -IC: gettim.c
condcc -c -IC: jsys.c
condcc -c -IC: malloc.c
condcc -c -IC: mktemp.c
condcc -c -IC: perror.c
condcc -c -IC: pipe.c
condcc -c -IC: pfork.c
condcc -c -IC: qsort.c
condcc -c -IC: rename.c
condcc -c -IC: sbrk.c
condcc -c -IC: setjmp.c
condcc -c -IC: signal.c
condcc -c -IC: sleep.c
condcc -c -IC: string.c
condcc -c -IC: system.c
condcc -c -IC: time.c
condcc -c -IC: unlink.c
condcc -c -IC: wait.c
