INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:ACTGEN.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ACTGEN.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ACTGEN.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:ACTGEN.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:ACTGEN.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:ACTGEN.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:ACTGEN.EXE TO-SUBSYS:*.*.-1
