
;Files required to build product
COPY FROM-SOURCE:ACTSYM.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ACTSYM.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ACTSYM.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:ACTSYM.TCO TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:ACTSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1

;Final product
