!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING CHECKD
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:CHECKD.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CHECKD.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CHECKD.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:CHECKD.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:CHECKD.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:CHECKD.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:QSRMAC.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:GLXMAC.UNV TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:PROLOG.UNV TO-SUBSYS:PROLOG.UNV

;Final product
COPY FROM-SOURCE:CHECKD.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:CHECKD.EXE TO-SYSTEM:*.*.-1
