!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING CHKPNT
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:CHKPNT.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CHKPNT.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ACTSYM.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CHKPNT.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:CHKPNT.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:CHKPNT.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:CHKPNT.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:ACTSYM.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:CHKPNT.EXE TO-SUBSYS:*.*.-1
