!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING CMD
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:CMD.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CMD.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CMD.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:REL1.MAC TO-SOURCE:*.*.-1

;Final product
COPY FROM-SOURCE:CMD.REL TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:CMD.UNV TO-SUBSYS:*.*.-1
