
;Files required to build product
COPY FROM-SOURCE:CNVDSK.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CNVDSK.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CNVDSK.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:CNVDSK.DOC TO-DOC:*.*.-1
COPY FROM-SOURCE:CNVDSK.HLP TO-SUBSYS:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:CNVDSK.EXE TO-SUBSYS:*.*.-1
