!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING DLUSER
INFORMATION LOGICAL-NAME

;Files required to build product
COPY FROM-SOURCE:DLUSER.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DLUSER.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DLUSER.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:DLUSER.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:DLUSER.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:DLUSER.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:DLUSER.EXE TO-SUBSYS:*.*.-1
