!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING DX20LD
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:DX20LD.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DX20LD.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DX20LD.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:DX20LD.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:DX20LD.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SUBSYS:UDDT.EXE TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:SDDT.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:DX20LD.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:DXMCA.ADX TO-SUBSYS:*.*.-1
