!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING FE
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:FE.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:FE.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:FE.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:FE.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:FE.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:FE.DOC TO-DOC:*.*.-1
COPY FROM-SOURCE:USEFE.MEM TO-DOC:*.*.-1

;Library files used for symbols

;Final product
COPY FROM-SOURCE:FE.EXE TO-SUBSYS:*.*.-1
