!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING FTP
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:FTP.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:FTP.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:FTP.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:FTPSER.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:FTP.DOC TO-DOC:*.*.-1
COPY FROM-SOURCE:FTP.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:FTP.TCO TO-DOC:*.*.-1

;Final product
COPY FROM-SOURCE:FTP.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:FTPSER.EXE TO-SYSTEM:*.*.-1
