INFORMATION LOGICAL-NAMES JOB

;Files required to build product
COPY FROM-SOURCE:HELPER.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:HELPER.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:HELPER.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:C.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:HELP.HLP TO-SOURCE:*.*.-1

;Final product
COPY FROM-SUBSYS:HELPER.REL TO-SUBSYS:*.*.-1

