!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING INFO
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:INFO.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:INFO.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:INFO.MAC TO-SOURCE:*.*.-1

COPY FROM-SOURCE:INFO.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:INFO.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:INFO.EXE TO-SUBSYS:*.*.-1
