INF LOG JOB

;Files required to build product
COPY FROM-SOURCE:JOBDAT.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:JOBDAT.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:JOBDAT.MAC TO-SOURCE:*.*.-1

;Final product
COPY FROM-SUBSYS:JOBDAT.REL TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:JOBDAT.UNV TO-SUBSYS:*.*.-1
