! UPD ID= 528, SNARK:<5.MONITOR>LN2060.CTL.13,  11-Mar-82 16:18:53 by PURRETTA
;Remove NSPINT
! UPD ID= 122, SNARK:<5.MONITOR>LN2060.CTL.12,  26-Aug-81 10:30:45 by GROUT
;Fix monitor checksums
;<5.MONITOR>LN2060.CTL.10, 26-Jan-81 10:26:24, EDIT BY GRANT
;Remove LCSSRV and CISRV
;<5.MONITOR>LN2060.CTL.9, 17-Jan-81 15:38:06, EDIT BY HALL
;add PHYP2
;<5.MONITOR>LN2060.CTL.8, 17-Jan-81 15:35:31, EDIT BY HALL
;add getsav
! UPD ID= 1379, SNARK:<5.MONITOR>LN2060.CTL.7,  23-Dec-80 04:40:56 by WACHS
;<5.MONITOR>LN2060.CTL.6,  3-Oct-80 14:55:40, EDIT BY ENGEL
;<5.MONITOR>LN2060.CTL.4, 20-Aug-80 22:56:32, EDIT BY MURPHY
;REMOVE FILNSP
!
! NAME: LN2060.CTL
! DATE: 21-JUN-78
!
!
! FUNCTION:	THIS CONTROL FILE BUILDS THE LN2060
!		MONITORS FROM SOURCES.
!
!TO ASSEMBLE AND BUILD ALL STANDARD LN2060 MONITORS:
!SUBMIT LN2060/TIME:2:0:0
!
!TO LOAD ALL STANDARD LN2060 MONITORS USING LN2060.REL:
!SUBMIT LN2060/TAG:ALL/TIME:1:0:0
!
!TO LOAD JUST ONE LN2060 MONITOR USING PARAM0 AND LN2060.REL:
!SUBMIT LN2060/TAG:SINGLE/TIME:1:0:0
!


@ENA
@NOERROR
@TAKE BATCH
@INFORMATION LOGICAL-NAMES ALL
!
! TAKE A CHECKSUMMED DIRECTORY OF ALL THE INPUT FILES
!
@VDIRECT SYS:LINK.EXE.0,SYS:CREF.EXE.0,SYS:MACRO.EXE.0,
@CHECKSUM SEQ
@
@VDIRECT SYS:MONSYM.UNV.0,SYS:MACSYM.UNV.0,SYS:MACREL.REL.0,SYS:PA1050.EXE.0,
@CHECKSUM SEQ
@
@
@GET SYS:MACRO
@INFORMATION VERSION
@GET SYS:LINK
@INFORMATION VERSION
@GET SYS:CREF
@INFORMATION VERSION
!
@DELETE MON.*
@COMPIL @MON:ASEMBL.CMD

!MAKE THE LIBRARY FILE
!
@DELETE LN2060.REL
@APPEND APRSRV.REL,SCHED.REL,PAGEM.REL LN2060.REL
@APPEND FORK.REL,MEXEC.REL,GETSAV.REL,SYSERR.REL,COMND.REL,DEVICE.REL LN2060.REL
@APPEND DIRECT.REL,ENQ.REL,FREE.REL,FUTILI.REL,GTJFN.REL LN2060.REL
@APPEND IO.REL,IPCF.REL,JSYSA.REL,JSYSF.REL,LOGNAM.REL LN2060.REL
@APPEND LOOKUP.REL,MSTR.REL,SWPALC.REL,DISC.REL,EFILIN.REL LN2060.REL
@APPEND FILMSC.REL,MFLIN.REL,MFLOUT.REL,DATIME.REL LN2060.REL
@APPEND PHYSIO.REL,DIAG.REL,DSKALC.REL,PHYH2.REL,PHYP4.REL,PHYP2.REL,TTYSRV.REL LN2060.REL
@APPEND FESRV.REL,MAGTAP.REL,TAPE.REL,TIMER.REL,PHYM2.REL,PHYX2.REL,DTESRV.REL,LINEPR.REL LN2060.REL
@APPEND PHYM78.REL,CDPSRV.REL,PLT.REL,PTP.REL,PTR.REL LN2060.REL
@APPEND CDRSRV.REL,NSPSRV.REL LN2060.REL
@APPEND KDDT.REL,MDDT.REL,POSTLD.REL LN2060.REL
!
@GOTO ALL1
!
ALL::
@INFORMATION LOGICAL-NAMES ALL
!
! TAKE A CHECKSUMMED DIRECTORY OF ALL THE INPUT FILES
!
@VDIRECT SYS:LINK.EXE.0,SYS:CREF.EXE.0,SYS:MACRO.EXE.0,
@CHECKSUM SEQ
@
@VDIRECT SYS:MONSYM.UNV.0,SYS:MACSYM.UNV.0,SYS:MACREL.REL.0,SYS:PA1050.EXE.0,
@CHECKSUM SEQ
@
@
@GET SYS:MACRO
@INFORMATION VERSION
@GET SYS:LINK
@INFORMATION VERSION
@GET SYS:CREF
@INFORMATION VERSION
!
ALL1::
!
@DELETE MON.*
!
!BUILD A BIG MONITOR
I PR
@DEL STG.REL,VERSIO.REL
@EXP
DAY
I PR
@COMPILE /COMP MON:N60BIG.MAC+MON:VERSIO.MAC VERSIO
@COMPILE /COMP MON:KLPRE.MAC+MON:P60BIG.MAC+MON:PARAMS.MAC+MON:STG.MAC STG
@R LINK
*@LNKMSX.CCL
*LN2060/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET MON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
RENAME MONITR.EXE.0 2060-MONBIG.EXE
!
!BUILD A MAX MONITOR
I PR
@DEL STG.REL,VERSIO.REL
@EXP
DAY
I PR
@COMPILE /COMP MON:N60MAX.MAC+MON:VERSIO.MAC VERSIO
@COMPILE /COMP MON:KLPRE.MAC+MON:P60MAX.MAC+MON:PARAMS.MAC+MON:STG.MAC STG
@R LINK
*@LNKMSX.CCL
*LN2060/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET MON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
RENAME MONITR.EXE.0 2060-MONMAX.EXE
!
@DIR 2060-*.EXE.0,
@CHECKSUM SEQ
@
@GOTO E
!
SINGLE::
!
!BUILD MONITR.EXE USING PARAM0, NAMAM0 AND LN2060.REL
!
@INFORMATION LOGICAL-NAMES ALL
!
! TAKE A CHECKSUMMED DIRECTORY OF ALL THE INPUT FILES
!
@VDIRECT SYS:LINK.EXE.0,SYS:CREF.EXE.0,SYS:MACRO.EXE.0,
@CHECKSUM SEQ
@
@VDIRECT SYS:MONSYM.UNV.0,SYS:MACSYM.UNV.0,SYS:MACREL.REL.0,SYS:PA1050.EXE.0,
@CHECKSUM SEQ
@
@
@GET SYS:MACRO
@INFORMATION VERSION
@GET SYS:LINK
@INFORMATION VERSION
@GET SYS:CREF
@INFORMATION VERSION
!
!
@DELETE MON.*
@DELETE STG.REL, VERSIO.REL
@DEL MONITR.*
!
@COMPILE /COMP MON:NAMAN0.MAC+MON:VERSIO.MAC VERSIO
@COMPILE /COMP MON:KLPRE.MAC+MON:PARAM0.MAC+MON:PARAMS.MAC+MON:STG.MAC STG
@R LINK
*@MON:LNKMSX.CCL
*LN2060/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@DELETE STG.REL, VERSIO.REL
@EXP
@GET MON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
G
!
@DIR MONITR.EXE.0,
@CHECKSUM SEQ
@
E::

!
@DELETE MON.*
!END OF LN2060.CTL
