!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING MAILER
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:MAILER.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAILER.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAILER.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:MAILER.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:MAILER.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:MAILER.EXE TO-SUBSYS:*.*.-1
