INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:MAKLIB.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAKLIB.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAKLIB.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:MAKLIB.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:MAKLIB.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:HELPER.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:WILD.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:SCN7B.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACTEN.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:UUOSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:SCNMAC.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:MAKLIB.EXE TO-SUBSYS:*.*.-1
