!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING MAKVFU
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:MAKVFU.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAKVFU.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAKVFU.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:MAKVFU.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:MAKVFU.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:MAKVFU.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:MAKVFU.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:NORMAL.VFU TO-SUBSYS:*.*.-1
