!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING MAPPER
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:MAPPER.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAPPER.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAPPER.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:MAPPER.TCO TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:MAPPER.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:PROGRAM-NAME-CACHE.TXT TO-SYSTEM:*.*.-1
