!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING NETSTA
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:NETSTA.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:NETSTA.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:NETSTA.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:NETSTA.DOC TO-DOC:*.*.-1
COPY FROM-SOURCE:NETSTA.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:NETSTA.TCO TO-DOC:*.*.-1

;Final product
COPY FROM-SOURCE:NETSTA.EXE TO-SUBSYS:*.*.-1
