!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING NETSRV
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:NETSRV.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:NETSRV.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:NETSRV.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:NETSRV.DOC TO-DOC:*.*.-1
COPY FROM-SOURCE:NETSRV.HLP TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:NETSRV.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:NETSRV.RUN TO-SYSTEM:*.*.-1
