!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING NMAILR
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:NMAILR.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:NMAILR.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:NMAILR.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:NMAILR.DOC TO-DOC:*.*.-1
COPY FROM-SOURCE:NMAILR.TCO TO-DOC:*.*.-1

;Final product
COPY FROM-SOURCE:NMAILR.EXE TO-SUBSYS:*.*.-1
