!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING PAT
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:PAT.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:PAT.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:PAT.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:PAT.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:PAT.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:UDDT.EXE TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:SDDT.EXE TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:FILDDT.EXE TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:FEDDT.EXE TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:PAT.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:PA1050.EXE TO-SUBSYS:*.*.-1
