!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING RDMAIL
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:RDMAIL.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:RDMAIL.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:RDMAIL.MAC TO-SOURCE:*.*.-1
;COPY FROM-SOURCE:REL1.MAC TO-SOURCE:*.*.-1
;COPY FROM-SOURCE:CMD.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:RDMAIL.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:RDMAIL.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:RDMAIL.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:RDMAIL.EXE TO-SUBSYS:*.*.-1
