!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING REAPER
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:REAPER.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:REAPER.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ARMAIL.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:REAPER.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:REAPER.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:REAPER.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:REAPER.DOC TO-DOC:*.*.-1

;Library files used for symbols

;Final product
COPY FROM-SOURCE:REAPER.EXE TO-SUBSYS:*.*.-1
