INF LOG JOB

;Files required to build product
COPY FROM-SOURCE:SCAN.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SCAN.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SCAN.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SCNMAC.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:SCAN.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACTEN.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:UUOSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:C.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SUBSYS:SCAN.REL TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:SCNMAC.UNV TO-SUBSYS:*.*.-1
