!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING SNDMSG
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:SNDMSG.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SNDMSG.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SNDMSG.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:SNDMSG.DOC TO-DOC:*.*.-1
COPY FROM-SOURCE:SNDMSG.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:SNDMSG.TCO TO-DOC:*.*.-1

;Final product
COPY FROM-SOURCE:SNDMSG.EXE TO-SUBSYS:*.*.-1
