!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING SYSJOB
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:SYSJOB.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SYSJOB.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SYSJOB.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:SYSJOB.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:SYSJOB.HLP TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:SYSJOB.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:SYSJOB.EXE TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:SYSJOB.RUN TO-SYSTEM:*.*.-1
