! UPD ID= 529, SNARK:<5.MONITOR>T20-AN.CTL.15,  11-Mar-82 16:21:37 by PURRETTA
;Remove NSPINT
! UPD ID= 213, SNARK:<5.MONITOR>T20-AN.CTL.13,  24-Sep-81 15:51:49 by PAETZOLD
! UPD ID= 123, SNARK:<5.MONITOR>T20-AN.CTL.12,  26-Aug-81 10:35:38 by GROUT
;Fix monitor checksums
! UPD ID= 1501, SNARK:<5.MONITOR>T20-AN.CTL.10,  26-Jan-81 17:56:17 by ZIMA
;TCO 5.1252 - Make the REL library Autopatchable, remove FILINI.
;<5.MONITOR>T20-AN.CTL.9, 26-Jan-81 10:28:49, EDIT BY GRANT
;Remove LCSSRV and CISRV
;<5.MONITOR>T20-AN.CTL.6,  3-Oct-80 14:56:38, EDIT BY ENGEL
;<5.MONITOR>T20-AN.CTL.4, 20-Aug-80 22:56:49, EDIT BY MURPHY
;REMOVE FILNSP
! NAME: T20-AN.CTL
! DATE: 20-JUN-78
!
!
! FUNCTION:	THIS CONTROL FILE BUILDS THE TOPS20-AN
!		MONITORS FROM SOURCES.
!
!TO ASSEMBLE AND BUILD ALL STANDARD TOPS20-AN MONITORS:
!SUBMIT T20-AN/TIME:2:0:0
!
!TO LOAD ALL STANDARD T20-AN MONITORS USING T20AN.REL:
!SUBMIT T20-AN/TAG:ALL/TIME:1:0:0
!
!TO LOAD JUST ONE T20-AN MONITOR USING PARAN AND T20AN.REL:
!SUBMIT T20-AN/TAG:SINGLE/TIME:1:0:0
!
@NOERROR
@TAKE BATCH
@INFORMATION LOGICAL-NAMES ALL
!
! TAKE A CHECKSUMMED DIRECTORY OF ALL THE INPUT FILES
!
@VDIRECT SYS:LINK.EXE.0,SYS:CREF.EXE.0,SYS:MACRO.EXE.0,
@CHECKSUM SEQ
@
@VDIRECT SYS:MONSYM.UNV.0,SYS:MACSYM.UNV.0,SYS:MACREL.REL.0,SYS:PA1050.EXE.0,
@CHECKSUM SEQ
@
@
@GET SYS:MACRO
@INFORMATION VERSION
@GET SYS:LINK
@INFORMATION VERSION
@GET SYS:CREF
@INFORMATION VERSION
!
@DEL AMON.*
@DEL STGAN.REL,VERSIO.REL

@COMPIL @MON:ASEMBL.CMD

!MAKE THE LIBRARY FILE
!
@DELETE T20AN.REL
@APPEND APRSRV.REL,SCHED.REL,PAGEM.REL T20AN.REL
@APPEND FORK.REL,MEXEC.REL,GETSAV.REL,SYSERR.REL,COMND.REL,DEVICE.REL T20AN.REL
@APPEND DIRECT.REL,ENQ.REL,FREE.REL,FUTILI.REL,GTJFN.REL T20AN.REL
@APPEND IO.REL,IPCF.REL,JSYSA.REL,JSYSF.REL,LOGNAM.REL T20AN.REL
@APPEND LOOKUP.REL,MSTR.REL,SWPALC.REL,DISC.REL,EFILIN.REL T20AN.REL
@APPEND FILMSC.REL,MFLIN.REL,MFLOUT.REL,DATIME.REL T20AN.REL
@APPEND PHYSIO.REL,DIAG.REL,DSKALC.REL,PHYH2.REL,PHYP4.REL,PHYP2.REL T20AN.REL
@APPEND TTYSNV.REL,FESRV.REL,MAGTAP.REL,TAPE.REL,TIMER.REL T20AN.REL
@APPEND PHYM2.REL,PHYM78.REL,PHYX2.REL,DTESRV.REL T20AN.REL
@APPEND LINEPR.REL,CDRSRV.REL,IMPDV.REL T20AN.REL
@APPEND PLT.REL,PTR.REL,PTP.REL,CDPSRV.REL T20AN.REL
@APPEND NETWRK.REL,IMPANX.REL,NSPSRV.REL,KDDT.REL,MDDT.REL,POSTLD.REL T20AN.REL
!
@GOTO ALL1
!
ALL::
@INFORMATION LOGICAL-NAMES ALL
!
! TAKE A CHECKSUMMED DIRECTORY OF ALL THE INPUT FILES
!
@VDIRECT SYS:LINK.EXE.0,SYS:CREF.EXE.0,SYS:MACRO.EXE.0,
@CHECKSUM SEQ
@
@VDIRECT SYS:MONSYM.UNV.0,SYS:MACSYM.UNV.0,SYS:MACREL.REL.0,SYS:PA1050.EXE.0,
@CHECKSUM SEQ
@
@
@GET SYS:MACRO
@INFORMATION VERSION
@GET SYS:LINK
@INFORMATION VERSION
@GET SYS:CREF
@INFORMATION VERSION
!
ALL1::
!
@DEL AMON.*
@DEL STGAN.REL,VERSIO.REL
!
!
!BUILD A SMALL MONITOR
@EXP
DAY
I PR
@COMPIL /COMP MON:ANNSML.MAC+MON:VERSIO.MAC VERSIO
@COMPIL /COMP MON:KLPRE.MAC+MON:ANPSML.MAC+MON:PARAMS.MAC+MON:STG.MAC STGAN
@R LINK
*@MON:LNKANS.CCL
*T20AN/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
RENAME AMONITR.EXE.0 AN-MONSML.EXE
!
!BUILD A MEDIUM MONITOR
@DEL STGAN.REL,VERSIO.REL
@EXP
DAY
I PR
@COMPIL /COMP MON:ANNMED.MAC+MON:VERSIO.MAC VERSIO
@COMPIL /COMP MON:KLPRE.MAC+MON:ANPMED.MAC+MON:PARAMS.MAC+MON:STG.MAC STGAN
@R LINK
*@MON:LNKANS.CCL
*T20AN/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
RENAME AMONITR.EXE.0 AN-MONMED.EXE
!
!BUILD A BIG MONITOR
I PR
@DEL STGAN.REL,VERSIO.REL
@EXP
DAY
I PR
@COMPIL /COMP MON:ANNBIG.MAC+MON:VERSIO.MAC VERSIO
@COMPIL /COMP MON:KLPRE.MAC+MON:ANPBIG.MAC+MON:PARAMS.MAC+MON:STG.MAC STGAN
@R LINK
*@MON:LNKANS.CCL
*T20AN/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
RENAME AMONITR.EXE.0 AN-MONBIG.EXE
!
!BUILD A LARGE MONITOR
I PR
@DEL STGAN.REL,VERSIO.REL
@EXP
DAY
I PR
@COMPIL /COMP MON:ANNLGE.MAC+MON:VERSIO.MAC VERSIO
@COMPIL /COMP MON:KLPRE.MAC+MON:ANPLGE.MAC+MON:PARAMS.MAC+MON:STG.MAC STGAN
@R LINK
*@MON:LNKANS.CCL
*T20AN/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
RENAME AMONITR.EXE.0 AN-MONLGE.EXE
!
@DIR AN-MON*.EXE.0,
@CHECKSUM SEQ
@
!
@GOTO E
!
SINGLE::
!
!BUILD AMONITR.EXE USING PARAN, NAMAN AND T20AN.REL
!
@INFORMATION LOGICAL-NAMES ALL
!
! TAKE A CHECKSUMMED DIRECTORY OF ALL THE INPUT FILES
!
@VDIRECT SYS:LINK.EXE.0,SYS:CREF.EXE.0,SYS:MACRO.EXE.0,
@CHECKSUM SEQ
@
@VDIRECT SYS:MONSYM.UNV.0,SYS:MACSYM.UNV.0,SYS:MACREL.REL.0,SYS:PA1050.EXE.0,
@CHECKSUM SEQ
@
@
@GET SYS:MACRO
@INFORMATION VERSION
@GET SYS:LINK
@INFORMATION VERSION
@GET SYS:CREF
@INFORMATION VERSION
!
!
@DEL AMON.*
@DEL AMONITR.*
@DEL STGAN.REL,VERSIO.REL
!
@COMPIL /COMP MON:NAMAN.MAC+MON:VERSIO.MAC VERSIO
@COMPIL /COMP MON:KLPRE.MAC+MON:PARAN.MAC+MON:PARAMS.MAC+MON:STG.MAC STGAN
@R LINK
*@MON:LNKANS.CCL
*T20AN/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET AMON
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
=G
!
@DIR AMONITR.EXE.0,
@CHECKSUM SEQ
@
!
E::

!
@DELETE AMON.*
!END OF T20-AN.CTL
