
;Files required to build product
COPY FROM-SOURCE:T20-AN.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ASEMBL.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:T20-AN.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SYSTAP.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANPLGE.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANPBIG.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANPMED.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANPSML.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANNLGE.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANNBIG.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANNMED.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:ANNSML.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:BUGS.MAC TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:KLPRE.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:STG.MAC TO-SOURCE:*.*.-1
COPY NUL: TO-SOURCE:PARAM0.MAC
COPY FROM-SOURCE:PARAMS.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:VERSIO.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:TOPS20.BWR TO-DOC:*.*.-1
COPY FROM-SOURCE:TOPS20.BWR TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:BUILD.MEM TO-DOC:*.*.-1
COPY FROM-SOURCE:BOOT.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:TOPS20.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:BOOT.DOC TO-DOC:*.*.-1
COPY FROM-SOURCE:TOPS20.DOC TO-DOC:*.*.-1
COPY FROM-SOURCE:TOPS20.DOC TO-SYSTEM:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:ACTSYM.UNV TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:PROKL.UNV TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:SERCOD.UNV TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:PHYPAR.UNV TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:PROLOG.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SUBSYS:T20AN.REL TO-SOURCE:*.*.-1
COPY FROM-SUBSYS:LDINIT.REL TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:AN-MONLGE.EXE TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:AN-MONBIG.EXE TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:AN-MONMED.EXE TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:AN-MONSML.EXE TO-SYSTEM:*.*.-1
COPY FROM-SUBSYS:FEDDT.EXE TO-SYSTEM:*.*.-1
;COPY FROM-SUBSYS:MAKDMP.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:BUGSTRINGS.TXT TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:RSX20F.MAP TO-SYSTEM:*.*.-1
COPY FROM-SOURCE:LNKANS.CCL TO-SOURCE:*.*.-1

;AUTOPATCH FILES
;COPY FROM-SOURCE:T20LM5.LNK TO-SOURCE:*.*.-1
