!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING VERIFY
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:VERIFY.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:VERIFY.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:VERIFY.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:VERIFY.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:VERIFY.DOC TO-DOC:*.*.-1

;Library files used for symbols

;Final product
COPY FROM-SOURCE:VERIFY.EXE TO-SUBSYS:*.*.-1
