!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING WATCH
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:WATCH.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:WATCH.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SYMSUB.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:WATMAI.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:WATDAT.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:WATCH.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:WATCH.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:WATCH.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:WATCH.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:MACREL.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MONSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:PROLOG.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:WATCH.EXE TO-SUBSYS:*.*.-1
