INF LOG JOB

;Files required to build product
COPY FROM-SOURCE:WILD11.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:WILD11.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:RNFSCC.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:WILD11.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:WILD11.TCO TO-DOC:*.*.-1

;Library files used for symbols
COPY FROM-SUBSYS:WILD11.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:UUOSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACTEN.UNV TO-SUBSYS:*.*.-1

;Final product
