INF LOG JOB

;Files required to build product
COPY FROM-SOURCE:WILD.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:WILD.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:WILD.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-DOC:WILD.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:UUOSYM.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:MACTEN.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:C.UNV TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:SCNMAC.UNV TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SUBSYS:WILD.REL TO-SUBSYS:*.*.-1
