;<5.ISI.MONITOR>IMPPAR.MAC.5010	22-Oct-82 08:56:28	Edit by JGOLDBERGER
;#501 Version 5 Multinet
;[BBND]<MONITOR>IMPPAR.MAC.2, 22-Jan-81 12:16:10, Ed: RBASCH
;Completed merge with DEC's final Release 4 code, also including stripping
;out all conditional assembly depending on the values of %%BASE and %%MODS
;(deleting %%BASE code).
;<4.MONITOR>IMPPAR.MAC.18,  3-Jan-80 08:08:57, EDIT BY R.ACE
;UPDATE COPYRIGHT DATE
;<4.MONITOR>IMPPAR.MAC.17,  3-Jan-79 13:01:10, Edit by LCAMPBELL
; Move definition of STY%NP to device-dependent modules
;<3A-JBORCHEK>IMPPAR.MAC.3, 24-Aug-78 19:54:37, EDIT BY JBORCHEK
;<3-CLEMENTS>IMPPAR.MAC.5, 11-Aug-78 23:40:16, EDIT BY CLEMENTS
;<3-CLEMENTS>IMPPAR.MAC.4, 11-Aug-78 22:57:31, EDIT BY CLEMENTS
;<3-CLEMENTS>IMPPAR.MAC.3, 11-Aug-78 17:45:01, EDIT BY CLEMENTS
;<3-CLEMENTS>IMPPAR.MAC.2, 11-Aug-78 16:21:53, EDIT BY CLEMENTS
;<3-CLEMENTS>IMPPAR.MAC.1, 11-Aug-78 16:14:30, EDIT BY CLEMENTS
;<BBN-3-MONITOR>IMPPAR.MAC.1,  4-Aug-78 14:56:49, EDIT BY CLEMENTS
;<3-CLEMENTS>IMPPAR.MAC.3, 30-Jul-78 23:28:43, EDIT BY CLEMENTS
; Only keep PROLOG stuff not local to IMPDV
;[BBN-TENEXD]<3-FRENCH>IMPPAR.MAC.1, 18-Jul-78 12:59:10, Ed: FRENCH
;ADDED STUFF TAKEN FROM BOB'S IMPDV WHICH HE GOT FROM DEC PROLOG?
;<3-CLEMENTS>IMPPAR.MAC.1, 15-Jun-78 14:24:07, EDIT BY CLEMENTS
;<BBN-1B-MONITOR>IMPPAR.MAC.8, 10-Mar-78 00:34:58, EDIT BY CLEMENTS
; Repair def of Inetf
;<BBN-1B-MONITOR>IMPPAR.MAC.7    24-Feb-78 12:27:04    EDIT BY PLUMMER
;<BBN-1B-MONITOR>IMPPAR.MAC.6    24-Feb-78 12:02:54    EDIT BY PLUMMER
; Add definitions needed for IMPPHY to find Internet format and version
;<BBN-1B-MONITOR>IMPPAR.MAC.5    23-Feb-78 17:19:05    EDIT BY PLUMMER
; Define STY%FC and STY%UC
;<ITP>IMPPAR.MAC.1    22-Feb-78 14:17:56    EDIT BY PLUMMER
; Define IHADR
; Define INTLNK
;<BBN-1B-MONITOR>IMPPAR.MAC.3, 26-Jan-78 15:58:49, EDIT BY CLEMENTS
;Add CLINK, FLINK, TNTLNK
;<BBN-1B-MONITOR>IMPPAR.MAC.2, 26-Jan-78 14:31:10, EDIT BY CLEMENTS
; Define LLINK as last link, not last plus 1, to make easier to understand
;<BBN-1B-MONITOR>IMPPAR.MAC.1, 25-Jan-78 16:19:15, EDIT BY CLEMENTS
; Into main line sources for reference by all.
;<1B-CLEMENTS>IMPPAR.MAC.11, 29-Nov-77 16:13:31, EDIT BY CLEMENTS
;<1B-CLEMENTS>IMPPAR.MAC.10, 11-Nov-77 17:38:15, EDIT BY CLEMENTS

;COPYRIGHT (C) 1977,1978,1979,1980, Digital Equipment Corp., Maynard, Mass.

	UNIVERSAL IMPPAR - UNIVERSAL FOR IMPDV AND ASSOCIATED MODULES
	SALL
	SEARCH MONSYM,MACSYM



;DEFINE THE WORDS IN A NET BUFFER

.NBHDR==0	;WORD 0 IS THE BUFFER HEADER (QUEUE POINTER AND SIZE)
.NBLD0==1	;IMP-TO-HOST LEADER, WORD 0
.NBLD1==2	;I-H LEADER, WORD 1
.NBLD2==3	;I-H LEADER, WORD 2
  .NBPTR==3	;While a file buffer, pointer to next byte goes here.
.NBHHL==4	;HOST-TO-HOST LEADER
  .NBCNT==4	;While a file buffer, count of bytes goes here.
.NBDW0==5	;DATA WORD ZERO

;DEFINE THE FIELDS IN THE BUFFER HEADER

DEFSTR NBQUE,.NBHDR,17,18	;LINK FOR QUEUE OF BUFFERS
DEFSTR NBBSZ,.NBHDR,35,18	;SIZE OF THE BUFFER

;FIELDS IN IMP-TO-HOST LEADER

DEFSTR IHFTY,.NBLD0,7,4		;FORMAT TYPE FIELD. MUST BE 17 FOR LONG LDRS
	ITY%LL==17		;Type 17 for long leaders from IMP
DEFSTR IHNET,.NBLD0,15,8	;NETWORK NUMBER MSG GOES TO/FROM
DEFSTR IHLDF,.NBLD0,23,4	;LEADER FLAGS
DEFSTR IHMTY,.NBLD0,31,8	;MESSAGE TYPE
DEFSTR IHHT2,.NBLD0,35,4	;High 4 bits of handling type
DEFSTR IHHTY,.NBLD1,3,4		;Handling type, low 4 bits
	HTY%NP==7		;Number of packets
	HTY%HP==200		;High priority bit
DEFSTR IHADR,.NBLD1,27,24	; Address (Host and IMP)
  ; Substructures for above
  DEFSTR IHHST,.NBLD1,11,8	;HOST (ON IMP)
  DEFSTR IHIMP,.NBLD1,27,16	;IMP NUMBER
DEFSTR IHLNK,.NBLD1,35,8	;LINK (TOP 8 OF MESSAGE ID)
DEFSTR IHMI2,.NBLD2,3,4		;REST OF MESSAGE ID
DEFSTR IHSTY,.NBLD2,7,4		;SUBTYPE
	STY%FC==0		; Normal flow-controlled
	STY%UC==3		; Uncontrolled flow
DEFSTR IHLEN,.NBLD2,23,16	;LENGTH OF MESSAGE
DEFSTR IHPD1,.NBLD2,35,12	;Low 12 bits must be moved to flush padding

;NETWRK and IMPDV treat a host address as one 32-bit quantity

HSTMSK==037777777777	; Net b4-b11, Host b12-b19, Imp b20-b35

; For user interface only, old-style Imp message leader bits

IMPHIP==1B0		; Hi priority imp msg leader bit
FRMIMP==1B1		; From imp

;FIELDS IN HOST-TO-HOST LEADER

DEFSTR HHSIZ,.NBHHL,11,8	;CONNECTION BYTE SIZE
DEFSTR HHCNT,.NBHHL,27,16	;NUMBER OF BYTES IN THIS MESSAGE

;Imp-to-Host parameters

FKHOST==^D252		;Fake hosts are 252. thru 255. on each Imp.

;Host-to-Host parameters, NCP defined

CLINK==0		;Control link
FNLINK==2		;First connection link, NCP
LLINK==^D71		;Last link usable by NCP.

;Special link numbers required for dispatching

TNTLNK==^D165		;Telenet traffic
INTLNK==^D155		; Internet traffic

;Message types in IHMTY (I2H = Imp to Host, & v.v.)

.IHREG==0		;Regular messages (Host-to-host)
.IHEWO==1		;Error, WithOut message ID (H2I)
.IHEIL==1		;Err in leader (I2H)
.IHHGD==2		;Host Going Down (H2I)
.IHIGD==2		;Imp Going Down (I2H)
.IHUNC==3		; Uncontrolled
.IHNOP==4		;No-op, takes padding request, tells my address.
.IHRFN==5		;Ready For Next message (I2H)
.IHDHS==6		;Dead Host Status (I2H)
.IHDDD==7		;Destination DeaD (I2H)
.IHERW==^D8		;Error, With message ID (H2I)
.IHERD==^D8		;Error in Data (I2H)
.IHINC==^D9		;Incomplete transmission (I2H)
.IHRES==^D10		;Interface reset (I2H)

; Special Internet parameters  -- must agree with TCPDEF.MAC

.INVER==.NBHHL+0	; Word in H-H leader containing Internet version
.INPRO==.NBHHL+2	; Word in H-H leader containing Internet protocol

DEFSTR(INPVR,.INVER,3,4)	; Internet packet version
  .INTVR==4
DEFSTR(INPPR,.INPRO,15,8)	; Internet packet protocol
  .SCRFM==2			; Secure TCP format

; Following belongs in NETWRK only, but IMPDV still uses it

DEFSTR LTIDX,NETAWD,35,9	;LINK TABLE INDEX


;;; Shared by MIMPDV and 1822DV (until NCP goes away)

;Fields in implt1

L1%FRE==1B19		;Bit on if LT entry is free
L1%SND==1B18		;Bit on if this is a send link
			;But if FRE is on, SND tells free from deleted
L1%LNK==377B35		;Link number mask
MSKSTR LTLINK,IMPLT1,L1%LNK

; Bits in implt2

RFNMCM==3B1		; RFNM outstanding (2 bit count)
LTDF==1B2		; 'done' flag
HIPFLG==1B3		; High priority connection
ILCKB==1B4		; Connection locked (no transmissions)
RXMTF==1B5		; Retransmission after time-out
RARF==1B6		; RAR expected
RARRF==1B7		; Send RAS when no RFNM's out

MSKSTR RFNMC,IMPLT2,RFNMCM	;RFNM COUNT FIELD
DEFSTR ILTBS,IMPLT2,17,8	;LINK TABLE'S CONNECTION BYTE SIZE

;Fields in implt5

DEFSTR LTHOST,IMPLT5,35,36	;Host number 32 bits wide


	END ; OF IMPPAR.MAC
