;[MIT-XX]SSY:<MONITOR.M5>PARXX.MAC.4, 25-Jun-84 10:44:30, Edit by BERLIN
;5766 Remove NHOSTS
;[MIT-XX]SSY:<MONITOR.M5>PARXX.MAC.2, 25-Mar-84 14:46:26, Edit by BERLIN
;3055 Add 16 more DH lines
;[MIT-XX]PS:<BERLIN.M5>PARXX.MAC.19,  1-Mar-83 09:32:42, Edit by BERLIN
;3032 ISIC version: no chaos, pacific time, tu77, no DX20
;[MIT-XX]SSY:<BERLIN.M5>PARXX.MAC.16, 18-Jan-83 14:13:05, Edit by BERLIN
;3025 Play with sections to maybe improve response? (changed back...)
;[MIT-XX]SSY:<BERLIN.M5>PARXX.MAC.14,  3-Jan-83 11:13:13, Edit by BERLIN
;3017 Flush NCP NVT's, more TVT's
;3015 Change CHST2P from ^D13 to ^D15, because host table grew
;<BERLIN.M5>PARXX.MAC.13  18-Nov-82 16:19:04, Edit by ROBERT
;1033 Remove bugptrs (bugstf==> 0)
;<BERLIN.M5>PARXX.MAC.2,  5-Jul-82 00:30:16, Edit by BERLIN
;1000 V5 merge
;	SPLTN ==> 0	(dover doesn't spool this way any more)
;  *** for now, no TCP/IP ***
;<SYS.MONITOR>PARXX.MAC.17,  5-May-82 13:10:22, Edit by BERLIN
;291 Limit CHST2P to 11 due to address space limitations
;<SYS.MONITOR>PARXX.MAC.16, 15-Apr-82 16:43:33, Edit by BERLIN
;286 increase number of tty buffers
;<SYS.MONITOR>PARXX.MAC.15, 23-Feb-82 15:16:45, Edit by BERLIN
;271 Remove PUP vestiges
;<SYS.MONITOR>PARXX.MAC.14, 29-Jan-82 16:11:39, Edit by BERLIN
;266 Increase number of forks for XX
;SRC:<SYS.MONITOR>PARXX.MAC.13 11-Nov-81 14:24:10, Edit by BERLIN
;250 Increase swapping space to 15K pages in prep for 3-pack PS
;SRC:<SYS.MONITOR>PARXX.MAC.12 30-Sep-81 10:34:22, Edit by BERLIN
;240 Fix number of PTY's to match definition
;SRC:<SYS.MONITOR>PARXX.MAC.11 15-Sep-81 15:45:58, Edit by BERLIN
;236 Increase number of fe lines, remove bugstrings
;SRC:<SYS.MONITOR>PARXX.MAC.9 15-Sep-81 15:33:27, Edit by BERLIN
;Increase swapping pages
;SRC:<SYS.MONITOR>PARXX.MAC.5  8-Dec-80 12:38:48, Edit by CPR
; Make number of jobs more reasonable (75).
;<SYS.MONITOR>PARXX.MAC.3,  4-Sep-80 15:22:11, Edit by MT
; Dike out Pup support
;<4.MONITOR>PARXX.MAC.1, 10-Feb-80 20:07:43, Edit by MT
;<SOURCES.3A>PARAM0.MAC.10, 28-Mar-79 01:00:00, Edit by DANG
; PARAMETERS FOR MIT-XX

TMZONE==:5			;TIME ZONE (8 for Pacific time)

;ASSEMBLY FEATURES

BUGSTF==:0			;1033 Remove bug pointers for more address space

ANBSEC==:5			;3025 Try switching section numbers for performance
INTSEC==:10


NETN==:1			;ARPA SYSTEM IF NONZERO
DCN==:0				;DECNET EXIST IF NONZERO
EXADF==:1			;EXTENDED DIRECTORY IF NONZERO
VTS==:1				;1000 VTS
CHAOS==:1			;CHAOS NET IF NONZERO
  NPKTBF==:^D3			;Cut back on buffer pages

;1001 These must match PROXX definitions...
MNET==:1			;1001 Multinet included
INETN==:1			;151 Internet included
TCPN==:1			;151 TCP INCLUDED
TCPVER==:4		;151 TCP protocol number

CHST2P==:^D15			;1000 Hope this fits! ;3015 Hope this fits too!

IEDDTF==:1			;Keep EDDT until 11-crashes are fixed

TM02F==:1			;3032 TM02/3 for TU77

;SYSTEM RESOURCE SIZES
NIQ==:20			;1000 Number Special Internet Queues
NJOBS==:^D75			;# JOBS ON SYSTEM
NFKS==:NJOBS*3+NJOBS/2		;266 Was 3*njobs
SSPT==:5000			;SIZE OF SPT
NDST==:^D<95*26*10>		;3032
SWDST==:NDST			;3032
MAXCOR==:^D2048*2		;UP TO 2 MEGS MEMORY!
NTTWK==:^D30			;NUM OF CHARS LEFT IN OUT BUF BEFORE WAKEUP
NTTBF==:200			;286 # TTY BUFFERS (was 200)

;SYSTEM DEVICES
NPTYS==:^D30			;# PTYS (FROM NLINES-NPTYS TO NLINES-1)
NTTPTY==:NPTYS			;240 define number everbody else uses, too
NTTNVT==:^D10			;3017 # ARPA NVTS
NTTCVT==:^d20			;3032 # CHAOS NVTS
NTTMLC==:0
IFN TCPN,<
	NTTTVT==:^D40			;3017 # TCP Virtual Terminals
>
IFE TCPN,<
	NTTTVT==:0			;1000 none of these yet
>
NMLCS==:0
NDHL==:^D80			;3055  # DH11 LINES
LPTN==:0			;# LINE PRINTERS
FELPTN==:0			;# FE LINE PRINTERS
MTAN==:2			;# MAG TAPE UNITS
DX20AF==:0			;3032 No DX20 support
DX20BF==:0			;3032

DX20F==:0			;# DX20 CONTROLLERS (TU70'S ETC)
DTEN==:2			;# DTES
CDRN==:0			;# CARD READERS
CDPN==:0			;# SPOOLED CARD PUNCHES
PCDPN==:0			;# PHYSICAL CARD PUNCHES
PLTN==:0			;# PLODDERS
SPLTN==:0			;1000 Spooled plotter (really the Dover)

;DIRECTORY DEFAULTS
.STDFP==:777752			;STANDARD FILE PROTECTION
.STDDP==:77777740		;32 STANDARD DIRECTORY PROTECTION
.STDBS==:0			;STANDARD GENERATION COUNT
.STDMX==:^D250			;32 STANDARD MAX DISK ALLOCATION
.STDSD==:0			;31 STANDARD SUBDIRECTORY QUOTA

GATEWF==:1B0			;We are a gateway

;;Multinet/Internet/TCP stuff

NDG	NIQ,^d16		;287 Number of Internet User Queues
NSKT==:^D160			;3032 Max number of sockets dfined at once
NNTBFS==:100000			;3032 Big net buffer space
MXSTRU==:^d6			;3032 Max units/structure

IFG TCPN,<
; TCP Configuration:
NDG MAXTCB,^D50			;3032 Max. simultaneous connection ends
NDG NTCPWP,4			; Number of monitor window pages
NDG TCBHSZ,4			; Size of TCB Hash table
NDG MAXJCN,20			; Each job allowed this many JCNs
NDG NTTTVT,20			; Number of TCP tty lines
NTWBTS==^D<MAXTCB*<8+2>+10>	; Appox. number of wait bits needed
IFG NTWBTS-^D511,<PRINTX % TOO MANY WAIT BITS
		NTWBTS==^D511	; Must fit in 9-bits for TCPOOT, TCPZOT,
				; and TOPNF and TERRF fields
>
NDG ABTCBS,^D35-^L<2*MAXJCN>	; Abort counter byte size
NDG NTACWD,<NFKS+<^D36/ABTCBS>>/ABTCBS	; Number of words for abort counters
>
IFE TCPN,<
NDG NTTTVT,0
NTWBTS==0
>
IFG INETN,<
NDG NFIXED,^D61			; Num fixed size blk lists (prime best)
NDG INTFSZ,20000		; Size of free area
NDG NTWBWD,<NTWBTS+1+35>/^D36	; Number of words of wait bits
>

ANXN=1
NFEN=1


;3032 Begin ISI addition

NJSBPG==:^D30			;number of JSB free pages



ANXN==:1			;#INET-01 1 AN10
BBNN==:0			;#INET-01 no IMP10's

;;; MLC support - turned off for ISI
MLCN==:0	;#471 was 2	; PTIP SUPPORT
NMLCS==:0	;#471 was ^D112	;# OF MLC LINES
NMLIOP==:0	;#471 was ^D26	;# OF MLC OPCODES
MLICTN==:0	;#471 was 20	;# OF MLC CTL MSGS TO RECORD IN MLICTB
MLOCTN==:0	;#471 was 20	;# OF MLC CTL MSGS TO RECORD IN MLOCTB
TNTN==:0			;TELENET SUPPORT
NTNTS==:0			;# OF TELENET LINES (AT LEAST 1!)
NTTMLC==:NMLCS			;# OF MLC TYPE LINES AVAILABLE
NTTTEL==:NTNTS			;# OF TELENET TYPE LINES AVAILABLE


QM1N==:0
BALPTN==:0
