
!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING TOPS-20 GALAXY V4.2
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:BATCON.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:BATCON.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:BATLOG.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:BATMAC.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:CDRIVE.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:CDRIVE.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:D60JSY.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:D60UNV.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GALAXY.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GALAXY.CMD  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GALCNF.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GALGEN.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GALGEN.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXCOM.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXFIL.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXINI.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXINT.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXIPC.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXKBD.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXLIB.CCL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXLIB.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXLNK.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXMAC.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXMEM.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXOTS.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXSCN.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:GLXTXT.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:LPTSPL.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:LPTSPL.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:MOUNTR.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:MOUNTR.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:MTRCFS.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:MTRMAC.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:MTRUSR.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:MTRDDB.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:NURD.MAC    TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:OPERAT.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:OPR.MAC     TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:OPRCMD.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:OPRERR.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:OPRLOG.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:OPRNET.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:OPRPAR.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:OPRQSR.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:ORION.MAC   TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:ORNMAC.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:PLEASE.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:PLEASE.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QMANGR.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QMANGR.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QSRADM.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QSRDSP.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QSRFSS.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QSRIPC.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QSRMAC.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QSRMDA.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QSRMEM.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QSRNET.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QSRQUE.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QSRSCH.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QSRT20.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QUASAR.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:QUASAR.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:SPRINT.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:SPRINT.MAC  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:SPROUT.CTL  TO-GAL-SRC:*.*.-1
COPY FROM-SOURCE:SPROUT.MAC  TO-GAL-SRC:*.*.-1

;System Utilities and Universals
COPY FROM-SUBSYS:GLXLIB.REL  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:GLXMAC.UNV  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:OPRPAR.REL  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:ORNMAC.UNV  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:QSRMAC.UNV  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:NCPTAB.REL  TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SUBSYS:BATCON.EXE  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:CDRIVE.EXE  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:GALGEN.EXE  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:GLXLIB.EXE  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:LPTSPL.EXE  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:MOUNTR.EXE  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:OPR.HLP     TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:OPR.EXE     TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:ORION.EXE   TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:PLEASE.HLP  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:PLEASE.EXE  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:QMANGR.EXE  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:QUASAR.EXE  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:SPRINT.EXE  TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:SPROUT.EXE  TO-SUBSYS:*.*.-1

;Documentation for product
COPY FROM-DOC:GALAXY.DOC  TO-DOC:*.*.-1
;COPY FROM-DOC:GALAXY.BWR  TO-DOC:*.*.-1
;COPY FROM-DOC:GALAXY.BWR  TO-SYSTEM:*.*.-1
COPY FROM-DOC:GLXLIB.MEM  TO-DOC:*.*.-1
