@DEF REL: DSK:
@DEF UNV: DSK:
@COMPILE QSRMAC.MAC
@COMPILE QUASAR.MAC
@COMPILE QSRADM.MAC
@COMPILE QSRDSP.MAC
@COMPILE QSRFSS.MAC
@COMPILE QSRIPC.MAC
@COMPILE QSRT20.MAC
@COMPILE QSRMEM.MAC
@COMPILE QSRQUE.MAC
@COMPILE QSRSCH.MAC
@COMPILE QSRNET.MAC
@COMPILE QSRMDA.MAC
@COMPILE QSRLPT.MAC
@LINK
*@QUASAR.CCL
