REDIT 1(103) COMPARE by user MKL, 31-Mar-89 13:11:33
File 1: SRC:<7.MONITOR>ENQ.MAC.1
File 2: SRC:<7.MONITOR.AP20>ENQ.MAC.1
***** CHANGE #1; PAGE 1, LINE 1; PAGE 1, LINE 1
 ---------------------------------
; Edit= 8965 to ENQ.MAC on 12-Sep-88 by BROOKS, for SPR #21912
;Add ENQ-DEQ capability to ENQC% .ENQCD function

***** CHANGE #2; PAGE 32, LINE 7; PAGE 32, LINE 7

;ENQC FUNCTION 3 - DUMP THE LOCKS AND QUEUES

	SWAPCD			;[7.1040]

ENQCD:	XCALL (XCDSEC,CHKWHL)	;[7.1040] MUST BE A WHEEL TO DO THIS FUNCTION
	 RETERR			;NOT PRIVILEGED!
 ---------------------------------

;ENQC FUNCTION 3 - DUMP THE LOCKS AND QUEUES

	SWAPCD			;[7.1040]

ENQCD:	XCALL (XCDSEC,CHKENP)	;[7.8965] REQUIRES WHEEL, OPR OR ENQ PRIV
	 RETERR			;NOT PRIVILEGED!

