REDIT 1(103) COMPARE by user MKL, 31-Mar-89 14:05:13
File 1: SRC:<7.MONITOR>MSTR.MAC.1
File 2: SRC:<7.MONITOR.AP20>MSTR.MAC.1
***** CHANGE #1; PAGE 1, LINE 1; PAGE 1, LINE 1
 ---------------------------------
; Edit= 8976 to MSTR.MAC on 4-Oct-88 by GSCOTT
;MSTR function .MSRNU/.MSRUS should return null string for structure name
;(.MSRSN) and alias name (.MSRSA) if structure is offline (usually because of
;U1.OFS).
; Edit= 8890 to MSTR.MAC on 12-Aug-88 by GSCOTT, for SPR #21932
;Attempt to increment mount count for job exclusive structure should return
;DEVX2 not STRX01. 
; Edit= 8861 to MSTR.MAC on 13-Jul-88 by GSCOTT, for SPR #21933
;Do only 1 TTMSG instead of 3 to each user who has a structure mounted when a
;dismount is forced. 

***** CHANGE #2; PAGE 6, LINE 39; PAGE 6, LINE 39
	CAIE Q2,.MSINI		;ARE WE INITIALIZING THIS STRUCTURE ?
	JRST MSTM30		;NO, GO CHECK THE HOME BLOCKS
	LOAD T1,MS%FCN,.MSIFL(P3) ;YES, GET PARTICULAR FUNCTION REQUESTED
	CAIE T1,.MSCRE		;CREATING NEW FILE SYSTEM ?
	CAIN T1,.MSWHB		; OR WRITING NEW HOME BLOCKS ?
	JRST [	CALL MAKHOM	;YES, GO CREATE A PAIR OF NEW HOME BLOCKS
		 JRST MNTR4 	;[7464] Failed, return error
		MOVEM T1,NEWMID	;Success, save new media ID of new home blocks
		JRST .+1 ]	;NOW CHECK THE NEW HOME BLOCKS
MSTM30:	CALL HOMCHK		;GO READ THE HOME BLOCKS, FIX UP IF NEEDED
 ---------------------------------
	CAIE Q2,.MSINI		;ARE WE INITIALIZING THIS STRUCTURE ?
	JRST MSTM30		;NO, GO CHECK THE HOME BLOCKS
	LOAD T1,MS%FCN,.MSIFL(P3) ;YES, GET PARTICULAR FUNCTION REQUESTED
	CAIE T1,.MSCRE		;CREATING NEW FILE SYSTEM ?
	CAIN T1,.MSWHB		; OR WRITING NEW HOME BLOCKS ?
	IFNSK.			;[8976] Yes, new file system or new home blocks
	  CALL MAKHOM		;Yes, go create a pair of new home blocks
	   JRST MNTR4		;[7464] Failed, return error
	  MOVEM T1,NEWMID	;Success, save new media ID of new home blocks
	ENDIF.			;[8976] Now check the new home blocks

MSTM30:	CALL HOMCHK		;GO READ THE HOME BLOCKS, FIX UP IF NEEDED

***** CHANGE #3; PAGE 24, LINE 7; PAGE 25, LINE 7

; LOCAL VARIABLE USAGE --
;
; MSTDMS - STRUCTURE NUMBER OF STRUCTURE BEING DISMOUNTED
; MSTDMB - ADDRESS OF SDB FOR STRUCTURE BEING DISMOUNTED
; MSTDMN - ASCIZ STRUCTURE NAME STRING FOR USE IN MESSAGES
; MSTDME - TEMPORARILY HOLDS ERROR CODE
; MSTDMU - STRUCTURE UNIQUE CODE

MSTDIS:	STKVAR <MSTDMS,MSTDMB,MSTDME,<MSTDMN,2>,MSTDMU>

 ---------------------------------

; LOCAL VARIABLE USAGE --
;
; MSTDMS - STRUCTURE NUMBER OF STRUCTURE BEING DISMOUNTED
; MSTDMB - ADDRESS OF SDB FOR STRUCTURE BEING DISMOUNTED
; MSTDME - TEMPORARILY HOLDS ERROR CODE
; MSTDMU - STRUCTURE UNIQUE CODE
; MSTDMT - Text to TTMSG to users who have structure mounted [8861]

MSTDIS:	STKVAR <MSTDMS,MSTDMB,MSTDME,MSTDMU,<MSTDMT,11>> ;[8861]


***** CHANGE #4; PAGE 24, LINE 35; PAGE 25, LINE 35
	CALL FNDSTD		;[7.1081](T1/T1) Is structure now mounted?
	 RETBAD (MSTX21)	;NO, RETURN "STRUCTURE NOT MOUNTED" ERROR CODE
	MOVEM T1,MSTDMS		;YES, SAVE STRUCTURE NUMBER
	CAIE T1,PSNUM		;[7.1112]Dismounting the boot structure?
	CAMN T1,LGSIDX		;[7.1112]Or the Login Structure
	IFNSK.			;[7.1112]If yes to either...
	  MOVX T1,MSTX24	;[7.1112]Return "Illegal to dismount system structure"
	  JRST MSDER1		;[7.1112]Unlock the structure and return error
	ENDIF.			;[7.1112]
	MOVE T2,T1		;use T2 instead of T1
	ADDI T2,DEVCH1+DVXST0	;compute address in DEVCH1
	MOVE T3,(T2)		;get device characterists
	TXNE T3,D1%INI		;device being initialized?
	 JRST [	MOVX T2,MSTX43	;yes, get "illegal to dismount while INITing"
		JRST MSDER1]	;go unlock the structure and return error
	MOVE T2,STRTAB(T1)	;GET ADDRESS OF SDB FOR THIS STRUCTURE
 ---------------------------------
	CALL FNDSTD		;[7.1081](T1/T1) Is structure now mounted?
	 RETBAD (MSTX21)	;NO, RETURN "STRUCTURE NOT MOUNTED" ERROR CODE
	MOVEM T1,MSTDMS		;YES, SAVE STRUCTURE NUMBER
	CAIE T1,PSNUM		;[7.1112]Dismounting the boot structure?
	CAMN T1,LGSIDX		;[7.1112]Or the Login Structure
	ERRJMP(MSTX24,MSDER1)	;[8861] Yes, "Illegal to dismount system str"
	MOVE T2,T1		;use T2 instead of T1
	ADDI T2,DEVCH1+DVXST0	;compute address in DEVCH1
	MOVE T3,(T2)		;get device characterists
	TXNE T3,D1%INI		;device being initialized?
	ERRJMP (MSTX43,MSDER1)	;[8861] Yes, "Ill to dismount while initing"
	MOVE T2,STRTAB(T1)	;GET ADDRESS OF SDB FOR THIS STRUCTURE

***** CHANGE #5; PAGE 24, LINE 52; PAGE 25, LINE 48
	MOVEM T2,MSTDMB		;SAVE ADDRESS OF SDB
	MOVE T1,MSTDMS		;GET STRUCTURE NUMBER
	CALL STRCNV		;GET UNIQUE CODE FOR THIS STRUCTURE
	 JFCL			;CANNOT FAIL WHILE STRUCTURE IS LOCKED
	MOVEM T1,MSTDMU		;STORE STRUCTURE UNIQUE CODE

; SAVE THE STRUCTURE NAME FOR LATER USE IN ADVISORY MESSAGE

	MOVE T2,T1		;GET STRUCTURE UNIQUE CODE
	HRLI T2,.DVDES+.DVDSK	;GET DEVICE TYPE
	HRROI T1,MSTDMN		;GET POINTER TO WHERE NAME WILL GO
	DEVST			;GET STRUCTURE NAME
	 JRST [	MOVX T1,MSTX21	;FAILED, GET "STRUCTURE NOT MOUNTED" ERROR
		JRST MSDER1 ]	;GO UNLOCK STRUCTURE AND RETURN
	MOVE T1,MSTDMU		;GET STRUCTURE UNIQUE CODE
	MOVEI T2,MSTDMN		;GET ADDRESS OF STRUCTURE NAME
	CALL FIXJOB		;GO FIX JSB'S OF ALL JOBS ON SYSTEM
	; ..
 ---------------------------------
	MOVEM T2,MSTDMB		;SAVE ADDRESS OF SDB
	MOVE T1,MSTDMS		;GET STRUCTURE NUMBER
	CALL STRCNV		;GET UNIQUE CODE FOR THIS STRUCTURE
	 JFCL			;CANNOT FAIL WHILE STRUCTURE IS LOCKED
	MOVEM T1,MSTDMU		;STORE STRUCTURE UNIQUE CODE
	; ..
	; ..

;[8861] Create advisory message to TTMSG to users

	MOVEI T1,MSTDMT		;[8861] Point to place to construct message
	HRLI T1,(POINT 7)	;[8861] Make a byte pointer to it
	MOVE T2,[POINT 7,[ASCIZ/[Structure /]] ;[8861] Point to initial string
	CALL MSTASC		;[8861] (T1,T2/T1) Copy that first
	MOVE T2,MSTDMS		;[8861] Load structure number
	CALL MSTOUT		;[8861] (T1,T2/T1) Append that to the string
	MOVE T2,[POINT 7,[ASCIZ/ has been dismounted]
/]]				;[8861] Finish up the message
	CALL MSTASC		;[8861] (T1,T2/T1) Copy that to finish up

;[8861] Call routine to purge structure from all jobs and notify users.

	MOVE T1,MSTDMU		;GET STRUCTURE UNIQUE CODE
	MOVEI T2,MSTDMT		;[8861] Point to notification message
	CALL FIXJOB		;(T1,T2/) Go fix JSBs of all jobs on system
	; ..

***** CHANGE #6; PAGE 25, LINE 29; PAGE 27, LINE 29
	HRLZ T1,MSTDMS		;SET UP FOR SCHEDULER TEST - STR NUMBER
	HRRI T1,STRTST		;GO OKSKED AND WAIT UNTIL THE LOCK BECOMES FREE
	MOVEI T2,^D200		;HOLD TIME
	HDISMS			;BYE BYE
	JRST MSTD00		;START OVER

 ---------------------------------
	HRLZ T1,MSTDMS		;SET UP FOR SCHEDULER TEST - STR NUMBER
	HRRI T1,STRTST		;GO OKSKED AND WAIT UNTIL THE LOCK BECOMES FREE
	MOVEI T2,^D200		;HOLD TIME
	HDISMS			;BYE BYE
	JRST MSTD00		;START OVER
	; ..
	; ..


***** CHANGE #7; PAGE 26, LINE 49; PAGE 29, LINE 49

;RETURN TO USER

	OKINT			;PERMIT INTERRUPTS AGAIN
	RETSKP			;RETURN TO USER

 ---------------------------------

;RETURN TO USER

	OKINT			;PERMIT INTERRUPTS AGAIN
	RETSKP			;RETURN TO USER


***** CHANGE #8; PAGE 27, LINE 8; PAGE 31, LINE 8
;	1.	ACCESS'ED THIS STRUCTURE
;	2.	MOUNTED THIS STRUCTURE
;	3.	CONNECTED TO A DIRECTORY ON THIS STRUCTURE
;
;ACCEPTS IN T1/	STRUCTURE UNIQUE CODE
;	    T2/	ADDRESS OF ASCIZ STRUCTURE NAME
;		CALL FIXJOB
 ---------------------------------
;	1.	ACCESS'ED THIS STRUCTURE
;	2.	MOUNTED THIS STRUCTURE
;	3.	CONNECTED TO A DIRECTORY ON THIS STRUCTURE
;
;ACCEPTS IN T1/	STRUCTURE UNIQUE CODE
;[8861]	    T2/	Address of ASCIZ "[Structure NAME dismounted]" message
;		CALL FIXJOB

***** CHANGE #9; PAGE 27, LINE 16; PAGE 31, LINE 16
;RETURNS: +1 ALWAYS, STR INFO PURGED AND REQUIRED MESSAGES ISSUED

FIXJOB:	STKVAR <FXJOBC,FXJOBN>
	SAVEP
	MOVEM T1,FXJOBC		;SAVE STRUCTURE UNIQUE CODE
	MOVEM T2,FXJOBN		;SAVE ADDRESS OF STRUCTURE NAME STRING
	MOVSI P1,-NJOBS		;SET UP TO LOOP OVER ALL JOBS IN SYSTEM
 ---------------------------------
;RETURNS: +1 ALWAYS, STR INFO PURGED AND REQUIRED MESSAGES ISSUED

FIXJOB:	STKVAR <FXJOBC,FXJOBN>
	SAVEP
	MOVEM T1,FXJOBC		;SAVE STRUCTURE UNIQUE CODE
	MOVEM T2,FXJOBN		;[8861] Save address of notification string
	MOVSI P1,-NJOBS		;SET UP TO LOOP OVER ALL JOBS IN SYSTEM

***** CHANGE #10; PAGE 27, LINE 34; PAGE 31, LINE 34
	LOCK JSSTLK(P2)		;LOCK THE STRUCTURE INFO BLOCKS IN JSB
	MOVE T1,FXJOBC		;GET STRUCTURE NUMBER
	MOVE T2,P2		;GET OFFSET TO JSB FOR OBJECT JOB
	CALL FNDSTM		;GO GET OFFSET TO BLOCK FOR THIS STRUCTURE
	 JRST FXJB40		;NOT USING THAT STR, GO CHECK CONNECTED DIR

 ---------------------------------
	LOCK JSSTLK(P2)		;LOCK THE STRUCTURE INFO BLOCKS IN JSB
	MOVE T1,FXJOBC		;GET STRUCTURE NUMBER
	MOVE T2,P2		;GET OFFSET TO JSB FOR OBJECT JOB
	CALL FNDSTM		;GO GET OFFSET TO BLOCK FOR THIS STRUCTURE
	 JRST FXJB40		;NOT USING THAT STR, GO CHECK CONNECTED DIR
	; ..
	; ..


***** CHANGE #11; PAGE 27, LINE 53; PAGE 32, LINE 20
	 JFCL			;SHOULD NOT FAIL
	CALL USTDIR		;UNLOCK THE DIRECTORY
FXJB20:	JE JSMCI,(T2),FXJB25	;WAS THIS STRUCTURE MOUNTED ?
	SETOM P3		;YES, MARK THAT A MESSAGE IS NEEDED
	SETZRO <JSMCI,JSXCL>,(T2) ;CLEAR STATUS FLAGS
	;..

 ---------------------------------
	 JFCL			;SHOULD NOT FAIL
	CALL USTDIR		;UNLOCK THE DIRECTORY
FXJB20:	JE JSMCI,(T2),FXJB25	;WAS THIS STRUCTURE MOUNTED ?
	SETOM P3		;YES, MARK THAT A MESSAGE IS NEEDED
	SETZRO <JSMCI,JSXCL>,(T2) ;CLEAR STATUS FLAGS


***** CHANGE #12; PAGE 28, LINE 15; PAGE 32, LINE 34

FXJB30:	MOVE T1,FXJOBC		;GET UNIQUE CODE
	MOVE T2,P2		;GET OFFSET TO MAPPED JSB
	CALL FRJSSO		;GO FREE STR BLOCK IN JSB IF NOW FREE
FXJB40:	UNLOCK JSSTLK(P2)	;UNLOCK STRUCTURE INFO BLOCK LOCK IN JSB

 ---------------------------------

FXJB30:	MOVE T1,FXJOBC		;GET UNIQUE CODE
	MOVE T2,P2		;GET OFFSET TO MAPPED JSB
	CALL FRJSSO		;GO FREE STR BLOCK IN JSB IF NOW FREE
FXJB40:	UNLOCK JSSTLK(P2)	;UNLOCK STRUCTURE INFO BLOCK LOCK IN JSB
	; ..
	; ..


***** CHANGE #13; PAGE 28, LINE 33; PAGE 33, LINE 19
	SKIPN P3		;IS A MESSAGE REQUIRED ?
	JRST FXJB60		;NO, GO CHECK NEXT JOB
	HLRE T1,JOBPT(P1)	;YES, GET CONTROLLING LINE #
	JUMPL T1,FXJB60		;DETACHED, SKIP MESSAGE
	TXO T1,.TTDES		;FORM DEVICE DESIGNATOR
	HRROI T2,[ASCIZ/[Structure /]
	TTMSG%			;[7190] OUTPUT FIRST PART OF MESSAGE
	 ERJMP .+1		;[7190] 
	HRRO T2,FXJOBN		;[7190] GET POINTER TO ASCIZ STRUCTURE NAME
	TTMSG%			;[7190] OUTPUT STRUCTURE NAME
	 ERJMP .+1		;[7190] 
	HRROI T2,[ASCIZ/ has been dismounted]
/]				;[7190] GET REMAINDER OF MESSAGE
	TTMSG%			;[7190] OUTPUT FINAL PART OF MESSAGE
	 ERJMP .+1		;[7190] 

 ---------------------------------
	SKIPN P3		;IS A MESSAGE REQUIRED ?
	JRST FXJB60		;NO, GO CHECK NEXT JOB
	HLRE T1,JOBPT(P1)	;YES, GET CONTROLLING LINE #
	JUMPL T1,FXJB60		;DETACHED, SKIP MESSAGE
	TXO T1,.TTDES		;FORM DEVICE DESIGNATOR
	HRRO T2,FXJOBN		;[8861] Get pointer to ASCIZ message
	TTMSG%			;[8861] Output structure name
	 ERJMP .+1		;[8861] Ignore error for now


***** CHANGE #14; PAGE 30, LINE 23; PAGE 35, LINE 23
; ACCUMULATOR USAGE --
;
; P1/ ADDRESS OF ARGUMENT BLOCK IN USER SPACE
; P2/ ADDRESS OF ARGUMENT BLOCK IN MONITOR SPACE
; P3/ STATUS TO BE RETURNED

; VERIFY THAT THE USER HAS THE REQUIRED CAPABILITIES ENABLED

	MOVE T1,CAPENB		;GET ENABLED CAPABILITIES
	TXNN T1,SC%WHL!SC%OPR!SC%MNT	;IS USER CURRENTLY A WHEEL, OR OPERATOR OR MAINT?
	RETBAD (CAPX2)		;NO, RETURN ERROR CODE

; CHECK SIZE OF ARGUMENT BLOCK

	XCTU [ HLRZ T1,1 ]	;GET SIZE OF BLOCK FROM USER
	SKIPG T1		;AT LEAST ONE ITEM REQUESTED ?
	RETBAD (MSTRX3)		;NO, RETURN "ARG BLOCK TOO SMALL" ERROR

 ---------------------------------
; ACCUMULATOR USAGE --
;
; P1/ ADDRESS OF ARGUMENT BLOCK IN USER SPACE
; P2/ ADDRESS OF ARGUMENT BLOCK IN MONITOR SPACE
; P3/ STATUS TO BE RETURNED
; P4/ Size of user's argument block [8976]

; VERIFY THAT THE USER HAS THE REQUIRED CAPABILITIES ENABLED

	MOVE T1,CAPENB		;GET ENABLED CAPABILITIES
	TXNN T1,SC%WHL!SC%OPR!SC%MNT ;Is user a WHEEL or OPERATOR or MAINT?
	RETBAD (CAPX2)		;NO, RETURN ERROR CODE

; CHECK SIZE OF ARGUMENT BLOCK

	XCTU [ HLRZ P4,1 ]	;[8976] Get size of block from user
	SKIPG P4		;[8976] At least one word specified?
	RETBAD (MSTRX3)		;[8976] No, return "arg block too small" error
	UMOVE P1,2		;[8976] Get adr of argument block in user space
	MOVEI P2,MSTRSB		;[8976] Get addr of arg block in monitor space

	;..
	;..


***** CHANGE #15; PAGE 30, LINE 45; PAGE 36, LINE 11
	MOVEI T1,1(T2)		;GET DESTINATION ADDRESS
	HRLI T1,(T2)		;GET SOURCE ADDRESS
	SETZM MSTRSB		;CLEAR FIRST WORD OF BLOCK
	BLT T1,.MSRLN-1(T2)	;INITIALIZE ARGUMENT BLOCK

; SET UP CHANNEL, CONTROLLER, AND UNIT NUMBERS IN ARG BLOCK TO BE RETURNED

	UMOVE P1,2		;GET ADDRESS OF ARGUMENT BLOCK IN USER SPACE
	MOVEI P2,MSTRSB		;GET ADDRESS OF ARGUMENT BLOCK IN MONITOR SPACE
	UMOVE T1,.MSRCH(P1)	;GET CHANNEL NUMBER FROM USER
 ---------------------------------
	MOVEI T1,1(T2)		;GET DESTINATION ADDRESS
	HRLI T1,(T2)		;GET SOURCE ADDRESS
	SETZM MSTRSB		;CLEAR FIRST WORD OF BLOCK
	BLT T1,.MSRLN-1(T2)	;INITIALIZE ARGUMENT BLOCK

;[8976] Initialize returned structure name and alias name to null strings.

	MOVEI T1,.MSRSN(P1)	;[8976] Get addr in user space of ptr dest
	MOVEI T2,BHC		;[8976] Get address of null string
	CAIL P4,.MSRSN+1	;[8976] Is he block big enough?
	CALL STOSTR		;[8976] (T1,T2/T1) Store null string

	MOVEI T1,.MSRSA(P1)	;[8976] Get addr in user space of ptr dest
	MOVEI T2,BHC		;[8976] Get address of null string
	CAIL P4,.MSRSA+1	;[8976] Is he block big enough?
	CALL STOSTR		;[8976] (T1,T2/T1) Store null string

; SET UP CHANNEL, CONTROLLER, AND UNIT NUMBERS IN ARG BLOCK TO BE RETURNED

	UMOVE T1,.MSRCH(P1)	;GET CHANNEL NUMBER FROM USER

***** CHANGE #16; PAGE 33, LINE 10; PAGE 39, LINE 10
	MOVE T2,MSTRSA		;GET VIRTUAL ADDRESS OF FIRST HOME BLOCK
	TXNN T1,HB%1OK		;IS THE FIRST HOME BLOCK OK ?
	ADDI T2,HBLEN		;NO, USE THE SECOND HOME BLOCK
	MOVS T3,HOMLUN(T2)	;GET UNIT INFO FROM HOME BLOCK
	MOVEM T3,.MSRNS(P2)	;SAVE UNIT INFO IN ARG BLOCK TO BE RETURNED
	XCTU [HLRZ T1,1]	; GET ARG BLK LENGTH
	CAIGE T1,.MSRSN+1	; DOES ARG BLK HAVE .MSRSN WORD?
	  JRST MSTRS7		; NO! SKIP STR NAME STRING XFER
	MOVE T1,HOMSNM(T2)	;GET STRUCTURE NAME FROM HOME BLOCK
 ---------------------------------
	MOVE T2,MSTRSA		;GET VIRTUAL ADDRESS OF FIRST HOME BLOCK
	TXNN T1,HB%1OK		;IS THE FIRST HOME BLOCK OK ?
	ADDI T2,HBLEN		;NO, USE THE SECOND HOME BLOCK
	MOVS T3,HOMLUN(T2)	;GET UNIT INFO FROM HOME BLOCK
	MOVEM T3,.MSRNS(P2)	;SAVE UNIT INFO IN ARG BLOCK TO BE RETURNED
	CAIGE P4,.MSRSN+1	;[8976] Does arg blk have .MSRSN word?
	JRST MSTRS7		;NO! SKIP STR NAME STRING XFER
	MOVE T1,HOMSNM(T2)	;GET STRUCTURE NAME FROM HOME BLOCK

***** CHANGE #17; PAGE 34, LINE 14; PAGE 40, LINE 14
	LOAD T1,STRNSS,(T2)	;GET NUMBER OF SECTORS FOR SWAPPING
	LSH T1,-2		;CONVERT TO PAGES
	LOAD T3,STRNUM,(T2)	;GET NUMBER OF UNITS IN STRUCTURE
	IMUL T1,T3		;NUMBER OF SWAPPING PAGES ON STRUCTURE
	MOVEM T1,.MSRSW(P2)	;SAVE NUMBER OF SWAPPING SECTORS
	XCTU [HLRZ T1,1]	; GET ARG BLK SIZE
	CAIGE T1,.MSRSA+1	; DOES IT HAVE .MSRSA WORD
	  JRST MSTRS6		; NO- SKIP ALIAS STRING XFER
	HRRZ T1,MSTRSS		;GET STRUCTURE NUMBER
 ---------------------------------
	LOAD T1,STRNSS,(T2)	;GET NUMBER OF SECTORS FOR SWAPPING
	LSH T1,-2		;CONVERT TO PAGES
	LOAD T3,STRNUM,(T2)	;GET NUMBER OF UNITS IN STRUCTURE
	IMUL T1,T3		;NUMBER OF SWAPPING PAGES ON STRUCTURE
	MOVEM T1,.MSRSW(P2)	;SAVE NUMBER OF SWAPPING SECTORS
	CAIGE P4,.MSRSA+1	;[8976] Does arg block have .MSRSA word?
	JRST MSTRS6		;No, skip alias string copy
	HRRZ T1,MSTRSS		;GET STRUCTURE NUMBER

***** CHANGE #18; PAGE 34, LINE 32; PAGE 40, LINE 31
; RETURN ARGUMENTS TO THE USER ARGUMENT BLOCK

MSTRS6:	IORM P3,.MSRST(P2)	;STORE STATUS IN ARGUMENT BLOCK
	MOVE T3,P1		;COPY ADDRESS OF USER ARGUMENT BLOCK
	MOVE T2,P2		;GET SOURCE
	XCTU [ HLRZ T1,1 ]	;GET SIZE OF USER ARGUMENT BLOCK
	CAILE T1,.MSRLN		;BIGGER THAN MAX ALLOWED ?
 ---------------------------------
; RETURN ARGUMENTS TO THE USER ARGUMENT BLOCK

MSTRS6:	IORM P3,.MSRST(P2)	;STORE STATUS IN ARGUMENT BLOCK
	MOVE T3,P1		;COPY ADDRESS OF USER ARGUMENT BLOCK
	MOVE T2,P2		;GET SOURCE
	MOVE T1,P4		;[8976] Get size of user argument block
	CAILE T1,.MSRLN		;BIGGER THAN MAX ALLOWED ?

***** CHANGE #19; PAGE 38, LINE 19; PAGE 44, LINE 19


MSTIMC:	TDZA T1,T1		;MARK THAT COUNT SHOULD BE INCREMENTED
MSTDMC:	SETOM T1		;MARK THAT COUNT SHOULD BE DECREMENTED
	ASUBR <MSTMCF>

 ---------------------------------


MSTIMC:	TDZA T1,T1		;MARK THAT COUNT SHOULD BE INCREMENTED
MSTDMC:	SETOM T1		;MARK THAT COUNT SHOULD BE DECREMENTED
	ASUBR <MSTMCF>
	STKVAR <<MSTDMT,11>>	;[8861] Place to construct notification string


***** CHANGE #20; PAGE 39, LINE 28; PAGE 45, LINE 28
	MOVE T1,P2		;GET THE STRUCTURE NUMBER
	CALL ULKSTR		;UNLOCK THE STRUCTURE
	SKIPN P5		;WAS THIS WORK FOR SOMEONE ELSE
	RETSKP			;NO, RETURN
	CALL CLRJSB		;UNMAP THE OBJECT JSB
	HLRE T1,JOBPT(P4)	;GET TTY OF OBJECT JOB
	SKIPGE T1		;IS IT DETACHED?
	RETSKP			;YES, FORGET MESSAGE

;SEND MESSAGE OF STRUCTURE MOUNT TO TTY, IF DONE TO ANOTHER JOB

	TXO T1,.TTDES		;[7190] MAKE LINE NUMBER INTO DESIGNATOR
	HRROI T2,[ASCIZ /
[/]				;[7190] 
	TTMSG%			;[7190] 
	 ERJMP .+1		;[7190] 
	MOVE T2,P2		;GET STRUCTURE NUMBER
	CALL MSTOUT		;OUTPUT STRUCTURE NAME
	HRROI T2,[ASCIZ / Mounted]
/]
	SKIPE MSTMCF		;IF STRUCTURE IS BEING DISMOUNTED,
	HRROI T2,[ASCIZ / Dismounted]
/]				; SAY SO
	TTMSG%			;[7190] 
	 ERJMP .+1		;[7190] 
 ---------------------------------
	MOVE T1,P2		;GET THE STRUCTURE NUMBER
	CALL ULKSTR		;UNLOCK THE STRUCTURE
	SKIPN P5		;WAS THIS WORK FOR SOMEONE ELSE
	RETSKP			;NO, RETURN
	CALL CLRJSB		;UNMAP THE OBJECT JSB

;[8861] Construct notification message to send to user whose work was done.

	MOVEI T1,MSTDMT		;[8861] Point to place on stack to construct 
	HRLI T1,(POINT 7)	;[8861]  the message we send to user
	MOVE T2,[POINT 7,[ASCIZ/
[/]]				;[8861] Start message with CRLF and bracket
	CALL MSTASC		;[8861] (T1,T2/T1) Call quick string copy rtn
	MOVE T2,P2		;[8861] Get structure number
	CALL MSTOUT		;[8861] (T1,T1/T1) Insert structure name 
	SKIPE MSTMCF		;[8861] Structure being mounted or dismounted?
	SKIPA T2,[POINT 7,[ASCIZ / Dismounted]
/]]				;[8861] It was just dismounted
	MOVE T2,[POINT 7,[ASCIZ / Mounted]
/]]				;[8861] It was just mounted
	CALL MSTASC		;[8861] (T1,T2/T1) Finish up the string

;[8861] Send notification message to user for which this function was done.

	HLRE T1,JOBPT(P4)	;GET TTY OF OBJECT JOB
	JUMPL T1,RSKP		;[8861] Skip return if it was detached
	TXO T1,.TTDES		;[7190] MAKE LINE NUMBER INTO DESIGNATOR
	HRROI T2,MSTDMT		;[8861] Point to the text string we just built
	TTMSG%			;[8861] Send that to the user's terminal
	 ERJMP .+1		;[7190] 

***** CHANGE #21; PAGE 39, LINE 61; PAGE 46, LINE 38
MCTERR:	EXCH P2,T1		;SAVE ERROR CODE, GET STRUCTURE NUMBER
	CALL ULKSTR		;UNLOCK THE STRUCTURE
	SKIPE P5		;WAS THIS WORK FOR SOMEONE ELSE?
	CALL CLRJSB		;YES, CLEAR MAPPED JSB
	MOVE T1,P2		;RESTORE THE ERROR CODE
	RETBAD ()			;RETURN ERROR TO USER
 ---------------------------------
MCTERR:	EXCH P2,T1		;SAVE ERROR CODE, GET STRUCTURE NUMBER
	CALL ULKSTR		;UNLOCK THE STRUCTURE
	SKIPE P5		;WAS THIS WORK FOR SOMEONE ELSE?
	CALL CLRJSB		;YES, CLEAR MAPPED JSB
	MOVE T1,P2		;RESTORE THE ERROR CODE
	RETBAD ()		;RETURN ERROR TO USER
	ENDSV.			;[8861] End of STKVAR

***** CHANGE #22; PAGE 56, LINE 40; PAGE 63, LINE 40
	JRST [	MOVX T1,ARGX18	;NO, GET ERROR CODE
		MOVEM T1,FSTERR	;SAVE ERROR CODE
		JRST FNDST2 ]	;GO RELEASE SPACE AND RETURN ERROR CODE
	MOVE T1,FSTSTR		;COPY DEVICE DESIGNATOR FOR CHKDEV
	CALL CHKDEV		;GO CHECK DEVICE DESIGNATOR
	 JRST [	MOVX T1,STRX01	;GET ERROR CODE
		MOVEM T1,FSTERR	;SAVE ERROR CODE
 ---------------------------------
	JRST [	MOVX T1,ARGX18	;NO, GET ERROR CODE
		MOVEM T1,FSTERR	;SAVE ERROR CODE
		JRST FNDST2 ]	;GO RELEASE SPACE AND RETURN ERROR CODE
	MOVE T1,FSTSTR		;COPY DEVICE DESIGNATOR FOR CHKDEV
	CALL CHKDEV		;GO CHECK DEVICE DESIGNATOR
	 JRST [	CAIE T1,DEVX2	;[8890] Device already assigned to another job?
		MOVX T1,STRX01	;[8890] No, get "Structure is not mounted"
		MOVEM T1,FSTERR	;SAVE ERROR CODE

***** CHANGE #23; PAGE 57, LINE 52; PAGE 64, LINE 52
	SUB T4,T2		;COMPUTE SHIFT REQUIRED
	LSH T1,(T4)		;POSITION BIT FOR THIS CHARACTER CLASS
	TXNN T1,CHRMSK		;IS THIS A VALID CHARACTER ?
	RETBAD ()		;NO, RETURN ILLEGAL CHARACTER
	RETSKP			;YES, RETURN SUCCESS

 ---------------------------------
	SUB T4,T2		;COMPUTE SHIFT REQUIRED
	LSH T1,(T4)		;POSITION BIT FOR THIS CHARACTER CLASS
	TXNN T1,CHRMSK		;IS THIS A VALID CHARACTER ?
	RETBAD ()		;NO, RETURN ILLEGAL CHARACTER
	RETSKP			;YES, RETURN SUCCESS

***** CHANGE #24; PAGE 59, LINE 9; PAGE 66, LINE 9
;ACCEPTS: T1/ BYTE POINTER TO 7-BIT ASCII AREA
;	  T2/ STRUCTURE NUMBER
;		CALL MSTOUT
;RETURNS: +1  ALWAYS, T1 UPDATED

MSTOUT: SAVEQ
	MOVE T2,STRTAB(T2)	;GET STRUCTURE BLOCK ADDRESS
	MOVEI T2,SDBNAM(T2)	;GET ADDRESS OF STRUCTURE NAME
	HRLI T2,440600		;SET UP 6-BIT POINTER
	MOVE T3,[440700,,Q1]	;SET UP BYTE PTR TO Q REGISTERS
	MOVEI T4,6		;THERE IS A MAXIMUM OF 6 BYTES
	SETZB Q1,Q2		;ZERO THE STRING AREA
MSTOU1:	ILDB Q3,T2		;GET 6-BIT CHARACTER
	JUMPE Q3,MSTOU2		;GET OUT OF LOOP IF ZERO BYTE
	ADDI Q3,40		;CONVERT IT TO 7-BIT
	IDPB Q3,T3		;PUT IT IN TEMPORARY LOCATION
	SOJG T4,MSTOU1		;LOOP IF MORE CHARACTERS
MSTOU2:	HRROI T2,Q1		;GET POINTER TO TEMP LOC
	TTMSG%			;[7190] OUTPUT IT
	 ERJMP .+1		;[7190]
	RET

 ---------------------------------
;ACCEPTS: T1/ BYTE POINTER TO 7-BIT ASCII AREA
;	  T2/ STRUCTURE NUMBER
;		CALL MSTOUT
;RETURNS: +1  ALWAYS, T1 UPDATED

MSTOUT:	MOVE T2,STRTAB(T2)	;GET STRUCTURE BLOCK ADDRESS
	MOVEI T2,SDBNAM(T2)	;GET ADDRESS OF STRUCTURE NAME
	HRLI T2,(POINT 6)	;[8861] Set up 6-bit pointer
	MOVEI T4,6		;THERE IS A MAXIMUM OF 6 BYTES
MSTOU1:	ILDB T3,T2		;[8861] Get 6-bit character
	JUMPE T3,MSTOU2		;[8861] Get out of loop if zero (space) byte
	ADDI T3,"A"-'A'		;[8861] Convert it to printable 7-bit byte
	IDPB T3,T1		;[8861] Store that in the destination string
	SOJG T4,MSTOU1		;LOOP IF MORE CHARACTERS
MSTOU2:	RET			;[8861] Return now if done

;[8861] Routine to quickly append one ASCIZ string to another.
;
;Accepts: T1/ destination byte pointer
;	  T2/ source byte pointer
;Returns +1 always, T1/ updated byte pointer, null at pointer for ASCIZ string

MSTASC:	ILDB T3,T2		;Load a character
	IDPB T3,T1		;Store one character
	JUMPN T3,MSTASC		;Loop for all characters
	MOVNI T3,1		;Load a -1
	ADJBP T3,T1		;Backup over the null
	MOVEM T3,T1		; and store the pointer back
	RET			;Return

