REDIT 1(103) COMPARE by user MKL, 31-Mar-89 14:50:55
File 1: SRC:<7.MONITOR>PROLOG.MAC.1
File 2: SRC:<7.MONITOR.AP20>PROLOG.MAC.1
***** CHANGE #1; PAGE 1, LINE 1; PAGE 1, LINE 1
 ---------------------------------
; Edit= 8971 to PROLOG.MAC on 22-Sep-88 by RASPUZZI
;Move FTHIST out of NISRV and put it in PROLOG where it should be.

***** CHANGE #2; PAGE 3, LINE 38; PAGE 3, LINE 38
FTPARANOID==:0			;DECNET-36 - DO EXTRA CAREFUL CHECKING
FTCORBUG==:0			;DECNET-36 - FTPARANOID FOR CORE MANAGER
FTLSTCOR==:0			;DECNET-36 - TRY TO TRACE LOST CORE
FTHMMEM==:0			;DECNET-36 - Memory request map
FTRTST==:0			;DECNET-36 - Router message looper
>				; END OF IFE DEBUG
 ---------------------------------
FTPARANOID==:0			;DECNET-36 - DO EXTRA CAREFUL CHECKING
FTCORBUG==:0			;DECNET-36 - FTPARANOID FOR CORE MANAGER
FTLSTCOR==:0			;DECNET-36 - TRY TO TRACE LOST CORE
FTHMMEM==:0			;DECNET-36 - Memory request map
FTRTST==:0			;DECNET-36 - Router message looper
NDG FTHIST,0			;[8971] - PHYKNI's history buffer
>				; END OF IFE DEBUG

***** CHANGE #3; PAGE 4, LINE 34; PAGE 4, LINE 34
NDG FTPARANOID,1		;DECNET-36 - DO EXTRA CAREFUL CHECKING
NDG FTCORBUG,0			;DECNET-36 - FTPARANOID FOR CORE MANAGER
NDG FTLSTCOR,1			;DECNET-36 - TRY TO TRACE LOST CORE
NDG FTHMMEM,1			;DECNET-36 - Memory request map
NDG FTRTST,1			;DECNET-36 - Router message looper
>
 ---------------------------------
NDG FTPARANOID,1		;DECNET-36 - DO EXTRA CAREFUL CHECKING
NDG FTCORBUG,0			;DECNET-36 - FTPARANOID FOR CORE MANAGER
NDG FTLSTCOR,1			;DECNET-36 - TRY TO TRACE LOST CORE
NDG FTHMMEM,1			;DECNET-36 - Memory request map
NDG FTRTST,1			;DECNET-36 - Router message looper
NDG FTHIST,0			;[8971] PHYKNI's history buffer (off)
>

