REDIT 1(103) COMPARE by user MKL, 31-Mar-89 15:48:17
File 1: SRC:<7.MONITOR>TTYDEF.MAC.1
File 2: SRC:<7.MONITOR.AP20>TTYDEF.MAC.1
***** CHANGE #1; PAGE 1, LINE 1; PAGE 1, LINE 1
 ---------------------------------
; Edit= 8977 to TTYDEF.MAC on 4-Oct-88 by JROSSELL, for SPR #21689
;Add support for optionally not flushing NULs when a terminal is in ASCII
;mode. 

***** CHANGE #2; PAGE 4, LINE 35; PAGE 4, LINE 35
				;(CTERM CLEARS NORMAL ECHO BIT - TT%ECO)
TT%WKC==1B21			;WAKE-UP SET HAS CHANGED
TT%SPG==1B22			;PAGE STOP IS TURNED ON IN THE SERVER
				;(CTERM CLEARS NORMAL PAGE STOP BIT - TT%PGM)
TT%BIN==1B23			;(CTHSRV) CURRENT DATA MODE IS BINARY (0=ASCII)
TT%LCK==77B35			;(30-35) COUNT OF LOCKS ON THIS BLOCK
 ---------------------------------
				;(CTERM CLEARS NORMAL ECHO BIT - TT%ECO)
TT%WKC==1B21			;WAKE-UP SET HAS CHANGED
TT%SPG==1B22			;PAGE STOP IS TURNED ON IN THE SERVER
				;(CTERM CLEARS NORMAL PAGE STOP BIT - TT%PGM)
TT%BIN==1B23			;(CTHSRV) CURRENT DATA MODE IS BINARY (0=ASCII)
TT%NUL==1B24			;[8977]ASCII mode NUL passthrough 
TT%LCK==77B35			;(30-35) COUNT OF LOCKS ON THIS BLOCK

***** CHANGE #3; PAGE 4, LINE 64; PAGE 4, LINE 65
MSKSTR TTXFF,TTFLG1,TT%XFF	;FORCE XOFF/XON STATUS TO FRONT-END
MSKSTR TTSEC,TTFLG1,TT%SEC
MSKSTR TTWKC,TTFLG1,TT%WKC
MSKSTR TTSPG,TTFLG1,TT%SPG
MSKSTR TTBIN,TTFLG1,TT%BIN
MSKSTR TTLCK,TTFLG1,TT%LCK
 ---------------------------------
MSKSTR TTXFF,TTFLG1,TT%XFF	;FORCE XOFF/XON STATUS TO FRONT-END
MSKSTR TTSEC,TTFLG1,TT%SEC
MSKSTR TTWKC,TTFLG1,TT%WKC
MSKSTR TTSPG,TTFLG1,TT%SPG
MSKSTR TTBIN,TTFLG1,TT%BIN
MSKSTR TTNUL,TTFLG1,TT%NUL	;[8977]ASCII NUL passthrough flag
MSKSTR TTLCK,TTFLG1,TT%LCK

