COMPILE EXEC:MICPRM.MAC R:MICPRM	;MIC symbols

					;Universal symbols
COMPILE EXEC:SUDEF.MAC + EXEC:EXECDE.MAC + EXEC:EXECGL.MAC R:EXECGL

					;Global storage, *NOT* for individual
					;local command storage; use TRVAR and
COMPILE EXEC:EXECPR.MAC R:EXECPR	;STKVAR for that.

					;Version information
COMPILE EXEC:SUDEF.MAC + EXEC:EXECVR.MAC R:EXECVR

COMPILE EXEC:EXEC0.MAC	R:EXEC0		;Top-level command input, SYSTAT
COMPILE EXEC:EXECCA.MAC	R:EXECCA	;Configuration varients
COMPILE EXEC:EXEC1.MAC	R:EXEC1		;Miscellaneous commands
COMPILE EXEC:EXECSE.MAC R:EXECSE	;SET commands and ^ESET commands
COMPILE EXEC:EXECMT.MAC R:EXECMT	;Tape and disk mounting
COMPILE EXEC:EXECP.MAC	R:EXECP		;Program commands (like RUN, DDT, CON)
COMPILE EXEC:EXECIN.MAC	R:EXECIN	;INFORMATION commands
COMPILE EXEC:EXEC2.MAC	R:EXEC2		;COPY, APPEND, TYPE
COMPILE EXEC:EXEC3.MAC	R:EXEC3		;DIRECTORY-class commands
COMPILE EXEC:EXEC4.MAC	R:EXEC4		;BUILD, ^ECREATE, INFO DIRECTORY
COMPILE EXEC:EXECED.MAC	R:EXECED	;EDIT, CREATE commands
COMPILE EXEC:EXECCS.MAC	R:EXECCS	;COMPIL-class commands
COMPILE EXEC:EXECHS.MAC R:EXECHS	;HISTORY stuff
COMPILE EXEC:EXECTT.MAC R:EXECTT	;TTY stuff for command editor
COMPILE EXEC:EXECQU.MAC	R:EXECQU	;QUEUE-class commands
COMPILE EXEC:EXECSU.MAC	R:EXECSU	;Subroutines
COMPILE EXEC:EXECMI.MAC	R:EXECMI	;MIC-class commands
COMPILE EXEC:EXECNC.MAC R:EXECNC	;NIC stuff
COMPILE EXEC:EXECPM.MAC R:EXECPM	;PCL
COMPILE EXEC:EXECPS.MAC R:EXECPS
COMPILE EXEC:EXECPI.B36 R:EXECPI
COMPILE EXEC:EXECPC.B36 R:EXECPC
COMPILE EXEC:EXECPX.B36 R:EXECPX
COMPILE EXEC:EXECPU.B36 R:EXECPU
