@ENABLE
@DEFINE EXEC: SRC:<6-1-EXEC>
@DEFINE MON: SRC:<6-1-MONITOR>
@DEFINE G: SRC:<5-GALAXY>
@DEFINE R: EXEC:
@DEFINE SYS: MON:, G:, SYS:
@DEFINE REL: SYS:
@CONNECT EXEC:
@TAKE ASEXEC.CMD
@LINK
*@ASEXEC.CCL
@GET EXEC
@START
*Y
@
