18-Jan-90 17:21:20-PST,1207;000000000001
Received: from uunet.UU.NET by NIC.DDN.MIL with TCP; Thu, 18 Jan 90 17:03:17 PST
Received: from plumhall.UUCP by uunet.UU.NET (5.61/1.14) with UUCP 
	id AA04919; Thu, 18 Jan 90 20:03:13 -0500
Date: Wed, 17 Jan 90 17:32:08 EST
From: plum%plumhall@uunet.UU.NET (Thomas Plum)
Subject: No appeals; FINAL!
Message-Id: <9001171732.0.UUL1.3#20135@plumhall.uu.net>
To: X3J11@NIC.DDN.MIL


By telephone conversation with Louise Germani,
at ANSI Board of Standards Review, I have confirmed the news given to me
yesterday by Jean Paul Emard at X3:
The time allowed for receipt of appeals to ANSI has expired.
No appeals have been received.
The approval by ANSI BSR is official.
The C Standard will be known as ANS X3.159-1989, because the approval
meeting was 14 December 1989.

I convey this news to you with great, and mixed, emotions.
Let me just express, on behalf of everyone, to everyone,
thanks for everything that was done to bring about this long-delayed result.

PS: My apologies if you had trouble reaching plumhall.uu.net last week;
we had a series of hardware problems.  Access should now be reliable.

Thomas Plum, Vice-Chair X3J11
plum@plumhall.uu.net   (USA) 609-927-3770

19-Jan-90 03:49:13-PST,1773;000000000005
Return-Path: <plumhall!plum@uunet.UU.NET>
Received: from uunet.UU.NET by NIC.DDN.MIL with TCP; Fri, 19 Jan 90 03:48:17 PST
Received: from plumhall.UUCP by uunet.UU.NET (5.61/1.14) with UUCP 
	id AA06059; Fri, 19 Jan 90 06:48:08 -0500
Date: Thu, 18 Jan 90 20:49:08 EST
From: plum%plumhall@uunet.UU.NET (Thomas Plum)
Subject: Address changes
Message-Id: <9001182049.0.UUL1.3#20135@plumhall.uu.net>
To: klh@NIC.DDN.MIL


Ken - Please add the following people to the x3j11 list:

uunet!wood@dg-rtp.dg.com	Tom Wood, Data General

Please make the following changes (some may duplicate previous messages):

andyj@osf.org               Andy Johnson, OSF (was Prime)
meissner@osf.org            Mike Meissner, OSF (was Data General)

linda@ocfmail.ocf.llnl.gov  Linda Stanberry, Lawrence Livermore

I am simultaneously sending the following happy message to the X3J11 list:
--------------------

No appeals; FINAL!

By telephone conversation with Louise Germani,
at ANSI Board of Standards Review, I have confirmed the news given to me
yesterday by Jean Paul Emard at X3:
The time allowed for receipt of appeals to ANSI has expired.
No appeals have been received.
The approval by ANSI BSR is official.
The C Standard will be known as ANS X3.159-1989, because the approval
meeting was 14 December 1989.

I convey this news to you with great, and mixed, emotions.
Let me just express, on behalf of everyone, to everyone,
thanks for everything that was done to bring about this long-delayed result.

PS: My apologies if you had trouble reaching plumhall.uu.net last week;
we had a series of hardware problems.  Access should now be reliable.

--------------------

Thomas Plum, Plum Hall Inc, plum@plumhall.uu.net , (USA) 609-927-3770


19-Jan-90 03:50:39-PST,1773;000000000015
Return-Path: <plumhall!plum@uunet.UU.NET>
Received: from uunet.UU.NET by NIC.DDN.MIL with TCP; Fri, 19 Jan 90 03:48:28 PST
Received: from plumhall.UUCP by uunet.UU.NET (5.61/1.14) with UUCP 
	id AA06093; Fri, 19 Jan 90 06:48:21 -0500
Date: Thu, 18 Jan 90 20:55:57 EST
From: plum%plumhall@uunet.UU.NET (Thomas Plum)
Subject: Address changes
Message-Id: <9001182055.0.UUL1.3#20135@plumhall.uu.net>
To: klh@NIC.DDN.MIL


Ken - Please add the following people to the x3j11 list:

uunet!wood@dg-rtp.dg.com	Tom Wood, Data General

Please make the following changes (some may duplicate previous messages):

andyj@osf.org               Andy Johnson, OSF (was Prime)
meissner@osf.org            Mike Meissner, OSF (was Data General)

linda@ocfmail.ocf.llnl.gov  Linda Stanberry, Lawrence Livermore

I am simultaneously sending the following happy message to the X3J11 list:
--------------------

No appeals; FINAL!

By telephone conversation with Louise Germani,
at ANSI Board of Standards Review, I have confirmed the news given to me
yesterday by Jean Paul Emard at X3:
The time allowed for receipt of appeals to ANSI has expired.
No appeals have been received.
The approval by ANSI BSR is official.
The C Standard will be known as ANS X3.159-1989, because the approval
meeting was 14 December 1989.

I convey this news to you with great, and mixed, emotions.
Let me just express, on behalf of everyone, to everyone,
thanks for everything that was done to bring about this long-delayed result.

PS: My apologies if you had trouble reaching plumhall.uu.net last week;
we had a series of hardware problems.  Access should now be reliable.

--------------------

Thomas Plum, Plum Hall Inc, plum@plumhall.uu.net , (USA) 609-927-3770


 1-Feb-90 06:09:01-PST,638;000000000005
Return-Path: <plumhall!plum@uunet.UU.NET>
Received: from uunet.uu.net by NIC.DDN.MIL with TCP; Thu, 1 Feb 90 06:08:39 PST
Received: from plumhall.UUCP by uunet.uu.net (5.61/1.14) with UUCP 
	id AA17083; Thu, 1 Feb 90 09:07:44 -0500
Date: Thu, 1 Feb 90 09:07:04 EST
From: plum%plumhall@uunet.UU.NET (Thomas Plum)
Message-Id: <9002010907.1.UUL1.3#20135@plumhall.uu.net>
To: klh@NIC.DDN.MIL
Cc: KLH@NIC.DDN.MIL

Address changes

Ken - Thanks for your note, and your good wishes.

Thomas Plum, Plum Hall Inc, plum@plumhall.uu.net , (USA) 609-927-3770


I have an address change:  fay@sun4.mri.uucp  -->  amdcad!sun0!fay


 1-Feb-90 09:25:07-PST,626;000000000001
Return-Path: <plumhall!plum@uunet.UU.NET>
Received: from uunet.uu.net by NIC.DDN.MIL with TCP; Thu, 1 Feb 90 09:22:24 PST
Received: from plumhall.UUCP by uunet.uu.net (5.61/1.14) with UUCP 
	id AA14489; Thu, 1 Feb 90 12:21:30 -0500
Date: Thu, 1 Feb 90 12:20:17 EST
From: plum%plumhall@uunet.UU.NET (Thomas Plum)
Subject: Address changes
Message-Id: <9002011220.0.UUL1.3#20135@plumhall.uu.net>
To: KLH@NIC.DDN.MIL


Ken - Thanks for your note, and your good wishes.

Thomas Plum, Plum Hall Inc, plum@plumhall.uu.net , (USA) 609-927-3770


I have an address change:  fay@sun4.mri.uucp  -->  amdcad!sun0!fay


