; Create Assembler file <ftrel,make-urel.run,> with viewspecs BOw AND filtered BOw.
; Move urel to oldrel
ena
connect oldrel
archive file *.*;*,
don't archive

delete *.*;*
undelete *.sav;*
expunge
connect urel
archive file *.*;*,
don't archive

delver
yy
expunge
xfiles
copy <urel>*.*;* <oldrel>*.*;*

q

cd oldrel
not perpetual *;*
perpetual *;1
del *;*
expunge
cd urel
del *.*;*
undelete *.log;*
undelete *.flags;*
undelete *.stat;*
expunge
; Copy to urel from ftrel
enable
connect ftrel
archive file *.*;*,
don't archive

delver
yy
expunge
xfiles
copy <ftrel>*.*;* <urel>*.*;*

q

; Delete extra archive file versions in urel
connect urel
not perpetual *;*
perpetual *;1
del *;*
expunge
archive file *.*;*,
don't archive

; presbe and presfe
; Output (to) Assembler File <FtRel,UPreSFE.run,> 
Connect URel 
Get PreFE.sav
DDT
startup/god
recover/restart
debug/0
presav/1
l10startg
SSave 0 767 NlsSpFE.sav;
; Output (to) Assembler File <FtRel,UPreSBE.run,> 
Connect URel 
Get PreBE.sav
DDT
howpcp/1
mdebug/0
donthelp/1
qtgy
nn
SSave 0 777 NlsSpBE.sav;
; news files
copy <ftrel>news.txt
copy <ftrel>news.aug
; update news file write date
append tty: news.txt


; Open <oldrel> Access
ena
cd oldrel
get nlsspfe.sav
ddt
reldir[36,,14
reldir 1/"/DSK:<OLDREL>/
jsys haltfx
ssave 0 777 nlsspfe.sav

