; Create Assembler file <xrel,make-ftrel.run,> <include,>
refuse links
connect ftobj
archive file *.*;*,
don't archive

delver
YY

expunge
connect ftrel
archive file *.*;*,
don't archive

delver
YY

expunge
; INCLUDEd source code files
copy <sssrc>nls-parse.aug
copy <sssrc>nls-grammar.aug
; <sssrc>    supported subsystems
copy <xrel>ftrel-bes.genbe.gen
copy <xrel>urel-bes.gen
copy <xrel>include.sg
copy <xrel>base.gr
copy <xrel>base.pfc
copy <xrel>base.pr
copy <xrel>calculator.gr
copy <xrel>calculator.be
copy <xrel>calculator.sup
copy <xrel>calculator.pfc
;copy <xrel>calculator.pr
 
copy <xrel>compose.gr
copy <xrel>compose.be
copy <xrel>compose.pr
copy <xrel>conference.gr
copy <xrel>conference.be
copy <xrel>conference.pfc
copy <xrel>conference.pr
 
copy <xrel>cs.gr
copy <xrel>cs.pfc
copy <xrel>exec.gr
copy <xrel>exec.be
; exec.be is copied into ftobj
copy <xrel>fontload.gr
copy <xrel>fontload.be
copy <xrel>graphics.gr
copy <xrel>graphics.be
copy <xrel>graphics.pfc
;copy <xrel>graphics.pr

copy <xrel>gpsys.sup
 
copy <xrel>ident.gr
copy <xrel>ident.be
copy <xrel>ident.sup
copy <xrel>ident.pr
 
copy <xrel>library.gr
copy <xrel>library.be
copy <xrel>library.sup
;copy <xrel>library.pr
 
copy <xrel>mail.gr
copy <xrel>mail.be
copy <xrel>mail.pr
copy <xrel>mail.sup
copy <xrel>mail2.sup
copy <xrel>idmail.sup
 
copy <xrel>programs.gr
copy <xrel>programs.be
; programs.be is copied into ftobj
copy <xrel>programs.pfc
copy <xrel>programs.pr
copy <xrel>spell.gr
copy <xrel>spell-dictionaries.aug
copy <xrel>spell.be
copy <xrel>spell.pfc
copy <xrel>spell.pr
 
copy <xrel>table.gr
copy <xrel>table.be
copy <xrel>table.pr
 
copy <xrel>telecopy.gr
copy <xrel>telecopy.be
copy <xrel>telecopy.pfc
copy <xrel>telecopy.pr
 
copy <xrel>uosys.l10
copy <xrel>wpcontrol.gr
copy <xrel>wpcontrol.be
copy <xrel>wpcontrol.pfc
;copy <xrel>wpcontrol.pr
 
; <xsubsys>    unsupported subsystems
copy <xrel>ah.gr
copy <xrel>ah.be
copy <xrel>ah.pfc
 
; <opsrc>    output processor
; fmd files
copy <xrel>c81dds.fmd
copy <xrel>c82dds.fmd
copy <xrel>s6000g.fmd
copy <xrel>vc5gpo.fmd
copy <xrel>vc5amdahl.fmd
copy <xrel>upfamdahl.fmd
copy <xrel>vc8dds.fmd
copy <xrel>vc8datacomp.fmd
copy <xrel>x9700a.fmd
copy <xrel>com-dmv-data.aug
; background Augment processes
copy <xrel>inmail.l10
copy <xrel>inmail.sup
copy <xrel>jentry.l10
copy <xrel>mailer.l10
; *.sav files which don't need to be reloaded
copy <xrel>arcldr.sav
copy <xrel>meta.sav
copy <xrel>l10.sav
copy <xrel>cml.sav
copy <xrel>ftp-fork.sav
copy <xrel>comprc-fork.sav
copy <xrel>upfc82-fork.sav
copy <xrel>x9700-fork.sav
copy <xrel>ophyphen-fork.sav
copy <xrel>spell-fork.sav
copy <xrel>telslv.sav
copy <xrel>smtptop.sav
copy <xrel>smtpsend.sav
copy <xrel>smtprslave.sav
; these actually run out of <SYSTEM>
copy <xrel>telctl.sav
copy <xrel>tymail.sav
; <xrel> *.tcp files copied
copy <xrel>term.prm
copy <xrel>term1-14.tcp
copy <xrel>term1-16.tcp
copy <xrel>term1-19.tcp
copy <xrel>term1-2.tcp
copy <xrel>term1-27.tcp
copy <xrel>term2-16.tcp
copy <xrel>term2-19.tcp
copy <xrel>term2-2.tcp
copy <xrel>term2-27.tcp
copy <xrel>term2-30.tcp
copy <xrel>term3-14.tcp
; <FTObj> unloaded object code
Connect FTObj
;    <compsrc>  compilers, loaders, libes, and runtime
copy <xobj>arcldr.l10
copy <xobj>cgram.l10
copy <xobj>cml.meta
copy <xobj>l10.meta
;copy <xobj>l1011.meta
copy <xobj>meta.meta
copy <xobj>opcodes-l10.txt
copy <xobj>opcodes-meta.txt
copy <xobj>opdinit.meta
copy <xobj>syms-cml.txt
copy <xobj>syms-l10.txt
copy <xobj>syms-os.l10
copy <xobj>libe.l10
copy <xobj>libedop.l10
copy <xobj>libel10.l10
copy <xobj>libemop.l10
copy <xobj>libeopdinit.l10
;copy <xobj>rt-11data.l1011
;copy <xobj>rt-11main.l1011
copy <xobj>rt-data.l10
copy <xobj>rt-lrp.l10
copy <xobj>rt-main.l10
copy <xobj>rt-minidata.l10
copy <xobj>rt-minimain.l10
copy <xobj>stgmgt.l10
;    <fesrc>    frontend
copy <xobj>cgramldr.l10
copy <xobj>cli.l10
;copy <xobj>ddt-11.l1011
copy <xobj>dpy-10.l10
copy <xobj>dpydata.l10
copy <xobj>dpypkg.l10
copy <xobj>fecomm.l10
copy <xobj>fedata.l10
copy <xobj>feosi.l10
copy <xobj>feosidata.l10
copy <xobj>fertns.l10
;copy <xobj>msgdata.l10
;copy <xobj>msgi.l10
;copy <xobj>osi-cli-11.l1011
copy <xobj>pcpb8.l10
copy <xobj>pcpl10.l10
;copy <xobj>safedata.l10
;copy <xobj>safei.l10
copy <xobj>spi.l10
copy <xobj>spidata.l10
copy <xobj>termpage.l10
;copy <xobj>tty-11.l1011
;copy <xobj>typei.l10
;copy <xobj>uddt-11.l1011
copy <xobj>up.l10
copy <xobj>wsprinter.l10
;    <nlsbesrc> nls backend
copy <xobj>programs.be
copy <xobj>exec.be
copy <xobj>adrmnp.l10
copy <xobj>auxcod.l10
copy <xobj>backview.l10
copy <xobj>bconst.l10
copy <xobj>bdata.l10
copy <xobj>bepresave.l10
copy <xobj>besymmnp.l10
copy <xobj>bintnls.l10
copy <xobj>brecords.l10
copy <xobj>colsrt.l10
copy <xobj>coresupport.l10
copy <xobj>delimiters.l10
copy <xobj>dirprc.l10
copy <xobj>dspgen.l10
copy <xobj>encapsulator.l10
copy <xobj>error.l10
copy <xobj>execfl.l10
copy <xobj>filmnp.l10
copy <xobj>frontend.l10
copy <xobj>hash.l10
copy <xobj>help.l10
copy <xobj>identsupport.l10
copy <xobj>ioexec.l10
copy <xobj>isp.l10
copy <xobj>maconst.l10
copy <xobj>madata.l10
copy <xobj>mdata.l10
copy <xobj>middle.l10
copy <xobj>msg3data.l10
copy <xobj>nlsacnv.l10
copy <xobj>psedt1.l10
copy <xobj>psedt2.l10
copy <xobj>sdata.l10
copy <xobj>segmap.l10
copy <xobj>seqfil.l10
copy <xobj>seqgen.l10
copy <xobj>spdata.l10
copy <xobj>srecords.l10
copy <xobj>tsprt.l10
copy <xobj>uodata.l10
copy <xobj>uobe.l10
copy <xobj>utility.l10
copy <xobj>verify.l10
;    <opsrc>    output processor
;       directive recognition
copy <xobj>dval.opdinit
copy <xobj>dval.txt
copy <xobj>drecex.meta
; l10 files
copy <xobj>docfmt.l10
copy <xobj>fastop.l10
copy <xobj>hdrfmt.l10
copy <xobj>input.l10
copy <xobj>lsgcol.l10
copy <xobj>number.l10
copy <xobj>opdata.l10
copy <xobj>opexec.l10
copy <xobj>oputil.l10
copy <xobj>pgnate.l10
copy <xobj>pstprc.l10
copy <xobj>stfmt.l10
copy <xobj>things.l10
;    compose translators
copy <xobj>comprc.l10
copy <xobj>xlcommon.l10
copy <xobj>xlupf.l10
copy <xobj>xlx9700.l10
Connect FTRel
; load files
copy <xrel>load-ftfe.runload-nlsspfe.run
copy <xrel>load-ftbe.runload-nlsspbe.run
copy <xrel>load-ftop.runload-outprc.run
copy <xrel>load-ftdp.runload-dirprc.run
; batch load jobs <ftrel>nlsspfe.sav,nlsspbe.sav,outprc.sav, and 
; dirprc.sav
batch
c<ftrel>load-nlsspfe.run
l<ftrel>load-nlsspfe.log

g
c<ftrel>load-nlsspbe.run
l<ftrel>load-nlsspbe.log

g
c<ftrel>load-outprc.run
l<ftrel>load-outprc.log

g
c<ftrel>load-dirprc.run
l<ftrel>load-dirprc.log

g
q
; news files
copy <xrel>news.txt
copy <xrel>news.aug
; update news file write date
append tty: news.txt


archive file <FTRel>*.* <FTObj>*.*,
don't delete

