!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING FORMAT
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:FORMAT.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:FORMAT.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:FORMAT.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:FORMAT.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:FORMAT.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SOURCE:FORMAT.EXE TO-SUBSYS:*.*.-1
