! UPD ID= 4038, SNARK:<6.MONITOR>LN2060.CTL.40,   2-Apr-84 11:20:02 by PURRETTA
! UPD ID= 3999, SNARK:<6.MONITOR>LN2060.CTL.39,  28-Mar-84 20:40:30 by PURRETTA
! UPD ID= 3760, SNARK:<6.MONITOR>LN2060.CTL.38,  26-Feb-84 16:33:20 by PURRETTA
! UPD ID= 3734, SNARK:<6.MONITOR>LN2060.CTL.37,  22-Feb-84 16:16:48 by PURRETTA
;<6.MONITOR>LN2060.CTL.35,  1-Feb-84 22:24:16, EDIT BY MURPHY
! UPD ID= 3147, SNARK:<6.MONITOR>LN2060.CTL.33,  15-Nov-83 00:38:16 by MOSER
;ADD PHYMVR
;<6.MONITOR>LN2060.CTL.30, 27-Jul-83 12:25:38, Edit by PURRETTA
;Remove KCCNSL
;Automatic re-link if PSECT overlaps.
;<6.MONITOR>LN2060.CTL.27, 14-May-83 13:29:39, Edit by PURRETTA
;Split ASEMBL.CMD into ASMBL1.CMD and ASMBL2.CMD
! UPD ID= 2320, SNARK:<6.MONITOR>LN2060.CTL.26,  20-Apr-83 16:51:31 by HALL
!Try again on previous edit
! UPD ID= 2318, SNARK:<6.MONITOR>LN2060.CTL.25,  20-Apr-83 13:14:14 by HALL
!Add CTSMON
! UPD ID= 2316, SNARK:<6.MONITOR>LN2060.CTL.24,  20-Apr-83 11:40:51 by HALL
!Really remove CISRV and LCSSRV
! UPD ID= 2315, SNARK:<6.MONITOR>LN2060.CTL.23,  20-Apr-83 07:37:52 by HALL
!Fix typo in previous edit. Remove PAGFIL
! UPD ID= 1921, SNARK:<6.MONITOR>LN2060.CTL.20,   7-Mar-83 20:14:20 by CDUNN
!Add SCAMPI, SCSJSY, CFSSRV, PHYKLP, and PHYMSC
! UPD ID= 1665, SNARK:<6.MONITOR>LN2060.CTL.19,  16-Jan-83 21:39:12 by GRANT
!TCO 6.1454 - Add NTMAN and remove NSPINT
! UPD ID= 1658, SNARK:<6.MONITOR>LN2060.CTL.18,  14-Jan-83 08:06:48 by HALL
!TCO 6.1463 - SPILT PAGEM INTO 3 MODULES
! UPD ID= 1144, SNARK:<6.MONITOR>LN2060.CTL.17,   3-Sep-82 18:35:57 by LEACHE
!Add CRYPT
!
! NAME: LN2060.CTL
! DATE: 21-JUN-78
!
!
! FUNCTION:	THIS CONTROL FILE BUILDS THE LN2060
!		MONITORS FROM SOURCES.
!
!TO ASSEMBLE AND BUILD ALL STANDARD LN2060 MONITORS:
!SUBMIT LN2060/TIME:2:0:0
!
!TO LOAD ALL STANDARD LN2060 MONITORS USING LN2060.REL:
!SUBMIT LN2060/TAG:ALL/TIME:1:0:0
!
!TO LOAD JUST ONE LN2060 MONITOR USING PARAM0 AND LN2060.REL:
!SUBMIT LN2060/TAG:SINGLE/TIME:1:0:0
!

@TAKE BATCH
@INFORMATION LOGICAL-NAMES ALL
!
!Before doing anything, see if we are connected to a reasonable directory.
!A reasonable directory will have SYSFLG.MAC which determines
!processor conditionals.  Also, you will see what processor you
!are assembling for.
@TYPE MON:SYSFLG.MAC
@IF (ERROR) @GOTO ZZZ
!
! TAKE A CHECKSUMMED DIRECTORY OF ALL THE INPUT FILES
!
@VDIRECT SYS:LINK.EXE.0,SYS:CREF.EXE.0,SYS:MACRO.EXE.0,
@CHECKSUM SEQ
@
@VDIRECT SYS:MONSYM.UNV.0,SYS:MACSYM.UNV.0,SYS:MACREL.REL.0,SYS:PA1050.EXE.0,
@CHECKSUM SEQ
@
@
@GET SYS:MACRO
@INFORMATION VERSION
@GET SYS:LINK
@INFORMATION VERSION
@GET SYS:CREF
@INFORMATION VERSION
!
@NOERROR
@DELETE MON.*

!COMPILE THE SOURCE MODULES
@TAKE MON:ASEMBL.CMD

!MAKE THE LIBRARY FILE
!
@DELETE LN2060.REL
@APPEND R:SCAMPI.REL,R:SCSJSY.REL,R:PHYKLP.REL,R:PHYMSC.REL LN2060.REL
@APPEND R:CFSSRV.REL,R:APRSRV.REL,R:SCHED.REL,R:PAGEM.REL LN2060.REL
@APPEND R:PAGUTL.REL,R:PHYMVR.REL,R:FORK.REL,R:MEXEC.REL LN2060.REL
@APPEND R:GETSAV.REL,R:SYSERR.REL,R:COMND.REL,R:DEVICE.REL LN2060.REL
@APPEND R:DIRECT.REL,R:ENQ.REL,R:FREE.REL,R:FUTILI.REL,R:GTJFN.REL LN2060.REL
@APPEND R:IO.REL,R:IPCF.REL,R:JSYSA.REL,R:JSYSF.REL,R:LOGNAM.REL LN2060.REL
@APPEND R:LOOKUP.REL,R:MSTR.REL,R:SWPALC.REL,R:DISC.REL,R:FILINI.REL LN2060.REL
@APPEND R:FILMSC.REL,R:MFLIN.REL,R:MFLOUT.REL,R:DATIME.REL LN2060.REL
@APPEND R:PHYSIO.REL,R:DIAG.REL,R:DSKALC.REL,R:PHYH2.REL,R:PHYP4.REL LN2060.REL
@APPEND R:PHYP2.REL,R:PHYM78,R:TTYSRV.REL,R:FESRV.REL,R:MAGTAP.REL LN2060.REL
@APPEND R:TAPE.REL,R:TIMER.REL,R:PHYM2.REL,R:PHYX2.REL,R:DTESRV.REL LN2060.REL
@APPEND R:LINEPR.REL,R:CDPSRV.REL,R:PLT.REL,R:PTP.REL,R:PTR.REL LN2060.REL
@APPEND R:CDRSRV.REL,R:NSPSRV.REL,R:NTMAN.REL,R:FILNFT.REL LN2060.REL
@APPEND R:CRYPT.REL,R:POSTLD.REL LN2060.REL
@DELETE MONDDT.REL
@APPEND R:KDDT.REL,R:MDDT.REL MONDDT.REL
!
@GOTO ALL1
!
ALL::
@INFORMATION LOGICAL-NAMES ALL
!
! TAKE A CHECKSUMMED DIRECTORY OF ALL THE INPUT FILES
!
@VDIRECT SYS:LINK.EXE.0,SYS:CREF.EXE.0,SYS:MACRO.EXE.0,
@CHECKSUM SEQ
@
@VDIRECT SYS:MONSYM.UNV.0,SYS:MACSYM.UNV.0,SYS:MACREL.REL.0,SYS:PA1050.EXE.0,
@CHECKSUM SEQ
@
@
@GET SYS:MACRO
@INFORMATION VERSION
@GET SYS:LINK
@INFORMATION VERSION
@GET SYS:CREF
@INFORMATION VERSION
!
ALL1::
!
@DELETE MON.*
!
!BUILD A BIG MONITOR
@DEL STG.REL,VERSIO.REL
@EXP
@COMPILE /COMP MON:N60BIG.MAC+MON:VERSIO.MAC VERSIO
@COMPILE /COMP MON:P60BIG.MAC+MON:PARAMS.MAC+MON:STG.MAC STG
@ERROR
@R LINK
*@MON:LNKMSX.CCL
*LN2060/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET MON
@IF (ERROR) @GOTO Z11
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
*DDTIBP^[10B
*^[10B+2/2
=G
@IF (NOERROR) @GOTO MOK
@NOERROR
@COMPILE /COMP MON:P60BIG.MAC+PARNEW.MAC+MON:PARAMS.MAC+MON:STG.MAC STG
@ERROR
@R LINK
*@LNKNEW.CCL
*@MON:LNKINI.CCL
*LN2060/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET MON
@IF (ERROR) @GOTO Z11
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
*DDTIBP^[10B
*^[10B+2/2
=G
MOK::
@RENAME MONITR.EXE.0 2060-MONBIG.EXE
Z11::
!
!BUILD A MAX MONITOR
@NOERROR
@DEL STG.REL,VERSIO.REL
@EXP
@COMPILE /COMP MON:N60MAX.MAC+MON:VERSIO.MAC VERSIO
@COMPILE /COMP MON:P60MAX.MAC+MON:PARAMS.MAC+MON:STG.MAC STG
@ERROR
@R LINK
*@MON:LNKMSX.CCL
*LN2060/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET MON
@IF (ERROR) @GOTO YYY
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
*DDTIBP^[10B
*^[10B+2/2
=G
@IF (NOERROR) @GOTO MOK
@NOERROR
@COMPILE /COMP MON:P60MAX.MAC+PARNEW.MAC+MON:PARAMS.MAC+MON:STG.MAC STG
@ERROR
@R LINK
*@LNKNEW.CCL
*@MON:LNKINI.CCL
*LN2060/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET MON
@IF (ERROR) @GOTO YYY
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
*DDTIBP^[10B
*^[10B+2/2
=G
MOK::
@RENAME MONITR.EXE.0 2060-MONMAX.EXE
!
YYY::
@NOERROR
@DIR 2060-*.EXE.0,
@CHECKSUM SEQ
@
@GOTO E
!
SINGLE::
!
!BUILD MONITR.EXE USING PARAM0, NAMAM0 AND LN2060.REL
!
@INFORMATION LOGICAL-NAMES ALL
!
! TAKE A CHECKSUMMED DIRECTORY OF ALL THE INPUT FILES
!
@VDIRECT SYS:LINK.EXE.0,SYS:CREF.EXE.0,SYS:MACRO.EXE.0,
@CHECKSUM SEQ
@
@VDIRECT SYS:MONSYM.UNV.0,SYS:MACSYM.UNV.0,SYS:MACREL.REL.0,SYS:PA1050.EXE.0,
@CHECKSUM SEQ
@
@
@GET SYS:MACRO
@INFORMATION VERSION
@GET SYS:LINK
@INFORMATION VERSION
@GET SYS:CREF
@INFORMATION VERSION
!
!
@DELETE MON.*
@DELETE STG.REL, VERSIO.REL
@DEL MONITR.*
!
@COMPILE /COMP MON:NAMAM0.MAC+MON:VERSIO.MAC VERSIO
@COMPILE /COMP MON:PARAM0.MAC+MON:PARAMS.MAC+MON:STG.MAC STG
@ERROR
@R LINK
*@MON:LNKMSX.CCL
*LN2060/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET MON
@IF (ERROR) @GOTO E
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
*DDTIBP^[10B
*^[10B+2/2
G
@IF (NOERROR) @GOTO MOK
@NOERROR
@COMPILE /COMP MON:PARAM0.MAC+PARNEW.MAC+MON:PARAMS.MAC+MON:STG.MAC STG
@ERROR
@R LINK
*@LNKNEW.CCL
*@MON:LNKINI.CCL
*LN2060/S, -
*/NOLOCALS, -
*/SYSLIB, -
*/G
@EXP
@GET MON
@IF (ERROR) @GOTO E
@START 142
=BUGHLT<HLTADR12B
=BUGCHK<CHKADR11B
*DDTIBP^[10B
*^[10B+2/2
=G
MOK::
@DIR MONITR.EXE.0,
@CHECKSUM SEQ
@
E::

!
@DELETE MON.*
ZZZ::
!END OF LN2060.CTL
