;<6.UTILITIES>PAT.CTL.3,  1-Sep-84 12:06:46, Edit by PURRETTA
;<4.UTILITIES>PAT.CTL.2, 11-Apr-78 14:41:33, Edit by HELLIWELL
!
! NAME: PAT.CTL
! DATE: 1-SEP-84
!
!THIS CONTROL FILE IS PROVIDED FOR INFORMATION PURPOSES ONLY.  THE
!PURPOSE OF THE FILE IS TO DOCUMENT THE PROCEDURES USED TO BUILD
!THE DISTRIBUTED SOFTWARE.  IT IS UNLIKELY THAT THIS CONTROL FILE
!WILL BE ABLE TO BE SUBMITTED WITHOUT MODIFICATION ON CONSUMER
!SYSTEMS.  PARTICULAR ATTENTION SHOULD BE GIVEN TO ERSATZ DEVICES
!AND STRUCTURE NAMES, PPN'S, AND OTHER SUCH PARAMETERS.  SUBMIT
!TIMES MAY VARY DEPENDING ON SYSTEM CONFIGURATION AND LOAD.  THE
!AVAILABILITY OF SUFFICIENT DISK SPACE AND CORE IS MANDATORY.
!
! FUNCTION:	THIS CONTROL FILE BUILDS THE COMPATABILITY
!		PACKAGE (PAT) FROM ITS BASIC SOURCES.  A
!		EXE FILE WITH WRITE PROTECTION APPROPRIATE FOR
!		PLACEMENT IN SYS: IS ALSO CREATED.
!
! SUBMIT WITH THE SWITCH "/TAG:CREF" TO OBTAIN 
!   A .CRF LISTING OF THE SOURCE FILE
!
!
@DEF FOO: NUL:
@GOTO A
!
CREF:: @DEF FOO: DSK:
!
A::
@NOERROR
@TAKE BATCH.CMD
!
@INFORMATION LOGICAL-NAMES ALL
!
! TAKE A CHECKSUMMED DIRECTORY OF ALL THE INPUT FILES
!
@VDIRECT SYS:LINK.EXE,SYS:*DDT.EXE,SYS:CREF.EXE,PAT.MAC,
@CHECKSUM SEQ
@
@VDIRECT SYS:MONSYM.UNV,SYS:MACSYM.UNV,SYS:MACREL.REL,SYS:PA1050.EXE,
@CHECKSUM SEQ
@
@
@RUN SYS:MACRO
@INFORMATION VERSION
@GET SYS:LINK
@INFORMATION VERSION
@GET SYS:CREF
@INFORMATION VERSION
!
@ERROR
@LOAD /CREF PAT.MAC
!
@START
!
@INFORMATION MEMORY-USAGE
!
@SAVE PAT
!
! WRITE AN EXE FILE WITH WRITE PROTECTION
!
@GET PAT
@START
*MAKEPFG

!
@NOERROR
@GET PA1050
@INFORMATION VERSION
;SM	@R CREF
;SM	*FOO:PAT.LST=PAT.CRF
!
@VDIRECT PAT.EXE,PA1050.EXE,
@CHECKSUM SEQ
@
!
! DELETE UNNECESSARY .REL FILES
! 
@DELETE PAT.REL
!
![End PAT.CTL]
