!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING SCSTST
INFORMATION LOGICAL FROM*:
INFORMATION LOGICAL TO*:

;Files required to build product
COPY FROM-SOURCE:SCSTST.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SCSTST.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SCSTST.MAC TO-SOURCE:*.*.-1

;Documentation for product
;When a DOC file exists this should be allowed again
;COPY FROM-SOURCE:SCSTST.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SUBSYS:SCSTST.EXE TO-SUBSYS:*.*.-1
