!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO SETSPD
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:SETSPD.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SETSPD.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SETSPD.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:SETSPD.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SOURCE:6-SETSPD.EXE TO-SYSTEM:*.*.-1
