;Command file to build SYSDPY
INFORMATION LOGICAL-NAMES FROM-*:
INFORMATION LOGICAL-NAMES TO-*:

;Files required to build product
COPY FROM-SOURCE:SYSDPY.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SYSDPY.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SYSDPY.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DPY.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DPYDEF.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:SYSDPY.MEM TO-DOC:*.*.-1
COPY FROM-SOURCE:SYSDPY.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:SYSDPY.DOC TO-DOC:*.*.-1

;Final product
COPY FROM-SOURCE:SYSDPY.EXE TO-SUBSYS:*.*.-1
