!GALAXY.CTL
!
!
!              COPYRIGHT (C) DIGITAL EQUIPMENT CORPORATION
!			1979,1980,1981,1982
!
!     THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY  BE  USED
!     AND COPIED ONLY IN ACCORDANCE WITH THE TERMS OF SUCH LICENSE
!     AND WITH THE INCLUSION OF THE ABOVE COPYRIGHT NOTICE.   THIS
!     SOFTWARE  OR ANY OTHER COPIES THEREOF MAY NOT BE PROVIDED OR
!     OTHERWISE MADE AVAILABLE TO ANY OTHER PERSON.  NO  TITLE  TO
!     AND OWNERSHIP OF THE SOFTWARE IS HEREBY TRANSFERRED.
!
!     THE INFORMATION  IN  THIS  SOFTWARE  IS  SUBJECT  TO  CHANGE
!     WITHOUT  NOTICE  AND SHOULD NOT BE CONSTRUED AS A COMMITMENT
!     BY DIGITAL EQUIPMENT CORPORATION.
!
!     DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR RELIABILITY
!     OF  ITS  SOFTWARE  ON  EQUIPMENT  WHICH  IS  NOT SUPPLIED BY
!     DIGITAL.

!This control file and it's subordinate files generate a DEC-20
!Galaxy System

!Before Submitting This Control file:

!	1.  Perform system installation to ensure current copies
!	    of required system universal and rel files and a running
!	    Batch system.

!	2.  Run GALGEN to generate GALCNF.MAC Tailored to your system

!	3.  SUBMIT GALAXY.CTL

!Description

!	GALAXY.CTL requires several Subordinate Control files for
!	the individual Components.  Each of these files may be used
!	independently to generate that particluar component.

!	This control file also builds the GALAXY library.
!The files required are:

!LINK command file

!	GLXLIB.CCL

!Source Files

!	GLXVER.MAC
!	GLXMAC.MAC
!	GLXINI.MAC
!	GLXOTS.MAC
!	GLXCOM.MAC
!	GLXIPC.MAC
!	GLXFIL.MAC
!	GLXTXT.MAC
!	GLXLNK.MAC
!	GLXSCN.MAC
!	GLXKBD.MAC
!	GLXMEM.MAC
!	GLXINT.MAC


!Output Files

!	GLXMAC.UNV
!	GLXLIB.REL
!	GLXLIB.EXE

!Subordinate Control Files

!	GLXLIB.CTL	generates the linkable and OTS galaxy library
!	QUASAR.CTL	generates GALAXY Scheduling and control program
!	OPERATOR.CTL	generates Operator Interface Control program
!			and Operator Interface program OPR
!	LPTSPL.CTL	generates Printer Spooler Program
!	CDRIVE.CTL	generates Card Reader Spooler Program
!	SPROUT.CTL	generates Punch and Plotter Spooler Program
!	BATCON.CTL	generates Batch Job Control Program
!	SPRINT.CTL	generates batch preprocessor and card reader interpreter
!	GALGEN.CTL
!	PLEASE.CTL	generates the PLEASE program
!	MOUNTR.CTL	generates the MOUNTR program
!	

.ASS DSK REL
.SET WATCH VERSION
@DEF REL: DSK:
@DEF UNV: DSK:,UNV:
@VDIR	GLXVER.MAC
@VDIR	GLXMAC.MAC
@VDIR	GLXINI.MAC
@VDIR	GLXOTS.MAC
@VDIR	GLXCOM.MAC
@VDIR	GLXIPC.MAC
@VDIR	GLXFIL.MAC
@VDIR	GLXTXT.MAC
@VDIR	GLXLNK.MAC
@VDIR	GLXSCN.MAC
@VDIR	GLXKBD.MAC
@VDIR	GLXMEM.MAC
@VDIR	GLXINT.MAC


.DIRECT	GLXVER.MAC
.DIRECT	GLXMAC.MAC
.DIRECT	GLXINI.MAC
.DIRECT	GLXOTS.MAC
.DIRECT	GLXCOM.MAC
.DIRECT	GLXIPC.MAC
.DIRECT	GLXFIL.MAC
.DIRECT	GLXTXT.MAC
.DIRECT	GLXLNK.MAC
.DIRECT	GLXSCN.MAC
.DIRECT	GLXKBD.MAC
.DIRECT	GLXMEM.MAC
.DIRECT	GLXINT.MAC


!Create GALAXY configuration universal
@
.
COMPILE/COMPILE GALCNF.MAC

!
!Build the linkable GALAXY library
!
.GOTO TOPS10
@GOTO TOPS20

TOPS20::
@COPY TTY: GLXPUR.MAC
@GLXPURE==0
@^Z
@GOTO NEXT

TOPS10::
.COPY GLXPUR.MAC=TTY:
*GLXPURE==0
*^Z

NEXT::
@
.
COMPILE /COMPILE GLXPUR.MAC+GLXVER.MAC+GLXMAC.MAC
COMPILE /COMPILE ORNMAC.MAC

COMPILE /COMPILE GLXINI.MAC
COMPILE /COMPILE GLXCOM.MAC
COMPILE /COMPILE GLXFIL.MAC
COMPILE /COMPILE GLXINT.MAC
COMPILE /COMPILE GLXIPC.MAC
COMPILE /COMPILE GLXKBD.MAC
COMPILE /COMPILE GLXLNK.MAC
COMPILE /COMPILE GLXMEM.MAC
COMPILE /COMPILE GLXOTS.MAC
COMPILE /COMPILE GLXSCN.MAC
COMPILE /COMPILE GLXTXT.MAC
DELETE GLXLIB.REL
@APPEND GLXINI.REL,GLXMAC.REL,GLXOTS.REL,GLXCOM.REL,GLXIPC.REL,GLXFIL.REL,GLXTXT.REL,GLXLNK.REL,GLXSCN.REL,GLXKBD.REL,GLXMEM.REL,GLXINT.REL (TO) GLXLIB.REL 
.COPY GLXLIB.REL =  GLXINI.REL,GLXMAC.REL,GLXOTS.REL,GLXCOM.REL,GLXIPC.REL,GLXFIL.REL,GLXTXT.REL,GLXLNK.REL,GLXSCN.REL,GLXKBD.REL,GLXMEM.REL,GLXINT.REL

!
!Build the object time system GLXLIB
!

.GOTO TOPS10
@GOTO TOPS20

TOPS20::
@COPY TTY: GLXPUR.MAC
@GLXPURE==-1
@^Z
@GOTO NEXT

TOPS10::
.COPY GLXPUR.MAC=TTY:
*GLXPURE==-1
*^Z

NEXT::
@
.
COMPILE /COMPILE GLXPUR.MAC+GLXVER.MAC+GLXMAC.MAC
COMPILE /COMPILE GLXINI.MAC
COMPILE /COMPILE GLXCOM.MAC
COMPILE /COMPILE GLXFIL.MAC
COMPILE /COMPILE GLXINT.MAC
COMPILE /COMPILE GLXIPC.MAC
COMPILE /COMPILE GLXKBD.MAC
COMPILE /COMPILE GLXLNK.MAC
COMPILE /COMPILE GLXMEM.MAC
COMPILE /COMPILE GLXOTS.MAC
COMPILE /COMPILE GLXSCN.MAC
COMPILE /COMPILE GLXTXT.MAC
R LINK
*@GLXLIB.CCL

!Create required universals
@
.
COMPILE/COMPILE QSRMAC.MAC
COMPILE/COMPILE D60UNV.MAC

!Create required rel files
@
.
COMPILE/COMPILE OPRPAR.MAC
COMPILE/COMPILE D60JSY.MAC
COMPILE/COMPILE NURD.MAC

!Vanquish rel files produces from UNV's

@
.
DELETE GLXMAC.REL,QSRMAC.REL,D60UNV.REL


@VDIRECT GLXMAC.UNV,QSRMAC.UNV,ORNMAC.UNV,D60UNV.UNV
@VDIRECT OPRPAR.REL,D60JSY.REL
.DIRECT GLXMAC.UNV,QSRMAC.UNV,ORNMAC.UNV,D60UNV.UNV
.DIRECT OPRPAR.REL,D60JSY.REL

!Resubmit ourself to finish up after all modules have completed
@
.
SUBMIT GALAXY/TAG:FINI/OUTPUT:NOLOG/DEPEND:10/TIME:5

!SUBMIT Subordinates
@
.
SUBMIT QUASAR/UNIQUE:NO/OUTPUT:NOLOG/TIME:01:00:00/RESTART:YES
SUBMIT OPERAT/UNIQUE:NO/OUTPUT:NOLOG/TIME:01:00:00/RESTART:YES
SUBMIT SPROUT/UNIQUE:NO/OUTPUT:NOLOG/TIME:01:00:00/RESTART:YES
SUBMIT PLEASE/UNIQUE:NO/OUTPUT:NOLOG/TIME:01:00:00/RESTART:YES
SUBMIT LPTSPL/UNIQUE:NO/OUTPUT:NOLOG/TIME:01:00:00/RESTART:YES
SUBMIT CDRIVE/UNIQUE:NO/OUTPUT:NOLOG/TIME:01:00:00/RESTART:YES
SUBMIT BATCON/UNIQUE:NO/OUTPUT:NOLOG/TIME:01:00:00/RESTART:YES
SUBMIT QMANGR/UNIQUE:NO/OUTPUT:NOLOG/TIME:01:00:00/RESTART:YES
SUBMIT SPRINT/UNIQUE:NO/OUTPUT:NOLOG/TIME:01:00:00/RESTART:YES
SUBMIT GALGEN/UNIQUE:NO/OUTPUT:NOLOG/TIME:01:00:00/RESTART:YES
SUBMIT MOUNTR/UNIQUE:NO/OUTPUT:NOLOG/TIME:01:00:00/RESTART:YES


!Finally wait for completion of all modules
GOTO WAIT

FINI::

@VDIRECT *.EXE,
@CHECK
@
.DIRECT/CHECK *.EXE
@
.
PLEASE	GALAXY Generation Successful
@
.
;PRI *.LOG/NOTE:"GALAXY LOG"

%CERR::
%ERR::
@
.
PLEASE Error During GALAXY Generation
WAIT::
%FIN::
