!GLXLIB.CTL	15-Apr-80
!This control file creates EXE and REL version of GLXLIB

!System Files

!	UUOSYM.MAC (TOPS-10)
!	MONINT.EXE
!	BLISS.EXE

!Required Files in Your Area

!	GALCNF.MAC	GALAXY Configuration File
!	ORNMAC.UNV

!Source Files

!	GLXVER.MAC
!	GLXMAC.MAC
!	GLXINI.MAC
!	GLXOTS.MAC
!	GLXCOM.MAC
!	GLXIPC.MAC
!	GLXFIL.MAC
!	GLXTXT.MAC
!	GLXLNK.MAC
!	GLXSCN.MAC
!	GLXKBD.MAC
!	GLXMEM.MAC
!	GLXINT.MAC

!Output Files

!	GLXMAC.UNV
!	GLXMAC.L36
!	GLXINI.REL
!	GLXLIB.REL
!	GLXLIB.EXE


; Build GLXLIB linkable library
;
@VDIR	GLXVER.MAC
@VDIR	GLXMAC.MAC
@VDIR	GLXINI.MAC
@VDIR	GLXOTS.MAC
@VDIR	GLXCOM.MAC
@VDIR	GLXIPC.MAC
@VDIR	GLXFIL.MAC
@VDIR	GLXTXT.MAC
@VDIR	GLXLNK.MAC
@VDIR	GLXSCN.MAC
@VDIR	GLXKBD.MAC
@VDIR	GLXMEM.MAC
@VDIR	GLXINT.MAC


.DIRECT	GLXVER.MAC
.DIRECT	GLXMAC.MAC
.DIRECT	GLXINI.MAC
.DIRECT	GLXOTS.MAC
.DIRECT	GLXCOM.MAC
.DIRECT	GLXIPC.MAC
.DIRECT	GLXFIL.MAC
.DIRECT	GLXTXT.MAC
.DIRECT	GLXLNK.MAC
.DIRECT	GLXSCN.MAC
.DIRECT	GLXKBD.MAC
.DIRECT	GLXMEM.MAC
.DIRECT	GLXINT.MAC

.GOTO TOPS10

@GOTO TOPS20

TOPS10::
.COPY GLXPUR.MAC=TTY:
*GLXPURE==0
=
.COMPILE /COMPILE GLXPUR.MAC+GLXVER.MAC+GLXMAC.MAC
.COMPILE /COMPILE GLXINI.MAC
.COMPILE /COMPILE GLXCOM.MAC
.COMPILE /COMPILE GLXFIL.MAC
.COMPILE /COMPILE GLXINT.MAC
.COMPILE /COMPILE GLXIPC.MAC
.COMPILE /COMPILE GLXKBD.MAC
.COMPILE /COMPILE GLXLNK.MAC
.COMPILE /COMPILE GLXMEM.MAC
.COMPILE /COMPILE GLXOTS.MAC
.COMPILE /COMPILE GLXPFH.MAC
.COMPILE /COMPILE GLXSCN.MAC
.COMPILE /COMPILE GLXTXT.MAC

.COPY GLXLIB.REL=GLXINI.REL,GLXMAC.REL,GLXOTS.REL,GLXPFH.REL,GLXCOM.REL,GLXIPC.REL,GLXFIL.REL,GLXTXT.REL,GLXLNK.REL,GLXSCN.REL,GLXKBD.REL,GLXMEM.REL,GLXINT.REL 


; Build GLXLIB Object Time System
;
.COPY GLXPUR.MAC=TTY:
*GLXPURE==-1
=
.COMPILE /COMPILE GLXPUR.MAC+GLXVER.MAC+GLXMAC.MAC
.COMPILE /COMPILE GLXINI.MAC
.COMPILE /COMPILE GLXCOM.MAC
.COMPILE /COMPILE GLXFIL.MAC
.COMPILE /COMPILE GLXINT.MAC
.COMPILE /COMPILE GLXIPC.MAC
.COMPILE /COMPILE GLXKBD.MAC
.COMPILE /COMPILE GLXLNK.MAC
.COMPILE /COMPILE GLXMEM.MAC
.COMPILE /COMPILE GLXOTS.MAC
.COMPILE /COMPILE GLXPFH.MAC
.COMPILE /COMPILE GLXSCN.MAC
.COMPILE /COMPILE GLXTXT.MAC

LOAD::
.R LINK
*GLXLIB/SSAVE = -
*/SET:.HIGH.:400000 /SET:DATA:600000 /SYMSEG:PSECT:.HIGH. /LOCALS -
*GLXMAC, GLXOTS, GLXCOM, GLXIPC, GLXFIL, GLXKBD, -
*GLXLNK, GLXMEM, GLXSCN, GLXTXT, GLXINT -
*/GO

FINI::

.DIRECT/CHECK GLXLIB.EXE,GLXLIB.REL
.PLEASE	GLXLIB Assembly Successful
.NOERROR
.SUBMIT GALAXY=/MOD/DEP:-1

%CERR::
%ERR::
.PLEASE	Error During GLXLIB Assembly
.GOTO END

TOPS20::

@COPY TTY: GLXPUR.MAC
@GLXPURE==0
@
@COMPILE /COMPILE GLXPUR.MAC+GLXVER.MAC+GLXMAC.MAC
@COMPILE /COMPILE GLXINI.MAC
@COMPILE /COMPILE GLXCOM.MAC
@COMPILE /COMPILE GLXFIL.MAC
@COMPILE /COMPILE GLXINT.MAC
@COMPILE /COMPILE GLXIPC.MAC
@COMPILE /COMPILE GLXKBD.MAC
@COMPILE /COMPILE GLXLNK.MAC
@COMPILE /COMPILE GLXMEM.MAC
@COMPILE /COMPILE GLXOTS.MAC
@;COMPILE /COMPILE GLXPFH.MAC
@COMPILE /COMPILE GLXSCN.MAC
@COMPILE /COMPILE GLXTXT.MAC

@DELETE GLXLIB.REL
@APPEND GLXINI.REL,GLXMAC.REL,GLXOTS.REL!,GLXPFH.REL!,GLXCOM.REL,GLXIPC.REL,GLXFIL.REL,GLXTXT.REL,GLXLNK.REL,GLXSCN.REL,GLXKBD.REL,GLXMEM.REL,GLXINT.REL GLXLIB.REL

; Build GLXLIB Object Time System
;
@COPY TTY: GLXPUR.MAC
@GLXPURE==-1
@
@COMPILE /COMPILE GLXPUR.MAC+GLXVER.MAC+GLXMAC.MAC
@COMPILE /COMPILE GLXINI.MAC
@COMPILE /COMPILE GLXCOM.MAC
@COMPILE /COMPILE GLXFIL.MAC
@COMPILE /COMPILE GLXINT.MAC
@COMPILE /COMPILE GLXIPC.MAC
@COMPILE /COMPILE GLXKBD.MAC
@COMPILE /COMPILE GLXLNK.MAC
@COMPILE /COMPILE GLXMEM.MAC
@COMPILE /COMPILE GLXOTS.MAC
@COMPILE /COMPILE GLXPFH.MAC
@COMPILE /COMPILE GLXSCN.MAC
@COMPILE /COMPILE GLXTXT.MAC

LOAD::
@R LINK
*GLXLIB/SAVE = -
*/SET:.HIGH.:400000 /SET:DATA:600000 /SYMSEG:PSECT:.HIGH. /LOCALS -
*GLXMAC, GLXOTS, GLXCOM, GLXIPC, GLXFIL, GLXKBD, -
*GLXLNK, GLXMEM, GLXSCN, GLXTXT, GLXINT -
*/GO

FINI::

@FDIRECT GLXLIB.EXE,GLXLIB.REL
@PLEASE	GLXLIB Assembly Successful
@NOERROR
@MODIFY GALAXY/DEP:-1

%CERR::
%ERR::
@PLEASE	Error During GLXLIB Assembly

END::
%FIN::
