SUBTTL	GLXVER	GLXLIB Version file

;	Assembly Instructions:

;		COMPILE GLXVER+GLXMAC

LODLEV==2	;INCREMENT TO FORCE RECOMPILE OF LIBRARY
%%.GLX==10	;INCREMENT TO FORCE RECOMPILE OF ALL PROGRAMS

; *** N o t e   Edit Levels here must match MODULE EDIT NUMBER
;		Symbol MOD'EDT Where MOD is the 3 character
;		abbreviation for the module (i.e. MAC would be
;		MACEDT, IPC would be IPCEDT etc.)

;The load of the library = the sum of the module edits
GLXLOD==:001137		;Sum of GLX module edits

;Following are Module edit definitions.  Each line should appear
;as:

; GLX MOD,EDT,LOD,GCO,WHO,DATE,NOTE

;Where:	MOD	is 3 character module abbreviation
;
;	EDT	is Edit level for module (must match module)
;
;	LOD	The GLXLOD sum after application of the edit
;
;	GCO	The Galaxy Change Order number (0 if no GCO)
;
;	WHO	initials of person who installed this edit
;
;	DATE	date edit was installed
;
;	NOTE	a one line note to be displayed when the module is assembled
;		(e.g. GLX FOO,15,PJT,19-Nov-78,? Requires New GLXSCN
;		 would cause "? Requires New GLXSCN" to be printed
;		 when GLXFOO is assembled)

;When Marking and edit for a module, Just put ";;" before the
;existing edit information to keep it as a comment.  Then insert the
;new edit information on the line preceeding the line just commented.
;The VEREDT editor does this all for you

DEFINE MODULES <

;;GLXLOD 001137
;;		ASCIZ needs to follow Prologue in order to prevent 
;;		Questionable error during assembly.
GLX COM,55,1137,1528,VD, 6-Dec-82,


;;GLXLOD 001136
;;		Fix copyright.
;;GLX COM,54,1136,1528,DEK,18-Nov-82,


;;GLXLOD 001135
;;		Don't update number of pages when checkpointing.
GLX FIL,104,1135,1495,DEK,20-Aug-82,


;;GLXLOD 001134
;;		Don't smash creation date of files when doing renames
;;GLX FIL,103,1134,1480,DPM, 6-Aug-82,


;;GLXLOD 001133
;;		Fix 2 problems dealing with command scanning...  (on the 10)
;;		Save ACs before entering K%TXTI in case we need to interrupt the processing
;;		then restore the ACs if we do need to interrupt.
;;		During the interrupt code, check for a ^U and the set some of the pointers
;;		to reflect the true state (one simular to an initial state)
GLX SCN,74,1133,1456,DEK,22-Jul-82,


;;GLXLOD 001132
;;		Fix bogus and multiple definitions of SZ.BUF and SZ.OBF.
;;GLX FIL,102,1132,1427,, 8-Jul-82,

GLX MAC,234,1132,1427,, 8-Jul-82,


;;GLXLOD 001130
;;		Insure all packets get received by setting MSGFLG early.
GLX IPC,64,1130,1394,DPM,22-Jun-82,


;;GLXLOD 001127
;;		Clear junk in AC so unprived user doesn't get IPCF message
;;		priv bits set after MRECV.
;;GLX IPC,63,1127,1372,DPM, 7-Jun-82,


;;GLXLOD 001126
;;		Make GLXSCN-10 handle CM%NSF
;;GLX MAC,233,1126,1371,DPM, 7-Jun-82,

;;GLX SCN,73,1126,1371,DPM, 7-Jun-82,


;;GLXLOD 001124
;;		Interrupt level stack too small. Increase from 30 to 50 words.
;;GLX MAC,232,1124,1243,TJW, 3-Mar-82,


;;GLXLOD 001123
;;		Remove IJU stopcode when a zero PPN is encountered
GLX TXT,51,1123,1216,DPM,12-Feb-82,


;;GLXLOD 001122
;;		FNDLST was modified to not stopcode but to just return
;;		an error. However, no-one ever checks to see if the
;;		call to FNDLST suceeded or not which could cause all sorts
;;		of bad things to happen. Add a check after each call to
;;		check for good'ness.
GLX LNK,11,1122,0,AWC,29-Jan-82,


;;GLXLOD 001121
;;		Define TOPS-10 PC flags.
;;GLX MAC,231,1121,1188,DPM,20-Jan-82,


;;GLXLOD 001120
;;		Invent routine .CPUTY to return CPU type.
;;GLX COM,53,1120,1187,DPM,20-Jan-82,

;;GLX MAC,230,1120,1187,DPM,20-Jan-82,


;;GLXLOD 001116
;;		Dont reset PT.ADR when restarting, so GLXMEM doesnt stopcode.
GLX MEM,27,1116,0,WSM,19-Jan-82,


;;GLXLOD 001115
;;		Make Date/time terminators work.
;;GLX SCN,72,1115,1176,NT,13-Jan-82,


;;GLXLOD 001114
;;		Remove I%RLIM and references to MEMLIM since the new
;;		PFH doesn't require us to set our physical limits.
GLX INT,105,1114,1167,DPM,11-Jan-82,

;;GLX MAC,227,1114,1167,DPM,11-Jan-82,

;;GLX MEM,26,1114,1167,DPM,11-Jan-82,


;;GLXLOD 001111
;;		Fix handling of recursive stopcodes.
;;GLX COM,52,1111,0,WSM, 6-Jan-82,

;;GLX INT,104,1111,0,WSM, 6-Jan-82,


;;GLXLOD 001107
;;		Define symbols .CHLAB ("<") and .CHRAB (">").
;;		Make lots of global symbols local.
;;GLX MAC,226,1107,1136,DPM, 4-Jan-82,


;;GLXLOD 001106
;;		Made S%DATI routines common to the -20 as well as the -10.
;;GLX COM,51,1106,1112,NT,29-Dec-81,

;;GLX INT,103,1106,1112,NT,29-Dec-81,

;;GLX MAC,225,1106,1112,NT,29-Dec-81,

;;GLX SCN,71,1106,1112,NT,29-Dec-81,


;;GLXLOD 001102
;;		Remove reference to old PFH symbols, and fix problem of M%CLNC not
;;		getting called enought to reduce core size.
;;GLX MAC,224,1102,0,WSM,28-Dec-81,

;;GLX MEM,25,1102,0,WSM,28-Dec-81,


;;GLXLOD 001100
;;		Delete file attribute block symbols in GLXFIL. They
;;		already exist in GLXMAC.
;;GLX FIL,101,1100,1115,DPM,22-Dec-81,


;;GLXLOD 001077
;;		Clean up and simplify M%IPRM. Allow it to give error returns.
;;GLX IPC,62,1077,0,DPM,15-Dec-81,

;;GLX MAC,223,1077,0,DPM,15-Dec-81,

;;GLX MEM,24,1077,0,DPM,15-Dec-81,


;;GLXLOD 001074
;;		Remove GLXLNK stopcodes and replace them with error returns.
;;		The new error codes are ERENF$ (Linked list entry not found)
;;		and ERNSL$ (No such linked list).
;;GLX LNK,10,1074,1090,DPM, 7-Dec-81,

;;GLX MAC,222,1074,1090,DPM, 7-Dec-81,


;;GLXLOD 001072
;;		Remove GLXPFH. Memorize current VIRT and PHY core limits
;;		at GLXMEM initialization time. Set the PHY core limit low
;;		and request a timer interrupt to invoke the system PFH.
;;		Add new GLXINT routine I%RLIM to reset the core limits. Make
;;		I%EXIT cann I%RLIM for free.
;;GLX INT,102,1072,1088,DPM, 7-Dec-81,

;;GLX MAC,221,1072,1088,DPM, 7-Dec-81,

;;GLX MEM,23,1072,1088,DPM, 7-Dec-81,


;;GLXLOD 001067
;;		Add a missing POPJ P,. Clean up TOPS-20 file accsss
;;		checking. Don't checkpoint a file at INTREL. There
;;		might not be a valid IFN setup.
;;GLX FIL,100,1067,1060,DPM,23-Nov-81,


;;GLXLOD 001066
;;		Don't turn PSI on and off around effective address
;;		calculations. This save several hundred UUOs typically.
;;GLX TXT,50,1066,1,NT,20-Nov-81,


;;GLXLOD 001065
;;		Fix FNDNAM bug and make sure we always return the pid in S1
;;GLX IPC,61,1065,0,AWC,14-Sep-81,


;;GLXLOD 001064
;;		Remove stopcode and insert CEI error for
;;		I%ION and I%IOFF.
;;		CEI = Can't enable/disable interrupt system
;;GLX INT,101,1064,0,AWC,10-Sep-81,

;;GLX MAC,220,1064,0,AWC,10-Sep-81,


;;GLXLOD 001062
;;		At CMRAT2+7 jump off to put the character back into the atom
;;		buffer before returning
;;GLX SCN,70,1062,0,AWC, 9-Sep-81,


;;GLXLOD 001061
;;		Do not GETTAB the WATCH bits, just clear them.
;;GLX INT,100,1061,0,AWC,20-Aug-81,


;;GLXLOD 001060
;;		Do not initialize the entry vector if already initialized.
GLX INI,21,1060,0,DEK,13-Jul-81,


;;GLXLOD 001057
;;		Fix race condition where character can be lost due to interrupt processing.
GLX KBD,56,1057,0,DEK, 8-Jul-81,


;;GLXLOD 001056
;;		Correct the length of FILOP., LOOKUP/ENTER/RENAME and
;;		PATH. UUO blocks.
;;GLX FIL,77,1056,0,DPM,24-Jun-81,


;;GLXLOD 001055
;;		MAKE SURE THAT K%INIT ALWAYS CALLS MAKBUF ON THE -20.
;;		ALSO MAKE SURE THAT K%FLSH HAS CORRECT CHARACTER COUNT
;;		WHEN SOUT'ING.
;;GLX KBD,55,1054,0,PGW,23-JUN-81,


;;GLXLOD 001054
;;		Try to fix date/time scanning
;;		Make [,] return logged in PPN
;;GLX SCN,67,1054,0,DEK,22-Jun-81,


;;GLXLOD 001053
;;		Prevent race where AC 'P' may not have a good PDL
;;		pointer and we get an interrupt. Turn off the PSI
;;		system before doing effective address calculation
;;		and turn it back on when we're done.
;;GLX TXT,47,1053,0,DPM,15-Jun-81,


;;GLXLOD 001052
;;		Fix a bad byte pointer at MAKPTR+ a few that caused lost
;;		buffers.
;;GLX KBD,54,1052,0,DPM,15-Jun-81,


;;GLXLOD 001051
;;		Add support for setting file attributes.
;;GLX FIL,76,1051,0,DPM,27-May-81,

;;GLX MAC,217,1051,0,DPM,27-May-81,


;;GLXLOD 001047
;;		Make $SAVE work on indexed variables
;;GLX MAC,216,1047,0,AWC,26-May-81,


;;GLXLOD 001046
;;		Correct TOPS-10 break character set.
;;GLX KBD,53,1046,0,DPM,22-May-81,


;;GLXLOD 001045
;;		Turn off WATCH when we detach from FRCLIN.
;;GLX INT,77,1045,0,DPM,19-May-81,


;;GLXLOD 001044
;;		Fix up PDL overflow trapping on the -20.
;;GLX INT,76,1044,0,DPM,15-May-81,


;;GLXLOD 001043
;;		Don't allow .ZCHNK to zero the ACs.
;;GLX COM,50,1043,0,DPM,14-May-81,


;;GLXLOD 001042
;;		Add a field in the FOBs for protection codes, and support
;;		physical-only RENAMEs.
;;GLX FIL,75,1042,0,DPM,12-May-81,

;;GLX MAC,215,1042,0,DPM,12-May-81,


;;GLXLOD 001040
;;		Add FRB.FL flag word for F%REN arg block
;;GLX FIL,74,1040,0,AWC, 4-May-81,

;;GLX MAC,214,1040,0,AWC, 4-May-81,


;;GLXLOD 001036
;;		Add FB.PHY to allow physical-only OPENs.
;;GLX FIL,73,1036,0,DPM, 4-May-81,

;;GLX MAC,213,1036,0,DPM, 4-May-81,


;;GLXLOD 001034
;;		Fix date/time scanning on TOPS-10.
;;GLX SCN,66,1034,0,DPM, 4-May-81,


;;GLXLOD 001033
;;		Restore ACs that .STOP trashes before processing the
;;		reason ITEXT block.
;;GLX COM,47,1033,0,DPM,30-Apr-81,


;;GLXLOD 001032
;;		Clean up messy TOPS-10 user name output in ^R display.
;;GLX TXT,46,1032,0,DPM,30-Apr-81,


;;GLXLOD 001031
;;		Map a couple more LOOKUP/ENTER/RENAME error codes.
;;GLX FIL,72,1031,0,DPM,30-Apr-81,

;;GLX MAC,212,1031,0,DPM,30-Apr-81,


;;GLXLOD 001027
;;		Fix some more PFH bugs...
;;GLX MEM,22,1027,0,TARL,17-Apr-81,

GLX PFH,16,1027,0,TARL,17-Apr-81,


;;GLXLOD 001025
;;		Have Tarl fix all remaining PFH bugs...
;;GLX MEM,21,1025,0,AWC,16-Apr-81,

;;GLX PFH,15,1025,0,AWC,16-Apr-81,


;;GLXLOD 001023
;;		Set .JBHRL (RH) so DDT will believe .JBHSO
;;GLX INI,20,1023,0,DEK,15-Apr-81,


;;GLXLOD 001022
;;		Rewrite for TOPS20 support.
;;GLX INI,17,1022,0,DEK, 6-Apr-81,


;;GLXLOD 001021
;;		Add END GLXOTS	statement so we can initialize
GLX OTS,7,1021,0,DEK, 6-Apr-81,


;;GLXLOD 001020
;;		Add part of missing HOSS edit (SPR #20-14262) to allow in-your-behalf
;;		renames and deletes work correctly.
;;GLX FIL,71,1020,0,DPM, 3-Apr-81,


;;GLXLOD 001017
;;		Fixed date/time parsing by delimiting date and time
;;		with space.
;;GLX SCN,65,1017,0,DLC, 2-Apr-81,


;;GLXLOD 001016
;;		Allow colon to be used to separate date and time
;;GLX SCN,64,1016,0,DEK, 1-Apr-81,


;;GLXLOD 001015
;;		Fix QAR 10-05695; F%CHKP lost data.
;;GLX FIL,70,1015,0,AWC,30-Mar-81,


;;GLXLOD 001014
;;		Get rid of fake colon for date/time scanner
;;GLX SCN,63,1014,0,DEK,29-Mar-81,


;;GLXLOD 001013
;;		Change $RETT to POPJ at ACTQ.3+5 since entry
;;		vector is not yet set up.
;;GLX INI,16,1013,0,DEK,29-Mar-81,


;;GLXLOD 001012
;;		More work to make GLXSCN work under MIC.
;;GLX KBD,52,1012,0,DPM,26-Mar-81,


;;GLXLOD 001011
;;		Rearrange AC usage at CMND.2 to avoid TOPS20 release 4 bug where COMND
;;		JSYS clobbers T2.
;;GLX SCN,62,1011,0,DLC,24-Mar-81,


;;GLXLOD 001010
;;		TOPS-20 compatibility.  Remove references to .JBHGH and CORG.
;;		Replace with .JBHSO
;;GLX INI,15,1010,0,DEK,21-Mar-81,


;;GLXLOD 001007
;;		Enter TSG fixes for SPRs 20-14773 & 20-14728
;;GLX FIL,67,1007,0,AWC,18-Mar-81,


;;GLXLOD 001006
;;		Change GLXIPC to use DEBUGW instead of .JBOPS
;;		Change GLXFIL to move the tops10 conditional for F%INFO to the right place
;;GLX FIL,66,1006,0,DAK,13-Mar-81,

;;GLX IPC,60,1006,0,DAK,13-Mar-81,


;;GLXLOD 001004
;;		Fix Stevens QAR on memory management loop. Allow calls to
;;		M%GMEM of greater then CNK.PM*PAGSIZ words.
;;GLX MEM,20,1004,0,AWC,11-Mar-81,


;;GLXLOD 001003
;;		Have the PDL overflow trap set up a PDL before stopcoding.
;;		Have the stopcode routine set up its own PDL since it never
;;		knows how much room is on the stack.
;;GLX COM,46,1003,0,DPM, 9-Mar-81,

;;GLX INT,75,1003,0,DPM, 9-Mar-81,


;;GLXLOD 001001
;;		Comment out the reference to the MONSYM version number until MONSYM has
;;		one to reference.
;;GLX MAC,211,1001,0,DPM, 3-Mar-81,


;;GLXLOD 001000
;;		Make GLXLIB reentrant once again (broken by previous PFH changes).
;;GLX MEM,17,1000,0,TARL, 3-Mar-81,

;;GLX PFH,14,1000,0,TARL, 3-Mar-81,


;;GLXLOD 000776
;;		Add future time and past time to make MIDNIGHT (among other things) work
;;GLX MAC,210,776,0,DEK,25-Feb-81,

;;GLX SCN,61,776,0,DEK,25-Feb-81,


;;GLXLOD 000774
;;		Change F%INFO to return correct creation date on TOPS10.
;;GLX FIL,65,774,0,DEK,24-Feb-81,


;;GLXLOD 000773
;;		Add DEVSIZ to get disk buffer length.
;;GLX FIL,64,773,0,AWC,17-Feb-81,


;;GLXLOD 000772
;;		Add code to make GLXPFH a real page fault handler.
;;GLX INT,74,772,0,TARL,14-Feb-81,

;;GLX MEM,16,772,0,TARL,14-Feb-81,

;;GLX PFH,13,772,0,TARL,14-Feb-81,


;;GLXLOD 000767
;;		Fix IPRM.1 to do the correct thing for both TOPS10 and TOPS20
;;GLX IPC,57,767,0,TJW, 5-Feb-81,


;;GLXLOD 000766
;;		Fix a bug in SNDSYS which caused the library to look at the
;;		wrong message when processing messages from SYSTEM[IPCC]. This
;;		is because the special PID index for [IPCC] is 0 and the recieve
;;		code was just loading the index (which is 0 for non system messages)
;;		and doing the compare. Since they were equal, SNDSYS assumed it had
;;		recieved the correct message, but in fact it had not.
;;GLX IPC,56,766,0,AWC, 4-Feb-81,


;;GLXLOD 000765
;;		Add .POPJ1 to the entry vector to allow SKIP returns.
;;GLX COM,45,765,0,DPM, 2-Feb-81,

;;GLX MAC,207,765,0,DPM, 2-Feb-81,


;;GLXLOD 000763
;;		Fix bug in $TEXT macros that would not allow a decimal number
;;		to be used as a field width (missing ^D).
;;GLX MAC,206,763,0,DPM,16-Jan-81,


;;GLXLOD 000762
;;		Prevent IFN, BPN, and ILM stopcodes caused by routine STAC.
;;GLX IPC,55,762,0,DPM,15-Jan-81,


;;GLXLOD 000761
;;		Delete second definition of the FLD macro. It was
;;		incorrect anyway.
;;GLX MAC,205,761,0,DPM,12-Jan-81,


;;GLXLOD 000760
;;		Turn off PSI interrupts at the start of stopcode processing
;;		and turn them back on when completed.
;;GLX COM,44,760,0,DPM,12-Jan-81,


;;GLXLOD 000757
;;		Only type out "% GLXIPC alternate..." when debugging.
;;GLX IPC,54,757,0,DPM,12-Jan-81,


;;GLXLOD 000756
;;		Call STKVAR and TRVAR with a PUSHJ, not a JSP
;;		so it will work in a non-zero section.
;;GLX COM,43,756,0,DPM,12-Jan-81,

;;GLX MAC,204,756,0,DPM,12-Jan-81,


;;GLXLOD 000754
;;		Expand file and I/O error codes and messages for TOPS-10.
;;GLX FIL,63,754,0,DPM, 9-Jan-81,

;;GLX MAC,203,754,0,DPM, 9-Jan-81,


;;GLXLOD 000752
;;		Move linked list initialization above IPCF initialization
;;GLX INT,73,752,0,AWC, 9-Jan-81,


;;GLXLOD 000751
;;		Fix a problem with SNDSYS flushing the IPCF queue when
;;		searching for the response from [SYSTEM]IPCC
;;GLX IPC,53,751,0,AWC, 9-Jan-81,


;;GLXLOD 000750
;;		Add new bit IB bit (IB.NPF) to allow a program to disable GLXPFH.
;;GLX INT,72,750,0,DPM, 6-Jan-81,

;;GLX MAC,202,750,0,DPM, 6-Jan-81,

;;GLX MEM,15,750,0,DPM, 6-Jan-81,


;;GLXLOD 000745
;;		Add missing PORTALs and cosmetic fixes in stopcode output.
;;GLX COM,42,745,0,DPM,29-Dec-80,

;;GLX INT,71,745,0,DPM,29-Dec-80,

;;GLX TXT,45,745,0,DPM,29-Dec-80,


;;GLXLOD 000742
;;		SEE EDIT 11
;;GLX PFH,12,742,0,DPM,22-Dec-80,


;;GLXLOD 000741
;;		*** Restructure GLXLIB ***
;;		The main thrust of these edits was to structure GLXLIB in such
;;		a way to make it wasy for a user to cause his/her/its program
;;		to GETSEG or link the library without having to recompile either
;;		the user program, GLXMAC or the library. Other nice side effects
;;		include allowing the library to be linked with user code in
;;		the high segment, and structuring the entry vector so that it
;;		will support the library living in a non-zero section. Note that
;;		a lot of library work is still required for extended addressing
;;		to work at all. Changing the entry vector now merely prevents an
;;		incompatible change in the future. This is in no way, a
;;		commitment by Digital Equipment Corporation to provide extended
;;		addressing facilities in the library. Due to the new style
;;		entry vector, a user program need not be recompiled or relinked
;;		should the high segment origin move. The following changes
;;		were made:
;;		GLXMAC	1) Rework PROLOG macro completely.
;;			2) .NODDT the following symbols:
;;				$CALL	$RET
;;				$RETT	$RETF
;;				$RETIT	$RETIF
;;				JUMPT	JUMPF
;;				SKIPT	SKIPF
;;			3) Remove CORG, DORG and VORG symbols and make code
;;			   smart snough to figure the stuff out. This allows
;;			   the PSECT origins set by LINK switches really
;;			   flexible.
;;			4) Define $RETE so that a PUSHJ gets generated
;;			   instead of a JSP. This will allow extended
;;			   addressing to work someday.
;;		GLXCOM	1) Call .RETE via a PUSHJ instead of a JSP. This
;;			   allows extended addressing to be used someday.
;;			2) GLXVRS is no longer external.
;;			3) Define global symbols CRSHAC (TOPS-10) and BUGACS
;;			   (TOPS-20) to point to .SACS. This causes FILDDT
;;			   to automatically load the ACs from .SACS.
;;		GLXLNK	The PHASE/DEPHASE stuff around the linked list offset
;;			definitions confused MACRO (and me) when the library
;;			was TWOSEG'ed. Remove the PHASE/DEPHASE and redefine
;;			the symbols another way.
;;		GLXINI	1) Rework CDO macro to generate a table that kinda
;;			   parallels the high segment entry vector and call
;;			   it ENTVEC just tocunfuse things. This is required
;;			   for extended addressing and saves and incompatible
;;			   change later on.
;;			2) If the program is execute-only do a physical-only
;;			   GETSEG.
;;		GLXINT	1) Define I%INIT in GLXINT. Note that it's also
;;			   defined in GLXINI, but since you don't link both,
;;			   it doesn't matter.
;;			2) Remove definition for I%INI1 since it is no longer
;;			   needed.
;;			3) Once again, set up the APR trap here. Remove I%APRT
;;			   since it is no longer needed.
;;			4) Add routine EXOCHK to check for execute-only
;;			   operation and set global flag EXOFLG. Currently,
;;			   the only place this is checked is in the memory
;;			   manager/page fault handler.
;;			5) Move data page creation out of here and into
;;			   GLXOTS. It's not needed if the library is linked
;;			   with the user program.
;;			6) Move the compatibility check out of here and into
;;			   GLXOTS. Anyone who links the library in with
;;			   their program should never have to worry about
;;			   version skews.
;;			7) Take call to SETPFH out of here and make it part
;;			   of the memory manager initialization code.
;;		GLXMEM	1) Do PFH initialization here instead of in PFH.
;;			   This includes mapping core and marking all symbol
;;			   table pages.
;;			2) Create a non-sharable page and BLT the PFH into it.
;;			3) As part of PFH setup, add new routine PFHADR to
;;			    tell the page fault handler where some of the
;;			    memory manager data base lives.
;;			4) Add PFHRET kludge to allow the page fault handler
;;			   to return to the library when execute-only is in
;;			   effect.
;;			5) Copy NODDT routine here from PFH.
;;		GLXOTS	1) Do compatibility check here instead of GLXINT.
;;			2) Create data pages here instead of GLXINT.
;;			3) Rework CDO macro. Don't PUSHJ to the unimplemented
;;			   stopcode since this may not work if execute-only.
;;			4) Create new stopcodes and global symbols so that
;;			   any module may call them. The stopcodes are:
;;			  .UNRTN::$STOP(UNR,Unimplemented routine executed),
;;			  .OBRTN::$STOP(OBR,Obsolete routine executed), and
;;			  .OORTN::$STOP(OOR,OTS only routine executed).
;;		GLXPFH	1) Remove PFHDAT PSECT. This is no longer needed since
;;			   PFH is moved to a non-sharable page separate from
;;			   the rest of the library.
;;			2) Put all the initialization code into GLXMEM.
;;			3) Since relocatable PSECTs aren't implemented, PFH
;;			   can't directly reference memory manager data from
;;			   within the PHASEd code. All references must be
;;			   calculated. This is only a pain for PAGTBL
;;			   references. All others are indirect.
;;			4) Use the PFHRET kludge in GLXMEM to return to
;;			   execute-only library.
;;			5) Stopcodes in PFH don't work and probably could
;;			   never be made to. On catastrophic errors, just
;;			   print a simple message and die (see $DIE macro).
;;GLX COM,41,741,0,DPM,22-Dec-80,

;;GLX INI,14,741,0,DPM,22-Dec-80,

;;GLX INT,70,741,0,DPM,22-Dec-80,

;;GLX LNK,7,741,0,DPM,22-Dec-80,

;;GLX MAC,201,741,0,DPM,22-Dec-80,

;;GLX MEM,14,741,0,DPM,22-Dec-80,

;;GLX OTS,6,741,0,DPM,22-Dec-80,

;;GLX PFH,11,741,0,DPM,22-Dec-80,


;;GLXLOD 000731
;;		Prevent PFH stopcodes by moving PFHACS into the PFHDAT PSECT.
;;GLX PFH,10,731,0,DPM,11-Dec-80,


;;GLXLOD 000730
;;		Allow job numbers to be used for PIDs. Invent new
;;		bit in the IB flag word and code in GLXIPC to support
;;		this functionality. With this change, no Galaxy
;;		component will be dependant on SYSINF (except when
;;		debugging).
;;GLX IPC,52,730,0,DPM,11-Dec-80,

;;GLX MAC,200,730,0,DPM,11-Dec-80,


;;GLXLOD 000726
;;		Set Operator priv for messages received from system components when debugging
;;GLX IPC,51,726,0,PJT,11-Dec-80,


;;GLXLOD 000725
;;		Yet another attempt to make the Galaxy scanner work under MIC.
;;GLX KBD,51,725,0,DPM, 9-Dec-80,


;;GLXLOD 000724
;;		*** Make GLXLIB run execute-only ***
;;		This massive edit will break all existing programs that use
;;		the library, even if execute-only is turned off. This occurs
;;		for several reasons; Data pages are not merged, but created
;;		on the fly; interrupt routines are not entered via a JSR. The
;;		The following changes were made:
;;		GLXMAC	1) Add "not-known-to-DDT" hardware mnemonics. GLXLIB
;;			   needs the PORTAL definition.
;;			2) Remove indirection from entry vector references.
;;			3) Change $BGINT so it does a $CALL instead of a JSR.
;;		GLXINT	1) Add new routine CREDAT to create the library's data
;;			   pages (if they don't already exist).
;;			2) Add new entry point I%APRT for APR traps. Note that
;;			   this MUST be set up by GLXINI prior to calling
;;			   I%INI1.
;;		GLXOTS	Change entry vectors to include PORTAL instructions.
;;		GLXINI  1) Set up APR trap prior to call to I%INI1.
;;			2) Remove code to merge GLXLIB data pages.
;;		GLXPFH	Set up PFHBEG on a call to SETPFH.
;;		GLXCOM	Add PORTAL instructions to all return points within
;;			the many AC/variable save co-routines. This includes
;;			the STKVAR and TRVAR routines, and calls to the user
;;			error processor (pointed to by IB.ERR).
;;GLX COM,40,724,0,DPM, 2-Dec-80,

;;GLX INI,13,724,0,DPM, 2-Dec-80,

;;GLX INT,67,724,0,DPM, 2-Dec-80,

;;GLX MAC,177,724,0,DPM, 2-Dec-80,

;;GLX OTS,5,724,0,DPM, 2-Dec-80,

;;GLX PFH,7,724,0,DPM, 2-Dec-80,


;;GLXLOD 000716
;;		Too many people don't know what their doing. Even more believe
;;		the TOPS-10 monitor calls manual. GLXLIB is one of several
;;		programs that don't know how to read the local date/time
;;		correctly. Do it the right way.
;;GLX INT,66,716,0,DPM,22-Nov-80,


;;GLXLOD 000715
;;		Globalize FTFTS flag defined in GALCNF
;;GLX MAC,176,715,0,PJT,21-Nov-80,


;;GLXLOD 000714
;;		Change PROLOG macro to .REQUEST REL:GLXINI instead of getting
;;		it from DSK:. This is consistant with all other TOPS-10 cusps.
;;GLX MAC,175,714,0,DPM,21-Nov-80,


;;GLXLOD 000713
;;		Delete CSF stopcode in WRTBUF and just .RETF (SPR 20-14724)
;;GLX FIL,62,713,0,AWC,19-Nov-80,


;;GLXLOD 000712
;;		Fix XCMTOK so it understands TOPS20-style string pointers.
;;GLX SCN,60,712,0,DLC, 9-Nov-80,


;;GLXLOD 000711
;;		Fix XCMTAD so it handles date/time fields before end of line. [QAR 10-4894]
;;GLX SCN,57,711,0,PJT, 6-Nov-80,


;;GLXLOD 000710
;;		Fix indirect files, make continuation lines in them work, etc.
;;GLX SCN,56,710,0,DLC, 6-Nov-80,


;;GLXLOD 000707
;;		Remove unwanted LALL [QAR 10-4899]
;;GLX MAC,174,707,0,PJT, 5-Nov-80,


;;GLXLOD 000706
;;		Move argument block information including data types from
;;		ORNMAC and QSRMAC to GLXMAC.
;;GLX MAC,173,706,0,DEK, 3-Nov-80,


;;GLXLOD 000705
;;		Add ac FB to the FB$CHN check in F%REL.
;;GLX FIL,61,705,0,AWC,31-Oct-80,


;;GLXLOD 000704
;;		On TOPS20, if the CHKAC fails, return 'protection failure'
;;		instead of stopcoding.
;;GLX FIL,60,704,0,AWC,29-Oct-80,


;;GLXLOD 000703
;;		Define error code ERFIO$ for "file is offline".
;;GLX MAC,172,703,0,DLC,21-Oct-80,


;;GLXLOD 000702
;;		Remove edit 161 which declared entry vector points to be external.
;;GLX MAC,171,702,0,PJT,16-Oct-80,


;;GLXLOD 000701
;;		Only dump ACs and stack if IB.STP set.
;;GLX COM,37,701,0,DPM,10-Oct-80,


;;GLXLOD 000700
;;		Fix clobberage of S1 at K%OPEN which caused TTY to always be
;;		opened image mode on TOPS20.
;;GLX KBD,50,700,0,DLC, 2-Oct-80,


;;GLXLOD 000677
;;		Changed I%SLP to accept TOPS10 hiber bits and
;;		could therefore change K%BIN to do I%SLP instead
;;		of HIBER.  This is to ultimatly fix OPR to wake
;;		up on the 10 due to terminal inactivity.
;;GLX INT,65,677,0,DEK, 2-Oct-80,

;;GLX KBD,47,677,0,DEK, 2-Oct-80,


;;GLXLOD 000675
;;		Delete IB.DET (GLXLIB defaults to detach if started on FRCLIN)
;;GLX MAC,170,675,0,AWC,30-Sep-80,


;;GLXLOD 000674
;;		Fix 2 bugs... Issue $FATAL error if no IPCF privs and
;;		SYSINF not running; Do not send $FATAL errors to ORION.
;;GLX COM,36,674,0,AWC,26-Sep-80,

;;GLX IPC,50,674,0,AWC,26-Sep-80,


;;GLXLOD 000672
;;		Delete the code to reset the terminal mode
;;		done in SETVT5
;;GLX KBD,46,672,0,AWC,23-Sep-80,


;;GLXLOD 000671
;;		Add new bit in the IB (IB.DET) to force job to
;;		detach if started up on FRCLIN.
;;GLX INT,64,671,0,DPM,22-Sep-80,

;;GLX MAC,167,671,0,DPM,22-Sep-80,


;;GLXLOD 000667
;;		Restore original meaning of BATFLG to mean BATCH only.  Always request
;;		character instead of doing hiber in K%BIN if BATFLG is set.
;;GLX KBD,45,667,0,PJT,22-Sep-80,


;;GLXLOD 000666
;;		Fix bugs in K%OPEN for TOPS20 which caused CGT stopcode
;;GLX KBD,44,666,0,PJT,22-Sep-80,


;;GLXLOD 000665
;;		Don't try to page out symbols in the high seg.
;;GLX PFH,6,665,0,DPM,22-Sep-80,


;;GLXLOD 000664
;;		Make TYPRMT a noop if output designator (.CMIOJ) not the TTY.
;;GLX SCN,55,664,0,DLC,19-Sep-80,


;;GLXLOD 000663
;;		At TXTL.4, if TXTINP fails, update caller's arg block before returning.
;;GLX KBD,43,663,0,DLC,19-Sep-80,


;;GLXLOD 000662
;;		Always set a terminal type in K%INIT to prevent ILM stopcodes
;;		when editing characters are typed with no terminal type set.
;;GLX KBD,42,662,0,PJT,19-Sep-80,


;;GLXLOD 000661
;;		Make K%TXTI use pointer in .RDIOJ when RD%JFN in .RDFLG is not set
;;GLX KBD,41,661,0,PJT,19-Sep-80,


;;GLXLOD 000660
;;		Remove edit 25 which caused K%BIN to sleep when terminal is a PTY.
;;		This caused IPCF interupts on TOPS10 to be delayed until a character
;;		was typed.
;;GLX KBD,40,660,0,PJT,19-Sep-80,


;;GLXLOD 000657
;;		Repair edit 54 to allow F%REW to win for short files instead of returning
;;		EOF.
;;GLX FIL,57,657,0,PJT,17-Sep-80,


;;GLXLOD 000656
;;		[QAR 10-4626] Fix I%TIMR so that .TIMBF function checks the
;;		PC word correctly.
;;GLX INT,63,656,0,PJT,16-Sep-80,


;;GLXLOD 000655
;;		Add definition for .CMFLT and .CMTAD
;;GLX MAC,166,655,0,PJT,16-Sep-80,


;;GLXLOD 000654
;;		Repair edit 33 so that it sleeps until output is done.
;;GLX KBD,37,654,0,PJT,16-Sep-80,


;;GLXLOD 000653
;;		Add support for TOPS-10's VT61 TTYs.
;;GLX KBD,36,653,0,DPM,15-Sep-80,

;;GLX MAC,165,653,0,DPM,15-Sep-80,


;;GLXLOD 000651
;;		When a ^H is typed (after the first character in a line),
;;		handle it like the TOPS-10 monitor does.
;;GLX KBD,35,651,0,DPM,12-Sep-80,


;;GLXLOD 000650
;;		Don't set up the page fault handler if the user doesn't
;;		have virtual memory privs. Determine this by GETTABing
;;		the user's maximum limits (table .GTMVL) and checking
;;		this value.
;;GLX PFH,5,650,0,DPM,11-Sep-80,


;;GLXLOD 000647
;;		On TOPS-10, don't trash AC 'TF' on an APR trap.
;;GLX INT,62,647,0,DPM,11-Sep-80,


;;GLXLOD 000646
;;		Change the meaning of BATFLG to mean any random PTY, not
;;		just a Batch PTY.
;;GLX KBD,34,646,0,DPM, 8-Sep-80,


;;GLXLOD 000645
;;		Modify edit 32 so that we don't loop continuously , but
;;		wait a tick or two between TRMOP.'s.
;;GLX KBD,33,645,0,AWC,25-Aug-80,


;;GLXLOD 000644
;;		Fix SFD printer to not type useless commas.
;;GLX TXT,44,644,0,DLC,24-Aug-80,


;;GLXLOD 000643
;;		Allow output to spooled devices;  after all, they are disks.
;;GLX FIL,56,643,0,DLC,22-Aug-80,


;;GLXLOD 000642
;;		On TOPS20, have M%INIT start scanning from c(.JBFF), not page zero.
;;GLX MEM,13,642,0,DLC,22-Aug-80,


;;GLXLOD 000641
;;		Add .OTFAL and rename .OTXFR to .OTFTS
;;GLX MAC,164,641,0,PJT,20-Aug-80,


;;GLXLOD 000640
;;		Don't print null paths (as in [10,3572,,,,,])
;;GLX TXT,43,640,0,DLC,15-Aug-80,


;;GLXLOD 000637
;;		.REQUEST library if impure instead of .REQUIRE.
;;GLX MAC,163,637,0,DLC,15-Aug-80,


;;GLXLOD 000636
;;		At TYPRMT, don't type CRLF unless terminal not at left margin.
;;GLX SCN,54,636,0,DLC,15-Aug-80,


;;GLXLOD 000635
;;		On TOPS10, make K%TPOS wait for all terminal output to cease
;;		before checking horizontal position.
;;GLX KBD,32,635,0,DLC,15-Aug-80,


;;GLXLOD 000634
;;		Move $DATA statements outside of code so that IMPURE GLXPFH doesn't blow up
;;GLX PFH,4,634,0,DLC,15-Aug-80,


;;GLXLOD 000633
;;		Add new routines K%BUFF, K%FLSH, and K%OPEN.
;;GLX MAC,162,633,0,PGW,11-Aug-80,


;;GLXLOD 000632
;;		Change K%INIT to open the TTY on the -20 if IB.OCT
;;		is lit.   Also save the channel or JFN of the TTY
;;		and the UDX or device designator in global storage.
;;		Add entries K%BUFF and K%FLSH for buffering output.
;;		Add K%OPEN routine.
;;GLX KBD,31,632,0,PGW,11-Aug-80,


;;GLXLOD 000631
;;		Change RETMEM to light the PT.USE bit as well as clearing
;;		the PT.INI bit.  This is to avoid stopcoding with
;;		BPN when we do the M%RMEM.
;;GLX PFH,3,631,0,PGW,8-Aug-80,


;;GLXLOD 000630
;;		Zero out our own $DATA space for GLXKBD.
;;GLX KBD,30,630,0,PGW,7-Aug-80,


;;GLXLOD 000627
;;		Zero out $DATA space for GLXSCN.
;;GLX SCN,53,627,0,PGW,7-Aug-80,


;;GLXLOD 000626
;;		Zero out our $DATA space like everyone else.
;;GLX COM,35,626,0,PGW,7-Aug-80,


;;GLXLOD 000625
;;		Remove definition of D%BEG from GLXOTS since we don't
;;		need it any more
;;GLX OTS,4,625,0,PGW,7-Aug-80,


;;GLXLOD 000624
;;		Make GLXLNK zero out its $DATA space the same way all
;;		the other modules do.
;;GLX LNK,6,624,0,PGW,7-Aug-80,


;;GLXLOD 000623
;;		Make C%INIT zero out its $DATA space and not zero
;;		out individual locations.
;;GLX IPC,47,623,0,PGW,7-Aug-80,


;;GLXLOD 000622
;;		Change T%INIT to zero out its $DATA space.
;;GLX TXT,42,621,0,PGW,7-Aug-80,


;;GLXLOD 000621
;;		Change GLXFIL to zero out its own $DATA space instead of
;;		only the IFN table on initialization.
;;GLX FIL,55,621,0,PGW,7-Aug-80,


;;GLXLOD 000620
;;		Allow GLXMEM to do its own data page zeroing.  Make sure
;;		that the stuff needed for restarts is not zeroed.  Comment
;;		out the in-line zeroing that should be done at init time.
;;GLX MEM,12,620,0,PGW,7-Aug-80,


;;GLXLOD 000617
;;		Remove the CREDAT section of I%INI1.  This now allows the 
;;		individual library module to do their own $DATA initialization.
;;		We now zero our own $DATA space.  Also remove D%END.
;;GLX INT,61,617,0,PGW,7-Aug-80,


;;GLXLOD 000616
;;		SPR 20-14563 Fix F%POS loop problem. Return EOF if positioning
;;		to the last byte of the last page of a file.
;;GLX FIL,54,616,0,AWC,5-Aug-80,


;;GLXLOD 000615
;;		Make S%CMND check for ^Z as a special break character.
;;		This allows programs to exit on ^Z (TOPS-10 style
;;		program exit character).
;;GLX SCN,52,615,0,DPM,1-Aug-80,


;;GLXLOD 000614
;;		Fix bugs in I%HOST/CNVNOD so that we can run with
;;		monitors built without network support.
;;GLX INT,60,614,0,AWC,22-Jul-80,


;;GLXLOD 000613
;;		Plug security leak that allowed JACCT'ed programs to grab a
;;		private copy of GLXLIB.
;;GLX INI,12,613,0,DPM,30-Jun-80,


;;GLXLOD 000612
;;		If BATCH, do not reset keypad mode on initialization
;;GLX KBD,27,612,0,AWC,26-Jun-80,


;;GLXLOD 000611
;;		Moved the REN.2: label up 2 instructions so that the
;;		FILOP. channel is closed if it was open'd
;;GLX FIL,53,611,0,AWC,25-Jun-80,


;;GLXLOD 000610
;;		Fix a bug caused by edit 157. Make GLXINI generate global library
;;		symbols by adding a : to the ..ASGN macro definition.
;;GLX MAC,161,610,0,AWC,20-Jun-80,


;;GLXLOD 000607
;;		Define CNVNOD and fix JI.LOC to return sixbit node name
;;GLX INT,57,607,0,PJT,15-May-80,


;;GLXLOD 000606
;;		Define CNVNOD to convert node numbers to octal etc
;;		Also make JI.LOC return sixbit node name for TOPS10
;;GLX INT,56,606,0,PJT,15-May-80,


;;GLXLOD 000605
;;		Change GLXTXT to call CNVNOD to convert node numbers to octal and vice versa
;;GLX TXT,41,605,0,PJT,15-May-80,


;;GLXLOD 000604
;;		add  ji.tlc to i%jinf to return terminal physical location
;;GLX INT,55,604,0,PJT,15-May-80,


;;GLXLOD 000603
;;		Return the located node string if requested in the PIB
;;		for TOPS10. (ala TOPS20)
;;GLX IPC,46,603,0,PJT,15-May-80,


;;GLXLOD 000602
;;		define md.sop, md.rop, md.lop priv flags for the mdb and c%recv
;;GLX MAC,160,602,0,PJT,15-May-80,


;;GLXLOD 000601
;;		Fix a bug in I%TIMR when called from I%SLP
;;GLX INT,54,601,0,PJT,14-May-80,


;;GLXLOD 000600
;;		Fix a bug in T%TEXT so that default IB routine is used if users specifies
;;		no routine in call
;;GLX TXT,40,600,0,PJT,12-May-80,


;;GLXLOD 000577
;;		Fix ..ASGN definition in PROLOG macro for GLXINI if GLXPURE is off
;;GLX MAC,157,577,0,PJT,6-May-80,


;;GLXLOD 000576
;;		Fix .STKST so that it will handle skip returns
;;GLX COM,34,576,0,PJT,5-May-80,


;;GLXLOD 000575
;;		Add check to execute timer revents if requested
;;GLX INT,53,576,0,PJT,2-May-80,


;;GLXLOD 000574
;;		Remove CNTDT routine since it lives in GLXSCN with CNVDT
;;GLX TXT,37,574,0,PJT,2-May-80,


;;GLXLOD 000573
;;		Fix date/time parsing routines
;;GLX SCN,51,573,0,PJT,2-May-80,


;;GLXLOD 000572
;;		Fixed phantom reference to T4 in F%REN
;;GLX FIL,52,572,0,PJT,29-Apr-80,


;;GLXLOD 000571
;;		Delete <CRLF> pair when rubbout is seen
;;GLX KBD,26,571,0,PJT,26-Apr-80,


;;GLXLOD 000570
;;		Add I%TIMR routine to handle timer events
;;GLX INT,52,570,0,PJT,26-Apr-80,


;;GLXLOD 000567
;;		Fixed .STOP so that CONTINUE typed after a stopcode
;;		won't cause ?Ill UUO at user PC 000000
;;GLX COM,33,567,0,DPM,24-Apr-80,


;;GLXLOD 000566
;;		Rework error processing to use globally defined errors
;;GLX SCN,50,566,0,PJT,22-Apr-80,


;;GLXLOD 000565
;;		Make error definitions for S%CMND as part of general galaxy errors
;;GLX MAC,156,565,0,PJT,22-Apr-80,


;;GLXLOD 000564
;;		Change I%EXIT to logout job if not logged in
;;GLX INT,51,564,0,PJT,21-Apr-80,


;;GLXLOD 000563
;;		Fix a bug in justification if last argument in ITEXT
;;GLX TXT,36,563,0,PJT,20-Apr-80,


;;GLXLOD 000562
;;		Add new $TEXT macros for performance improvement at compile time
;;GLX MAC,155,562,0,PJT,10-Apr-80,


;;GLXLOD 000561
;;		Rework logic for deceiding where to get the OTS on
;;		TOPS-10. Also add SFD support.
;;GLX INI,11,561,0,DPM,6-Mar-80,


;;GLXLOD 000560
;;		make changes to GLXFIL so that in OPNCOM, if the
;;		FILOP. open fails, we release the extended channel
;;		before returning. Also, make INTREL always call
;;		RELFB to release the file data base.
;;GLX FIL,51,560,0,AWC,4-Mar-80,


;;GLXLOD 000557
;;		Changed SZ.PAK from ^D50 to PAGSIZ-1 so that very large
;;		packets from [SYSTEM]GOPHER will be recieved ok.
;;GLX IPC,45,557,0,AWC,20-Feb-80,

;;GLX MAC,154,557,0,AWC,20-Feb-80,


;;GLXLOD 000555
;;		Don't output any help text if JFN is for Null IO (in-core parse)
;;		Don't output multiple OR, OR if alternatives are invisible
;;GLX SCN,47,555,0,PJT,16-Jan-80,


;;GLXLOD 000554
;;		MAKE ENTRY VECTOR SYMBOLS IN GLXINI GLOBAL
;;GLX MAC,153,554,0,DC,3-Jan-80,


;;GLXLOD 000553
;;		Fix some caps in XCMDEV
;;GLX SCN,46,553,0,DC,31-Dec-79,


;;GLXLOD 000552
;;		Change WTO block processors to allow arguments to be passed in TF
;;GLX INT,50,552,0,DC,26-Dec-79,


;;GLXLOD 000551
;;		.XCREF and SUPPRESS all symbols created by macros in GLXLIB
;;		via the %xxx construct at the macro definition.
;;GLX MAC,152,551,0,DC,23-Dec-79,


;;GLXLOD 000550
;;		Fix device, node parse so char following terinator gets used.
;;GLX SCN,45,550,0,DC,20-Dec-79,


;;GLXLOD 000547
;;		Add LA120 to TRMTYP macro for the -10
;;GLX MAC,151,547,0,DC,17-Dec-79,


;;GLXLOD 000546
;;		Change XCMDEV to require : as terminator, and supply it for recognition.
;;		Change XCMNOD to require :: or _ as terminator, and supply :: for escape.
;;GLX SCN,44,546,0,DC,17-Dec-79,


;;GLXLOD 000545
;;		Initialize LINPTR in the $TEXT initialization code.
;;GLX TXT,35,545,0,AWC,9-Nov-79,


;;GLXLOD 000544
;;		Make PUTU out out some text if DIRST fails (-20 only)
;;GLX TXT,34,544,0,AWC,9-Nov-79,


;;GLXLOD 000543
;;		On the 10, if the MERGE for library data pages fails, don't
;;		$STOP, since this would only cause an ?Ill mem ref.  Just OUTSTR and EXIT
;;GLX INI,10,543,0,DC,7-Nov-79,


;;GLXLOD 000542
;;		Change CMPDAT to use T3 instead of P1 to prevent illegal memory reference
;;GLX SCN,43,542,0,PJT,21-Oct-79,


;;GLXLOD 000541
;;		Added entry for S%DATI to parse a date/time
;;GLX MAC,150,541,0,PJT,20-Oct-79,

;;GLX SCN,42,541,0,PJT,20-Oct-79,


;;GLXLOD 000537
;;		Added check to K%BIN to avoid HIBER if running under BATCH.
;;GLX KBD,25,537,0,PJT,20-Oct-79,


;;GLXLOD 000536
;;		Add $ERRTXT macro for OPRPAR
;;GLX MAC,147,536,0,PJT,18-Oct-79,


;;GLXLOD 000535
;;		Added definitions for $RETIT and $RETIF Psuedo ops
;;GLX MAC,146,535,0,PJT,13-Oct-79,


;;GLXLOD 000534
;;		Add external library entry S%NUMI to parse an ASCIZ number and error
;;		codes ERRAD$ and ERNUM$
;;GLX MAC,145,534,0,PJT,9-Oct-79,


;;GLXLOD 000533
;;		Add external entry for S%NUMI to parse a number
;;GLX SCN,41,533,0,PJT,9-Oct-79,


;;GLXLOD 000532
;;		ADD .FDNAT, .FDLOC, .FDNET AND .FDFRN FD TYPE DEFINITIONS
;;GLX MAC,144,532,0,PJT,9-Oct-79,


;;GLXLOD 000531
;;		1) Add support for IPCF send to a name.
;;		2) -10, If sending to [SYSTEM]GOPHER, never send a page.
;;GLX IPC,44,531,0,DC,9-Oct-79,

;;GLX MAC,143,531,0,DC,9-Oct-79,


;;GLXLOD 000527
;;		Fixed bug in RDPATH and changed CMRFLD to test break set before checking
;;		special characters like ? and ESCAPE to accomodate CM%BRK bit
;;GLX SCN,40,527,0,PJT,8-Oct-79,


;;GLXLOD 000526
;;		Changed SETFD to correctly remember actual path in lookup/enter block
;;GLX FIL,50,526,0,PJT,7-Oct-79,


;;GLXLOD 000525
;;		Merge in PARUNV to GLXMAC
;;GLX MAC,142,525,0,MLB,3-Oct-79,


;;GLXLOD 000524
;;		Changing calling convention for CNTDT to use S1 and S2
;;GLX TXT,33,524,0,MLB,27-Sep-79,


;;GLXLOD 000523
;;		ADD SUPPORT FOR .CMTAD IN GLXSCN
;;GLX SCN,37,523,0,MLB,25-Sep-79,


;;GLXLOD 000522
;;		Add symbols on -10 for the .CMTAD function in GLXSCN
;;GLX MAC,141,522,0,MLB,25-Sep-79,


;;GLXLOD 000521
;;		CHANGE CALLING CONVENTION TO NUMIN ROUTINE TO CONFORM
;;		TO STANDARD GALAXY ROUTINES USING S1 AND S2
;;GLX SCN,36,521,0,MLB,24-Sep-79,


;;GLXLOD 000520
;;		SUPPORT OUTPUT FILES ON THE -10 WITH COMND, NULL INPUT AND OUTPUT,
;;		AND CM%BRK ON THE -10
;;GLX KBD,24,520,0,MLB,20-Sep-79,

;;GLX MAC,140,520,0,MLB,20-Sep-79,

;;GLX SCN,35,520,0,MLB,20-Sep-79,


;;GLXLOD 000515
;;		Add MAPERR code for the -20 and change INTREL to do a
;;		RLJFN on the -20 if the CLOSF fails (OPENF failed but
;;		GTJFN succeeded).
;;GLX FIL,47,515,0,MLB,12-Sep-79,


;;GLXLOD 000514
;;		Change F%DEL to do F%AOPN instead of F%OOPN
;;		Change F%DREL CHKAC on TOPS20 to check for write access 
;;		instead of directory access.
;;GLX FIL,46,514,0,AWC,31-Aug-79,


;;GLXLOD 000513
;;		SUPPORT THE VT100 KEYPAD.
;;GLX KBD,23,513,0,MLB,31-Aug-79,


;;GLXLOD 000512
;;		Change the Unrecognized Control Character Message to Ambiguous and
;;		adjust the casing on all error messages
;;GLX SCN,34,512,0,MLB,22-Aug-79,


;;GLXLOD 000511
;;		Fix F%DEL to do F%OOPN so we get write access check
;;		on user's behalf instead of read.
;;GLX FIL,45,511,0,DC,20-Aug-79,


;;GLXLOD 000510
;;		Make F%REN give back IFN if file structure is different
;;GLX FIL,44,510,0,DC,9-Aug-79,


;;GLXLOD 000507
;;		DO NOT ALLOW NULL NODE NAMES
;;GLX SCN,33,507,0,MLB,8-Aug-79,


;;GLXLOD 000506
;;		Make F%CHKP return 0 for an input file which has not
;;		yet been read.
;;GLX FIL,43,506,0,DC,27-Jul-79,


;;GLXLOD 000505
;;		Don't page out symbols until first timer trap,
;;		and then do it with 1 or two PAGE. UUOs
;;GLX PFH,2,505,0,DC,27-Jul-79,


;;GLXLOD 000503
;;		Fix F%DREL to lite PRV bit and exit through INTREL on errors.
;;GLX FIL,42,503,0,AWC,13-Jul-79,


;;GLXLOD 000503
;;		Fix CHKIFN to prevent 'Illegal IFN Stopcode' for valid IFN's.
;;GLX FIL,41,503,0,AWC,11-Jul-79,


;;GLXLOD 000502
;;		Make F%REW & F%POS not loop forever when positioning null files.
;;		Make F%REW & F%POS return FDE if GETBUF returns FDE.
;;GLX FIL,40,502,0,AWC,11-Jul-79,


;;GLXLOD 000501
;;		Added code to adjust Greenwich time to local time
;;		inline on the 20 thus avoiding expensive calls to
;;		ODTIM. It is expected that this change will greatly
;;		reduce the overhead involved in outputting dates/times.
;;GLX TXT,32,501,0,WLH,11-Jul-79,


;;GLXLOD 000500
;;		TOPS10... fix K%INIT to not tell monitor of terminal type which
;;		we just got from the monitor!
;;GLX KBD,22,500,0,DC,11-Jul-79,


;;GLXLOD 000477
;;		Fix .ZCHNK to exit if calling count is zero
;;GLX COM,32,477,0,PJT,9-Jul-79,


;;GLXLOD 000476
;;		Fix the padding of nulls on output to not add any if
;;		on a full word boundary.
;;GLX FIL,37,476,0,MLB,9-Jul-79,


;;GLXLOD 000475
;;		Change the text of the GLXLIB incompatible message.
;;GLX INT,47,475,0,MLB,5-Jul-79,


;;GLXLOD 000474
;;		Change GLXINT incompatible GLXLIB to just a call to K%SOUT
;;		instead of $FATAL since library is not initialized. Change I%EXIT
;;		to remove the $FATAL for same reason. Also define %%.GLX in all
;;		non-library modules and have GLXINI reference it external.
;;GLX INI,7,474,0,MLB,3-Jul-79,

;;GLX INT,46,474,0,MLB,3-Jul-79,

;;GLX MAC,137,474,0,MLB,3-Jul-79,


;;GLXLOD 000471
;;		Add code for .MSFLG in the WTO macros
;;GLX INT,45,471,0,MLB,29-Jun-79,

;;GLX MAC,136,471,0,MLB,29-Jun-79,


;;GLXLOD 000467
;;		Make GLXVRS symbol external and on the -20
;;		Save the STOPCODE name in the File Spec Name
;;GLX COM,31,467,0,MLB,29-Jun-79,


;;GLXLOD 000466
;;		
;;		USED TRVARS TO PROVIDE SPACE FOR STRING USED IN GTJFN
;;		CHANGED THE GET SO THAT IT BRINGS IN THE ENTIRE EXE
;;		FILE INSTEAD OF SELECTED PAGES
;;GLX INI,6,466,0,DC,29-Jun-79,


;;GLXLOD 000465
;;		Change the $FATAL message on version skew to show the
;;		version numbers.
;;GLX INT,44,465,0,MLB,29-Jun-79,


;;GLXLOD 000464
;;		CHANGE F%REN SO THAT IF THE SECOND IFN GET
;;		FAILS, IT RELEASES THE FIRST BEFORE RETURNING
;;		AN ERROR
;;GLX FIL,36,464,0,PW,29-Jun-79,


;;GLXLOD 000462
;;		Remove REL: from require of GLXINI in GLXMAC
;;		1) Most of our stuff will be hard to link
;;		2) Anyone else can just as easliy define DSK: as DSK:, REL:
;;GLX MAC,135,462,0,DC,28-Jun-79,


;;GLXLOD 000461
;;		TOPS10..  Make K%INIT use extended channel instead of F%FCHN
;;		and make K%STYP tell the monitor about the change
;;GLX KBD,21,461,0,DC,28-Jun-79,


;;GLXLOD 000460
;;		Fix -10 LDLEB to not make a path block if caller gives 0 for a PPN
;;		even if the passed FB is long enough to contain a path block
;;GLX FIL,35,460,0,DC,26-Jun-79,


;;GLXLOD 000457
;;		Fixed -10 OPNERR to RELFB so IFNTAB slots don't disappear
;;GLX FIL,34,457,0,DC,26-Jun-79,


;;GLXLOD 000456
;;		Change .REQUIRE to REL:GLXINI so that people can easily link in.
;;GLX MAC,134,456,0,DC,26-Jun-79,


;;GLXLOD 000455
;;		1) Move PFH into the library.
;;		2) Rearrange $DATA so that it puts library data in a PSECT DATA
;;		3) Add the GLXPURE assembly switch so that the library can be linked
;;			into a low segment.
;;		Add a new module GLXPFH.
;;GLX PFH,1,455,1,DC,19-Jun-79,

;;GLX INI,5,455,1,DC,19-Jun-79,

;;GLX INT,43,455,1,DC,19-Jun-79,

;;GLX MAC,133,455,1,DC,19-Jun-79,

;;GLX OTS,3,455,1,DC,19-Jun-79,


;;GLXLOD 000451
;;		Fix WTO range check stopcode to give a hint of where things went wrong
;;GLX INT,42,451,0,DC,15-Jun-79,


;;GLXLOD 000450
;;		Changed the text description of .OTMNT to 'Device"
;;		Modified PROB in GLXTXT to output units for .OTMNT as sixbit
;;GLX MAC,132,450,0,AWC,13-Jun-79,

;;GLX TXT,31,450,0,AWC,13-Jun-79,


;;GLXLOD 000446
;;		CHANGE THE SEND QUOTA CODE TO ADD THE SEND QUOTA REQUESTED
;;		TO THE CURRENT QUOTA INORDER TO GET THE NEW SEND QUOTA.
;;GLX IPC,43,446,0,MLB,11-Jun-79,


;;GLXLOD 000445
;;		CORRECT THE EXTRA LINE APPEARING AFTER ? ON HELP. THIS INCLUDES
;;		THE EXTRA ONE ON SOME KEYWORD/SWITCH TABLES
;;GLX SCN,32,445,0,MLB,7-Jun-79,


;;GLXLOD 000444
;;		-10,Use job number as PID when conversing with INFO to
;;		get PIDs of debugging components.
;;GLX IPC,42,444,0,DC,6-Jun-79,


;;GLXLOD 000443
;;		Add Support for L%APOS - Position to a link via its address.
;;GLX LNK,5,443,0,AWC,6-Jun-79,

;;GLX MAC,131,443,0,AWC,6-Jun-79,


;;GLXLOD 000441
;;		-10,Make erase to end of screen work for VT05s.
;;		Broken when installing TRMTYP macros.
;;GLX MAC,130,441,0,DC,5-Jun-79,


;;GLXLOD 000440
;;		-10, Clear EOF after USETI to EOF during position
;;		request which would change buffers
;;GLX FIL,33,440,0,DC,1-Jun-79,


;;GLXLOD 000437
;;		On the -10, don't try to release the channel if the OPEN fails.
;;		Since the channel isn't assigned until the OPEN wins, we'd release
;;		channel 0!! (Broke BATCON)
;;GLX FIL,32,437,0,DC,29-May-79,


;;GLXLOD 000436
;;		Fix output code on the -20 to zero the remainder of the last word written in
;;		the buffer before writing the buffer out.
;;GLX FIL,31,436,0,LSS,24-May-79,


;;GLXLOD 000435
;;		Fix a library bug in memory manager. Make .ZCHNK zero
;;		the correct number of words if length is 1. Make DCT.MN=1.
;;GLX COM,30,435,0,AWC,17-May-79,

;;GLX MAC,127,435,0,AWC,17-May-79,


;;GLXLOD 000433
;;		Fix a bug in wait logic for debugging system if component does not
;;		yet exist.
;;GLX IPC,41,433,0,AWC,7-May-79,


;;GLXLOD 000432
;;		Remove WT.SJI from being set on WTOR if ACK code specified. Also,
;;		change $ACK to lite WT.SJI
;;GLX INT,41,432,0,MLB,7-May-79,

;;GLX MAC,126,432,0,MLB,7-May-79,


;;GLXLOD 000430
;;		Write system PID table after setting MYPID.  This way, we don't
;;		send to IPCC with 0 for a PID to write the table.
;;GLX IPC,40,430,0,DC,30-Apr-79,


;;GLXLOD 000427
;;		Fix expansion of TRMTYP so TTTAB has 0 in RH for non-video terminal
;;GLX KBD,20,427,0,DC,24-Apr-79,


;;GLXLOD 000426
;;		TOPS10 - Set up job number as PID when getting a pid
;;GLX IPC,37,426,0,DC,24-Apr-79,


;;GLXLOD 000425
;;		Fix object block BLT in WTO logic
;;GLX INT,40,425,0,AWC,24-Apr-79,


;;GLXLOD 000424
;;		Make TRMTYP macro which will expand parse tables, sixbit tables,
;;		cursor control tables, etc. Use it in GLXKBD, and in OPR, ORNMAC, OPRCMD.
;;GLX KBD,17,424,0,DC,19-Apr-79,

;;GLX MAC,125,424,0,DC,19-Apr-79,


;;GLXLOD 000422
;;		fix SAVCRS to put null on end of CRASH name.
;;GLX COM,27,422,0,MLB,19-Apr-79,


;;GLXLOD 000421
;;		Disallow Send with 0 PID.
;;GLX IPC,36,421,0,DC,17-Apr-79,


;;GLXLOD 000420
;;		In C%SEND, return ERARG$ if the message length is 0.
;;GLX IPC,35,420,0,DC,13-Apr-79,


;;GLXLOD 000417
;;		Fix WTO action routines so that args in S1, S2 work.
;;GLX INT,37,417,0,DC,13-Apr-79,


;;GLXLOD 000416
;;		Added .OTDBM for DBMS system.
;;GLX MAC,124,416,0,AWC,3-Apr-79,


;;GLXLOD 000415
;;		Made MAXPAK global in IPC.
;;		Made I%WTO send a packet whenever possible.
;;GLX INT,36,415,0,AWC,30-Mar-79,

;;GLX IPC,34,415,0,AWC,30-Mar-79,


;;GLXLOD 000413
;;		Make MAPERR save the TOPS20 system error code in .LGERR,
;;		not the GALAXY system error code. We still return the
;;		GALAXY error code in S1 as before.
;;GLX FIL,30,413,0,AWC,28-Mar-79,


;;GLXLOD 000412
;;		ADD NEW WTO SUPPORT ROUTINES FOR APPLICATION CODE AND
;;		OBJECT TYPE BLOCK
;;GLX INT,35,412,0,MLB,23-Mar-79,

;;GLX MAC,123,412,0,MLB,23-Mar-79,


;;GLXLOD 000410
;;		Fix some bugs and make LSN processing faster
;;GLX FIL,27,410,0,LSS,23-Mar-79,


;;GLXLOD 000407
;;		fix CM%NOP to return true on the -20
;;GLX SCN,31,407,0,MLB,16-Mar-79,


;;GLXLOD 000406
;;		Fix a problem in the file positioning code which caused holes in
;;		some files.
;;GLX FIL,26,406,0,LSS,15-Mar-79,


;;GLXLOD 000405
;;		Fixed a bug in PROLOG to define entry vector offsets with ^O
;;GLX MAC,122,405,0,PJT,13-Mar-79,


;;GLXLOD 000404
;;		Make IFNs start at 1 rather than 0.
;;GLX FIL,25,404,0,LSS,12-Mar-79,


;;GLXLOD 000403
;;		Rework GLXFIL to resolve a number of internal problems and
;;		cleanup the code.
;;GLX FIL,24,403,0,LSS,12-Mar-79,

;;GLX MAC,121,403,0,LSS,12-Mar-79,


;;GLXLOD 000401
;;		Fix bug in ITEXT expansion of $FATAL and don't allow $FATAL to enter DDT
;;GLX COM,26,401,0,PJT,12-Mar-79,


;;GLXLOD 000400
;;		CORRECT MAXIMUM PID SETTING PROBLEM
;;GLX IPC,33,400,0,MLB,11-Mar-79,


;;GLXLOD 000377
;;		Change PROLOG to process GLXINI as a library component and Equate entry
;;		vector symbols in GLXINI.
;;		
;;		Change PROLOG to DEFINE library entry points as MACROS for non library
;;		components.  This allows Pseudo instructions which reference the entry
;;		vector locations to be simple OPDEFS
;;		
;;		Changed $CALL $RETT $RETF to simple OPDEFS
;;GLX INI,4,377,0,PJT,10-Mar-79,

;;GLX MAC,120,377,0,PJT,10-Mar-79,


;;GLXLOD 000375
;;		Change LOAD, STORE, INCR, DECR and ZERO to skip structure stuff if called
;;		without a possible structure name.
;;GLX MAC,117,375,0,PJT,9-Mar-79,


;;GLXLOD 000374
;;		Changed SAVE macro calls to $SAVE
;;GLX FIL,23,374,0,PJT,9-Mar-79,

;;GLX INT,34,374,0,PJT,9-Mar-79,

;;GLX IPC,32,374,0,PJT,9-Mar-79,

;;GLX KBD,16,374,0,PJT,9-Mar-79,

;;GLX MAC,116,374,0,PJT,9-Mar-79,

;;GLX SCN,30,374,0,PJT,9-Mar-79,


;;GLXLOD 000366
;;		Changed LOAD, STORE, INCR, DECR and ZERO macros to skip structure check
;;		if called with no possible structure
;;GLX MAC,115,366,0,PJT,9-Mar-79,


;;GLXLOD 000365
;;		Added $FATAL processing to Stopcode processor
;;GLX COM,25,365,0,PJT, 8-Mar-79,


;;GLXLOD 000364
;;		FIX SETTING OF MAXIMUM NUMBER OF PIDS TO READ THEM FIRST AND
;;		ADD IN THE REQUESTED AMOUNT.
;;GLX IPC,31,364,0,MLB, 8-Mar-79,


;;GLXLOD 000363
;;		Move .BGINT into Prolog macro so that $BGINT can be used in
;;		the Library
;;GLX MAC,114,363,0,MLB, 7-Mar-79,


;;GLXLOD 000362
;;		MAKE C%KPID WORK (SORT OF) FOR NAMED PIDS ON THE -10.
;;		ALSO KILL QUASARS PID AT END OF IPCF TESTER.
;;GLX IPC,30,362,0,DC, 7-Mar-79,


;;GLXLOD 000361
;;		Enable Panic Channels on the -20 if PSI setup and
;;		Save Crashes on the -20 if sending Stopcodes to
;;		ORION and not debugging.
;;		The File Spec for the SAVE is in SAVBUF a global area in GLXSCN
;;GLX COM,24,361,0,MLB, 7-Mar-79,

;;GLX INT,33,361,0,MLB, 7-Mar-79,

;;GLX SCN,27,361,0,MLB, 7-Mar-79,


;;GLXLOD 000356
;;		Change Stopcode to use new ^E function for last -20 Error Code
;;GLX COM,23,356,0,MLB, 6-Mar-79,


;;GLXLOD 000355
;;		Correct -10 Problem with ^B to check Node name and
;;		Node Number to determine if at the same Node
;;GLX TXT,30,355,0,MLB, 6-Mar-79,


;;GLXLOD 000354
;;		Change ^E to get buffer dynamicly and accept -2
;;		for last TOPS20 error code
;;GLX TXT,27,354,0,MLB, 6-Mar-79,


;;GLXLOD 000353
;;		Add processing to ^Q to allow ^Q/KEYTAB(S1),LHMASK/ to generate an asciz
;;		pointer using the address specified in the left half of KEYTAB(S1)
;;GLX TXT,26,353,0,PJT, 5-Mar-79,


;;GLXLOD 000352
;;		Removed name display from $FATAL and $WARN
;;GLX MAC,113,352,0,PJT, 2-Mar-79,


;;GLXLOD 000351
;;		Added C%PIDJ library entry to return Pid's job number
;;GLX MAC,112,351,0,PJT,28-Feb-79,


;;GLXLOD 000350
;;		Added C%PIDJ library entry to return Pid's job number
;;GLX IPC,27,350,0,PJT,28-Feb-79,


;;GLXLOD 000347
;;		Preserve RCVMDB+MDB.MS during SNDSYS so C%REL will work properly in DEBUG
;;		mode.
;;GLX IPC,26,347,0,PJT,27-Feb-79,


;;GLXLOD 000346
;;		Make getting maximum packet size a part of C%INIT even if no PIB is specified
;;		in IB
;;GLX IPC,25,346,0,PJT,26-Feb-79,


;;GLXLOD 000345
;;		ADD CODE TO AVOID LOSING DATA ON REWIND OF SHORT FILES
;;GLX FIL,22,345,0,WLH,23-Feb-79,


;;GLXLOD 000344
;;		Extend DEFSTR and MSKSTR definitions to allow index specification
;;		within the LOCN field.
;;GLX MAC,111,344,0,PJT,21-Feb-79,


;;GLXLOD 000343
;;		ADDED A STOPCODE TO GLXTXT FOR BAD ^E FUNCTION AND DISPLAYED
;;		THE VALUE. THIS PREVENTS SKEW WITH NEW MONITOR DEFINED SYMBOLS
;;		AND THE NEEDED VALIDITY CHECKING.
;;GLX TXT,25,343,0,MLB,21-Feb-79,


;;GLXLOD 000342
;;		Added code to allow indexing and indirect on ^Q qualifier in $TEXT and ITEXT
;;GLX TXT,24,342,0,PJT,13-Feb-79,


;;GLXLOD 000341
;;		Added $KWTOR macro for killing outstanding $WTOR requests.
;;GLX MAC,110,341,0,AWC,12-Feb-79,


;;GLXLOD 000340
;;		ADD IB.PRG IN THE IB TO HOLD PROGRAM NAME
;;GLX COM,22,340,0,MLB, 9-Feb-79,

;;GLX INT,32,340,0,MLB, 9-Feb-79,


;;GLXLOD 000336
;;		ADD ENTRY FOR MAXIMUM SMALL PACKET SIZE C%MAXP AND
;;		WHEN DEBUGING TYPE OUT THE BECOMMING PID MESSAGE
;;GLX IPC,24,336,0,MLB, 5-Feb-79,

;;GLX MAC,107,336,0,MLB, 5-Feb-79,


;;GLXLOD 000334
;;		ALLOW ^E ON THE -20 TO EXPAND 20 ERROR CODES.
;;		THOSE CODES GREATER THAN 600000
;;GLX TXT,23,334,0,MLB,25-Jan-79,


;;GLXLOD 000333
;;		Remove PJUMPN in tops10 conditional (replace with JUMPN)
;;GLX KBD,15,333,0,PJT,22-Jan-79,


;;GLXLOD 000332
;;		Removed extra CRLF's from macro definitions of $TEXT, ITEXT, $WARN, $FATAL,
;;		$STOP and a newly defined macro $ERROR.
;;		
;;		Added module name display to $FATAL, $WARN and $ERROR
;;GLX MAC,106,332,0,PJT,15-Jan-79,


;;GLXLOD 000331
;;		Bump edit number by 1 since I removed GLXWTO from GLXVER.
;;		WTOEDT was 1, so the sum got off by 1 upon this removal
;;GLX MAC,105,331,0,DC,12-Jan-79,


;;GLXLOD 000331
;;		Fixed WTPJBN (WTO job number block processor) to
;;		load a real WT.JOB code
;;GLX INT,31,331,0,DC,12-Jan-79,


;;GLXLOD 000330
;;		Change FLD to look exaclty like INSVL.
;;GLX MAC,104,330,0,DC,12-Jan-79,


;;GLXLOD 000327
;;		Fixed DEFSTR and MSKSTR definitions to allow LOAD and STORE to function
;;		as GETLIM and STOLIM currently do.
;;GLX MAC,103,327,0,PJT,11-Jan-79,


;;GLXLOD 000326
;;		Fixed .STKST and .TRSET to operate properly so STKVAR and TRVAR will work
;;GLX COM,21,326,0,PJT,11-Jan-79,


;;GLXLOD 000325
;;		Change internal WTO opcodes from WT.xxx to WO.xxx
;;		so we don't conflict with ORNMAC bit definitions
;;GLX INT,30,325,0,DC,10-Jan-79,

;;GLX MAC,102,325,0,DC,10-Jan-79,


;;GLXLOD 000323
;;		CHANGE WTO JOB BLOCK NAME TO WJB SO DON'T CONFLICT WITH
;;		WT.JOB IN ORNMAC
;;GLX INT,27,323,0,DC, 9-Jan-79,

;;GLX MAC,101,323,0,DC, 9-Jan-79,


;;GLXLOD 000321
;;		FIX GJBLOC ON THE -20
;;GLX INT,26,321,0,MLB, 9-Jan-79,


;;GLXLOD 000320
;;		Changed $SET to operate with DEFSTR and MSKSTR defined structures.
;;		The still operate with non-stucture offsets and masks
;;GLX MAC,100,320,0,PJT, 8-Jan-79,


;;GLXLOD 000317
;;		Removed usage of PJUMPE opdef
;;GLX MEM,11,317,0,PJT, 5-Jan-79,


;;GLXLOD 000316
;;		Removed usage of PJUMPE opdef
;;GLX TXT,22,316,0,PJT, 5-Jan-79,


;;GLXLOD 000315
;;		Removed usage of PJUMPE and PJMPGE opdefs
;;GLX FIL,21,315,0,PJT, 5-Jan-79,


;;GLXLOD 000314
;;		Removed ASUBR support code.
;;GLX COM,20,314,0,PJT, 4-Jan-79,


;;GLXLOD 000313
;;		Removed JX* macros, PJUM* macros, ASUBR macros.
;;GLX MAC,77,313,0,PJT, 4-Jan-79,


;;GLXLOD 000312
;;		Make BTA $STOP use new ITEXT
;;GLX TXT,21,312,0,DC, 4-Jan-79,


;;GLXLOD 000311
;;		Restore S1,S2,TF after WTO
;;GLX INT,25,311,0,DC, 4-Jan-79,


;;GLXLOD 000310
;;		Take advantage of new $STOP  in BPN, IQN, etc
;;GLX INT,24,310,0,DC, 4-Jan-79,

;;GLX MEM,10,310,0,DC, 4-Jan-79,

;;GLX TXT,20,310,0,DC, 4-Jan-79,


;;GLXLOD 000305
;;		Make $STOP generate ITEXT instead of ASCIZ.
;;		Make $STOP do a real $WTO, if desired.
;;GLX COM,17,305,0,DC, 4-Jan-79,


;;GLXLOD 000304
;;		Add a global version fetch routine
;;GLX INT,23,304,0,DC, 4-Jan-79,


;;GLXLOD 000303
;;		Rework IB, install!PIB
;;GLX INT,22,303,0,DC, 4-Jan-79,

;;GLX IPC,23,303,0,DC, 4-Jan-79,

;;GLX KBD,14,303,0,DC, 4-Jan-79,

;;GLX MAC,76,303,0,DC, 4-Jan-79,


;;GLXLOD 000277
;;		Remove I%IWTO, I%SWTO, I%WTO  finish new $WTO macros and support code
;;GLX INT,21,277,0,DC, 4-Jan-79,

;;GLX MAC,75,277,0,DC, 4-Jan-79,


;;GLXLOD 000275
;;		Remove I%%WTO routines, begin rework of $WTO and support code
;;GLX INT,20,275,0,DC, 4-Jan-79,

;;GLX MAC,74,275,0,DC, 4-Jan-79,


;;GLXLOD 000273
;;		MODIFY ? FOR TABLES WITH ONLY ONE ELEMENT IN THEM
;;GLX SCN,26,273,0,MLB,27-Dec-78,


;;GLXLOD 000272
;;		Added symbols .OTXFR, and .OTBIN.
;;GLX MAC,73,272,1,AWC,18-Dec-78,


;;GLXLOD 000271
;;		Change meaning of DEBUGW so -1 is on, 0 is off.
;;		Debugging names are now based on SPIDS, not on IB.PRG
;;GLX IPC,22,271,0,DC,11-Dec-78,


;;GLXLOD 000270
;;		Add S%SIXB to entry vector, and support code in GLXSCN
;;GLX MAC,72,270,0,DC, 6-Dec-78,

;;GLX SCN,25,270,0,DC, 6-Dec-78,


;;GLXLOD 000266
;;		FIX NODE FUNCTION TO SAVE RESULT WHEN CM%PO IS SET
;;GLX SCN,24,266,0,MLB, 6-Dec-78,


;;GLXLOD 000265
;;		FIX ^N TO TAKE NODE NAME ON THE -10
;;GLX TXT,17,265,0,MLB, 5-Dec-78,


;;GLXLOD 000264
;;		FIX GLXTXT ^R BUG IN -10 NAME OUTPUT OF ZERO SECOND WORD
;;GLX TXT,16,264,0,MLB, 4-Dec-78,


;;GLXLOD 000263
;;		Fix S%TBLK to save the P regs
;;GLX SCN,23,263,0,DC, 1-Dec-78,


;;GLXLOD 000262
;;		FIX $ACK CODE TO LITE WT.SJI TO SUPPRESS JOB INFO DISPLAY
;;GLX INT,17,262,0,MLB,30-Nov-78,


;;GLXLOD 000261
;;		CONVERT TO USE I%JINF
;;GLX INT,16,261,0,MLB,29-Nov-78,

;;GLX TXT,15,261,0,MLB,29-Nov-78,


;;GLXLOD 000257
;;		ADD I%JINF CALL TO LIBRARY
;;GLX INT,15,257,0,MLB,29-Nov-78,

;;GLX MAC,71,257,0,MLB,29-Nov-78,


;;GLXLOD 000255
;;		FIX CMDEV FUNCTIONS AND ADD ITEXT FOR EXPANDING ERRORS.
;;		ALSO LET NODE TAKE PARSE ONLY
;;GLX SCN,22,255,0,MLB,28-Nov-78,


;;GLXLOD 000254
;;		Change ^R Display
;;GLX TXT,14,254,0,MLB,27-Nov-78,


;;GLXLOD 000253
;;		REORGANIZE THE SYSTEM PID TABLE AND REMOVE SP.IPC FROM -20
;;GLX IPC,21,253,0,DC,21-Nov-78,

;;GLX MAC,70,253,0,DC,21-Nov-78,


;;GLXLOD 000251
;;		ADD STOPCODE TO ^R PROCESSING FOR BAD USER INFO IN JIB
;;GLX TXT,13,251,0,MLB,14-Nov-78,



;;GLXLOD 000250
;;		ADD I%HOST TO THE  LIBRARY
;;GLX INT,14,250,0,MLB, 9-Nov-78,

;;GLX MAC,67,250,0,MLB, 9-Nov-78,


;;GLXLOD 000246
;;		Change Stopcode to use $HALT instead of I%EXIT to exit without a reset
;;GLX COM,16,246,0,, 9-Nov-78,


;;GLXLOD 000245
;;		Fix a S%TBAD Bug had wrong AC for GETER return
;;GLX SCN,21,245,0,, 9-Nov-78,


;;GLXLOD 000244
;;		ADD A NEW TEXT QUALIFIER ^R FOR DISPLAYING A JOB INFORMATION BLOCK AS
;;		NOW DEFINED IN GLXMAC
;;GLX MAC,66,244,0,, 8-Nov-78,

;;GLX TXT,12,244,0,, 8-Nov-78,


;;GLXLOD 000242
;;		Changed ERICA$ to ERARG$
;;GLX MAC,65,242,0,PJT,31-Oct-78,


;;GLXLOD 000241
;;		Added 'PULSAR' to special pid name table for TOPS10
;;		Spelling fixes -- cosmetics
;;GLX IPC,20,241,0,PJT,31-Oct-78,


;;GLXLOD 000240
;;		Changed $CALL to do range check for entry vector
;;		Defined VMAX as last absolute location of entry vector
;;GLX MAC,64,240,0,PJT,27-Oct-78,


;;GLXLOD 000237
;;		Fix a bug with the new F%OBUF with APPEND mode.
;;GLX FIL,20,237,0,AWC,25-Oct-78,


;;GLXLOD 000236
;;		FIXED RECIVE LOGIC TO CLEAR RECIEVE PAGE AFTER A SUCCESSFULL
;;		PAGE RECIEVE
;;GLX IPC,17,236,0,PJT,25-Oct-78,


;;GLXLOD 000235
;;		Rewrite F%OBUF, Move QUOTA EXCEEDED code to -10 dependent area.
;;		Delete QUOTA EX code from F%OBYT.
;;GLX FIL,17,235,0,AWC,25-Oct-78,


;;GLXLOD 000234
;;		Changed JUMPT,JUMPF,SKIPT,SKIPF definitions to OPDEFS
;;		Changed JUMPT and SKIPT to JUMPN and SKIPN
;;GLX MAC,63,234,2,PJT,24-Oct-78,


;;GLXLOD 000233
;;		fixed SNDSYS and KILPID in TOPS20 code to work properly
;;GLX IPC,16,233,1,PJT,23-Oct-78,


;;GLXLOD 000232
;;		Add special pid indexes for FILDAE, PULSAR, Accounting
;;GLX MAC,62,232,0,DC,19-Oct-78,


;;GLX MAC,61,0,0,PJT,18-Oct-78
;;	Added .OTMNT for Mount requests
;;	Added .RET to entry vector as .POPJ
;;GLX MAC,60,PJT,5-Oct-78
;;	Changed $CALL to OPDEF [PUSHJ P,@] for non-library components
;;GLX MAC,57,PJT,5-Oct-78
;;	Redefined SAVE macro to use co-routines
;;GLX MAC,56,MLB,28-Sep-78
;;  Added symbols for GLXMEM (CNK.PM and AVLPAG)
;;GLX MAC,55,PJT,26-Sep-78
;;GLX MAC,54,PJT,26-SEP-78
;;GLX MAC,53,AWC,25-SEP-78
;;GLX MAC,52,PJT,22-Jul-78

;;GLX COM,15,0,0,PJT,4-Oct-78
;;	Removed reference to ALTOPR in Stop code processor
;;GLX COM,14,PJT,21-Sep-78
;;	Cleaned up .SAVE8 routine
;;GLX COM,13,PJT,21-Sep-78
;;GLX COM,10,PJT,18-Sep-78
;;GLX COM,7,MLB,18-Jul-78

;;GLX FIL,16,0,0,PJT,17-Sep-78
;;	Added range check for FD size in OPNCOM
;;GLX FIL,15,MLB,12-Sep-78
;;GLX FIL,14,MLB,1-Sep-78

;;GLX INI,3,0,0,PJT,5-Oct-78
;;	Changed I%INIT to appear as an entry vector (e.g. jfcl .+1)
;;	to support PUSHJ P,@I%INIT in new $CALL definition
;;GLX INI,2,PJT,28-SEP-78
;;GLX INI,1,MLB,18-MAY-78

;;GLX INT,13,0,0,PJT,16-OCT-78
;;	Handle send errors for I%SOPR if user doesn't want send
;;	errors returned
;;GLX INT,12,PJT,9-OCT-78
;;	Support Multiple Interrupt levels on the 20
;;GLX INT,11,PJT,28-SEP-78
;;GLX INT,10,MLB,8-Sep-78
;;GLX INT,7,MLB,11-Jul-78

;;GLX IPC,15,0,0,PJT,4-Oct-78
;;	Fixed Startup race and cleaned up Debugging system
;;	Added errors ERICA$	Invalid Calling Argument
;;	Modified C%SEND to clear entry in internal Pid table
;;	  if send to system pid fails.  This allows retry and
;;	  also allows a component to pick up a new system pid.
;;GLX IPC,14,PJT,26-Sep-78
;;GLX IPC,13,MLB,13-Sep-78
;;GLX IPC,12,MLB,19-Jun-78

;;GLX KBD,13,0,0,PJT,28-Sep-78
;;  Modified K%INIT to use IIB instead of Calling Args
;;GLX KBD,12,WLH,18-Aug-78

;;GLX LNK,4,0,0,LSS,7-Oct-78

;;GLX MEM,7,0,0,MLB,28-Sep-78
;;	Add garbage collection to GMEM and RMEM when request
;;	exceeds number of pages available
;;GLX MEM,6,MLB,13-Sep-78

;;GLX OTS,2,0,0,PJT,20-SEP-78,

;;GLX SCN,20,0,0,WLH,16-Aug-78

;;GLX TXT,11,0,0,PJT,17-Oct-78
;;	Changed T%INIT to use IIB set up be I%INI1
;;GLX TXT,10
;;GLX TXT,7,MLB,2-Jun-78

;;GLX VER,1,0,0,PJT,7-Sep-78

;;GLX WTO,1,0,0,DC,18-Oct-78 ;;Removed since GLXWTO is a red herring
> ;END DEFINE MODULES
;Macro to Define MOD'$WHO and MOD'$NOTE which will print the
;information in this file for the particular module if the
;edit levels do not match what is stated in glxver.
;Adds the Edit level for the module to the edit level of GLXVER

;Also makes MOD'EDT Internal so LINK can Check for skew

DEFINE GLX (MOD,NUM,LOD,GCO,WHO,DATE,NOTE) <

	MOD'EDT==NUM			;DEFINE UNIVERSAL EDIT LEVEL
	INTERN MOD'EDT			;LET LINK CHECK FOR SKEW
	GLXEDT==GLXEDT+MOD'EDT		;ADD EDIT LEVEL OF MODULE TO GLXEDT
	DEFINE MOD'$WHO (ACTNUM) <
	PRINTX GLXVER	GLX'MOD Edit(NUM) by WHO on DATE
	PRINTX	    	GLX'MOD	Actual Edit(ACTNUM)
	> ;END DEFINE MOD'$WHO
	DEFINE MOD'$NOTE <
	IFNB <NOTE>,<
	PRINTX NOTE (From GLXVER)
	> ;END IFNB NOTE
	> ;END DEFINE MOD'$NOTE

> ;END DEFINE GLX

IF1,<					;Only define things on first pass
	GLXVER==1			;MAJOR LIBRARY VERSION NUMBER
	GLXMIN==0			;MINOR LIBRARY VERSION NUMBER
	GLXWHO==0			;CUSTOMER VERSION
	GLXEDT==0			;INITIALIZE EDIT LEVEL TO ZERO
	MODULES				;COMPUTE ACTUAL VALUE FOR GLXEDT
	IFN <GLXEDT-GLXLOD>,<PRINTX %GLXLOD doesn't equal sum of module edits>
>;End IF1


GLXVRS==<BYTE(3)GLXWHO(9)GLXVER(6)GLXMIN(18)GLXEDT>

	LOC 137
	EXP GLXVRS			;SET VERSION
	RELOC

;Macro to be invoked by Prolog for Galaxy Library Components
;CHKEDT will compare edit level in Glxver to Edit level in
;Component and Flag any Descrepencies

DEFINE CHKEDT (MOD) <

	IF1, <%%EDT==MOD'EDT>	;;SAVE GLXVER EDIT LEVEL FOR PASS 2

	IF2, <IFN <%%EDT-MOD'EDT>,<
		PRINTX ? Edit Number Doesn't Match GLXVER in GLX'MOD
		MOD'$WHO(\MOD'EDT)>	;;SHOW WHO DID IT
		MOD'$NOTE		;;SHOW NOTE IF ANY
	INTERN MOD'EDT		;;LET LINK CHECK SKEW FOR MODULE
	INTERN LODLEV		;;AND LIBRARY LOAD LEVEL
;	PURGE %%EDT> ;END IF2

> ;END CHKEDT
	IFN GLXPURE,<
	IF2 , <PURGE MODULES,GLX,WHO,NOTE>
	>
