!SPROUT.CTL	Phil Taylor	14-Jul-78

!28-Jan-79	LSS	Editted in preparation of R4 Loadtest


!
!
!                  COPYRIGHT (c) 1979,1980,1981,1982
!                    DIGITAL EQUIPMENT CORPORATION
!
!     THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY  BE  USED
!     AND COPIED ONLY IN ACCORDANCE WITH THE TERMS OF SUCH LICENSE
!     AND WITH THE INCLUSION OF THE ABOVE COPYRIGHT NOTICE.   THIS
!     SOFTWARE  OR ANY OTHER COPIES THEREOF MAY NOT BE PROVIDED OR
!     OTHERWISE MADE AVAILABLE TO ANY OTHER PERSON.  NO  TITLE  TO
!     AND OWNERSHIP OF THE SOFTWARE IS HEREBY TRANSFERRED.
!
!     THE INFORMATION  IN  THIS  SOFTWARE  IS  SUBJECT  TO  CHANGE
!     WITHOUT  NOTICE  AND SHOULD NOT BE CONSTRUED AS A COMMITMENT
!     BY DIGITAL EQUIPMENT CORPORATION.
!
!     DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR RELIABILITY
!     OF  ITS  SOFTWARE  ON  EQUIPMENT  WHICH  IS  NOT SUPPLIED BY
!     DIGITAL.

!This Control File Assembles, Loads, and saves SPROUT

!System Files

!	MONSYM.UNV

!Required Files in or Your Area

!	GLXMAC.UNV	Library Macro and Symbol Definitions
!	GLXINI.REL	Library Load Module

!Source Files

!	SPROUT.MAC

!Output Files

!	SPROUT.EXE

.ASS DSK REL
.SET WATCH VERSION
@DEF REL: DSK:
@DEF UNV: DSK:,UNV:
@VDIR	SPROUT.MAC

.DIRECT	SPROUT.MAC

COMP::
@
.
COMPILE/COMPILE SPROUT.MAC
LOAD SPROUT
SAVE SPROUT

@VDIRECT SPROUT.EXE
.DIRECT SPROUT.EXE

@
.
PLEASE	SPROUT Assembly Successful
NOERROR
@MODIFY BATCH GALAXY/DEP:-1
.SUB GALAXY=/MOD/DEP:-1

%CERR::
%ERR::
@
.
PLEASE	Error During SPROUT Assembly
%FIN::
