/* 
 * This file is automatically generated.  
 */

/*
 Author: Howie Kaye

 Columbia University Center for Computing Activities, July 1986.
 Copyright (C) 1986, 1987, Trustees of Columbia University in the City
 of New York.  Permission is granted to any individual or institution
 to use, copy, or redistribute this software so long as it is not sold
 for profit, provided this copyright notice is retained.
*/


#define MAJORVERSION 1
#define MINORVERSION 16
#define VERSIONDATE "Sun Jun 28 13:54:09 1987"

/*
 * $Log:	cmver.h,v $
 * Revision 1.19  87/06/28  13:54:10  howie
 * stack indirect files
 * error messages for stacks
 * cm_set_ind call in cmmisc.c
 * 
 * Revision 1.18  87/06/26  19:05:00  howie
 * Change filelist.c to check for modifications to directories when
 * checking if the path needs to be searched again
 * 
 * Some corrections to sysv junk
 * add cm_set_ind call to turn indirection on or off.
 * 
 * Revision 1.17  87/06/24  22:56:13  howie
 * Add system V support
 * 
 * Revision 1.16  87/06/18  15:49:20  howie
 * fix up endif's -- no more endif foo -- now foo is inside a comment
 * make comments end at the end of the line inside an indirection.
 * 
 * Revision 1.15  87/06/17  13:17:24  howie
 * Add @indirection
 * change keyword structure to use a (keyval) as the return value.
 * 
 * Revision 1.14  87/05/19  15:20:39  howie
 * use vprintf's from cmxprintf
 * 
 * Revision 1.13  87/05/18  13:10:39  howie
 * change handling of NULL in various places, to avoid possible
 * NULL dereferences.  This breaks on SUNS (and is bad anyway).
 * Thanks to Maurice Wuts at USC for the sun port.
 * 
 * Revision 1.12  87/05/11  18:15:48  howie
 * cmfil: don't search directories on null input
 * filelist: fix handling of S_IFDIR stat flag.
 * 
 * Revision 1.11  87/05/11  13:05:47  fuat
 * in checkact, only call action routine if an action character AND
 * the action routine is non NULL.
 * 
 * Revision 1.10  87/05/11  11:51:54  fuat
 * fix redispact in cmpara to handle wrapped lines
 * 
 * Revision 1.9  87/05/07  19:38:35  howie
 * change the usage for defaults at the beginning of a line.
 * also fix up full/partial completion on defaults
 * 
 * Revision 1.8  87/05/07  13:24:53  howie
 * new datime code.
 * other bug fixes
 * 
 * Revision 1.7  87/04/08  19:41:20  howie
 * add _cmmax field to the CSB.  This is the maximum number of tokens
 * to display when giving help.  If there are more than this, just
 * tell how many there are.
 * Also made CMFIL, CMUSR, CMGRP use this.
 * 
 * Revision 1.6  87/04/08  18:04:13  howie
 * Some bug fixes.
 * fix a bug not allowing escape completion in CMTOK
 * fix bug with KEY_M`NOR flag in CMKEY.  If only one match, not ignored.
 * 
 * Revision 1.5  87/04/05  19:17:15  howie
 * some cosmetic changes.
 * 
 * Revision 1.4  87/04/05  18:14:56  howie
 * Added single character parse module: cmchar.
 * update copyrite notices.
 * add Version module cmversion, and incversion program
 *  to handle automatic version updates.
 * add cmini() function to cmmisc(), to make initialization easier.
 * 
 * Revision 1.4  87/04/05  18:14:56  howie
 * Added single character parse module: cmchar.
 * update copyrite notices.
 * add Version module cmversion, and incversion program
 *  to handle automatic version updates.
 * add cmini() function to cmmisc(), to make initialization easier.
 * 
 * Revision 1.3  87/04/05  17:27:10  howie
 * update copyrite notice.
 * 
 * Revision 1.2  87/04/03  18:27:17  howie
 * Added version numbers
 * 
 */

