.TH WEBSTER 1 ECN
.UC E 85-1
.SH NAME
webster \- look up words in the dictionary
.SH SYNOPSIS
.B webster
[\fIwords\fP]
.SH DESCRIPTION
.PP
.B Webster
is used to look up words in the online copy of Webster's 7th dictionary,
stored at SRI-NIC.
If words are given as arguments to the program,
they will be looked up and their definitions printed.
If no arguments are given,
.B webster
enters interactive mode,
and prompts for words to be defined.
.PP
In interactive mode,
you will be prompted with ``Word: ''.
Just type the word you want defined,
or simply type a blank line to exit.
If the word is found,
.B webster
will then provide the complete dictionary entry for the word including
definitions,
pronunciation,
and derivation.
If the specified word was not found,
.B webster
will try to find close matches,
as if you spelled the word wrong.
The possibilities are numbered and typed out.
To select one of them,
you can just give its number.
.PP
Additionally,
.B webster
can match words using wildcards.
The character
`%' in a word means match exactly one character,
so ``w%n'' matches
``win'',
``won'',
``wan'',
etc.
The character `*' matches
.I "zero or more"
characters,
so ``a*d''matches
``ad'',
``and'',
``abound'',
``absentminded'',
and so on.
Any number of wildcards can be used,
and in any arrangement.
.PP
The ESC (escape) and `?' characters also perform special functions.
Typing a partial word,
followed by ESC,
tries to complete what you have typed so far.
If what you have typed is a unique abbreviation for a word,
the word is typed out.
If what you typed is ambiguous,
.B webster
will beep at you and do nothing.
Typing `?' at the end of a partial word will print out all the possible
endings for the word you typed.
If there are no possible endings,
.B webster
will beep at you and do nothing.
.SH EXAMPLES
.nf
.ta 5m 20m 35m 50m
Word: \fIplur?\fP
Maybe you mean:
	1. plural	2. pluralism	3. plurality	4. pluralization
	5. pluralize	6. pluri-	7. pluriaxial
Word: \fIpluri?\fP
Maybe you mean:
	1. pluri-	2. pluriaxial
Word: \fIpluria<ESC>\fPxial
.fi
.LP
Where the text in italics is typed by the user,
and the rest by
.BR webster .
Note that wildcards may be used in conjuntion with ESC and `?',
for example
.nf
.sp
Word: \fIplu*x<ESC>\fP
Word: pluriaxial
.fi
.SH SEE ALSO
.BR look (1),
.BR spell (1)
.SH BUGS
.PP
Occasionally,
when you type a word to the prompt,
another prompt appears without the word being defined.
If this happens,
try typing the word again.
If it still doesn't work,
exit the program and start again.
.SH AUTHOR
David A. Curry
.br
davy@purdue-ecn
