; Edit= 8839 to PAGEM.MAC on 3-May-88 by RASPUZZI, for SPR #21881 (TCO 7.1282)
;Prevent NSKDIS BUGHLTs in SECMAP.
; UPD ID= 8663, RIP:<7.MONITOR>PAGEM.MAC.11,  22-Feb-88 18:49:25 by GSCOTT
;TCO 7.1238 - Set SWDDEL and SWEDEL normally not dumpable.
; UPD ID= 8573, RIP:<7.MONITOR>PAGEM.MAC.10,  11-Feb-88 16:51:31 by GSCOTT
;TCO 7.1218 - Update copyright date.
; UPD ID= 8458, RIP:<7.MONITOR>PAGEM.MAC.9,   5-Feb-88 09:20:38 by GSCOTT
;More of TCO 7.1210 - Fix up spelling in ILOFN1
; UPD ID= 8427, RIP:<7.MONITOR>PAGEM.MAC.8,   4-Feb-88 13:41:37 by GSCOTT
;TCO 7.1210 - Set DRMFUL, SWPDIR, SWPIBE, SWPJSB, SWPPSB, SWPPT, SWPPTP, and
; SWPUPT normally not dumpable.
; UPD ID= 8383, RIP:<7.MONITOR>PAGEM.MAC.6,  25-Jan-88 23:55:59 by GSCOTT
;TCO 7.1197 - Prevent problems when XRCOD+XNCOD+ENCOD is larger than NRCOD.
; UPD ID= 8329, RIP:<7.MONITOR>PAGEM.MAC.5,  23-Dec-87 09:36:10 by SHREFFLER
;TCO 7.1167 - Prevent SWOFCT BUGCHKs.
; UPD ID= 67, RIP:<7.MONITOR>PAGEM.MAC.4,  12-Aug-87 10:48:53 by LOMARTIRE
;TCO 7.1036 - Fix OFN lock tracer (SPTDSW)
; UPD ID= 5, RIP:<7.MONITOR>PAGEM.MAC.3,  28-May-87 16:08:37 by RASPUZZI
;TCO 7.1002 - Implement PMOVE/M instructions.
; *** Edit 7442 to PAGEM.MAC by THOUMIRE on 8-Apr-87, for SPR #21591
; Prevent NSKDIS BUGHLT when calling LCKOFN at RELPG4 
; *** Edit 7416 to PAGEM.MAC by RASPUZZI on 11-Feb-87, for SPR #21389
; Prevent SKDPF1s when working set preloading is enabled and the monitor is
; preloading a page in an extended section
; *** Edit 7366 to PAGEM.MAC by EVANS on 24-Sep-86, for SPR #21258
; Change a JFCL to NOP in DSKRT to get a faster instruction.
; *** Edit 7356 to PAGEM.MAC by MCCOLLUM on 20-Aug-86, for SPR #21231
; PLKMOD fixes - Re-cache OFN after GETCFS failure and add BUGHLTs. 
; *** Edit 7354 to PAGEM.MAC by LOMARTIRE on 12-Aug-86
; Do not clobber T4 by call to LCKOFN at RELP41 - MOVDSK needs it 
; *** Edit 7339 to PAGEM.MAC by LOMARTIRE on 23-Jul-86
; Lock the OFN sooner at RELP4 since MOVDSK goes OKSKED as of edit 7201 
; *** Edit 7314 to PAGEM.MAC by LOMARTIRE on 9-Jun-86, for SPR #21208
; Prevent NSKDIS BUGHLTs from NOSKED before call to RELMPG in WCPY 
; *** Edit 7303 to PAGEM.MAC by WAGNER on 27-May-86
; Restore code removed in edit 7164 to prevent ILPSEC bughalts. 
; *** Edit 7283 to PAGEM.MAC by LOMARTIRE on 4-Apr-86, for SPR #21144
; Prevent OPNX9 errors from OF%RDU opens and bug in CHKLAC 
; *** Edit 7247 to PAGEM.MAC by LOMARTIRE on 19-Feb-86
; Implement OFN caching 
; *** Edit 7201 to PAGEM.MAC by GRANT on 19-Nov-85
; In MOVDSK, cause page fault while CSKED instead of NOSKED 
; Edit 7164 to PAGEM.MAC by WAGNER on 21-Oct-85
; ***PERFORMANCE*** modify scheduler and called routines to be more efficient 
; Edit 7136 to PAGEM.MAC by LOMARTIRE on 15-Aug-85, for SPR #20860 (TCO 6-1-1525)
; Prevent NSKDIS BUGHLT from LCKOFN call in RELP4 
; UPD ID= 2232, SNARK:<6.1.MONITOR>PAGEM.MAC.266,  18-Jun-85 15:17:23 by MOSER
;MORE 6.1.1447 - FIX A BUG
; UPD ID= 2227, SNARK:<6.1.MONITOR>PAGEM.MAC.265,  17-Jun-85 14:45:03 by MOSER
;TCO 6.1.1447 - ALWAYS CHECK FOR SKDPF1
; UPD ID= 2143, SNARK:<6.1.MONITOR>PAGEM.MAC.264,   5-Jun-85 10:24:45 by MCCOLLUM
;TCO 6.1.1406  - Update copyright notice.
; UPD ID= 2111, SNARK:<6.1.MONITOR>PAGEM.MAC.263,   3-Jun-85 16:15:12 by LOMARTIRE
;TCO 6.1.1393 - Fix potential DDMP hang
; UPD ID= 2039, SNARK:<6.1.MONITOR>PAGEM.MAC.261,   3-Jun-85 13:34:12 by TBOYLE
;TCO 6.1.1421 - Make SETPT0 error return PAGPTN and have callers either
; retry or BUGHLT depending on the routine.
; UPD ID= 1983, SNARK:<6.1.MONITOR>PAGEM.MAC.259,  16-May-85 17:38:57 by TBOYLE
;Remove 6.1.1297 until a better solution is invented.
; UPD ID= 1952, SNARK:<6.1.MONITOR>PAGEM.MAC.258,   9-May-85 18:17:10 by MCCOLLUM
;TCO 6.1.1238 - Fix more BUG. documentation
; UPD ID= 1905, SNARK:<6.1.MONITOR>PAGEM.MAC.257,   4-May-85 20:37:22 by MCCOLLUM
;TCO 6.1.1238 - Fix more BUG. documentation
; UPD ID= 1855, SNARK:<6.1.MONITOR>PAGEM.MAC.256,  30-Apr-85 15:20:04 by MCCOLLUM
;TCO 6.1.1238 - Fix more BUG. documentation
; UPD ID= 1840, SNARK:<6.1.MONITOR>PAGEM.MAC.255,  29-Apr-85 14:42:19 by GROSSMAN
;TCO 6.1.1347 - Fix FPTAXC to return correct page ownership for XCDSEC pages.
;Also fix indentation at FPTAX2.
;TCO 6.1.1346 - Fix MRPAC% to prevent MDDT from touching PSB special pages in
;XCDSEC, and eventually causing PAGLCK BUGHLT's.
; UPD ID= 1791, SNARK:<6.1.MONITOR>PAGEM.MAC.254,  23-Apr-85 13:06:45 by MCCOLLUM
;TCO 6.1.1238 - Fix more BUG. documentation
; UPD ID= 1736, SNARK:<6.1.MONITOR>PAGEM.MAC.253,   9-Apr-85 11:03:36 by MCCOLLUM
;TCO 6.1.1238 - Fix BUG. documentation
; UPD ID= 1708, SNARK:<6.1.MONITOR>PAGEM.MAC.252,   1-Apr-85 16:17:56 by TBOYLE
; TCO 6.1.1297 - In MSETPT remove window between RELMP5 and SETPT0.
; UPD ID= 1180, SNARK:<6.1.MONITOR>PAGEM.MAC.251,  11-Dec-84 14:09:40 by LEACHE
;Change EHLJSB conditional to EXTJSB
; UPD ID= 945, SNARK:<6.1.MONITOR>PAGEM.MAC.250,   4-Nov-84 15:26:48 by GLINDELL
;More TCO 6.1.1021 - MDDT is now in XCDSEC - change FPTAXC
; UPD ID= 5017, SNARK:<6.MONITOR>PAGEM.MAC.248,  26-Oc