;-*-Macro-*-

comment \
assumed file format: (if changed here, change the definitions in
	the file generation program too)

header [n words, where n is the length of a single tty data block]
0/	# of blocks (not including this) in file [maxK]
1/	# of words per block [n]
2/	version #

3/	start of 1st block, for TTY0 (the fake, generic, * one)
	...
k*n/	[for k:=1 to maxK] one tty entry, for line k
	see below for definition of one entry
\

;OFFSETS INTO HEADER RECORD
b%maxK==0
b%n==1
B%VERS==2
b%headl==3			;length of header

;DEFAULTS FOR NEW FILES
B%DEFL==^D18			;DEFAULT LENGTH OF FILE
B%VNO==2			;VERSION NUMBER

comment \
Each line has an associated terminal block of the following format:

TYPE
    ttynumber = 1..511;             (* Up to 511 lines *)
    directiontype = (toleft, toright, acrossglass, facing, diagonal,
		     behind, acrosspartition);      (* For fing/neighbor *)
    locationtype =  (ceras105, ceraslobby, cerasother,
		     terman104, termanother,
		     dialin, gandalf,
		     ethernvt, arpanvt, decnvt)	    (* Typical locations *)
    flagtype =      (consultant, assignable, overhead, formfeed,
		     lowercase, tabs, pagepause, commandpause,
		     raise, flag);
    tty = RECORD (* Tty *)
	      ttytype,		    (* Terminal type number, or -1 if ? *)
	      defttytype,	    (* Default type number or -1 if ? *)
	      length,		    (* Terminal length or -1 if ? *)
	      width:     integer;   (* Terminal width or -1 if ? *)
				    (* Total 4 wds *)
	      address:   PACKED ARRAY[1..30] OF char;
				    (* String for finger.  6 wds *)
	      location:  locationtype;
				    (* Where it is for finger.  1 wd *)
	      neighbors: PACKED ARRAY[directiontype] OF ttynumber;
				    (* For FINGER/NEIGHBORS.  2 wds *)
	      dplxmode:  (fullduplex, noduplex, halfduplex, linehduplex);
				    (* 1 wd *)
	      bits:     PACKED SET OF flagtype;
				    (* Bits.  2 wds currently *)
	      print-node: PACKED ARRAY [1..10] OF char;
				    (* 6 letter DECnet node name.  2 wds *)
	  END  (* Tty *)	(* 18 words, currently *)
\


	PHASE 0			;DEFINITIONS OF TTY DATA BLOCKS
; N.B. ALL FIELDS ARE -1 IF UNKNOWN
B%TTYTYPE:	0		;TERMINAL TYPE NUMBER
B%DEFTTYTYPE:	0		;DEFAULT TERMINAL TYPE NUMBER
B%LENGTH:	0		;TERMINAL LENGTH
B%WIDTH:	0		;TERMINAL WIDTH
B%ADDRESS:	BLOCK 6		;PACKED ARRAY [1..30] OF CHAR
B%LOCATION:	0		;UNKNOWN,CERAS105,CERASLOBBY,CERASOTHER,
				; TERMAN104,TERMANOTHER,DIALIN,GANDALF,
				; ETHERNVT,ARPANVT,DECNVT, ETC...
B%NEIGHBOR:	BLOCK 2		;PACKED ARRAY [DIRECTION] OF 0..511--I.E. 9 BIT
				; DIRECTION=(TOLEFT,TORIGHT,ACROSSGLASS,FACING,
				; DIAGONALLY-OPPOSITE,BEHIND,ACROSSPARTITION
B%DPLXMODE:	0
B%BITS:		BLOCK 2		;SEE BELOW
B%PRINT:	BLOCK 2		;SIX LETTER DECNET NODE NAME
	DEPHASE

; BITS IN B%BITS
B%CONSULTANT==	1B0		;NOT USED IN THIS PROGRAM
B%ASSIGNABLE==	1B1		;NOT USED IN THIS PROGRAM
B%OVERHEAD==	1B2		;NOT USED IN THIS PROGRAM
B%FORMFEED==	1B3
B%LOWERCASE==	1B4
B%TABS==	1B5
B%PAGEPAUSE==	1B6
B%COMMANDPAUSE==1B7
B%RAISE==	1B8
B%FLAG==	1B9
B%EXPRESS==	1B10		;NOT USED IN THIS PROGRAM

	END
