; *********** WARNING WARNING WARNING *************
;
; If we are running a v7 monitor, delete this file and go
; edit 7-CONFIG.CMD instead.  If we are still running v6,
; then copy this file to 7-CONFIG.CMD after you edit.
;
;
; dial-out modem 
TERMINAL 1 SPEED 0
; not in use
TERMINAL 2 SPEED 9600
; operator office
TERMINAL 3 SPEED 9600 
; direct dialup
TERMINAL 4-10 REMOTE AUTO
; Micom lines
TERMINAL 11-17 REMOTE AUTO
; Micom status line
TERMINAL 20 SPEED 9600
; direct lines
TERMINAL 21 SPEED 9600
; mkl's home line
TERMINAL 22 SPEED 9600
; direct lines
TERMINAL 23-24 SPEED 9600
; imagen
TERMINAL 25 SPEED 9600
; direct lines
TERMINAL 26-30 SPEED 9600
; more Micom
TERMINAL 31-40 REMOTE AUTO
; direct lines
TERMINAL 41-47 SPEED 9600
; unused
TERMINAL 50 SPEED 0
; micom?
TERMINAL 51-53 SPEED 9600
; dataproducts
TERMINAL 54 SPEED 9600
; LaserWriter
TERMINAL 55 SPEED 9600
; Line to Katie's office - she's not using it
TERMINAL 56 SPEED 0
TERMINAL 57 SPEED 9600
; outgoing MICOM
TERMINAL 60 SPEED 0
; dump tty
TERMINAL 61 SPEED 2400
; direct line
TERMINAL 62 SPEED 9600
; unused
TERMINAL 63-70 SPEED 9600
; This is the WWV clock -- Defined as CLOCK: below!
TERMINAL 71 SPEED 9600
; unused 76-100 are probably bad
TERMINAL 72-100 SPEED 0

MAGTAPE 0 5509 TU78
MAGTAPE 1 5568 TU78

PRINTER 0 LOWERCASE VFU SYS:NORMAL.VFU

TIMEZONE 8

;Turned this off 10-Jun-87.  Are disks are overloaded. -- MKL
DISABLE WORKING-SET-PRELOADING

ENABLE FULL-LATENCY-OPTIMIZATION
TAPE-RECYCLE-PERIOD 3650
ARCHIVE-TAPE-RECYCLE-PERIOD 3650
DISABLE ACCOUNT-VALIDATION
ENABLE HANGUP-IF-LOGGED-IN
ENABLE HANGUP-IF-LOGGED-OUT
NODE LOCAL

BIAS 11

Define AT:		TS:<AUDIT-TRAIL>,TS:<AUDIT-TRAIL.1988>,TS:<AUDIT-TRAIL.1987>
Define BBD:		PS:<BBOARD>
Define C:		PS:<KCC>
Define CLOCK:		TTY71:
Define CSNET:		PS:<CSNET>
Define DB-BIB:		PS:<BIBLIO>BIB
Define DB-DOCS:		TS:<DOCS>DOCS
Define DB-ID:		PS:<ID>ID
Define DB-NETS:	      	PS:<ID>NETS
Define DB-VH:		VH:VH-DB
Define DDN-NEWS:	PS:<DDN-NEWS>
Define DEFAULT-EXEC:	SYSTEM:EXEC.EXE
Define DMP:		XS:<SYSTEM>
Define DOC:		PS:<DOCUMENTATION>
Define DOMAIN:		PS:<DOMAIN>,PS:<DOMAIN.VERSION5>,PS:<DOMAIN.TEST>
Define EDITOR:		SYS:EMACS.EXE
Define EMACS:		PS:<EMACS165>
Define ERRMES:		SYSTEM:ERRMES.BIN
Define FONT:		PS:<FONTS>,PS:<FONTS.SCRIBE-300DPI>,PS:<FONTS.240DPI>,PS:<FONTS.XGP>
Define HLP:		PS:<HELP>
Define IDEA:		IETF:
Define IEN:		PS:<IEN>, PS:<NETINFO>
Define IETF:		PS:<IETF>
Define IMAGEN:		TTY25:
Define INFO:		PS:<INFO>
Define JSYS:		PS:<DOCUMENTATION.JSYS>
Define KCCDIST:		PS:<KCC-5>
Define LIB:		MID:
Define LSR:		CDP1:
Define MAIL:		PS:<MAIL>
Define MAILB:		PS:<MAIL.BULK>
Define MAILL:		PS:<MAIL.LIST>
Define MAILQ:		PS:<MAIL.QUEUE>
Define MAILQR:		PS:<MAIL.QUEUE.REGISTER>
Define MAINTSYS:	PS:<MAINTSYS>
Define MICOM-STATUS:	TTY20:
Define MID:		SRC:<LOC.LIBRARY>
Define NET-DIRECTIVES:	PS:<NET-DIRECTIVES>
Define NETINFO:		PS:<NETINFO>,PS:<IEN>,PS:<RFC>
Define NETPROG:		PS:<NETPROG>
Define NEW:		PS:<NEWSYS>,SYS:
Define NEWC:		PS:<KCC-NEW>
Define NICPROG:		PS:<NICPROG>
Define NUMBERSFILE:	PS:<NIC-ADMIN>NUMBRS.DAT
Define OLD:		PS:<OLDSYS>,SYS:
Define PASCAL:		PS:<PASCAL>
Define PCL:		PS:<PCL>
Define PLPT1:		TTY25:	! Printer SMOKEY
Define PLPT2:		TTY54:	! Printer SPEEDY
Define PLPT3:		TTY55:	! Printer PIPPIN
Define PLPT4:		TTY42:  ! Printer HP
Define PLPT7:		TCP:777.DDN-PMO-MIL-TAC-15639.0;CONNECTION:ACTIVE;TIMEOUT:60		! Printer DDNPMO
Define PRIMARYPERSFILE:	PS:<NIC-ADMIN>PERSON.DAT
Define PROTOCOLS:	PS:<PROTOCOLS>
Define PUB:		PS:<LOC-SUBSYS>,PS:<SUBSYS>,DSK:
Define QUERY:		PS:<QUERY>
Define REF:		PS:<REFERENCE>
Define REFHLP:		PS:<REFHELP>,PS:<REFERENCE>
Define RFC:		PS:<RFC>, PS:<NETINFO>
Define SAFETY:		PS:<SAFETY>
;For LINK with SAIL
Define SAI:		PS:<SAIL>
;For SAIL-- not needed? 3/20/85
;Define SAIL:		PS:<NEWSAIL>,PS:<SAIL>
Define SCRIBE:		SCRIBE5:
Define SCRIBE5:		PS:<SCRIBE-5.LOCAL>,PS:<SCRIBE-5>
Define SCRIBE6:		PS:<SCRIBE-6.LOCAL>,PS:<SCRIBE-6>
Define SERR:		PS:<SYSTEM-ERROR>
Define SERVICE:		NETINFO:, DDN-NEWS:, RFC:, IEN:, PROTOCOLS:
Define SPOOL:		PS:<SPOOL>
Define SS:		PS:
Define SYS:		PS:<LOC-SUBSYS>,PS:<SUBSYS>,DSK:
Define SYSTEM:		PS:<SYSTEM>
Define TEX:		TS:<TEX>
Define TEXFONTS:	TS:<TEX.FONTS>,PS:<FONTS>
Define TEXFORMATS:	TS:<TEX.FORMATS>
Define TEXGFS:		TS:<TEX.GF>
Define TEXINPUTS:	TS:<TEX.INPUTS>,TS:<TEX.LATEX>,TS:<TEX.AMSTEX>
Define TEXSPOOL:	SYS:DVIIMP.EXE
Define USE-STATS:	TS:<ID>
Define USER-DRV:	PS:<USER-DRIVE>
Define UNV:		PS:<UNIVERSALS>
Define VH:		TS:<VHTAPE>
Define WEB:		SRC:<LOC.WEBSTER>
Define W7:		TS:<WEBSTER>, WEB:

;Do the correct thing with the accounting file
Change 8:00 Weekdays
Change 18:00 Weekdays
Change 0:00 Weekdays
Change 0:00 Saturday
