;This is the domain configuration file.
;It specifies the local default domain and local nicknames.
;It is read on system startup.

;local default domain
LOCAL-DOMAIN		SRI.COM

;--- NICKNAMES ---
;SRI hosts
SRI-NIC.ARPA		SRI-NIC,NIC
F4.CSL.SRI.COM		F4
CSL.SRI.COM		CSL
CRVAX.SRI.COM		CRVAX
GIZMO.SRI.COM		GIZMO
B.CSL.SRI.COM		CSLB
KL.SRI.COM		KL
STRIPE.SRI.COM		STRIPE
SPAM.ISTC.SRI.COM	SPAM
TSCA.ISTC.SRI.COM	TSC,TSCA
SRI-NIXON.ARPA		NIXON
BLACKJACK.SRI.COM	BLACKJACK,BJ
SRI-ROBOTX.ARPA		ROBOTX
FS1.SRI.COM		FS1
WS1.SRI.COM		WS1
WS2.SRI.COM		WS2
WS3.SRI.COM		WS3

;randoms
SCORE.STANFORD.EDU	SCORE
CSLI.STANFORD.EDU	CSLI
SUMEX-AIM.STANFORD.EDU	SUMEX
SUSHI.STANFORD.EDU	SUSHI
SIERRA.STANFORD.EDU	SIERRA
XX.LCS.MIT.EDU		XX
MC.LCS.MIT.EDU		MC
TE.CC.CMU.EDU		TE
CU20B.COLUMBIA.EDU	CU20B
CS.COLUMBIA.EDU		COLUMBIA
HPLABS.HP.COM		HPLABS
DDN1.ARPA               DDN1
GARNET.BERKELEY.EDU	GARNET
DEWEY.SOE.BERKELEY.EDU	DEWEY
