;[MACBETH.STANFORD.EDU]SRC:<7.FT2.MONITOR.STANFORD.LOTS>PARLOT.MAC.2, 30-Apr-88 14:25:13, Edit by A.ALDERSON
; Increase swapping space and default swapping space to 40000 pages.
; Decrease number of PNVs to 20, and number of PUP ports to 40
;SRC:<6.1.MONITOR.STANFORD.LOTS>PARLOT.MAC.6, 17-Dec-86 17:47:27, Edit by ALDERSON
; Make monitor for 4mw memory
; Set number of spooled LPTs to 20 (for TCPSPL)
; Set number of LAT terminals to 0
; Set default page limit for new directory to 50 pages (conform with UPDATE)
;DEV:<MONITOR.LOTS>PARLOT.MAC.4, 13-Apr-86 19:25:03, Edit by A.AIRHEAD
; Increase TVTs to ^D80 to accomodate the change to TCP tips
;DEV:<MONITOR.LOTS>PARLOT.MAC.3,  5-Apr-86 10:55:14, Edit by A.ALDERSON
; Increase TVTs to ^D50, decrease PNVs to ^D40
;<FT5>PARLOT.MAC.26, 31-May-85 18:10:11, Edit by H.HEGARTY
; More memory ... set parameter for 4.0MW (who cares if its too much)
;<FT5>PARLOT.MAC.25, 15-May-85 18:29:15, Edit by HEGARTY
; Up JSB free pages to default (from 40. to 50.)
; should solve some of our Pup problems ...
;<FT5>PARLOT.MAC.24,  9-May-85 15:18:03, Edit by HEGARTY
; Oops, get rid of NI stuff in monitor by setting parameters to 0
;<FT5>PARLOT.MAC.23,  5-May-85 19:28:00, Edit by HEGARTY
; Add new style password hacking protection
;<FT5>PARLOT.MAC.22,  1-May-85 22:13:30, Edit by HEGARTY
; Merge in new 6.1 parameters ...
;<5-3-MONITOR>PARLOT.MAC.21, 11-Mar-85 20:54:11, Edit by HEGARTY
; Only 16 DH lines now, bump memory up to 2.75 MW
;<5-3-MONITOR>PARLOT.MAC.20, 25-Oct-84 00:32:08, Edit by LOUGHEED
; 160. PUP ports, 120. PUP NVTs
;<5-3-MONITOR>PARLOT.MAC.19, 30-Sep-84 14:41:15, Edit by LOUGHEED
; Number of DH lines goes from 80. to 48. (no Terman kludge on LOTSA)
; Maximum number of structures goes from 4 to 3
; Don't retain EDDT by default
;<5-3-MONITOR>PARLOT.MAC.18, 28-Apr-84 18:00:06, Edit by L.LOUGHEED
; Flush bugstrings
;ACCT:<5-3-MONITOR>PARLOT.MAC.17,  5-Jan-84 11:19:54, Edit by R.RMK
; 2.25MW of memory nowadays
; Search PUPSYM
;ACCT:<5-3-MONITOR>PARLOT.MAC.16, 20-Oct-83 10:02:02, Edit by R.RMK
; NHOSTS moved to STG.
;ACCT:<5-3-MONITOR>PARLOT.MAC.15, 11-Oct-83 12:13:47, Edit by R.RMK
; Drop JSB free pages.
;ACCT:<5-3-MONITOR>PARLOT.MAC.14, 11-Oct-83 11:56:10, Edit by R.RMK
; Increase JSB free pages, turn on Internet
;BX:<5-3-MONITOR>PARLOT.MAC.13, 19-Jul-83 17:24:51, Edit by R.RMK
; Decrease JSB free pages, up NNTBFS.
;ACCT:<5-MONITOR>PARLOT.MAC.12, 17-Jun-83 11:35:24, Edit by R.RMK
; Lose a JSB free page;  increase NHOSTS to 1201.
;ACCT:<5-MONITOR>PARLOT.MAC.11, 13-May-83 08:52:34, Edit by R.RMK
; Only 80 jobs, not 100.
;ACCT:<5-MONITOR>PARLOT.MAC.10, 28-Apr-83 02:18:54, Edit by R.RMK
; Decrease STRN to 4.  Retain EDDT by default.
;ACCT:<5-MONITOR>PARLOT.MAC.9, 27-Apr-83 16:16:54, Edit by R.RMK
; Decrease number of TVT's.
;ACCT:<5-MONITOR>PARLOT.MAC.8, 25-Apr-83 16:27:58, Edit by R.RMK
; NHOSTS, NNTBFS, up JSB space.
;ACCT:<5-MONITOR>PARLOT.MAC.7, 25-Apr-83 12:30:26, Edit by R.RMK
;TCP/IP.
;<5-MONITOR>PARLOT.MAC.6, 31-Dec-82 22:45:25, Edit by B.BOMBADIL
;Up to 2MW of physical memory
;<5-MONITOR>PARLOT.MAC.5, 21-Sep-82 16:27:02, Edit by B.BOMBADIL
;Allow up to six structures instead of only three
;<5-MONITOR>PARLOT.MAC.4, 18-Sep-82 18:22:54, Edit by B.BOMBADIL
;search PUPPAR for pup parameters
;<5-MONITOR>PARLOT.MAC.2, 16-Sep-82 23:04:13, Edit by B.BOMBADIL
;TU78 support
;Up to 2 tape drives
;Up to 2 FE PLPT's
;<5-MONITOR.LOTS>PARLOT.MAC.2, 13-Jun-82 23:28:28, Edit by B.BOMBADIL
;^D80 DH LINES, NOT ^D84
;<5-MONITOR.LOTS>PARLOT.MAC.1, 11-Jun-82 14:28:29, Edit by B.BOMBADIL
;Parameters for LOTS

SEARCH MONSYM			; Get monitor definitions

; Parameters for storage configuration

NJOBS==:^D80			; number of jobs on system
NDHL==:^D16			; number of terminals
NTTPTY==:^D20			; number of PTYs
NTTTVT==:^D80			; number of TVTs
NTTPNV==:^D20			; number of PNV's
NPUPUN==:^D40			; number of PUP ports
NTTLAH==:0			; number of LAT terminals
MAXCOR==:20000			; 4MW of memory
SSPT==:5000			; size of SPT
NDST==:^D40000			; 40000 pages of swapping space
SWDST==:^D40000			; default swapping space
MXSTRU==:6			; up to 3-RP06s per structure
NNTBFS==:100000			; space for network buffers
TTSIZ==:100			; UP SIZE OF TTY BUFFERS FOR TCP MONITOR

; System configuration

NETN==:1			; ARPANET
MEISN==:2			; Have 2 MEIS devices.
ANXN==:0			; No AN20.
DCN==:0				; no DECnet
IPCIN==:1			; one KLIPA
KNIN==:0			; no KLNI's
IPNIN==:0			; no IP over the KLNI
STRN==:6			; maximum number of structures
MTAN==:2			; number of magtapes
DX20AF==:0			; no DX20 TU70,71,72
DX20BF==:0			; no DX20 RP20
TM78F==1			; TM78/TU78
DTEN==:1			; number of DTE20s
FELPTN==:2			; number of LPTs on FE
LPTN==:FELPTN			; number of physical LPTs
LPTSPN==^D20			; number of spooled LPTs
FECDRN==:0			; no CDRs on FE
CDRN==:FECDRN			; no card reader
PCDPN==:0			; no card punch
CDPN==:PCDPN			; no spooled card punch
SPLTN==:0			; no spooled plotter
SPTPN==:0			; no spooled paper tape punch

; Directory parameters

.STDFP==:775202			; standard file protection
.STDDP==:774040			; standard directory protection
.STDBS==:1			; standard number of versions to keep
.STDMX==:^D50			; standard disk allocation
.STDSD==:0			; standard subdirectory quota

; Other parameter settings

COFMIN==:^D30			; Carrier off interval is 30 minutes
TMZONE==:8			; PST
IPTIMF==:1			; include page fault time in runtime
IEDDTF==:0			; don't retain EDDT by default
DGOFKN==:^D8			; allow up to 8 forks before calling ACJ
EXADF==:-1			; big directories (2060 system)
SAVTRF==:1			; One line BUGxxx output on CTY
PSPNTP==:1			; New style password hacking protection
