DEFINE LM7: SRC:<7.FT3.MONITOR.STANFORD.LOTS>
DEFINE LU7: SRC:<7.FT3.UTILITIES.STANFORD.LOTS>
DEFINE LL7: SRC:<7.FT3.LANGUAGES.STANFORD.LOTS>
DEFINE LM72: SRC:<7.FT2.MONITOR.STANFORD.LOTS>
DEFINE LU72: SRC:<7.FT2.UTILITIES.STANFORD.LOTS>
DEFINE LL72: SRC:<7.FT2.LANGUAGES.STANFORD.LOTS>
DEFINE LM71: SRC:<7.FT1.MONITOR.STANFORD.LOTS>
DEFINE LU71: SRC:<7.FT1.UTILITIES.STANFORD.LOTS>
DEFINE LL71: SRC:<7.FT1.LANGUAGES.STANFORD.LOTS>
DEFINE MON: LM7:,LM72:,LM71:,M7:,M72:,M71:
DEFINE LNG: LL7:,LL72:,LL71:,L7:,L72:,L71:
DEFINE UTL: LU7:,LU72:,LU71:,U7:,U72:,U71:
DEFINE R: DSK:,MON:,LNG:,UTL:
DEFINE UNV: UTL:,LOCAL:<NEW-SUBSYS>
TAKE
